### ISSUE TITLE
这个开发大概还需要多久

### ISSUE THREAD

**Issue by youth1996** [Bililive/BililiveRecorder#1]
下载以后自己用vs也不能编译

**Comment by Genteure** [comment]
不能用是真的，不能编译应该是你自己编译环境的问题。
`BililiveRecorder.FlvProcessor` 和 `BililiveRecorder.Core` 是 .NET Standard 2.0
`BililiveRecorder.WPF` 是 .NET Framework 4.6.2

开发还差，大概，两三天？
WPF 界面有的按钮还没写对应的代码
Appveyor 还没配
基本上就差这两项了，然后可以发个测试版本看看有没有什么漏了的问题

**Comment by Genteure** [comment]
从现在开始测试版本会由 Appveyor 自动编译了。
如果你真的急着想测试/试用的话，可以从 [这里](https://soft.danmuji.org/BililiveRecorder/setup.exe) 或者 [这里](https://soft.danmuji.org/BililiveRecorder/BililiveRecorder.WPF.application) 下载安装。

**Comment by Genteure** [comment]
注，目前已知问题：
- 回放剪辑的开头会灰屏，因为没有刚好裁剪到关键帧上。
- 回放剪辑的显示的视频时长和真实时长对不上。

**Comment by youth1996** [comment]
就是以前的一个录播biliroku有些问题，想试试看新软件，谢谢！

**Comment by Genteure** [comment]
哦还有一个忘了说的
录制之前先点设置选择一下保存路径，否则会录到 exe 同目录里面去，是在系统盘里的。

**Comment by youth1996** [comment]
BUG：
![image](https://user-images.githubusercontent.com/32319709/37872049-33041554-3031-11e8-9c9e-a674c0b030ed.png)

在录制中，点启动 自动录制 会出现显示错误，显示waiting实际还在录制

**Comment by Genteure** [comment]
这部分是在打算改的，本来设计的是用一个 enum 存状态，但是后来发现不合理，打算改成两个 bool

**Comment by youth1996** [comment]
现在设置了几个可能下午会直播的主播看看自动录制的情况

**Comment by Genteure** [comment]
没太想明白问题可能出在哪，弹幕服务器是有重连的，录制出错之后也会重置的，我等会再看看吧。
你用过 Nlog 吗？可以改一下 exe 同目录里的 `Nlog.config` 输出一份日志到文本文件，方便调试。

**Comment by youth1996** [comment]
刚刚没看消息，那会看的时候前面的日志已经刷过去了，现在保存了日志

**Comment by youth1996** [comment]
可能是没点 “启动所有直播间”，刚才闪退，重新开的

**Comment by Genteure** [comment]
好奇问一下，你平常都是录哪些直播间？是录播组？房管？普通观众？
在弹幕姬群里（都是主播）简单宣传了一下，基本没人有需求的。。超不待见 😞

**Comment by youth1996** [comment]
就是普通观众，闲的没事录着玩，后来发现了你是宅急送队长，在弹幕姬群发现的
