### ISSUE TITLE
连接弹幕服务器再次出错

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [Bililive/BililiveRecorder#102]
![image](https://user-images.githubusercontent.com/44915585/81473792-b4a63400-9233-11ea-9cd2-c37ce758c946.png)

**Comment by Genteure** [comment]
emmmmmmm。。你先在设置里把弹幕重连间隔调高吧。。。
B站如果真的要 rate limit 你，我也没啥办法（

**Comment by SaltyFishOnTheSea** [comment]
突然又自己好了，太奇怪了
之前是给服务器ban掉了吗

**Comment by SaltyFishOnTheSea** [comment]
短暂恢复之后再次412

**Comment by SaltyFishOnTheSea** [comment]
在和客服反复反馈三次之后，浏览器/手机客户端不再出现无法获取直播间数据的情况，但录播姬仍旧显示 412 错误

**Comment by Genteure** [comment]
你有修改过设置里的参数吗？昨天发现有人是把检查间隔改到了10秒，那肯定被屏蔽。
你录的直播间数量确实很多，把设置里那些检查间隔、重连间隔都改的大一点试试会不会缓解。
如果登录之后就能正常使用了，可以试试设置一下 Cookie。现在弹幕连接的请求是没有带上设置里的 Cookie 的，只有直播间信息有带上。注：不保证不会影响B站账号，建议用小号的Cookie。

**Comment by SaltyFishOnTheSea** [comment]
> 你有修改过设置里的参数吗？昨天发现有人是把检查间隔改到了10秒，那肯定被屏蔽。
> 你录的直播间数量确实很多，把设置里那些检查间隔、重连间隔都改的大一点试试会不会缓解。
> 如果登录之后就能正常使用了，可以试试设置一下 Cookie。现在弹幕连接的请求是没有带上设置里的 Cookie 的，只有直播间信息有带上。注：不保证不会影响B站账号，建议用小号的Cookie。

![image](https://user-images.githubusercontent.com/44915585/81521841-0d341900-937b-11ea-8377-7c160162431c.png)
z这个是我目前的设置，在这次事情发生之前一年多的时间内没有更改过，且没有出现过这样的情况

**Comment by Genteure** [comment]
录制重试间隔改到 10000 （10秒）
弹幕重连间隔改到 15000 （15秒）
开播检查间隔改到 600 （10分钟，这个是通过HTTP接口主动检查的间隔）
不使用腾讯云那个勾去掉吧。
有出现过录播姬主动断开的情况吗？接收数据超时是以前的默认吗？有点点短，可以设置到 10000 （10秒）
可以试一下设置个 Cookie

**Comment by SaltyFishOnTheSea** [comment]
现在的问题是重启录播姬，在初始化阶段加载完直播间标题后，会出现：
①412错误
②连接弹幕服务器成功，但是并不会启动录制，即使列表中有直播间处于直播状态

昨天咨询B站客服时，给到一个网址：https://live.bilibili.com/blackboard/live-clinic.html
在之前浏览器无法连接直播间时，显示为：
![image](https://user-images.githubusercontent.com/44915585/81522311-b16a8f80-937c-11ea-96b7-c025c1fbfffe.png)
现在显示为：
![image](https://user-images.githubusercontent.com/44915585/81522326-c0e9d880-937c-11ea-9441-35c273130e05.png)

**Comment by SaltyFishOnTheSea** [comment]
主动断开挺常见的，即使是白天只录制一个直播间的时候也会，晚上录制数量上升主动断开的频率也随之上升

**Comment by SaltyFishOnTheSea** [comment]
尝试添加Cookie，更改间隔，去掉腾讯云勾选后重启录播姬，录播姬无法主动开始录制

**Comment by Genteure** [comment]
412错误就是被B站WAF给拦了，八成是因为发请求太多，这个没啥办法。我也不知道B站是什么策略，就算知道了，B站也可以随时改。就只能尽量减少发的请求数量，缓解这个问题。
你录这么多直播间，发的请求数量也多。别人就录几个的可能平均每小时发50个请求，你平均每小时估计得至少有一千个请求。
随便写个WAF规则也能给抓出来，哪有正常用户只大量请求两三个API，不访问HTML也不访问其他API的。

除非你能给出比较明确的对录播姬代码、或者录制逻辑的修改建议，我也没法改。只能给你参数修改建议：把各种请求间隔时间设置长一点，减少请求数量。

**Comment by SaltyFishOnTheSea** [comment]
现在倒是不报412错误了，就是无法自动开始录制

**Comment by SaltyFishOnTheSea** [comment]
金山云是B站的服务主机吗，这次跟之前close掉的情况一样，无法连接至IP显示为金山云的主机地址，ping也ping不通
![image](https://user-images.githubusercontent.com/44915585/81769531-70a37f80-9510-11ea-85c3-8f071443d426.png)
![image](https://user-images.githubusercontent.com/44915585/81769263-bd3a8b00-950f-11ea-839f-3c368539f246.png)
这个是目前的配置
![image](https://user-images.githubusercontent.com/44915585/81769528-6d0ff880-9510-11ea-92cb-c2a0e0a5cd44.png)

**Comment by zjqwtm543** [comment]
看着老铁这一层终于知道cookie写啥了，果然对游客的码率有限制，录的房间多了啊B限码率
