### ISSUE TITLE
新坑: FlvInteractiveRebase

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#103]
## 需求

偶尔会有人录出来各种极其神奇的 flv 文件，比如：

- 没有 video header 导致视频无法播放
- video header 错误导致视频花屏
- audio header sample rate 不对导致声音低沉
- 连续收到多个 header

目前没有工具（至少我不知道）能实现对 flv 文件进行 tag 级的修复，导致有时虽然知道应该怎么修却无法实际操作（直接从另一个同主播正常的录播文件里把 header 复制到有问题的文件里即可）

虽然理论上可以手动用 HexEditor 修改，但是操作起来非常麻烦，而且需要对 FLV 文件结构非常熟悉。

## 参考 git rebase -i

参考 [git interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) 的设计

```rebase
pick f7f3f6d Change my name a bit
pick 310154e Update README formatting and add blame
pick a5f4a0d Add cat-file

# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
```

## 基本设计

实现三个主要的子命令：

- `./fib parse <input.flv> <rebase.txt> [--skip-hash]`
- `./fib build <rebase.txt> <output.flv> [--skip-hash]`
- `./fib extract <input.flv> <tag id> <output>`

简单用法：

1. 运行 `fib parse` 给有问题的录像文件输出一份 rebase.txt
1. [可选] 运行 `fib parse` 给其他已知正常的文件输出一份 rebase.txt
1. [可选] 运行 `fib extract` 导出某一个 Tag 并手动用二进制编辑器修改
1. 修改有问题的文件的 rebase.txt
1. 运行 `fib build` 根据 rebase.txt 里的指令生成 flv 文件

## `rebase.txt` 文件语法

当每行第一个字符是 `#` 时整行都是注释

第一行是原文件的信息，语法：

```
file [--hash <原文件的Hash>] [--file <原文件完整路径>]
```

从第二行开始每行是一个 FLV Tag，语法：

```
<命令> <Tag 序号> <时间戳> [--type <Tag 类型>] [--header [true|false]] [--keyframe [true|false]] [--from <FLV 文件路径>] [--raw <FLV Tag 路径>]
```

`type`, `header`, `keyframe` 这三个参数在 `build` 命令里没有任何作用，只是在运行 `parse` 命令时为了可读性而输出。

命令有：

- `p`, `pick` 正常使用这个 Tag
- `d`, `drop` 丢弃这个 Tag

示例：

```diff
file --hash ed076287532e86365e841e92bfc50d8c --file C:\path\to\bad.flv
# 请不要修改上一行的内容
# 当每行文字的第一个字符是 # 时为注释
# 
# 此处省略若干使用说明……
#
pick 1 00:00:00.0 --type script
# 使用原视频的 flv 头
drop 2 00:00:00.0 --type video --header true --keyframe true
#pick 3 00:00:00.0 --type audio --header true --keyframe true
# 丢弃原视频的第 2 3 个 Tag (NOP)
# 可以修改 pick 到 drop
# 也可以在开头添加 # 使其变成注释
pick 2 00:00:00.0 --from C:\path\to\good.flv
# 把 C:\path\to\good.flv 文件里的第 2 个 Tag 复制到这里
pick 0 00:00:00.0 --raw C:\path\to\raw_tag_data.blob
# 把 C:\path\to\raw_tag_data.blob 文件里的数据作为一个完整 Tag 复制到这里
pick 4 00:00:00.0 --type video --keyframe true
# 正常地从原文件复制其他数据
pick 5 00:00:00.33 --type video
pick 6 00:00:00.66 --type video
pick 7 00:00:00.100 --type video
pick 8 00:00:00.133 --type video
pick 9 00:00:00.166 --type video
pick 10 00:00:00.200 --type video
# 此处省略一段
pick 31 00:00:01.0 --type video
```

先把设计写出来备忘，回头有空了再实现（（咕

**Comment by Genteure** [comment]
完成了初版，实现了核心功能。要到了一个直播中途分辨率变化导致视频花屏的样本，测试编辑效果很棒，修改后能正常播放。
![image](https://user-images.githubusercontent.com/11240579/82068604-c9d40480-9704-11ea-8ab1-aec3b3530aa0.png)

build 阶段解析 fib 命令文件使用的是 [CommandLine](https://github.com/commandlineparser/commandline)，效率很低。一小时长 25 FPS 的 FLV 文件生成的命令文件，解析要花大概2分钟。暂时没有怎么优化的头绪。

如果改成每行一个 JSON 感觉解析效率可能会高一点，但是单行JSON对手动编辑很不友好。
有没有什么东西是手写方便、语法简单、解析效率高的啊

**Comment by simon300000** [comment]
简易命令解析 (JavaScript)
类似方法可能比使用CommandLine快

```javascript
const parseParams = params => Object.fromEntries(params
  .split('--')
  .filter((_, i) => i)
  .map(part => [...part.trim().split(' '), true]))

const parseCommand = line => {
  const [command, tag, timestamp, ...rest] = line.split(' ')
  const params = parseParams(rest.join(' '))
  return { command, tag, timestamp, ...params }
}
```

```javascript
parseCommand('Pick 800 00:00:00 --type Video --size 34 --header --keyframe')

{
  command: 'Pick',
  tag: '800',
  timestamp: '00:00:00',
  type: 'Video',
  size: '34',
  header: true,
  keyframe: true
}
```

**Comment by Genteure** [comment]
改成用 XML 了

https://github.com/Genteure/FlvInteractiveRebase
