### ISSUE TITLE
录制文件的直播标题经常会是上一场直播的标题

### ISSUE THREAD

**Issue by ZTMC** [Bililive/BililiveRecorder#105]
也许可以按录制时段内用的最久的标题为准?

**Comment by Genteure** [comment]
现在是用的直播开始的时候的标题。

> 按录制时段内用的最久的标题

还要持续记录统计标题的变动，好麻烦。而且还要录制结束后再重新修改标题，时间日期什么的就更麻烦了。

因为暂时没有修改的打算所以先 close
有其他建议可以继续说

**Comment by H4M5TER** [comment]
其实不需要持续统计标题，标题改变b站直播的ws会发的。
