### ISSUE TITLE
建议增加随系统启动(开机自启)功能

### ISSUE THREAD

**Issue by HeartFireCN** [Bililive/BililiveRecorder#107]
建议增加随系统启动(开机自启)功能

**Comment by climba03003** [comment]
Windows 系統下
Win + R 開啟執行
shell:startup 打開啟動資料夾
把程式捷徑放這就可以了
![image](https://user-images.githubusercontent.com/23028015/85232412-49a26c80-b431-11ea-9772-09c7c6320872.png)

這樣就能開機自動啟動

**Comment by sappy5678** [comment]
但是開機時依然會需要手動選擇工作目錄，這部份該怎樣解決呢 ？

**Comment by Genteure** [comment]
@sappy5678 加一个 `-w 路径` 的参数
举例： `%localappdata%\BililiveRecorder\BililiveRecorder.WPF.exe -w F:\`

**Comment by sappy5678** [comment]
感謝大大的協助＾＾

**Comment by 821938089** [comment]
这样自动启动每次开机都会显示一个窗口。
我不想让它显示，怎么让它默认不显示窗口直接进入后台运行？

**Comment by Genteure** [comment]
@821938089 

> 加一个 -w 路径 的参数
举例： %localappdata%\BililiveRecorder\BililiveRecorder.WPF.exe -w F:\
