### ISSUE TITLE
无法录制

### ISSUE THREAD

**Issue by Taekkjin** [Bililive/BililiveRecorder#11]
[11:45:12] INFO 4719881 弹幕服务器连接成功 
[11:45:32] WARN 4719881 启动直播流下载出错。 The operation has timed out

*手动也不可以开始录制
*发现多个房间都这样

**Comment by Genteure** [comment]
你能在浏览器里看直播吗？在什么环境运行的？

**Comment by Taekkjin** [comment]
浏览器是可以看的，
windows 10 Ver.1803

**Comment by Genteure** [comment]
我感觉玄学网络问题的可能性比较大。重启软件&重启系统可以试一下先。
在任务管理器里右键进程，打开文件所在位置，在 exe 同目录里有日志文件，日志文件里有错误的详细信息，可以 attach 出来。

**Comment by Taekkjin** [comment]
不知道哪行是错误的详细信息

[log.txt](https://github.com/Bililive/BililiveRecorder/files/2065137/log.txt)

**Comment by Genteure** [comment]
我 99% 肯定这是你用的设备的网络问题。错误原因都是 _连接超时_ 和 _DNS 错误_。
我这里可以正常录制你尝试录制的直播间。
建议你换个网络环境再试一下。如果有开系统全局代理可以关掉试一下。
