### ISSUE TITLE
HLS Support

### ISSUE THREAD

**Issue by jitingcn** [Bililive/BililiveRecorder#112]
移动端H5页面使用的是 HLS 流，示例 API： `https://api.live.bilibili.com/xlive/web-room/v1/playUrl/playUrl?cid=3&platform=h5&otype=json&qn=10000`
有没有可能改为使用 HLS 流录制？ 或许可以一定程度上避免 FLV 断片的问题（猜测

**Comment by liushengqi000** [comment]
hls不容易断片，而且片段在服务器上不会立刻删除，按m4s文件名序号逆序可以下载大概1000个片段（可追录10分钟左右的直播历史）。下载m3u8，下载里面的 h****.m4s 文件头，和一堆 ****.m4s 文件，拼到一起就能放了。可能格式不太标准就是了

**Comment by Genteure** [comment]
不是所有直播间都有 HLS，并且考虑本项目目前的发展方向，之后应该不会加 HLS 录制。
