### ISSUE TITLE
视频码率不一样

### ISSUE THREAD

**Issue by kawayifork** [Bililive/BililiveRecorder#113]
今天录播发现突然有2个视频的码率只有1000而平常是4000的，整个视频是一卡一卡的，之前一直没这样的问题，直播我也看了是没问题，就是不懂为什么今天会出现这种情况。谢谢。

**Comment by kawayifork** [comment]
视频长度是对的，但就是有部分变成了空白帧。

**Comment by Genteure** [comment]
这类问题基本都是服务器的锅。一般只要视频文件大小看起来没啥问题，处理一下基本都能救回来，建议加群讨论。
