### ISSUE TITLE
PK画面录制成了坏档

### ISSUE THREAD

**Issue by yuki1404** [Bililive/BililiveRecorder#116]
PK画面开始时候，分辨率改变，有流有断开，录播姬会分成单独的flv。
PK画面信号可能不完整，PK断连，分辨率改变，此时流没有断开，继续写入，后面的数据成了坏档。

**Comment by Genteure** [comment]
大部分都可以修，找到变动的地方切开，让前后部分都用正确的参数解码就可以了。

在QQ群的群文件里有一个我之前做的处理工具，或者用这同一个思路用其他方法其他工具把视频文件分开也可以。
处理工具之后我有空的时候整理一下发到GitHub上来，这个 issue 就先开着备忘吧。

之后**有可能**会对录播和数据处理的部分重构一下，把检测分辨率变动这种功能内置进去。

**Comment by yuki1404** [comment]
> 大部分都可以修，找到变动的地方切开，让前后部分都用正确的参数解码就可以了。
> 
> 在QQ群的群文件里有一个我之前做的处理工具，或者用这同一个思路用其他方法其他工具把视频文件分开也可以。
> 处理工具之后我有空的时候整理一下发到GitHub上来，这个 issue 就先开着备忘吧。
> 
> 之后**有可能**会对录播和数据处理的部分重构一下，把检测分辨率变动这种功能内置进去。

确实，手工处理搞定了，花了2天时间研究，有些麻烦。希望有处理工具，感谢！
