### ISSUE TITLE
选择按文件大小分段时录制错误

### ISSUE THREAD

**Issue by n12z** [Bililive/BililiveRecorder#117]
![QQ截图20200914210139](https://user-images.githubusercontent.com/39026577/93078334-a7abbc80-f6cd-11ea-93f7-775a8bd82bc6.png)
![QQ截图20200914210321](https://user-images.githubusercontent.com/39026577/93078388-bc885000-f6cd-11ea-83ba-3bc996e556fd.png)

**Comment by Genteure** [comment]
与分段应该是没有关系的吧？是测试发现只有开了自动分段之后才有问题吗？

看起来和 #111 应该是同一个问题，只有 gotcha05 有这个问题，之后会修，如果问题很严重的话可以先用其他录制工具录着。

**Comment by Genteure** [comment]
已在 1.2.2 修复
