### ISSUE TITLE
设置里「请求API时使用Cookie」具体是指哪一项Cookie？

### ISSUE THREAD

**Issue by nebulas-star** [Bililive/BililiveRecorder#118]
非常抱歉……但我实在看不懂C#的文件结构……更找不到注释……

**Comment by sgqy** [comment]
https://github.com/Bililive/BililiveRecorder/issues/71#issuecomment-552432299
大概是 request header 里的直接复制

**Comment by Genteure** [comment]
是，request header 里的直接复制

`example=value; example=value` 的格式
