### ISSUE TITLE
use BililiveRecorder on linux

### ISSUE THREAD

**Issue by wwang-at-github** [Bililive/BililiveRecorder#123]
如果可以在Linux下运行BililiveRecorder就好了。

**Comment by valkjsaaa** [comment]
我试了一下，CLI 版本还挺容易在 linux 下跑的，我准备制作一个 docker image 来跑这个 CLI 的版本

**Comment by wwang-at-github** [comment]
CLI is already quite useful.  Thanks much!

**Comment by valkjsaaa** [comment]
Do you have any idea how to enable console logging in CLI? CLI mode works for me, but there are no console output at all.

**Comment by wwang-at-github** [comment]
Sorry, no idea.
