### ISSUE TITLE
xml弹幕转换

### ISSUE THREAD

**Issue by Jack6811** [Bililive/BililiveRecorder#132]
主页推荐的项目，测试了一下效果还行，不过并不支持最新版本的除文字弹幕以外的xml弹幕数据转换，不过平时应该够用了、
作者可以给推荐一种装换方式吗？
就是指导出的礼物、上船的弹幕消息

**Comment by Genteure** [comment]
礼物、上船这些信息的格式是本项目特有的，目前应该还没有任何软件支持。
如果需要的话，现在需要你自己写代码实现。
