### ISSUE TITLE
[建议]添加portable版打包

### ISSUE THREAD

**Issue by I-love-study** [Bililive/BililiveRecorder#136]
也就是中文俗称的“绿色版”(不是单文件版)
这样使用可以更加方便

**Comment by Genteure** [comment]
暂时不打算做，之后可能考虑一下。
有需要的话可以直接把 `%localappdata%\BililiveRecorder\app-{version}` 里的文件单独拖出来，就是绿色版了。
或者在 Release 里有各个版本的安装包，用 7z 之类的压缩软件打开安装exe、再打开里面的 nupkg、在 `\lib\net45` 里就是本体文件。

**Comment by katyurua** [comment]
同求 portable

**Comment by Genteure** [comment]
已添加
