### ISSUE TITLE
根据大小或者时间来自动分割视频录制

### ISSUE THREAD

**Issue by zhengye1** [Bililive/BililiveRecorder#14]
鉴于有些主播设置的码率很高，导致最后处理时会要先处理分割然后再上传回B站，会造成音画不同步的现象，如果一开始录制的时候能根据大小或者时间来开一个新的录制文件，那么在上传回b站的时候就会方便些。

P.S. 如果我有空的话我也想帮忙去改下code...然而我不知道怎么build 这个project...

**Comment by Genteure** [comment]
最近我在尝试用 DI 库 (Autofac) 重构一下总体结构，方便加测试。重构之前暂时先不要发 pull request ，发了也不方便合并。你可以先在自己的分支里改改试试。

我看了你的个人资料，感觉你写 Java 比较多？编译的话先下载 [Visual Studio Community 2017](https://visualstudio.microsoft.com/vs/)。
安装时必选： .NET 桌面开发 、 .NET Core 跨平台开发
直接用 VS2017 打开项目根目录里的 `BililiveRecorder.sln` 编译即可。
第一次编译前会提示有错误，是因为有一个文件 `BililiveRecorder.WPF/BuildInfo.cs` 是由编译前脚本自动生成的，编译一次就不会提示错误了。

**Comment by zhengye1** [comment]
好的，谢谢~

**Comment by Genteure** [comment]
done. 87816beaed54095d7a187147ae62919e85e26fe7
