### ISSUE TITLE
窗口滚轮下拉后程序崩溃卡死、412 按刷新直播间信息无效

### ISSUE THREAD

**Issue by Andy8r0X** [Bililive/BililiveRecorder#140]
作业系统: Windows 7 
b站录播姬版本: 1.1.25 80a20dec最新版本

1. 监控约60个房间，窗口非最大化，滚轮往下会抖动像跳针一样，最终导致程序崩溃卡死，却仍在持续录影，但有新的直播开始并未录影，确定是程序崩溃。必须强制中止程序但有可能又继续崩溃。窗口最大化就没有发生崩溃卡死情况。(上一个版本没有发生类似情况)

2. 出现获取直播间 xxx 的信息错误 412，房间名称显示「获取中」，按下「刷新直播间信息」无效，必须按开始录制，才能正常显示房间。

谢谢开发者!

**Comment by Genteure** [comment]
1. 已修复，下个版本更新
2. 412错误是发请求太多，被B站服务器临时屏蔽了
