### ISSUE TITLE
希望可以自选直播录制清晰度

### ISSUE THREAD

**Issue by 821938089** [Bililive/BililiveRecorder#145]
b站跨年晚会录不到4k，录的原画只有1080p。

**Comment by Genteure** [comment]
确实是这样的，近期肯定是加不了，有需求的话可以自己改一下代码里的接口地址然后自己编译一下

**Comment by real-Shigure** [comment]
如果选择录制“原始数据”，那么录制的画质即为直播间支持的最高画质吗？例如：直播间最高清晰度为蓝光画质，那么录制下来的原始数据即为蓝光画质的数据吗？非常感谢！！（因为不擅长于代码，如果要指定清晰度/帧率，我该修改哪一处代码呢）

**Comment by Genteure** [comment]
刚添加了这个功能，急用可以从 Actions 里下载最新一个 build

现在 4K 的画质ID是 `20000`，可以填写 `20000,10000` 到设置里就是优先 4K， fallback 原画。

配置文件的 JSON Schema 也跟着同步更新了。

**Comment by real-Shigure** [comment]
> 刚添加了这个功能，急用可以从 Actions 里下载最新一个 build
> 
> 现在 4K 的画质ID是 `20000`，可以填写 `20000,10000` 到设置里就是优先 4K， fallback 原画。
> 
> 配置文件的 JSON Schema 也跟着同步更新了。

非常感谢！！！已经完成build正在使用了❤👍
