### ISSUE TITLE
【新功能提议】获取直播间所在分区

### ISSUE THREAD

**Issue by vincentkilua** [Bililive/BililiveRecorder#152]
不知道有没有办法探测到直播间更改分区的操作？如果能做到的话那不用打开就可以知道主播在播什么了，同时补足现在「直播中」显示不太醒目这点

**Comment by Genteure** [comment]
Added in https://github.com/Bililive/BililiveRecorder/commit/7897ddaf9953f9d7da30d548d6562f0f81f1073e
