### ISSUE TITLE
[讨论]直播流

### ISSUE THREAD

**Issue by Jack6811** [Bililive/BililiveRecorder#158]
现在bilibili有部分直播间采取了HLS方式进行推流，但绝大多数依旧是RTMP推流，且全部保留了该方式。
目前看不出规律，我仅仅只观察了电脑端的部分，并不能绝对肯定
以目前看HLS流是m3u8+ts 或 m3u8+m4s的方式进行的，在统计信息里显示`Player Core: HIs7Player(SistersFetcher)`，目测此方法处于测试阶段，但并不排除在未来大规模使用。
一旦使用意味着我们用户必须承受其高昂的延时，我一般来说是20s-50s，和RTMP相比确实体验不太好，但协议本身的缺陷我们无法避免，只能去祈祷B站官方做优化吧。（仅为个人推测，勿喷）
录播姬是不是可以考虑兼容呢，虽然目前没必要但万一以后呢（狗头保命）

**Comment by Genteure** [comment]
你的意思是“拉流”而不是“推流”吧？ RTMP 应该是指 HTTP-FLV ？

`SistersFetcher` 是 P2P 分发直播数据的，你观看直播的同时会把直播数据上传给其他观众。
这个已经上线了很长时间了，估计早脱离测试阶段了（

只有观众比较多的直播间才会开 p2p ，一般的主播还是普通的 HTTP-FLV。
**所有直播间都有 HTTP-FLV**，并不是所有直播间都有 HLS。
感觉录播姬现在使用 RTMP 拉流需求不是很大，还是以 FLV 为主。

录播姬除了实现“录”这个功能以外还有一个重点在于处理和修复，直播服务器因为各种各样的原因偶尔会发一些比较有问题的数据，包括 ffmpeg 在内的很多工具都处理不了或者不好处理。
这个项目目前只有项目初期实现的一个简单的处理，没有对问题的修复。目前正在重构数据处理部分，加入更多直播数据的修复功能，这个也依赖于 FLV 格式。

在可预见的将来B站不会删除 HTTP-FLV 拉流的支持，所以没有支持 HLS 的需要。
如果以后真的只有 HLS 了，那估计本项目就直接 archive 停更了，随便找个 HLS Downloader 就行了（
