### ISSUE TITLE
连麦

### ISSUE THREAD

**Issue by 760286098** [Bililive/BililiveRecorder#159]
录播时主播突然连麦，导致录制视频黑屏卡顿

**Comment by 760286098** [comment]
换了几个播放器，连麦前都是正常的，连麦和之后的，要么解析不出来（黑屏），要么进度条错乱，无法定位

**Comment by Genteure** [comment]
用这个工具修复一下 https://github.com/Genteure/BililiveStreamFileFixer/releases/download/0.0.1/fix.zip

之后的版本会把修复工具内置到录播姬本体里
