### ISSUE TITLE
能否增加录制音频功能

### ISSUE THREAD

**Issue by caijiqhx** [Bililive/BililiveRecorder#165]
对于 相声 这类直播会有只录制音频的需求，不知道能否直接加在软件中？

**Comment by liushengqi000** [comment]
flvTag分视频和音频，应该可以拆开，没试过。就算可以，视频音频还是一起下载的，只是软件扔掉视频数据而已

**Comment by Genteure** [comment]
技术角度可以实现，不过这个功能太小众，不太想维护，所以不打算添加。
我记得手机客户端好像有只有音频的流，没有确认过。
