### ISSUE TITLE
请求更新B站录播姬 for linux！

### ISSUE THREAD

**Issue by Karmylr** [Bililive/BililiveRecorder#169]
请求更新B站录播姬 for linux！
B站录播姬很好用，但是我很难做到24小时不关计算机。我想用vps运行B站录播姬。

**Comment by Genteure** [comment]
1.2: https://ci.appveyor.com/project/Genteure/bililiverecorder/builds/37648937/artifacts
1.3: https://github.com/Bililive/BililiveRecorder/actions

都是姑且能用，没怎么测试过的状态。
尤其是 1.3 还在逐步完善的阶段。

配置文件和桌面版的通用的，1.2 的 CLI 对应 1.2 的 WPF 桌面版，1.3 的对应 1.3 的。
