### ISSUE TITLE
关于XML弹幕文件转换ASS

### ISSUE THREAD

**Issue by sy1412** [Bililive/BililiveRecorder#170]
Danmu2Ass
bilibili ASS 弹幕在线转换
都转换不了 是什么情况呢？但BiliLocal播放正常
请问还有其他XML转换ASS的工具吗？感谢

**Comment by Genteure** [comment]
我可以正常使用 https://tiansh.github.io/us-danmaku/bilibili/ ，应该是你的问题。

> 请问还有其他XML转换ASS的工具吗？

不了解

**Comment by sy1412** [comment]
> 
> 
> 我可以正常使用 https://tiansh.github.io/us-danmaku/bilibili/ ，应该是你的问题。
> 
> > 请问还有其他XML转换ASS的工具吗？
> 
> 不了解

居然其他地址 我都不知道 一直用这个来的
https://tiansh.github.io/ass-danmaku-online/
发现还有个DanmakuFactory 好使 奇怪之前没搜到。。。
