### ISSUE TITLE
能否在这里反应一个录播机Linux版的问题

### ISSUE THREAD

**Issue by Ksdb104** [Bililive/BililiveRecorder#174]
我个人跑在服务器上的linux版本,自从0.0.0.435版本之后,录播出来的文件就非常的细碎,如图
![image](https://user-images.githubusercontent.com/36178808/113599374-1a33b800-9671-11eb-8682-1e7c5e54f6a8.png)
我的设置是不分段,之前录得都还可以,不过目前还不能排除我这边网络的问题,我自己输出了日志,如下
[log.log](https://github.com/Bililive/BililiveRecorder/files/6259298/log.log)
我简单看了下,每次分段都会输出
修复逻辑输出 时间戳问题：间隔过大

**Comment by Genteure** [comment]
录播姬 1.3 主要修改之一是新写了录播修复系统，现在处于能用、基本稳定无恶性bug、但是还在继续测试的状态，修复系统能控制输出分段。
“时间戳问题：间隔过大”是在分段发生之后的日志（虽然在日志文件里靠前），是因为分段了所以才会有间隔过大，而不是先间隔过大才分段。
这个问题前两天在QQ群里也有人反馈过，猜测是因为收到的数据导致的，晚点我再多加几处日志输出方便确定具体原因，现在有两处会导致分段的代码没有日志输出，没法确定具体是什么触发了分段。

如果你想帮忙的话，可以用 录播姬 1.2.2 录，然后用 1.3 WPF 版里的修复工具检查是否有一样的分段问题，把会导致分段的样本用修复工具里的导出分析数据功能导出发给我。方便的话可以加一下QQ群，讨论起来更方便一点。
或者不想帮忙测试 1.3 的话，可以用 Appveyor 上 0.0.0.414 这个 build，对应的是 dev 分支 1.2 的代码。

**Comment by Ksdb104** [comment]
我这边Windows的网络不是很稳定,所以一般用linux版...而且我也不是很会用WPF工具 ( ╯□╰ ),我先回滚版本试试

**Comment by Ksdb104** [comment]
很奇怪,我回滚到0.0.0.434还是不行,明明之前都是可以的,难道是B站的设置变了?
另外我是Windows客户端1.2.2生成的config在传给Linux使用的,我注意到linux使用过的config体积会小很多,不知道有没有问题
0.0.0.414看起来倒是确实没问题了

**Comment by Genteure** [comment]
dev-1.3 分支的是 1.3, dev 分支的是 1.2
导致最近出现分段是因为从B站直播服务器收到了特定的数据、触发了 1.3 一直就有的分段逻辑，而不是因为最近 1.3 的修改调整了分段逻辑

你能稳定复现分段的问题吗？每次直播都有这个情况吗？方便用 1.3 WPF 版里的工具导出一下用 1.2.2 / 0.0.0.414 录的录播文件的分析数据吗？
从 GitHub Actions 里最新一次 build 的 Artifact 里下载 WPF-Debug，打开 BililiveRecorder.WPF.exe 之后选 工具箱模式，在左侧点工具箱图标、录播修复，选择文件之后点 “修复失败” 然后 “导出原始分析数据”，会生成一个 `.brec.xml.gz` 文件。把那个文件发出来，直接上传到这个 issue 里就行。

关于配置文件，1.2 的 json 是所有设置项全部保存，1.3 为了减少文件体积改成了只保存非默认值，默认设置就不保存了。

**Comment by Ksdb104** [comment]
最近几次用 dev-1.3分支会稳定复现这一问题,我用1.3最新的WPF做了如上操作,分析的是最靠前的一段,这个分析工具似乎不能多选

昨天dev-1.2 0.0.0.414录的测试数据直接删掉了( ╯□╰ ),今晚上再试试
这有两段分析数据,都是dev-1.3录的,上面这段是有问题的分段
[录制-597450-20210331-154320-和勺宝玩双人成行.brec.xml.gz](https://github.com/Bililive/BililiveRecorder/files/6269384/-597450-20210331-154320-.brec.xml.gz)

下面这段是没问题的
[录制-597450-20210314-151147-开播播啦.brec.xml.gz](https://github.com/Bililive/BililiveRecorder/files/6269441/-597450-20210314-151147-.brec.xml.gz)

**Comment by Genteure** [comment]
1.3 录出来的文件里看不出来原因，需要用 1.2 是因为 1.2 录出来的结果基本上相当于从直播服务器收到的原始数据。
有打算在 1.3 里加一个原始数据录制模式，不过现在还没有做，所以需要用 1.2 来采集样本。

给 1.3 加了一些记录日志的地方，试一下最新的版本 https://github.com/Bililive/BililiveRecorder/actions/runs/725671367
如果遇到了分段的问题的话发一下日志。

**Comment by Ksdb104** [comment]
这是用0.0.0.414录的文件的分析
[录制-1016-20210407-193115-星象学家随便玩.brec.xml.gz](https://github.com/Bililive/BililiveRecorder/files/6275580/-1016-20210407-193115-.brec.xml.gz)


这是0.0.0.440录制的日志,这次也有分段问题,但是并不明显
![image](https://user-images.githubusercontent.com/36178808/113958302-6d656080-9853-11eb-9feb-582b0c49b1d3.png)
[log.log](https://github.com/Bililive/BililiveRecorder/files/6275573/log.log)

**Comment by Genteure** [comment]
分段后录出来的文件是正常的吗？
从日志来看最后的这两个分段好像是重复的片段，应该是主播断开推流后直播服务器又向观众重复发送了两次最后一组数据。

你发的第一张图片里的那些文件还都有存着吗？有打开播放过吗？里面的内容正常吗？有没有重复片段？主要检查一下每个文件的开头和结尾，对比前一个文件的结尾和后一个文件的开头。

现在确定了为什么会触发分段了，但是我还没想好要不要改这个逻辑。
如果除了分了段以外其他完全没问题，可以改一下处理规则让它不分段。
但是如果有重复片段之类的情况，我感觉现在这样分段分开反而是最优处理方案，方便后期再处理。

**Comment by Ksdb104** [comment]
之前异常分段的片段我检察过,有一部分如你所说,另一部分则是
![image](https://user-images.githubusercontent.com/36178808/113975338-ed022800-9871-11eb-97bc-0c327420c93a.png)

我这里还有之前1.3录的异常文件打包,如果你需要的话
http://cure.huan-yue.org/video/20210331package.tar.gz
(巨大文件警告

**Comment by Genteure** [comment]
嗯。。那还是保持现状吧，感觉现在这样切开更合理。
有需要的话可以再用 ffmpeg 把主要片段拼起来，重复的小段就丢掉。
