### ISSUE TITLE
希望实现只录制弹幕的功能

### ISSUE THREAD

**Issue by Sodapopoo** [Bililive/BililiveRecorder#176]
以及希望能录制直播回放的弹幕，我在网上找了很多录制直播的方法，没有一个能实现只录制弹幕的需求，拜托了，因为我很想通过查找特定弹幕来锁定某个想看的直播片段，但无法录制弹幕的话就什么都做不到。

**Comment by Genteure** [comment]
本项目是以录制直播为主。如果要实现只录制弹幕需要的改动比较大。
因为需要的改动大+功能有点超纲，所以不打算实现。
