### ISSUE TITLE
希望加入录制直播回放的功能

### ISSUE THREAD

**Issue by Sodapopoo** [Bililive/BililiveRecorder#177]
这个录播姬功能很好，就是要求一台随时待机且拥有良好网络的电脑才能进行有效的录制，对我我这种网络不佳也没有闲置电脑的用户来说，更希望能录制b站自带的直播回放，如果增加这个功能有什么难点吗？

**Comment by HMBSbige** [comment]
直播回放直接用 IDM 之类的下载工具都能下，如果嫌麻烦可以试试 [BilibiliLiveRecordDownLoader](https://github.com/HMBSbige/BilibiliLiveRecordDownLoader)
