### ISSUE TITLE
[建议]增加录制条件：某直播间是否正在录制。（eg.若A正在录制，则B不录制。）

### ISSUE THREAD

**Issue by GrievedPear** [Bililive/BililiveRecorder#182]
喜欢的好几位up主他们彼此是好朋友，所以一般会一起开播，然后4-5个人播的是相同的游戏内容。
所以想问问看……可不可以加个判定条件？比如……若正在录制A的直播，那BCDE就都不录制。

嗯……就是不知道我这样的使用场景会不会只是挺少一部分？

**Comment by Genteure** [comment]
确实是个非常小众的需求，建议你直接修改代码来实现，在开始录制之前加一个判断。
之后有可能会考虑用一些其他方式实现类似的需求，不过近期肯定是不会做。
