### ISSUE TITLE
录制速度不稳定,导致录制的视频丢帧播放卡顿

### ISSUE THREAD

**Issue by 2314933036** [Bililive/BililiveRecorder#183]
已确保本地网络环境畅通,浏览器看多个直播间原画不卡
已在不同网络环境(移动有线100m/电信有线1000m/联通无线50m)下测试均存在该问题
问题描述:
录制时瞬间速度由5Mbps(正常速度)掉到0.6Mbps几秒后又飙到15Mbps
旧版本在网络畅通情况下没出现过此问题
1.2.*开始频繁出现此问题

**Comment by Genteure** [comment]
在QQ群里通过录播姬1.3的工具箱确认了是音视频时间戳错位的问题，是直播服务器给的数据本来就有问题
