### ISSUE TITLE
新版帧速率降低的问题

### ISSUE THREAD

**Issue by WithShadow000** [Bililive/BililiveRecorder#193]
对比了以更新前后录制的直播，更新后帧速率常出现20帧/s，少于以前的30帧/s

**Comment by Genteure** [comment]
使用的录制模式是什么？
是整个文件的平均FPS降低了吗？
整个文件的播放速度是否有异常？如播放速度看起来像是正常速度的 2/3
确定不是主播一侧网络不稳定所以丢帧导致的吗？
检查一下录播姬的日志里是否有记录修复过，日志文件在 `%localappdata%\BililiveRecorder\app-1.3.4\logs`
可以用工具箱里的导出分析数据（在“修复失败”按钮里面）导出一下有问题的文件，把导出的 `brec.xml.gz` 文件发一下。

**Comment by WithShadow000** [comment]
> 使用的录制模式是什么？
> 是整个文件的平均FPS降低了吗？
> 整个文件的播放速度是否有异常？如播放速度看起来像是正常速度的 2/3
> 确定不是主播一侧网络不稳定所以丢帧导致的吗？
> 检查一下录播姬的日志里是否有记录修复过，日志文件在 `%localappdata%\BililiveRecorder\app-1.3.4\logs`
> 可以用工具箱里的导出分析数据（在“修复失败”按钮里面）导出一下有问题的文件，把导出的 `brec.xml.gz` 文件发一下。

**Comment by WithShadow000** [comment]
我又试了一下旧版和其它库录播，发现都是20帧，应该是B站那边的问题，不好意思打扰了
