### ISSUE TITLE
1.3.4版本添加-w启动参数后无法启动录播姬

### ISSUE THREAD

**Issue by YukiRus** [Bililive/BililiveRecorder#194]
添加
```
 -w 路径 
```
如
```
C:\Users\username\AppData\Local\BililiveRecorder\BililiveRecorder.WPF.exe -w E:\bilibiliRecoder
```
启动参数后，双击录播姬图标无法启动，没有任何反应
不添加启动参数时可正常启动并设置录播保存路径

在之前版本中该功能正常

**Comment by Genteure** [comment]
从 1.3 开始这个参数改为了 `run "路径"`，在网站上1.3更新说明和常见问题里有写

**Comment by YukiRus** [comment]
> 从 1.3 开始这个参数改为了 `run "路径"`，在网站上1.3更新说明和常见问题里有写

好的，感谢
