### ISSUE TITLE
电脑从睡眠中唤醒后不会立即刷新直播开始录制

### ISSUE THREAD

**Issue by bojiwama** [Bililive/BililiveRecorder#199]
手动刷新直播间信息后会立即录制，否则需要等很久才会开始录制，是因为监控的直播间太多了吗（20多个）？
还有希望可以在上面菜单监控栏添加一个“立即刷新所有直播间信息”的按钮。

**Comment by Genteure** [comment]
现在的默认刷新间隔是10分钟一次，也不算特别长时间吧。添加一个刷新所有直播间信息的话，感觉容易有人把它像Windows桌面的刷新一样没事点两下，容易导致被屏蔽。
最简单的解决方案是直接关掉软件重开。

**Comment by bojiwama** [comment]
好的谢谢了解了
