### ISSUE TITLE
录播姬Docker版时区不正确

### ISSUE THREAD

**Issue by sola97** [Bililive/BililiveRecorder#203]
默认是UTC+0的，目前我是手动设置
`docker exec -it recorder ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`

**Comment by Genteure** [comment]
在 https://github.com/Bililive/BililiveRecorder/commit/9fa19da9f5d4a64744862936441608996eb69424 修改了时区为 Asia/Shanghai 
我现在没测试，不过应该没有问题
