### ISSUE TITLE
录制没有声音的流会导致出错

### ISSUE THREAD

**Issue by FovenX3** [Bililive/BililiveRecorder#204]
开始接收直播流
录制时发生了错误 no audio header tag avalible
录制结束
一直刷日志里一直刷这几行
流是用gstreamer 1.8推的 没有音频 纯视频流
b站客户端和网页端均可正常播放
b站网页端播放器调试界面
Mime Type: video/mp4; codecs="avc1.640028"
Player Core: fMp4Player (Fetch)
Video Info: 1920x1080, 24FPS, 2.6Mbps
Audio Info: NaNKHz, undefinedCh, 0Kbps
Encoder: GStreamer 1.18.4 FLV muxer
Stream Host: d1--cn-gotcha03.bilivideo.com
Buffer Length: 5.453s
Decoded Frames: 3/100, 0FPS
Download Bitrate:  0Mbps

**Comment by Genteure** [comment]
还有这种直播。。。
在设置里可以切换录制模式为原始数据模式，没有处理，不会检查 audio header

**Comment by FovenX3** [comment]
感谢!
