### ISSUE TITLE
命令行自动识别配置文件更新

### ISSUE THREAD

**Issue by FishMagic** [Bililive/BililiveRecorder#208]
目前命令版是否有办法在配置文件被修改后自动识别到，目前似乎只有在重启软件后才能让新的配置文件生效

**Comment by Genteure** [comment]
目前不能做到运行时重载配置

有兴趣的话可以试一下 `feature/web_api` branch 上的版本，加了个简单的 graphql API
<https://github.com/Bililive/BililiveRecorder/actions?query=branch%3Afeature%2Fweb_api>
能给点意见反馈就更好了。之后有可能在这个基础上继续写，也有可能推翻重来。

**Comment by FishMagic** [comment]
不知道有没有写API文档呢

**Comment by Genteure** [comment]
是 graphql 的，带了 4 个 graphql 的工具。
找了点之前截的图，供参考

<details>

![image](https://user-images.githubusercontent.com/11240579/124387553-b07b8680-dd11-11eb-81d5-6f1edb88e897.png)

![image](https://user-images.githubusercontent.com/11240579/124387563-b6716780-dd11-11eb-8e7a-9c1997e4085b.png)

![image](https://user-images.githubusercontent.com/11240579/124389695-d8231c80-dd1a-11eb-954a-51b4d3216bac.png)

![image](https://user-images.githubusercontent.com/11240579/124389714-f6891800-dd1a-11eb-9c12-369e020eb6ec.png)

</details>

**Comment by FishMagic** [comment]
请问通过这种形式修改的配置文件是否会自动写入config.json

**Comment by Genteure** [comment]
添加房间、移除房间、软件退出时会写入 `config.json`

**Comment by Genteure** [comment]
已经实现了 API
