### ISSUE TITLE
希望能设置录制码率

### ISSUE THREAD

**Issue by aabbcczhy** [Bililive/BililiveRecorder#209]
有的主播设置的码率很高，但本身不需要那么高码率的视频来存直播回放

**Comment by Genteure** [comment]
本项目不会对直播数据二次编码，所以不能设置录制码率

**Comment by aabbcczhy** [comment]
那有其他什么解决方案可以让录制的视频小点么

**Comment by Genteure** [comment]
录完之后再压制

现在不支持录低画质的流 #145 ，只能录原画
