### ISSUE TITLE
安装程序被安全中心报告Program:Win32/Uwamson.A!ml

### ISSUE THREAD

**Issue by tomtiao** [Bililive/BililiveRecorder#210]
在官网下载的安装包被安全中心报告[Program:Win32/Uwamson.A!ml](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Program%3aWin32%2fUwamson.A!ml&threatid=250070)，软件本身不会。

**Comment by Genteure** [comment]
它的分类是什么？是“潜在不需要的软件”吗？

**Comment by Genteure** [comment]
我已经提交了 false positive 了，如果顺利的话一两天内就能解决了。
之前版本的安装包也有被判断为 potentially unwanted application 的情况。

**Comment by tomtiao** [comment]
> 它的分类是什么？是“潜在不需要的软件”吗？

是的

> 我已经提交了 false positive 了，如果顺利的话一两天内就能解决了。
> 之前版本的安装包也有被判断为 potentially unwanted application 的情况。

不知 Windows Defender 根据什么判断的😂
