### ISSUE TITLE
考虑加入超过某时间后，强制停止录制的功能吗？

### ISSUE THREAD

**Issue by ashesofdream** [Bililive/BililiveRecorder#212]
有的主播会在正常直播完成后，接着放录播... 
希望可以设置成，只在某个时间段会进行录制。

**Comment by Genteure** [comment]
感觉可以通过 #184 来实现

**Comment by Genteure** [comment]
打算做这个功能，但没想好这个功能具体要怎么实现比较合理，你们有什么想法吗？

放一个日期时间输入框？两个时间输入框？只录制选定时间范围内的直播？
这样是不是就会导致每天都要修改一次设置？

这个时间范围的设置项和现有的“自动录制”之间的交互应该是什么样的？

---

合并到 #285 讨论吧，虽然这个 issue 比较早
