### ISSUE TITLE
特定情况下添加短号房间号会连接到错误的弹幕房间

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#216]
当网络断开时使用短号添加直播间（或添加房间时的请求出错），恢复后会使用短号而不是原房间号连接弹幕服务器。

**Comment by wpcwzy** [comment]
既然通过 https://github.com/Bililive/BililiveRecorder/commit/7dbcbb4069cea6d577bc8f448fa90762f66f4ec6 实现了网络状态检测，是否可以在 `NetworkAddressChanged` 时再次调用 `RefreshRoomInfoAsync` 来规避这个bug？

**Comment by Genteure** [comment]
这个是之前有一天我自己用的时候遇到的，因为觉得一般也不会有人在断网的时候添加房间，遇到这个问题的概率很小，就一直搁置着。

我还没有去梳理问题具体在哪，但我感觉你说的这个方案应该不能解决这个问题。
这个bug的原因是在请求直播间信息之前就连接弹幕服务器了，实际应该保证在连接弹幕服务器之前至少成功请求过一次直播间信息。

**Comment by Genteure** [comment]
fixed in 2.8.1
b826ebf611aa69a9594d2a77bb76e17c54a225e8
