### ISSUE TITLE
安装过程中的bug

### ISSUE THREAD

**Issue by calculusfan** [Bililive/BililiveRecorder#22]
点击安装文件安装时直接报错：
BililiveRecorder.WPF Setup
An error occurred attempting to install BililiveRecorder.WPF

点击details后进一步显示：
An error occurred trying to download 'https://soft.danmuji.org/BililiveRecorder/BililiveRecorder.WPF.application'.

See the setup log file located at 'C:\Users\ADMINI~1\AppData\Local\Temp\VSD5B1D.tmp\install.log' for more information.

测试平台win10，安装包为官网上下载的1.0.12.0

希望能尽快修正，谢谢

**Comment by calculusfan** [comment]
安装日志文件内容：

The following properties have been set:
Property: [AdminUser] = true {boolean}
Property: [InstallMode] = HomeSite {string}
Property: [NTProductType] = 1 {int}
Property: [ProcessorArchitecture] = AMD64 {string}
Property: [VersionNT] = 10.0.0 {version}
Running checks for package 'Microsoft .NET Framework 4.6.2 (x86 and x64)', phase BuildList
Reading value 'Release' of registry key 'HKLM\Software\Microsoft\NET Framework Setup\NDP\v4\Full'
Read integer value 461808
Setting value '461808 {int}' for property 'DotNet462Full_Release'
Reading value 'v4' of registry key 'HKLM\SOFTWARE\Microsoft\NET Framework Setup\OS Integration'
Read integer value 1
Setting value '1 {int}' for property 'DotNet462Full_OSIntegrated'
The following properties have been set for package 'Microsoft .NET Framework 4.6.2 (x86 and x64)':
Property: [DotNet462Full_OSIntegrated] = 1 {int}
Property: [DotNet462Full_Release] = 461808 {int}
Running checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-ENU.exe'
Result of running operator 'ValueEqualTo' on property 'InstallMode' and value 'HomeSite': true
Result of checks for command 'DotNetFX462\NDP462-KB3151800-x86-x64-AllOS-ENU.exe' is 'Bypass'
Running checks for command 'DotNetFX462\NDP462-KB3151802-Web.exe'
Result of running operator 'ValueNotEqualTo' on property 'InstallMode' and value 'HomeSite': false
Result of running operator 'ValueGreaterThanEqualTo' on property 'DotNet462Full_Release' and value '394802': true
Result of checks for command 'DotNetFX462\NDP462-KB3151802-Web.exe' is 'Bypass'
'Microsoft .NET Framework 4.6.2 (x86 and x64)' RunCheck result: No Install Needed
Launching Application.
URLDownloadToCacheFile failed with HRESULT '-2146697211'
Error: An error occurred trying to download 'https://soft.danmuji.org/BililiveRecorder/BililiveRecorder.WPF.application'.

**Comment by Genteure** [comment]
你这一侧的网络问题导致。
尝试更换网络环境再试，或尝试换个 DNS 服务器，最近有不少 DNS 问题。
今天会更换安装方式，不再用 ClickOnce
