### ISSUE TITLE
可以考虑使用AvaloniaUI跨平台

### ISSUE THREAD

**Issue by seayxu** [Bililive/BililiveRecorder#221]
传送门: [AvaloniaUI](https://github.com/AvaloniaUI/Avalonia)

**Comment by Genteure** [comment]
之前有了解过，没有使用的主要原因有：

- 对 CJK 字符以及输入法的支持还不太完善
- 几个版本之前我运行Demo测试时很容易崩溃
- 如果在 Windows 上使用，编译输出的文件大小有点太大了
- 如果在 Linux 上使用，API + Web UI 的方案更合理一些

我不是很了解有多少人有在 Mac 上使用的需求，我也没有 Mac 设备

**Comment by seayxu** [comment]
现在应该好些了

**Comment by Genteure** [comment]
现在已经有 API + WebUI 了，就不考虑用 AvaloniaUI 了
