### ISSUE TITLE
优化一下录播姬的日志界面

### ISSUE THREAD

**Issue by Randark-JMT** [Bililive/BililiveRecorder#222]
录播姬的日志界面现在看起来只能显示一小段时间的日志，并且最新的日志需要手动拉到页面最底下才能看得到
希望未来版本能加入日志的分类显示系统（想Windows事件那样子），以及延长日志显示的时间范围，并让日志自动显示最新一条
还有，日志界面的标题不补一下吗，空空的怪难受
![图片](https://user-images.githubusercontent.com/56223739/126890544-20996ca3-c469-40e4-9598-ed77988035d7.png)

**Comment by Genteure** [comment]
分类有点麻烦，感觉必要性也不大。
其他的近期会修改一下。
