### ISSUE TITLE
XML 弹幕合并

### ISSUE THREAD

**Issue by inkydragon** [Bililive/BililiveRecorder#223]
录制的视频可以拿 ffmpeg 合并。

XML 弹幕看起来只能自己写程序合并。
希望能提供 XML 合并的功能，命令行接口就行。

----

目测合并弹幕需要改动的地方有：
+ `<BililiveRecorderRecordInfo start_time="2021-04-09T21:08:36.8202743+08:00" />` 这里以第一个 XML 文件为准
+ `<gift ts="2.2189212" />` 礼物的时间戳均以 `start_time` 重新计算
+ `<d p="3.9307257,1,25,14893055,1617973720751,0,16182201,0" />` 弹幕时间戳同上

不知道 raw 里面的内容有没有需要修改的。

另外由于直播时可以修改直播标题，且直播时间很容易跨日期。目前来看不太好自动化的确定哪些 XML 属于一场直播。
可能按  `start_time` 计算两个 XML 之间的时间距离，然后无监督聚类比较可行。
xref: #114

**Comment by Randark-JMT** [comment]
@inkydragon 之前已经有人写过合并弹幕文件的轮子了（不过是Python的）
如果只是自己需求的话，可以考虑使用这个项目
https://github.com/valkjsaaa/danmaku_tools
至于判断两个xml文件是否属于同一场直播，个人认为不仅仅可以看时间间隔，也可以Webhook自动化

**Comment by Genteure** [comment]
之后会做。也可以用 [valkjsaaa/danmaku_tools](https://github.com/valkjsaaa/danmaku_tools)

**Comment by Genteure** [comment]
已实现，下个版本发布
