### ISSUE TITLE
使用vps运行经常显示与弹幕服务器断开连接

### ISSUE THREAD

**Issue by xiaocainiao2020** [Bililive/BililiveRecorder#235]
使用vps录制，经常显示与弹幕服务器断开连接，如果在录制的时候显示断开就导致弹幕录的不全有丢失。用本地的电脑就不会有这种情况。

**Comment by Randark-JMT** [comment]
建议贴出来录播姬当时的日志文件，以及建议使用国内靠谱的VPS，已知B站国外的服务器存在玄学问题

**Comment by Randark-JMT** [comment]
@xiaocainiao2020 建议贴出来录播姬当时的日志文件，以及建议使用国内靠谱的VPS，已知B站国外的服务器存在玄学问题
