### ISSUE TITLE
设置：自动转码和执行脚本

### ISSUE THREAD

**Issue by mingl0280** [Bililive/BililiveRecorder#243]
希望能增加功能：RecordTask_RecordFileClosed会自动调用（可设置的）用户脚本或者程序，用来执行一些自动的转码工作之类的。

**Comment by Genteure** [comment]
调用命令不太好传参数，而且目前有 webhook 功能了，可以直接用 webhook 来实现。
可以用 nodejs / python 之类的写个脚本，侦听一下 127.0.0.1，然后接收到 HTTP POST 的时候执行命令。
或者不想手写代码的话可以用 node-red 或者 n8n.io 这种项目。

**Comment by mingl0280** [comment]
> 
> 
> 调用命令不太好传参数，而且目前有 webhook 功能了，可以直接用 webhook 来实现。
> 可以用 nodejs / python 之类的写个脚本，侦听一下 127.0.0.1，然后接收到 HTTP POST 的时候执行命令。
> 或者不想手写代码的话可以用 node-red 或者 n8n.io 这种项目。

我自己已经加了，不过我并没有修改配置文件，是写死的。
方法是BililiveRecorder.Core: Room.cs: RecordTask_RecordFileClosed()
添加
``` C#
            this.basicDanmakuWriter.Disable();
// Add start
            Process p = new()
           {
                StartInfo = new ProcessStartInfo {FileName = "PostExec.exe", Arguments = e.FullPath} 
                // 这里的PostExec.exe可以换成任意配置好的程序或者命令，如果你想用参数化的话，
                // 这里的Arguments内容可以替换为其它的格式化字符串。例如用String.Replace("{FullPath}",e.FullPath)之类的。
            };
            p.Start();
// Add end
            RecordFileClosed?.Invoke(this, e);
```
不用webhook纯粹是因为不想再多开个node……
