### ISSUE TITLE
SRT推流出现音视频数据错位问题

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#244]
新的问题：
通过 SRT 协议推流、视频 60 FPS、音频 44.1 kHz 时，出现了计算结果为最大偏移 16 ms、最小偏移 17 ms 的情况。
修改音频到 48 kHz 后可以正常计算出来偏移 16 ms。

还需要再观察

如果遇到了这个问题，临时解决方法是切换录制模式为“原始数据”

潜在解决方法：如果计算结果只差了 1 ms 不成立，就直接忽略

**Comment by Genteure** [comment]
收到邮件反馈又有一个人遇到了此问题，看起来也是 SRT 60FPS 44.1KHz

猜测：可能时间戳是正确的，但是音频的位置（发送顺序）比视频靠后了一位。又因为 60 FPS 下一帧是大约 16 ms，所以计算出的偏移量大概是 16 ms。

---

SRT 60FPS 48KHz 的情况下，目前的修复逻辑会持续计算出偏移量 16 ms

目前我还没能成功复现 SRT 推流导致音视频数据错位的情况，没法确认到底是数据的顺序错了还是相对时间戳错了，猜测可能是顺序错了。

**Comment by 77580** [comment]
在原始数据录制模式时如果点停止录制，录制的视频虽然可以播放，但时长显示是00：00，至少我用的vlc播放器是这样，只有主播下播程序自动结束录制时时长显示正常

**Comment by Genteure** [comment]
@77580 总时长显示 00:00 是符合预期的，有的时候能显示出来总时长也是正常情况，这个和是不是自动结束的没有直接关联，是由直播服务器给的数据决定的。

Edit: 好像有可能有关联，不过也算是符合预期吧
