### ISSUE TITLE
命令行使用配置文件后无法正常启动

### ISSUE THREAD

**Issue by xzajyjs** [Bililive/BililiveRecorder#248]
## 使用命令./BililiveRecorder.Cli run "..."后一直卡在第一步“弹幕服务器已连接”，然后就没有下一步了(配置文件是通过win移植过去的，后来测试了configure自动生成，也不行)。而不使用配置文件./BililiveRecorder.Cli portable "..." 1 2 3 4 5后则可以正常录制。

**Comment by xzajyjs** [comment]
使用的是本地linux虚拟机和阿里vps，都不行

**Comment by Genteure** [comment]
有启用自动录制吗？

**Comment by xzajyjs** [comment]
找到症结了，原来是那个直播间关掉了。现在测试一个正在直播的直播间就可以正常录制了
