### ISSUE TITLE
请问直播画质原画以外的id在哪里查看

### ISSUE THREAD

**Issue by 77580** [Bililive/BililiveRecorder#249]
现在只知道原画是10000，看了之前的issue知道4k是20000，那请问蓝光是多少呢，试了4000，6000好像都没什么用

**Comment by shugen002** [comment]
蓝光属于从原画压缩出来的画质，有没有什么录制的必要吗？

**Comment by Genteure** [comment]
画质 | ID
:--:|:--:
4K | 20000
原画 | 10000
蓝光(杜比) | 401
蓝光 | 400
超清 | 250
高清 | 150
流畅 | 80
