### ISSUE TITLE
录制画质能否更加智能？

### ISSUE THREAD

**Issue by LazzyFatty** [Bililive/BililiveRecorder#250]
比如今天我录B站中秋晚会录着玩，上了鬼子的洋当了，原画画质的ID是10000，可是网页上还有一个4K，日志上写着画质代码是20000
能否增加一个功能，让直播姬录制最高画质？
还是说除了B站自己的活动，没有别的直播会用到比原画更高的画质？

**Comment by Genteure** [comment]
确实，除了B站自己的活动，没有别的直播会用到比原画更高的画质。
主播推流上去就是原画，不管实际推流到底是什么内容，720P 1080P 4K 8K 全都是原画。
4K 这个画质只有B站做的活动才会有，属于特殊情况。

**Comment by 6Bpencle** [comment]
现在大部分B站自己的活动的4K是从原画1080P直接拉伸成4K的，非常糊。去年是直接推的4K

**Comment by Genteure** [comment]
现在设置里就有画质ID的设置，需要录4K的话就设置成 `20000,10000` 就行了
