### ISSUE TITLE
Feature request:希望托盘预览加入开播图示

### ISSUE THREAD

**Issue by vincentkilua** [Bililive/BililiveRecorder#251]
就是现在鼠标放在托盘图标上会有预览，会显示监控中和录制中，希望能把开播中的图标也塞进去

感谢作者

**Comment by ChenZhuoSteve** [comment]
如果录制中能直接在系统托盘看到这个状态，确实更直观

**Comment by Genteure** [comment]
已在 https://github.com/Bililive/BililiveRecorder/commit/7669c865fe7baa72171ba0450f57113161f02623 实现
