### ISSUE TITLE
关于报错

### ISSUE THREAD

**Issue by ADY-ZAT** [Bililive/BililiveRecorder#252]
运行日志显示了报错，但同时间内的相关录播没有出现异常
![9F@1HOMYC ZWS94 _B~QGR](https://user-images.githubusercontent.com/87921949/136389767-ea2bb07a-9c1c-4380-b8d2-9f89129cabcf.png)

**Comment by Genteure** [comment]
主播在网页上点了开始直播，直播间状态是直播中，但是还没有在直播软件里开始推流的时候，直播服务器会返回 404 Not Found，是正常情况。

**Comment by tomtiao** [comment]
![image.png](https://i.loli.net/2021/11/07/TX7gzjqlFMZsyko.png)
日志中提示Not Found，且录制会停止。
场景是手机在客户端直播，PC使用软件录制。手机一直处于推流状态，网页端观看直播没有中断现象。
