### ISSUE TITLE
qn画质设置仅在中途开启录播时起效

### ISSUE THREAD

**Issue by catbule** [Bililive/BililiveRecorder#257]
主播刚开播时，直播间有且仅有原画选项。如果录播姬从头开始监听直播，录播姬仅能以原画方式录完整场直播，失去画质设置的意义。
可否增加可选择项，仅录制而不是优先录制指定画质直播。
或者添加延时录制功能，开播指定时间后启动录制。

**Comment by Genteure** [comment]
确实是有这个问题，之后会改成严格遵守设置的画质ID

**Comment by Genteure** [comment]
已实现 https://github.com/Bililive/BililiveRecorder/commit/06a4c59bb764679db91ec7db279072ddf04d3bfe
今天晚点发新版本
