### ISSUE TITLE
录制文件位置超出允许范围，请检查设置。将写入到默认路径。

### ISSUE THREAD

**Issue by ddaodan** [Bililive/BililiveRecorder#259]
因为vps硬盘太小，我就把路径改成一个非录播姬所在的路径，但是录制的时候提示：录制文件位置超出允许范围，请检查设置。将写入到默认路径。

录播姬所在路径是"root/luboji/"，配置文件里我填写的保存路径是"/root/录播/录制-{roomid}-{date}-{time}-{title}.flv"

**Comment by Genteure** [comment]
把 `config.json` 移动到 `/root/录播/` 里，然后启动命令换成 `/root/luboji/BililiveRecorder.Cli run /root/录播/`。
为了防止设置不小心改错导致录播文件写到不知道什么地方了，文件的路径只允许在启动时指定的目录里面。

**Comment by ddaodan** [comment]
> 把 `config.json` 移动到 `/root/录播/` 里，然后启动命令换成 `/root/luboji/BililiveRecorder.Cli run /root/录播/`。 为了防止设置不小心改错导致录播文件写到不知道什么地方了，文件的路径只允许在启动时指定的目录里面。

感谢，已解决
