### ISSUE TITLE
希望可以在命令行版本添加无配置文件的原始数据录播模式

### ISSUE THREAD

**Issue by waitsaber** [Bililive/BililiveRecorder#262]
当前的命令行版在使用无配置文件模式运行的时候程序执行的是默认的标准模式，希望可以添加原始数据模式，在有些时候标准模式会导致录播碎片化，无配置文件模式可以更方便的运行。

**Comment by Genteure** [comment]
已实现 5a5f5b6239548c7486b8365ea1971d465bd1bdd6
