### ISSUE TITLE
无法支持付费直播的录制

### ISSUE THREAD

**Issue by HayashiKaori** [Bililive/BililiveRecorder#263]
测试房间：22377146
这种直播需要B站账号买票才能看（比如线上演唱会），建议支持账号登陆录制。

**Comment by Radekyspec** [comment]
录播姬桌面版支持使用B站cookie登录
方法：在桌面版右键两次设置会出现高级设置的选项，可以在此处填写cookie
![0e6908a50a1bacc8f892dc306706e9b](https://user-images.githubusercontent.com/93813543/144711088-376bf2ad-2c66-40bc-bac9-2f58750c25f6.png)
![46cc61d7306d71e6326e092743b3c20](https://user-images.githubusercontent.com/93813543/144711091-f20835bb-9902-4c1b-94d9-718242e4f68f.png)

**Comment by HayashiKaori** [comment]
谢谢 @Radekyspec 
我搞明白了，复制 Cookie 字符串到配置项，牛逼啊！
![图片](https://user-images.githubusercontent.com/57685624/144711440-bd6d5bd6-ccf5-454c-b5f9-481ac49b66cf.png)
