### ISSUE TITLE
如何在每次启动的时候自动录制全部房间

### ISSUE THREAD

**Issue by WithShadow000** [Bililive/BililiveRecorder#264]

**Comment by Genteure** [comment]
就。。设置为自动录制？

**Comment by WithShadow000** [comment]
> 就。。设置为自动录制？

就比如前一天有几个房间取消了自动录制，然后希望第二天重新启动录播姬的时候所有房间都是自动录制，有没有什么启动项参数之类的

**Comment by Genteure** [comment]
没有。

两个实现这个效果的方法：

1. 不要取消自动录制，而是点“停止录制”。界面上会出现一个新的图标，并且临时禁用自动录制，直到主播**关闭**直播。
2. 你可以写个脚本，在启动录播姬之前修改配置文件，把自动录制改成 `true`。
