### ISSUE TITLE
实现对第三方接口的推送

### ISSUE THREAD

**Issue by LxnChan** [Bililive/BililiveRecorder#267]
比如在开播、录制、断流等问题时推送到第三方接口（企业微信、个推、PushBot等）上面提醒用户。

这个主要体现在服务器挂机监控，感觉会比较有用。

**Comment by Genteure** [comment]
可以用 webhook + 自己写个脚本来实现，可以用你个人比较熟悉的语言，nodejs python 之类的都可以。
webhook 文档：https://rec.danmuji.org/docs/basic/webhook/

开播通知的话目前是没有的

**Comment by Genteure** [comment]
现在还是推荐基于 webhook 实现。
现在已经添加了开播通知的 webhook。
