### ISSUE TITLE
问个问题。B站的原画码率显示10M可以我录下来重封装mkv就成了8M

### ISSUE THREAD

**Issue by Fuchalicious** [Bililive/BililiveRecorder#271]
https://live.bilibili.com/6
录制中显示8M，文件Bit rate显示10 000 kb/s，是腾讯的问题还是B站的问题还是…
B站播放直播显示数据还是10M
General
Complete name               : F:\1\新建文件夹 (2)\7734200-哔哩哔哩英雄联盟赛事\录制-7734200-20220123-150003-629-【直播】 AL vs WBG.flv
Format                      : Flash Video
File size                   : 9.01 MiB
Duration                    : 11 s 398 ms
Overall bit rate            : 6 631 kb/s
Writing application         : Lavf58.29.100
_displayWidth               : 1920.000
_displayHeight              : 1080.000
_fps                        : 60.000

Video
Format                      : AVC
Format/Info                 : Advanced Video Codec
Format profile              : High@L4.2
Format settings             : CABAC / 4 Ref Frames
Format settings, CABAC      : Yes
Format settings, Reference  : 4 frames
Codec ID                    : 7
Duration                    : 11 s 383 ms
Bit rate                    : 10 000 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 60.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Scan type                   : Progressive
Bits/(Pixel*Frame)          : 0.080
Stream size                 : 13.6 MiB

**Comment by Genteure** [comment]
metadata 里的 bitrate 是可以随便写的，写个 99999999 进去都可以，甚至可以写负数或者`NaN`。
最终肯定是以实际的数据量为准，视频数据大小/时间。
