### ISSUE TITLE
特殊环境运行出现程序失效问题

### ISSUE THREAD

**Issue by wjcwqc** [Bililive/BililiveRecorder#274]
腾讯云函数 终端 薅羊毛会出现下列情况
1. 执行命令报错：Segmentation fault      (core dumped) nohup ./BililiveRecorder.Cli run rec/
1. 无回显且不执行
1. 执行成功
为了让他后台跑 我用nohup和&，挂起到后台
所以我每次都启动多个，根据最终top确定成功运行的进程，在杀死进程，希望排查一下那里有问题，我一开始还以为环境问题，最后发现可以跑，但是有概率，所以应该不是环境问题。或者触发某种机制，希望解决一下。简单点就是确定程序正常运行而不是挂在后台啥也不干，测试情况随便多开可以，因为直播间开关在自己手上，实际情况不可能从外部确认这个程序跑没跑，希望检测一下保证稳定性。

**Comment by Genteure** [comment]
没太看懂。

至少提供一个具体的复现步骤吧。
具体什么环境？什么系统？怎么操作的？配置文件内容是啥？“每次启动多个”是啥意思？为啥每次启动多个？“直播间开关在自己手上”？
