### ISSUE TITLE
[BUG反馈]出现直播间识别错误，分段录制

### ISSUE THREAD

**Issue by Harrydi2006** [Bililive/BililiveRecorder#275]
上图：
![GIF 2022-1-29 22-39-11](https://user-images.githubusercontent.com/50307581/151665177-0a03a2da-7dc4-4ba4-9af0-e34837ea776b.gif)
![微信截图_20220129224010](https://user-images.githubusercontent.com/50307581/151665179-8a85dd54-b557-479d-906d-361768a3b589.png)

**Comment by qqqianye** [comment]
我也遇到这个问题， 不停的在监测和录制之间跳动，产生很多几M的录制文件，我自己把自己的梯子关了就好了，但是这样边录制边上网就很不方便。。。。。
按说国内url，明明不走梯子为啥会被影响到呢

**Comment by Genteure** [comment]
@Harrydi2006 应该是 #244 这个问题，可以把录制模式改成原始数据模式，就可以录了。

@CyanTailwinds 不要开全局代理。

**Comment by rubbish-wang** [comment]
@Genteure 今天我也遇到了这种问题，一直在不停的在监测和录制之间跳动，然而我是没开梯子，录制模式标准和原始都试过了，电脑重启，切换至手机流量也还是这样

**Comment by Genteure** [comment]
@rubbish-wang 看一下日志，发一下日志文件。不想公开的话可以发到 `rec@danmuji.org`

**Comment by rubbish-wang** [comment]
@Genteure 已发

**Comment by Genteure** [comment]
@rubbish-wang 你的应该是服务器问题，是服务器主动断开的，如果视频内容看起来没问题可以用 ffmpeg 直接拼起来。

**Comment by EarthTuzki** [comment]
> 看一下日志，发一下日志文件。不想公开的话可以发到 `rec@danmuji.org`

这几天我也出现了这种问题，在检测和录制之间跳动，色条在红色下行和绿色上行之间跳动…产生的都是几秒钟的片段，日志里全是类似的内容：

"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"Logging","C":"收到了 onMetaData","$type":"ProcessingComment"}],"RoomId":80397,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":4344,"ThreadId":130}
"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"TimestampOffset","C":"音视频时间戳偏移, D: 16","$type":"ProcessingComment"}],"RoomId":80397,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":4344,"ThreadId":58}
"修复逻辑输出 {@Comments}","@l":"Debug","Comments":[{"T":"Unrepairable","C":"出现了无法计算偏移量的音视频偏移","$type":"ProcessingComment"}],"RoomId":80397,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":4344,"ThreadId":236}
"根据修复逻辑的要求结束录制","RoomId":80397,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":4344,"ThreadId":236}
"录制结束","RoomId":80397,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":4344,"ThreadId":236}

不知道是为啥捏···求教，谢谢。@Genteure

**Comment by rubbish-wang** [comment]
@Genteure @sm19951010 你艾特错了，我的大概率是网络环境问题，现在已经解决

**Comment by EarthTuzki** [comment]
@rubbish-wang 尴尬了，谢谢！我倒是没有开代理之类的，明儿我重启下光猫路由试试看。

**Comment by qqqianye** [comment]
我这边观察了一下全局代理的日志，发现有个smtcdns.net的URL走了代理，会造成服务器把我踢掉。把这个网址加入直连规则后，程序表现正常了
