### ISSUE TITLE
用命令行版遇到的问题，无法建立 SSL 连接

### ISSUE THREAD

**Issue by xiaozhou2013** [Bililive/BililiveRecorder#276]
在Linux服务器(腾讯轻量)上用命令挂好了程序，但一直弹无法建立 SSL 连接
![2022-02-08 16-08-54](https://user-images.githubusercontent.com/99242277/152944718-aefa54ea-7dd6-4b32-9618-911dad436433.png)
谢谢！

**Comment by Genteure** [comment]
这个问题之前也遇到过几次，都是用的 Centos
我不知道原因，但是我自己在腾讯云上新开的 Centos 服务器是可以正常使用的
可以试一下命令 `sudo yum install -y ca-certificates`

Image transcription for search:
```
Systenm.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
--> System.Security.Authentication.AuthenticationException: The remote certificate is invalid because of errors in the certificate chain: PartialChain
```

**Comment by xiaozhou2013** [comment]
执行命令后重启服务器依然这样，还有其他方法吗？
录播姬我放在/usr/bin下执行的，之前没拷完报了次无Net库，用的linux-x64版没用linux-arm64（不知道两个的区别），开了443,80的端口的
![2022-02-08 22-18-06](https://user-images.githubusercontent.com/99242277/153008687-cdcbd5f1-85cd-4f4e-a73a-c7f7d7434f9f.png)

**Comment by Genteure** [comment]
我不知道怎么解决
搜了一下以前也有 issue 是相同的问题，是直接重装了个系统 #253
