### ISSUE TITLE
希望添加一键/自动刷新房间信息相关功能

### ISSUE THREAD

**Issue by SyuueenN** [Bililive/BililiveRecorder#277]
有时启动正好碰上网络故障、拨号等原因，此时如果疏忽没注意就会持续显示[☁❗]不加载出相关信息而不录播。手动挨个刷新时，往往数量庞大造成冗长的手动作业。希望就这点增加一些功能，谢谢！

**Comment by Genteure** [comment]
因为如果频繁发送请求会被屏蔽，所以录播姬的设计是尽量少发请求。
现在默认主动刷新直播间信息的时间间隔是10分钟。

你说的这个情况也可以直接重启一下软件，也能达到同样的效果。

**Comment by Genteure** [comment]
已实现 https://github.com/BililiveRecorder/BililiveRecorder/commit/fadb90f48789b178555298af6ac32234e8f9cb0a
