### ISSUE TITLE
在 Github Actions 里运行 cli 无法加载 config.json

### ISSUE THREAD

**Issue by yjl9903** [Bililive/BililiveRecorder#278]
## 复现

1. 创建一个新的 repo
2. 在根目录下创建 `config.json`
3. 创建一个 actions，编辑 `.github/workflows/test.yml`

```yml
name: Record

on:
  push:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BililiveRecorder
        run: |
          wget https://github.com/Bililive/BililiveRecorder/releases/download/v1.3.11/BililiveRecorder-CLI-linux-x64.zip
          unzip BililiveRecorder-CLI-linux-x64.zip -d ~
          echo ~/linux-x64 >> $GITHUB_PATH
          rm -rf BililiveRecorder-CLI-linux-x64.zip
          ~/linux-x64/BililiveRecorder.Cli --version
      - name: Record
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Go')
            console.log('Path:', process.cwd())
            const record = async () => {
              await exec.exec('BililiveRecorder.Cli', ['--version']);
              await exec.exec('BililiveRecorder.Cli', ['run', './']);
            };
            const sleep = new Promise(res => {
              setTimeout(() => res(), 30 * 1000);
            });
            await Promise.race([record(), sleep]);
            console.log('OK')
            process.exit(0);
      - run: |
          ls -l .
          ls -l logs
          cat logs/bilirec20220213.txt
          # 修改日志日期
```

![image](https://user-images.githubusercontent.com/30072175/153762666-6d1e9798-f209-45d9-815d-7b241a0dc925.png)

**Comment by Genteure** [comment]
你这个是很明确的 abuse。。。。会被 disable 的
在 [GitHub Terms for Additional Products and Features 的 Actions 段落](https://docs.github.com/en/github/site-policy/github-terms-for-additional-products-and-features#actions) 里明确写了

> - any activity that places a burden on our servers, where that burden is disproportionate to the benefits provided to users (for example, don't use Actions as a content delivery network or as part of a serverless application, but a low benefit Action could be ok if it’s also low burden); or
> - if using GitHub-hosted runners, any other activity unrelated to the production, testing, deployment, or publication of the software project associated with the repository where GitHub Actions are used.


并且也有已经被 disable 的例子了，比如这个 https://github.com/auqhjjqdo/Kano-Live-Record/actions

-----

至于无法加载 config.json 的原因，是因为你没有把 repo 里的文件 clone 到 Action Runner 里面。
你在最后一步 ls 列出的 config.json 是录播姬新创建的。
参考资料： https://github.com/actions/checkout
