### ISSUE TITLE
[Feature] 希望能够指定软件强制使用ipv4

### ISSUE THREAD

**Issue by PeanutMelonSeedBigAlmond** [Bililive/BililiveRecorder#279]
背景：
在某些网络环境（比如我，教育网环境）下，程序会使用ipv6连接`api.bilibili.com`，`api.live.bilibili.com`等接口，会导致网络连接超时，无法获取房间/开播信息，但是使用ipv4连接就没有这个问题

请求：
希望能够加入选项，让软件强制使用ipv4连接

谢谢

**Comment by Genteure** [comment]
有什么原因不能直接禁用系统的 IPv6 吗？

**Comment by PeanutMelonSeedBigAlmond** [comment]
> 有什么原因不能直接禁用系统的 IPv6 吗？

因为这个服务器对外提供了一些依赖于IPV6的服务，所以没法禁用系统的IPV6服务，而且我也没有改这些东西的权限(っ °Д °;)っ

**Comment by Genteure** [comment]
我感觉可能有点困难，如果自己手动请求一下 DNS 然后照着 IP 地址来发请求的话应该也能实现。

可以先照着这个[微软文档](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/enabling-and-disabling-ipv6)改一下配置文件试试，不过我感觉可能会没有效果？这个文档里的信息看起来不像是很准确的感觉。

**Comment by PeanutMelonSeedBigAlmond** [comment]
感谢，我看了一下你所说的方法，发现

1. B站的接口是套了CDN的，因此如果直接用**ip地址+请求头host字段**发请求的话，估计不行

2. 这个文档貌似只写了Windows系统的配置，我这系统是Ubuntu

3. 我能想到的方法是：在代码里面自定义DNS，把ipv6的ip过滤掉 ~~，因为我不会写C#所以不知道怎么处理~~

谢谢

**Comment by Genteure** [comment]
1 在技术上是可行的啊，如果有 HTTP 302 跳转的话每一步都自己请求 DNS 然后照着对应的 IP 发请求就行了。

3 不可行，没有针对一个进程单独设置 DNS 服务器的接口，是跟随系统的。

在 Ubuntu 上的话，可以考虑丢到 docker 里面运行，也算是个 workaround。
会有一个独立的网络环境，可以单独设置 DNS 和禁用 ipv6。docker 好像默认都没有开 ipv6。
