### ISSUE TITLE
希望桌面版本增加黑白主题选择

### ISSUE THREAD

**Issue by rainyorange** [Bililive/BililiveRecorder#281]
用电脑录播有时会在半夜被Windows updated gank 息屏完全不知道被gank了 只能切黑壁纸亮屏录播
希望增加黑色主题

**Comment by Genteure** [comment]
![image](https://user-images.githubusercontent.com/11240579/154706149-7f9b054a-6b43-4384-9839-f6486f5e1301.png)
像这样？现在就有了，是跟随 Windows 系统设置的。
