### ISSUE TITLE
是否可以添加仅录制直播弹幕的模式

### ISSUE THREAD

**Issue by axojhf** [Bililive/BililiveRecorder#287]
有时候可能仅需要录制弹幕而不需要录制视频

看了下代码，能否让一个新的类继承[IRecordTask](https://github.com/Bililive/BililiveRecorder/blob/dev/BililiveRecorder.Core/Recording/IRecordTask.cs)来不处理视频数据

**Comment by Genteure** [comment]
技术上是可以的，但是应该不会把这个功能加到本体里。
主要是录制的开始和结束不太好控制，现在的判定逻辑完全是针对录直播视频写的。
有需要的话可以 fork 一下自己改一个版本用。

**Comment by axojhf** [comment]
谢谢了，好像确实不好控制，我在本地fork了一个现在采取的是自动录制+强制退出的方法控制

**Comment by Genteure** [comment]
相关的一个大饼 #185 但是我感觉这个功能应该是不会做了。。
如果有 24*7 录弹幕的需求，也可以在 GitHub 上找一下其他专门录弹幕的项目。
