### ISSUE TITLE
能否选择屏蔽免费礼物？

### ISSUE THREAD

**Issue by 2267184123** [Bililive/BililiveRecorder#288]

**Comment by Genteure** [comment]
这个功能可以通过新的[用户脚本](https://rec.danmuji.org/user/user-script/)实现。
不添加新的设置是因为如果每个人的每个弹幕过滤需求都加一个新的设置，要不了多久设置页里就全是各种弹幕过滤开关了。

一个过滤免费礼物的脚本例子: https://github.com/BililiveRecorder/recorder-scripting-template/blob/main/examples/example-1.js

这个设置项在软件的高级设置里，WPF版的高级设置打开方法是鼠标右键两次界面左下角的设置按钮。
关于设置的网站文档还没写好，之后会完善一下。
