### ISSUE TITLE
每次直播自动建立文件夹

### ISSUE THREAD

**Issue by Jue-Xu** [Bililive/BililiveRecorder#290]
希望能每次直播自动建立文件夹，文件夹名为直播开始时间+房间号，此次录播文件存储在这个文件夹内。如果直播断开超过一定时间后（比如半小时）再度开播，建立一个新文件夹。这样能使文件整理查看更加方便

**Comment by Genteure** [comment]
应该可以通过新的文件名模板来实现
现在在一个独立的 branch 上 https://github.com/Bililive/BililiveRecorder/tree/feature/fluid_filename

**Comment by Genteure** [comment]
已经在 https://github.com/Bililive/BililiveRecorder/commit/2fe47fd6f1fa8001ef7dce8dce8d5e38feed8176 里实现。
文档： https://rec.danmuji.org/user/file-name-template/#json

近期应该还发不了正式版，急着用的话可以从 GitHub Actions 里下编译好的二进制，不过开发版不保证每个版本都能用。
