### ISSUE TITLE
是否有开发WebUI（for docker/command line）的打算

### ISSUE THREAD

**Issue by Jue-Xu** [Bililive/BililiveRecorder#291]
或者已经有了第三方WebUI

**Comment by Genteure** [comment]
是有这个打算，但不知道啥时候会做。也有可能会咕掉（

**Comment by Genteure** [comment]
在 [feature/web_api2](https://github.com/Bililive/BililiveRecorder/tree/feature/web_api2) 里更新了个 graphql api

**Comment by Genteure** [comment]
现在有 Web UI 了 https://github.com/BililiveRecorder/BililiveRecorder-WebUI
本仓库的 [GitHub Actions](https://github.com/BililiveRecorder/BililiveRecorder/actions) 从 dev 分支上编译出来的可执行文件里内置了一份。
或者可以在 https://webui.rec.danmuji.org 使用独立的 Web UI。

**Comment by Jue-Xu** [comment]
感谢！

Best,
Jue

**Comment by Jue-Xu** [comment]
希望给WebUI添加一个backup/restore配置文件的选项
