### ISSUE TITLE
docker数据卷权限问题

### ISSUE THREAD

**Issue by 123485k** [Bililive/BililiveRecorder#292]
在运行docker版的时候，会把挂载的数据卷下的文件的权限全部变为`root:root`，是否可以通过传入环境变量的方式来控制被挂载数据卷，如`/rec`下的文件权限变为传入环境变量对应的值？

**Comment by Genteure** [comment]
没有做这个功能，可以用 docker 本身的用户参数来实现

`docker run -u 1000:1000 --name recorder .....`

参考文档：https://docs.docker.com/engine/reference/run/#user

或 docker-compose 的 `user` 参数
文档： https://docs.docker.com/compose/compose-file/compose-file-v3/#domainname-hostname-ipc-mac_address-privileged-read_only-shm_size-stdin_open-tty-user-working_dir
