### ISSUE TITLE
可否添加一个录制结束后自动执行某脚本的选项

### ISSUE THREAD

**Issue by dongchiz** [Bililive/BililiveRecorder#294]
设想的用途为自动录播后自动上传

如果可以通过已有功能实现还请指出

**Comment by stackinspector** [comment]
已有的webhook就是为了解决这个问题，你可以研究一下如何使用

**Comment by dongchiz** [comment]
> 已有的webhook就是为了解决这个问题，你可以研究一下如何使用

thanks，我去学习一下

**Comment by dongchiz** [comment]
翻了一下之前的issues，发现[这里](https://github.com/Bililive/BililiveRecorder/issues/243)提到过完全相同的问题，作者也给了实现方式

以及使用webhook个人感觉过于不便，在windows的情况下更是如此

还是希望可以添加一个“录制结束后执行”的功能

**Comment by Genteure** [comment]
用现在的 webhook 而不是直接执行命令有以下几个好处：

- 不需要考虑命令行传参时特殊字符的转义
- 能传递的信息更多
- 能传递的事件类型更多
- 无法通过录播姬本身实现任意代码执行（主要针对命令行版）

考虑到的缺点有：

- 需要多一个常驻进程
- 编写 HTTP 服务的难度可能比写直接运行命令的脚本更高一些

综合这些考虑，我觉得现有的 webhook 比较合适。

如果有什么其他的没有考虑到的地方也可以提。

issue 先 close 了，如果有必要的话再 reopen。
