### ISSUE TITLE
希望cli可以添加热重载配置

### ISSUE THREAD

**Issue by waitsaber** [Bililive/BililiveRecorder#303]
希望可以在CLI版本中加入热重载配置功能，或者做成跟gui一样交换式的，这样就可以在不重启进程不影响正在录制的直播的情况下新增直播间。

**Comment by Genteure** [comment]
下个版本会有 API，估计会有 Web UI。

**Comment by waitsaber** [comment]
如果有web ui就更好了，不过需要考虑一个场景，当运行多个进程的时候是采用一个web进行管理，还是进程单独修改监听端口分开管理。

**Comment by Genteure** [comment]
已经实现 API
