### ISSUE TITLE
工作目录

### ISSUE THREAD

**Issue by gy39830** [Bililive/BililiveRecorder#304]
今天重启电脑运行客户端，弹窗选择工作目录，提示工作目录已有其他文件，无法选择原来设置过的文件夹做为工作目录

**Comment by Genteure** [comment]
这个判定逻辑是检查工作目录里是否有配置文件 `config.json`，可能是你把配置删除或挪走了？
上一次写入的文件会改名为 `config.backup.json` 可以复制一份到 `config.json`

**Comment by gy39830** [comment]
> 这个判定逻辑是检查工作目录里是否有配置文件 `config.json`，可能是你把配置删除或挪走了？ 上一次写入的文件会改名为 `config.backup.json` 可以复制一份到 `config.json`

雀食是丢了，估计是傲腾给机械盘加速在关机的时候没完成写入
