### ISSUE TITLE
录制弹幕时增加过滤抽奖弹幕功能

### ISSUE THREAD

**Issue by KazegaFuHua** [Bililive/BililiveRecorder#312]
希望录制弹幕的时候能给一个关键词屏蔽，或者屏蔽抽奖弹幕（红包抽奖弹幕）

说一个实例
最近录制某游戏的周年庆直播，录制分段是1G一段（大约28分钟），录制下来了4段内容，其中
1P的弹幕文件100M（感觉像是文件大小上限了？），其中约1.2w条弹幕，有8千条是红包抽奖弹幕
2P的弹幕文件33M，其中约1w条弹幕，有2.5千条是红包抽奖弹幕
3P的弹幕文件38M，其中约1.1w条弹幕，没有红包抽奖弹幕
4P的弹幕文件66M，其中约2.8w条弹幕，没有红包抽奖弹幕
所以由此可得，1P可能有很多弹幕都因为抽奖弹幕而没能成功录制到（但也不排除确实就这些弹幕）

所以希望能屏蔽一下红包抽奖弹幕

红包抽奖弹幕示例：
```
<d p="271.698,1,25,16777215,1650713377026,0,503146731,0" user="法外狂徒陆某" raw="[[0,1,25,16777215,1650713377026,0,0,&quot;54bf86ad&quot;,0,2,0,&quot;&quot;,0,&quot;{}&quot;,&quot;{}&quot;,{&quot;mode&quot;:0,&quot;show_player_type&quot;:0,&quot;extra&quot;:&quot;{\&quot;send_from_me\&quot;:false,\&quot;mode\&quot;:0,\&quot;color\&quot;:16777215,\&quot;dm_type\&quot;:0,\&quot;font_size\&quot;:25,\&quot;player_mode\&quot;:1,\&quot;show_player_type\&quot;:0,\&quot;content\&quot;:\&quot;老板大气！点点红包抽礼物！\&quot;,\&quot;user_hash\&quot;:\&quot;1421837997\&quot;,\&quot;emoticon_unique\&quot;:\&quot;\&quot;,\&quot;bulge_display\&quot;:0,\&quot;recommend_score\&quot;:9,\&quot;direction\&quot;:0,\&quot;pk_direction\&quot;:0,\&quot;quartet_direction\&quot;:0,\&quot;yeah_space_type\&quot;:\&quot;\&quot;,\&quot;yeah_space_url\&quot;:\&quot;\&quot;,\&quot;jump_to_url\&quot;:\&quot;\&quot;,\&quot;space_type\&quot;:\&quot;\&quot;,\&quot;space_url\&quot;:\&quot;\&quot;}&quot;}],&quot;老板大气！点点红包抽礼物！&quot;,[503146731,&quot;法外狂徒陆某&quot;,0,0,0,10000,1,&quot;&quot;],[],[0,0,9868950,&quot;&gt;50000&quot;,0],[&quot;&quot;,&quot;&quot;],0,0,null,{&quot;ts&quot;:1650713377,&quot;ct&quot;:&quot;215094E9&quot;},0,0,null,null,0,7]">老板大气！点点红包抽礼物！</d>
```

**Comment by Genteure** [comment]
第一个弹幕文件的大小是 100M 整吗？104857600 字节？应该是没有文件大小上限的。

录播姬也不会丢弹幕，要不就是收到的全写到文件里了，要不就是出错然后全都没录到，不会因为弹幕太多而主动丢弃一部分数据。
弹幕服务器倒是有可能会少发弹幕，不过这个在录播姬里过滤抽奖弹幕也解决不了。

**Comment by KazegaFuHua** [comment]
第一个弹幕文件大小是105 282 836字节，如果不会因为录制姬丢掉了弹幕的话，那要不还是加个过滤，去掉这个抽奖弹幕？这个红包抽奖弹幕实在是太多了。。。有点影响，如果有用户需要保留就加个开关？

**Comment by PeanutMelonSeedBigAlmond** [comment]
如果只是判断是否是抽奖弹幕的话，B站似乎用的是`object["info"][0][9]`这个字段来判断的，只要判断这个字段是否为0就行了

![image](https://user-images.githubusercontent.com/25266280/165893321-04569383-8404-4e2e-9dc0-9745faec4e41.png)

当然也不排除有的人是手动打字发送的，似乎判断不到

**Comment by Genteure** [comment]
这个功能可以通过新的[用户脚本](https://rec.danmuji.org/user/user-script/)实现。
不添加新的设置是因为如果每个人的每个弹幕过滤需求都加一个新的设置，要不了多久设置页里就全是各种弹幕过滤开关了。

脚本例子: https://github.com/BililiveRecorder/recorder-scripting-template/blob/main/examples/example-1.js

这个设置项在软件的高级设置里，WPF版的高级设置打开方法是鼠标右键两次界面左下角的设置按钮。
关于设置的网站文档还没写好，之后会完善一下。
