### ISSUE TITLE
能否增加在安装时选择安装位置的功能。

### ISSUE THREAD

**Issue by BelugaRex** [Bililive/BililiveRecorder#315]
如题，因为c盘是ssd比较小，希望能把软件安装到其他盘里。

**Comment by Genteure** [comment]
实现不了。
可以从 [GitHub Releases](https://github.com/Bililive/BililiveRecorder/releases) 里面下载 zip 包解压运行，放哪里都行。
和网站的安装包功能一样，但没有更新。可以 watch 一下这个仓库的 Releases 然后手动更。

**Comment by BelugaRex** [comment]
我试过下载那个win-x64的，好像没办法运行。

**Comment by Genteure** [comment]
`BililiveRecorder-CLI` 是命令行版
`BililiveRecorder-WPF` 是桌面版
