### ISSUE TITLE
使用录播修复时如果最小化程序再打开会重置界面

### ISSUE THREAD

**Issue by kafu0611** [Bililive/BililiveRecorder#316]
如题，如果在使用录播修复功能修复期间时最小化程序，再重新打开窗口会使修复中的窗口消失
但修复仍然在进行且无法取消，点击右上角关闭按钮没有反应，需等待后台修复完成

操作步骤：
1，打开录播机
2，选择录播修复功能，选择需要修复的文件，进行修复
3，最小化窗口，然后再打开
4，复现

**Comment by Genteure** [comment]
能复现。

算是个小问题，找原因又太费劲太花时间了。
如果有人想帮忙折腾一下 WPF 的话可以研究研究发个 PR。

回头修的话我可能直接在弹窗显示的时候禁用最小化/隐藏到托盘，简单粗暴，能解决问题。
