### ISSUE TITLE
关于收到 onMetaData 导致录播分段的问题

### ISSUE THREAD

**Issue by mylolis** [Bililive/BililiveRecorder#320]
原标题：**目前自动拼接功能是否已经可以使用？**
Edit by @Genteure

-----

最近录播总是会断成好几节，log里也没有报错信息，就只有新建录制文件。
请问 #295 是否已经可以使用？另外如果开启自动拼接，那么弹幕是否也会自动拼接？
又或者是否可以自己选择连接的b站CDN？最近好像是换了个连接的CDN才出现录播碎掉的情况。

**Comment by Genteure** [comment]
还不能用，甚至还没有开始写。

录播断开的问题应该是因为[B站自建的CDN](https://rec.danmuji.org/dev/bilibili-cdn/#b%E7%AB%99%E8%A7%86%E9%A2%91%E4%BA%91)与上一级源站的连接断开重连了。录播姬的修复系统检测到这种情况就会新建一个文件。
日志文件里会记录 `修复逻辑输出` `收到了 onMetaData`，因为是 debug 级别的所以不在软件界面里显示。日志文件可以点房间列表界面的 “文件” 菜单找到，或者在 exe 旁边的 `logs` 文件夹里。

```mermaid
flowchart RL
   s1[推流服务器/其他直播 CDN] --- s[主播]
   c[直播 CDN] --怀疑是这里断了--> s1
   z11[其他观众] --> c1[直播 CDN] --> s1
   z12[其他观众] --> c1
   z21[其他观众] --> c2[直播 CDN] --> s1
   z22[其他观众] --> c2
   p1[观众 1] --> c
   p2[观众 2] --> c

```

根据其他用户的反馈，分段的位置可能会多数据或者少数据，拼接起来之前建议手动检查一下是否连贯。拼接可以用 ffmpeg。

以前用腾讯云比较多的时候确实没有这个问题。

自己选连接的CDN的话可以用[新的脚本系统](https://rec.danmuji.org/user/user-script/)实现，在 GitHub Actions 里可以下载最新的二进制（不保证每个都能用）。因为直播流地址有签名验证，这个链接最终还是得请求B站 API 获取，不可能完全自己生成。

或者你也可以试一下 [blrec](https://github.com/acgnhiki/blrec)，可以试一下用 blrec 录 HLS 流看看效果会不会更好一些。

**Comment by Asultop** [comment]
自动连接真的非常有必要，像我这边就录得稀碎

**Comment by Genteure** [comment]
@Tncent 就这个问题来说，断开的不是录播姬与CDN边缘节点之间的连接，而是CDN节点与上级源站之间的连接。因此就算录播姬加了重连自动拼接也不会解决这个问题，因为录播姬的网络连接本来就没有断。

文件分段的原因我上面说了。
因为CDN节点与上级断开重连之后中间可能会多数据少数据，就我个人来说认为分开是最合理的，人工检查之后再决定下一步怎么处理。

不分段的话也可以实现，把这一行代码注释掉就行了

https://github.com/Bililive/BililiveRecorder/blob/dbfbce12ca5423fb313bc2246f8e9751af19bd5d/BililiveRecorder.Flv/Pipeline/Rules/HandleNewScriptRule.cs#L74

但是这样的话录出来的文件中间多数据少数据了你也不容易发现。

目前的重复数据判定逻辑会漏掉一部分，之后会优化调整重复数据的检测逻辑，多的重复数据会都被删掉，因此就只会有刚好不多不少和缺片段两种情况了。

**Comment by youth1996** [comment]
> @Tncent 就这个问题来说，断开的不是录播姬与CDN边缘节点之间的连接，而是CDN节点与上级源站之间的连接。因此就算录播姬加了重连自动拼接也不会解决这个问题，因为录播姬的网络连接本来就没有断。
> 
> 文件分段的原因我上面说了。 因为CDN节点与上级断开重连之后中间可能会多数据少数据，就我个人来说认为分开是最合理的，人工检查之后再决定下一步怎么处理。
> 
> 不分段的话也可以实现，把这一行代码注释掉就行了
> 
> https://github.com/Bililive/BililiveRecorder/blob/dbfbce12ca5423fb313bc2246f8e9751af19bd5d/BililiveRecorder.Flv/Pipeline/Rules/HandleNewScriptRule.cs#L74
> 
> 但是这样的话录出来的文件中间多数据少数据了你也不容易发现。
> 
> 目前的重复数据判定逻辑会漏掉一部分，之后会优化调整重复数据的检测逻辑，多的重复数据会都被删掉，因此就只会有刚好不多不少和缺片段两种情况了。

是不是可以根据时间戳和码率来计算丢失的帧数，画面可以用丢失前的最后一帧画面重复，音频就空，对应把音频的时间加长，现在分段之后直接拼接视频的话，弹幕文件的时间戳会有问题。
同样的当主播网络不稳定的时候，录制的视频时间也有比弹幕时间少的情况

**Comment by Genteure** [comment]
我在 [feature/disable-new-file-onmetadata](https://github.com/BililiveRecorder/BililiveRecorder/tree/feature/disable-new-file-onmetadata) 分支上修改了一下收到 `onMetaData` 的行为，不再会分段而是忽略不管。

如果有人想试一下的话，可以从 GitHub Actions 里面的 Artifacts 区域下载。用的时候记得关注一下日志里面的 `重复收到 onMetaData` 信息。

https://github.com/BililiveRecorder/BililiveRecorder/actions?query=event%3Apush+branch%3Afeature%2Fdisable-new-file-onmetadata

不需登录 GitHub：https://nightly.link/BililiveRecorder/BililiveRecorder/workflows/build/feature%2Fdisable-new-file-onmetadata

------

和我上面说的一样，这是 CDN 的问题，CDN 多给了数据少给了数据没有办法解决。
这样确实是不会分段了，但他的问题一样还是在那里。

我自己测试的结果：

![image](https://user-images.githubusercontent.com/11240579/173231791-f0dec164-594b-4d5f-8df3-7290e0ece740.png)

日志里提示收到 onMetaData 的位置，在播放器里打开是不连贯的。我用 ffmpeg 切了一段出来，在本地播放器播放切出来的片段和播放原 FLV 文件效果一样，发上来做参考。

```sh
# 使用的命令
ffmpeg -i .\录制-22347054-20220612-192259-476-原画-【B限】钢琴弹唱【Yorushika】.flv -c copy -ss 1129 -t 15 out.mp4
```

https://user-images.githubusercontent.com/11240579/173232029-ca4fa75f-20e8-494c-bed6-bee06291be9c.mp4

如果只是因为录播姬能检测这种问题，把它分开方便用户后期处理，而其他工具不检测这样的问题直接收啥存啥所以不断，从而认为这是录播姬的问题的话，有一说一会让我心里有那么一点不平衡。  
用其他方法直接下载直播流（比如直接用 IDM 等）录到解码参数变动了的文件（比如连麦PK的时候）那也不会分段呢，可它也不能正常播放了啊。

上面推荐试一下 blrec 的 HLS 录制是因为我觉得 HLS 流应该没有这个问题。

如果这个分支上的判定逻辑测试没问题，而且确实有人更倾向于像这样不管有没有缺数据都拼一起的话，之后的版本会把这个功能做成一个开关。

**Comment by mylolis** [comment]
> 我在 [feature/disable-new-file-onmetadata](https://github.com/BililiveRecorder/BililiveRecorder/tree/feature/disable-new-file-onmetadata) 分支上修改了一下收到 `onMetaData` 的行为，不再会分段而是忽略不管。
> 
> 如果有人想试一下的话，可以从 GitHub Actions 里面的 Artifacts 区域下载。用的时候记得关注一下日志里面的 `重复收到 onMetaData` 信息。
> 
> https://github.com/BililiveRecorder/BililiveRecorder/actions?query=event%3Apush+branch%3Afeature%2Fdisable-new-file-onmetadata
> 
> 不需登录 GitHub：https://nightly.link/BililiveRecorder/BililiveRecorder/workflows/build/feature%2Fdisable-new-file-onmetadata
> 
> 和我上面说的一样，这是 CDN 的问题，CDN 多给了数据少给了数据没有办法解决。 这样确实是不会分段了，但他的问题一样还是在那里。
> 
> 我自己测试的结果：
> 
> ![image](https://user-images.githubusercontent.com/11240579/173231791-f0dec164-594b-4d5f-8df3-7290e0ece740.png)
> 
> 日志里提示收到 onMetaData 的位置，在播放器里打开是不连贯的。我用 ffmpeg 切了一段出来，在本地播放器播放切出来的片段和播放原 FLV 文件效果一样，发上来做参考。
> 
> ```shell
> # 使用的命令
> ffmpeg -i .\录制-22347054-20220612-192259-476-原画-【B限】钢琴弹唱【Yorushika】.flv -c copy -ss 1129 -t 15 out.mp4
> ```
> 
>  out.mp4 
> 如果只是因为录播姬能检测这种问题，把它分开方便用户后期处理，而其他工具不检测这样的问题直接收啥存啥所以不断，从而认为这是录播姬的问题的话，有一说一会让我心里有那么一点不平衡。 用其他方法直接下载直播流（比如直接用 IDM 等）录到解码参数变动了的文件（比如连麦PK的时候）那也不会分段呢，可它也不能正常播放了啊。
> 
> 上面推荐试一下 blrec 的 HLS 录制是因为我觉得 HLS 流应该没有这个问题。
> 
> 如果这个分支上的判定逻辑测试没问题，而且确实有人更倾向于像这样不管有没有缺数据都拼一起的话，之后的版本会把这个功能做成一个开关。

试了一下拼在一起确实会出现重复或者跳段等不连贯的问题，另外目前试了一个月的hls流，确实没有出现过这个问题（不过hls流要另外注意弹幕和视频直接存在时间差的问题），而使用flv录制就时常这样，b站的问题

**Comment by Genteure** [comment]
之前录播姬已经调整了重复数据的判定方法，目前的正式版 2.0.0 以及这个新分支上的版本录出来的文件不会有重复片段了，会被删除。

**Comment by mylolis** [comment]
> 之前录播姬已经调整了重复数据的判定方法，目前的正式版 2.0.0 以及这个新分支上的版本录出来的文件不会有重复片段了，会被删除。

也就是说目前2.0.0正式版本当收到onMetaData时会分段，但不会录到重复数据，而新分支会直接将两段拼在一起（只会出现平滑连接和跳段两种情况，不会有重复）吗？

**Comment by Genteure** [comment]
> 也就是说目前2.0.0正式版本当收到onMetaData时会分段，但不会录到重复数据，而新分支会直接将两段拼在一起（只会出现平滑连接和跳段两种情况，不会有重复）吗？

正确

**Comment by mylolis** [comment]
> > 也就是说目前2.0.0正式版本当收到onMetaData时会分段，但不会录到重复数据，而新分支会直接将两段拼在一起（只会出现平滑连接和跳段两种情况，不会有重复）吗？
> 
> 正确

感谢大佬，另外想问一下当由于主播网络波动导致的几秒钟短时间中断，或者由于主播电脑死机导致的长时间中断，新分支会怎么处理这样的数据呢？将他们拼一起还是会新建录播文件？

**Comment by Genteure** [comment]
如果网络连接断了，一定会分成两个文件。

**Comment by gin3715** [comment]
请问2.1.0开始的新版本的命令行的`BililiveRecorder.Cli tool fix`是在命令结尾添加`pipeline-settings '{"SplitOnScriptTag": true}'`来实现和旧版本一样的分段行为吗。后续是否会添加一个参数对应GUI中的“检测到可能缺少数据时分段”选择框？谢谢
