### ISSUE TITLE
linux CLI下无法开启录制弹幕

### ISSUE THREAD

**Issue by GrayXu** [Bililive/BililiveRecorder#326]
```
Usage:
  BililiveRecorder.Cli [options] portable <output-path> [<room-ids>...]
```
根据help usage来使用：
`$ ./BililiveRecorder.Cli --danmaku portable $(path) $(room-ids)`  
但会直接报错
```
'--danmaku' was not matched. Did you mean one of the following?
--danmaku
Unrecognized command or argument '--danmaku'
```

`-d`也是一样报错。

谢谢

**Comment by GrayXu** [comment]
-d需要设置具体值。。我看漏了。  
但
`$ ./BililiveRecorder.Cli --danmaku All portable $(path) $(room-ids)`不可用，  
`$ ./BililiveRecorder.Cli portable --danmaku All $(path) $(room-ids)`是正常工作的。  

help usage应该修改显示为如下？
```
Usage:
  BililiveRecorder.Cli portable [options] <output-path> [<room-ids>...]
```

**Comment by Genteure** [comment]
> help usage应该修改显示为如下？

这个帮助消息是用 [System.CommandLine](https://github.com/dotnet/command-line-api) 生成的，不是手动写的，所以改不了。
