### ISSUE TITLE
b站直播的原始弹幕数据可能已经发生变化？弹幕解析是否会受影响？

### ISSUE THREAD

**Issue by InterestingFred** [Bililive/BililiveRecorder#327]
是这样的，我是用隔壁blrec的，发现它不能正常解析原始弹幕数据并存入xml了（虽然只是一次录制出现了问题，但对比了一下jsonl，确实不大一样），可能是阿b那边变了？就担心录播姬是不是也会受到这个影响。过来发个issue，如果没问题的话直接close吧。

**Comment by Genteure** [comment]
是没有问题的

https://github.com/BililiveRecorder/BililiveRecorder/blob/dfba519e4137f5e9ca0f8a15c14baa21a040a6a7/BililiveRecorder.Core/Api/Danmaku/DanmakuModel.cs#L179-L180
