### ISSUE TITLE
不知道什么原因就崩掉了

### ISSUE THREAD

**Issue by xinjiangdapanji** [Bililive/BililiveRecorder#342]
进程没有了，找不到log在哪里，如果有的话可以去翻翻

**Comment by Genteure** [comment]
用的是哪个版本？是 CLI 还是 WPF ？
日志文件在可执行文件旁边的 logs 文件夹，如果用的是 docker 的话就是在容器里面。

**Comment by xinjiangdapanji** [comment]
WPF的，挖到了一些log，不过是在app-1.3.11文件夹中（这两天似乎自动更新成2.0.0版本了？）

bilirec20220616.txt
`{"@t":"2022-06-16T01:28:54.9431533Z","@mt":"Checking updates","@l":"Debug","SourceContext":"BililiveRecorder.WPF.Update","ProcessId":10996,"ThreadId":134}
{"@t":"2022-06-16T07:31:59.8933025Z","@mt":"Unhandled exception from AppDomain.UnhandledException","@l":"Fatal","@x":"System.Threading.AbandonedMutexException: Leaked a Mutex!\r\n   在 Squirrel.SingleGlobalInstance.Finalize() 位置 C:\\Users\\ani\\code\\squirrel\\squirrel.windows\\src\\Squirrel\\Utility.cs:行号 864","ProcessId":10996,"ThreadId":2,"ExceptionDetail":{"HResult":-2146233043,"Message":"Leaked a Mutex!","Source":"Squirrel","Mutex":null,"MutexIndex":-1,"Type":"System.Threading.AbandonedMutexException"}}
`
bilirec20220611.txt
`{"@t":"2022-06-11T02:21:13.8173995Z","@mt":"Unhandled exception from AppDomain.UnhandledException","@l":"Fatal","@x":"System.Exception: You must dispose UpdateManager!\r\n   在 Squirrel.UpdateManager.Finalize() 位置 C:\\Users\\ani\\code\\squirrel\\squirrel.windows\\src\\Squirrel\\UpdateManager.cs:行号 261","ProcessId":12108,"ThreadId":2,"ExceptionDetail":{"Type":"System.Exception","HResult":-2146233088,"Message":"You must dispose UpdateManager!","Source":"Squirrel"}}
`
bilirec20220531.txt
`{"@t":"2022-05-31T04:52:39.1528234Z","@mt":"Checking updates","@l":"Debug","SourceContext":"BililiveRecorder.WPF.Update","ProcessId":2816,"ThreadId":177}
{"@t":"2022-05-31T05:09:17.9156464Z","@mt":"Unhandled exception from AppDomain.UnhandledException","@l":"Fatal","@x":"System.Exception: You must dispose UpdateManager!\r\n   在 Squirrel.UpdateManager.Finalize() 位置 C:\\Users\\ani\\code\\squirrel\\squirrel.windows\\src\\Squirrel\\UpdateManager.cs:行号 261","ProcessId":2816,"ThreadId":2,"ExceptionDetail":{"Type":"System.Exception","HResult":-2146233088,"Message":"You must dispose UpdateManager!","Source":"Squirrel"}}
`
bilirec20220521.txt
`{"@t":"2022-05-21T03:22:09.4948312Z","@mt":"Checking updates","@l":"Debug","SourceContext":"BililiveRecorder.WPF.Update","ProcessId":11344,"ThreadId":93}
{"@t":"2022-05-21T03:32:13.4990158Z","@mt":"Unhandled exception from AppDomain.UnhandledException","@l":"Fatal","@x":"System.Exception: You must dispose UpdateManager!\r\n   在 Squirrel.UpdateManager.Finalize() 位置 C:\\Users\\ani\\code\\squirrel\\squirrel.windows\\src\\Squirrel\\UpdateManager.cs:行号 261","ProcessId":11344,"ThreadId":2,"ExceptionDetail":{"Type":"System.Exception","HResult":-2146233088,"Message":"You must dispose UpdateManager!","Source":"Squirrel"}}
`
隔几天就会自杀的样子（
从log看像是凌晨检查更新崩掉了

**Comment by xinjiangdapanji** [comment]
点错了，gayhub不会用。。。关闭了再打开

**Comment by Genteure** [comment]
是更新组件的问题，如果崩溃很多影响使用的话，可以从 GitHub Release 里面下载没有更新组件的 zip 包。
下个版本打算把它换掉，应该能解决这类问题。

**Comment by xinjiangdapanji** [comment]
已重新拉取程序，并且是最新版，应该没问题了，持续观察中:)
