### ISSUE TITLE
屏蔽一些cdn？

### ISSUE THREAD

**Issue by ChooseBetterr** [Bililive/BililiveRecorder#344]
有的cdn感觉稳定性质量比较低，而且网页自己看会用别的cdn，但是录制的话死活不会变

**Comment by jkfujr** [comment]
可以尝试拿台腾讯轻量云的机器去反代官方api

**Comment by Genteure** [comment]
你可以自己写[脚本](https://rec.danmuji.org/user/user-script/)替换掉录播姬获取直播流地址的逻辑。
B站网页上CDN域名和录播姬用的不一样是因为，大直播间现在大多数都是用 HLS 流，录播姬用的是 HTTP-FLV 流。
