### ISSUE TITLE
威联通(qnap) nas docker版 刷新房间信息出错，报HttpClient超时

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [Bililive/BililiveRecorder#354]
使用docker版的Recorder报 HttpClient Timeout, 并导致房间信息无法刷新，使用本组件的自动录播上传库同样报此错误，开播信息也无法监控，仅监控了4个直播间，重启路由换IP无效：报错信息如下：
```
"System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing
```
dns 和 curl 都正常
[bilirec20220707.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/9061242/bilirec20220707.txt)
.

**Comment by Genteure** [comment]
在qq群里讨论测试的结果，把超时时间从 10 秒 改到 15 秒就好了。
我也不知道为什么 10 秒会有问题，我也不知道为啥改成 15 秒就好了，反正它就是好了。
aa3b554a5edd1bd6e7938653838a05e9478db792

报错除了 

```
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 10 seconds elapsing
```

以外，还有：

```
System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.live.bilibili.com:443)
 ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
```
