### ISSUE TITLE
用 WebUI 修改设置 config.json 文件不更新

### ISSUE THREAD

**Issue by gxusb** [Bililive/BililiveRecorder#357]
用 WebUI 添加或删除 房间号 config.json 文件更新
用 WebUI 修改设置 config.json 文件不更新

**Comment by shugen002** [comment]
你保存了吗？

**Comment by gxusb** [comment]
> 你保存了吗？
保存了

**Comment by shugen002** [comment]
![image](https://user-images.githubusercontent.com/10257291/177996029-d7c291e8-0921-482b-ba80-1cdaba0509ae.png)

**Comment by shugen002** [comment]
![image](https://user-images.githubusercontent.com/10257291/177996320-369e8bbc-fd47-4891-ae3a-1795a591ac9c.png)

**Comment by gxusb** [comment]
也就是 保存 不会触发 config.json 文件更新

**Comment by Genteure** [comment]
现在会了： f26067cd5d0a01fd064fa3293b20d748ca370029
