### ISSUE TITLE
无法安装

### ISSUE THREAD

**Issue by g90130** [Bililive/BililiveRecorder#359]
已知Windows7 SP1，已安装NET4.8，NET6.0.7，powershell5.1，powershell7
安装时报错缺少api-ms-win-core-winrt-|1-1-0.dll安装不能继续
![20220716001539](https://user-images.githubusercontent.com/46667747/179264589-dc7f245d-83e6-4ce2-b0fd-61cfedbd02ce.png)

**Comment by Genteure** [comment]
是有这个问题，可以从 GitHub Release 里面下载没有安装包的 zip 包解压运行。
GitHub Release 里面的文件没有版本检查和自动更新，可以考虑 watch 本仓库的 release。
