### ISSUE TITLE
录播姬的命名规则能否做到标序号的功能

### ISSUE THREAD

**Issue by b1xcy** [Bililive/BililiveRecorder#360]
例如：
      我现在的文件名模板是：{{ name }}/{{ "now" | time_zone: "Asia/Shanghai" | format_date: "M.dd" }}/{{ title }}.flv
      预览是：工作目录/shugen/7.19/废物还不干活.flv
我能否通过修改模板，达到：工作目录/shugen/7.19/1-废物还不干活.flv，工作目录/shugen/7.19/2-废物还不干活.flv，工作目录/shugen/7.19/3-废物还不干活.flv，……
在看过liquid模板后没发现实现该功能的Filters

**Comment by Genteure** [comment]
现在没有这个功能，之后会加

**Comment by Genteure** [comment]
duplicate of #114 
今天晚点加上
