### ISSUE TITLE
录播姬文件夹（名称）问题

### ISSUE THREAD

**Issue by yukitomega** [Bililive/BililiveRecorder#363]
文件问题：
在提前设置好录播后，每一次录播的第一份flv和ass，所存储的文件夹都是19700101-080000。
自身情况：
因为选择按30分钟间隔录制，除第一份文件出现问题外，之后所有文件都存储正常。
怀疑是个案，因为同时录制两个直播间，而另一个直播间一个月中仅出现过一次问题，目前正常。所以请问开发者是否知道这样的原因是什么，以及如何将其修改正常，如果需要提供其他信息我愿意配合。
补充说明：
以下是录制文件名格式{{ name }}-{{ roomId }}/{{ json.room_info.live_start_time | time_zone: 'Asia/Shanghai' | format_date: "yyyyMMdd-HHmmss" }}/{{ name }}-{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd-HHmmss-fff" }}-{{ title }}.flv

**Comment by Genteure** [comment]
是因为最开始启动录制的时候，直播间信息还没有刷新。
之后会改一下，在每次开始录制之前都重新拉取直播间信息。

**Comment by Genteure** [comment]
已在 dev 分支实现
