### ISSUE TITLE
弹幕录制无法记录到b站宝盒爆出的礼物

### ISSUE THREAD

**Issue by SunLRikka** [Bililive/BililiveRecorder#367]

**Comment by Genteure** [comment]
宝盒礼物有什么特殊的地方吗？
有哪个直播间一般送宝盒的比较多的，方便测试的？

**Comment by SunLRikka** [comment]
> 

宝盒礼物是先抽礼物然后将礼物赠送给主播，弹幕姬里倒是可以记录到实际的礼物。
这个直播间基本每次开播都有人送宝盒
https://live.bilibili.com/25446854

**Comment by SunLRikka** [comment]
> > 
> 
> 宝盒礼物是先抽礼物然后将礼物赠送给主播，弹幕姬里倒是可以记录到实际的礼物。 这个直播间基本每次开播都有人送宝盒 https://live.bilibili.com/25446854

昨晚又录制了一次，能正常记录到礼物。可能之前是我机器的网络问题吧？

**Comment by Genteure** [comment]
先 close 了，后续如果发现还有问题的话再 reopen
