### ISSUE TITLE
直播结束时，仍然在跑下载流量

### ISSUE THREAD

**Issue by rmm233** [Bililive/BililiveRecorder#368]
如题，在两种录制模式下都会出现这个问题。
直播结束后有下载流量，但录制文件实际上也没有增加时长。

**Comment by Genteure** [comment]
和 #364 是同一个问题。
是因为B站直播服务器在直播结束后不会断开直播流，而是继续大量发送最后一段直播数据导致的。
文件没有增加时长是因为录播姬会检测重复数据然后删除。
