### ISSUE TITLE
对文件路径进行校验

### ISSUE THREAD

**Issue by koitococo** [Bililive/BililiveRecorder#369]
例如文件名模板为
`[{{ roomId }}-{{ name }}][{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yy-MM-dd" }}]{{ title }}/{{ "now" | time_zone: "Asia/Shanghai" | format_date: "HH-mm-ss-ffffff"}}.flv`
将会保存到：工作目录/[直播间id-主播名字][日期]标题/时间.flv

但当直播间标题含有一些特殊字符时，例如以 .（英文的点）结尾，在Windows下就会无法创建目录，录制时发生io错误
所以希望能对标题等参数进行校验，删除或转义会导致无法创建正常目录的字符

**Comment by Genteure** [comment]
在 bf40fe27ecd4b7f18e2db00d84179b1ef1f7c639 实现了过滤目录名字的最后一个字符。
其他的字符已经有过滤了。
