### ISSUE TITLE
新问题  下载了新版本录制不了了

### ISSUE THREAD

**Issue by menheng** [Bililive/BililiveRecorder#372]
![QQ图片20220804152419](https://user-images.githubusercontent.com/109516293/182788627-003de360-e033-4ac6-8feb-fc175b3e8a92.png)

**Comment by menheng** [comment]
退回到2.1.1可以录制 ，希望修复

**Comment by Genteure** [comment]
2.1.1 到 2.2.0 开始录制这部分代码没有改动，也没有其他人反馈出现问题。
可以看一下日志文件里的具体错误信息。
可以检查一下是不是有其他软件（杀软之类）阻止了新版本发送网络请求。

**Comment by menheng** [comment]
\"BVC-SRT LiveHime/4.25.2 (Windows)\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":76}
{"@t":"2022-08-07T13:31:39.9970372Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(RepeatingData,A): 重复数据"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":34}
{"@t":"2022-08-07T13:31:39.9970372Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到直播服务器发送的 onMetaData 数据，请检查此位置是否有重复的直播片段或缺少数据。\n造成这个问题的原因可能是录播姬所连接的直播服务器与它的上级服务器的连接断开重连了。\n数据内容: [{\"Type\":\"String\",\"Value\":\"onMetaData\"},{\"Type\":\"Object\",\"Value\":{\"Rawdata\":{\"Type\":\"String\",\"Value\":\"\"},\"width\":{\"Type\":\"Number\",\"Value\":1920.0},\"height\":{\"Type\":\"Number\",\"Value\":1080.0},\"displayWidth\":{\"Type\":\"Number\",\"Value\":1920.0},\"displayHeight\":{\"Type\":\"Number\",\"Value\":1080.0},\"framerate\":{\"Type\":\"Number\",\"Value\":30.0},\"fps\":{\"Type\":\"Number\",\"Value\":30.0},\"videodatarate\":{\"Type\":\"Number\",\"Value\":2700.0},\"videocodecid\":{\"Type\":\"Number\",\"Value\":0.0},\"audiodatarate\":{\"Type\":\"Number\",\"Value\":256.0},\"audiocodecid\":{\"Type\":\"Number\",\"Value\":16.0},\"profile\":{\"Type\":\"String\",\"Value\":\"\"},\"level\":{\"Type\":\"String\",\"Value\":\"\"},\"encoder\":{\"Type\":\"String\",\"Value\":\"BVC-SRT LiveHime/4.25.2 (Windows)\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":34}
{"@t":"2022-08-07T13:31:40.1192051Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(RepeatingData,A): 重复数据"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":37}
{"@t":"2022-08-07T13:31:40.1211991Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到直播服务器发送的 onMetaData 数据，请检查此位置是否有重复的直播片段或缺少数据。\n造成这个问题的原因可能是录播姬所连接的直播服务器与它的上级服务器的连接断开重连了。\n数据内容: [{\"Type\":\"String\",\"Value\":\"onMetaData\"},{\"Type\":\"Object\",\"Value\":{\"Rawdata\":{\"Type\":\"String\",\"Value\":\"\"},\"width\":{\"Type\":\"Number\",\"Value\":1920.0},\"height\":{\"Type\":\"Number\",\"Value\":1080.0},\"displayWidth\":{\"Type\":\"Number\",\"Value\":1920.0},\"displayHeight\":{\"Type\":\"Number\",\"Value\":1080.0},\"framerate\":{\"Type\":\"Number\",\"Value\":30.0},\"fps\":{\"Type\":\"Number\",\"Value\":30.0},\"videodatarate\":{\"Type\":\"Number\",\"Value\":2700.0},\"videocodecid\":{\"Type\":\"Number\",\"Value\":0.0},\"audiodatarate\":{\"Type\":\"Number\",\"Value\":256.0},\"audiocodecid\":{\"Type\":\"Number\",\"Value\":16.0},\"profile\":{\"Type\":\"String\",\"Value\":\"\"},\"level\":{\"Type\":\"String\",\"Value\":\"\"},\"encoder\":{\"Type\":\"String\",\"Value\":\"BVC-SRT LiveHime/4.25.2 (Windows)\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":37}
{"@t":"2022-08-07T13:31:40.1600945Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(RepeatingData,A): 重复数据"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":123}
{"@t":"2022-08-07T13:31:40.1610912Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到直播服务器发送的 onMetaData 数据，请检查此位置是否有重复的直播片段或缺少数据。\n造成这个问题的原因可能是录播姬所连接的直播服务器与它的上级服务器的连接断开重连了。\n数据内容: [{\"Type\":\"String\",\"Value\":\"onMetaData\"},{\"Type\":\"Object\",\"Value\":{\"Rawdata\":{\"Type\":\"String\",\"Value\":\"\"},\"width\":{\"Type\":\"Number\",\"Value\":1920.0},\"height\":{\"Type\":\"Number\",\"Value\":1080.0},\"displayWidth\":{\"Type\":\"Number\",\"Value\":1920.0},\"displayHeight\":{\"Type\":\"Number\",\"Value\":1080.0},\"framerate\":{\"Type\":\"Number\",\"Value\":30.0},\"fps\":{\"Type\":\"Number\",\"Value\":30.0},\"videodatarate\":{\"Type\":\"Number\",\"Value\":2700.0},\"videocodecid\":{\"Type\":\"Number\",\"Value\":0.0},\"audiodatarate\":{\"Type\":\"Number\",\"Value\":256.0},\"audiocodecid\":{\"Type\":\"Number\",\"Value\":16.0},\"profile\":{\"Type\":\"String\",\"Value\":\"\"},\"level\":{\"Type\":\"String\",\"Value\":\"\"},\"encoder\":{\"Type\":\"String\",\"Value\":\"BVC-SRT LiveHime/4.25.2 (Windows)\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":22556461,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":123}

**Comment by menheng** [comment]
几百条都是这样

**Comment by menheng** [comment]
关闭了杀毒软件还是有问题

**Comment by Genteure** [comment]
上面发的是哪个版本的日志？你发的日志内容也不是“启动录制出错”啊。

**Comment by menheng** [comment]
2.2.0      相同差不多的问题 就录了几秒的数据都
![QQ图片20220807231908](https://user-images.githubusercontent.com/109516293/183298164-e1feb4e4-cb00-4ece-979a-e38d7bd3af5c.png)

**Comment by menheng** [comment]
{"@t":"2022-08-07T15:13:27.8391812Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到直播服务器发送的 onMetaData 数据，请检查此位置是否有重复的直播片段或缺少数据。\n造成这个问题的原因可能是录播姬所连接的直播服务器与它的上级服务器的连接断开重连了。\n数据内容: [{\"Type\":\"String\",\"Value\":\"onMetaData\"},{\"Type\":\"Object\",\"Value\":{\"Rawdata\":{\"Type\":\"String\",\"Value\":\"\"},\"width\":{\"Type\":\"Number\",\"Value\":720.0},\"height\":{\"Type\":\"Number\",\"Value\":1280.0},\"displayWidth\":{\"Type\":\"Number\",\"Value\":720.0},\"displayHeight\":{\"Type\":\"Number\",\"Value\":1280.0},\"framerate\":{\"Type\":\"Number\",\"Value\":25.0},\"fps\":{\"Type\":\"Number\",\"Value\":25.0},\"videodatarate\":{\"Type\":\"Number\",\"Value\":3000.0},\"videocodecid\":{\"Type\":\"Number\",\"Value\":0.0},\"audiodatarate\":{\"Type\":\"Number\",\"Value\":128.0},\"audiocodecid\":{\"Type\":\"Number\",\"Value\":16.0},\"profile\":{\"Type\":\"String\",\"Value\":\"\"},\"level\":{\"Type\":\"String\",\"Value\":\"\"},\"encoder\":{\"Type\":\"String\",\"Value\":\"iPhone 12 Pro Max/15.6/2.5.2 直播姬/5.51.0\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":18}
{"@t":"2022-08-07T15:13:27.8411769Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(TimestampJump,A): 时间戳间隔过大, curr: 47604, diff: 47604"],"RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":23}
{"@t":"2022-08-07T15:13:27.8411769Z","@mt":"新建录制文件 {Path}","Path":"D:\\B站录播姬\\21213163-富婆七奈\\录制-21213163-20220807-231327-841-喜欢姐姐吗.flv","RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":23}
{"@t":"2022-08-07T15:13:31.6176688Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到直播服务器发送的 onMetaData 数据，请检查此位置是否有重复的直播片段或缺少数据。\n造成这个问题的原因可能是录播姬所连接的直播服务器与它的上级服务器的连接断开重连了。\n数据内容: [{\"Type\":\"String\",\"Value\":\"onMetaData\"},{\"Type\":\"Object\",\"Value\":{\"Rawdata\":{\"Type\":\"String\",\"Value\":\"\"},\"width\":{\"Type\":\"Number\",\"Value\":720.0},\"height\":{\"Type\":\"Number\",\"Value\":1280.0},\"displayWidth\":{\"Type\":\"Number\",\"Value\":720.0},\"displayHeight\":{\"Type\":\"Number\",\"Value\":1280.0},\"framerate\":{\"Type\":\"Number\",\"Value\":25.0},\"fps\":{\"Type\":\"Number\",\"Value\":25.0},\"videodatarate\":{\"Type\":\"Number\",\"Value\":3000.0},\"videocodecid\":{\"Type\":\"Number\",\"Value\":0.0},\"audiodatarate\":{\"Type\":\"Number\",\"Value\":128.0},\"audiocodecid\":{\"Type\":\"Number\",\"Value\":16.0},\"profile\":{\"Type\":\"String\",\"Value\":\"\"},\"level\":{\"Type\":\"String\",\"Value\":\"\"},\"encoder\":{\"Type\":\"String\",\"Value\":\"iPhone 12 Pro Max/15.6/2.5.2 直播姬/5.51.0\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":194}
{"@t":"2022-08-07T15:13:31.7240867Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(TimestampJump,A): 时间戳间隔过大, curr: 50412, diff: 50412"],"RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":50}
{"@t":"2022-08-07T15:13:31.7250847Z","@mt":"新建录制文件 {Path}","Path":"D:\\B站录播姬\\21213163-富婆七奈\\录制-21213163-20220807-231331-724-喜欢姐姐吗.flv","RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":50}
{"@t":"2022-08-07T15:13:31.7520128Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到直播服务器发送的 onMetaData 数据，请检查此位置是否有重复的直播片段或缺少数据。\n造成这个问题的原因可能是录播姬所连接的直播服务器与它的上级服务器的连接断开重连了。\n数据内容: [{\"Type\":\"String\",\"Value\":\"onMetaData\"},{\"Type\":\"Object\",\"Value\":{\"Rawdata\":{\"Type\":\"String\",\"Value\":\"\"},\"width\":{\"Type\":\"Number\",\"Value\":720.0},\"height\":{\"Type\":\"Number\",\"Value\":1280.0},\"displayWidth\":{\"Type\":\"Number\",\"Value\":720.0},\"displayHeight\":{\"Type\":\"Number\",\"Value\":1280.0},\"framerate\":{\"Type\":\"Number\",\"Value\":25.0},\"fps\":{\"Type\":\"Number\",\"Value\":25.0},\"videodatarate\":{\"Type\":\"Number\",\"Value\":3000.0},\"videocodecid\":{\"Type\":\"Number\",\"Value\":0.0},\"audiodatarate\":{\"Type\":\"Number\",\"Value\":128.0},\"audiocodecid\":{\"Type\":\"Number\",\"Value\":16.0},\"profile\":{\"Type\":\"String\",\"Value\":\"\"},\"level\":{\"Type\":\"String\",\"Value\":\"\"},\"encoder\":{\"Type\":\"String\",\"Value\":\"iPhone 12 Pro Max/15.6/2.5.2 直播姬/5.51.0\"},\"server\":{\"Type\":\"String\",\"Value\":\"BSRS/1.4.4(Sco)\"},\"server_version\":{\"Type\":\"String\",\"Value\":\"1.4.4\"}}}]"],"RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":181}
{"@t":"2022-08-07T15:13:32.0320577Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(RepeatingData,A): 重复数据"],"RoomId":21213163,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":7324,"ThreadId":73}
{"@t":"2022-08-07T15:13:34.0246717Z","@mt":"录制被取消","@l":"Debug","@x":"System.OperationCanceledException: 已取消该操作。\r\n   在 System.Threading.CancellationToken.ThrowOperationCanceledException()\r\n   在 System.IO.Pipelines.Pipe.GetReadAsyncResult()\r\n   在 BililiveRecorder.Flv.Parser.FlvTagPipeReader.<ReadNextTagAsync>d__17.MoveNext()\r\n--- 引发异常的上一位置中堆栈跟踪的末尾 ---\r\n   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   在 System.Runtime.CompilerSe

**Comment by menheng** [comment]
昨天也是这样的 ，启动录制 ，录了几秒就又开始重复操作了

**Comment by Genteure** [comment]
最开始的“启动录制出错”需要日志文件里的具体报错信息才能知道原因，根据你现在发的这个错误说明今天现在是能连接到直播服务器的，那就忽略不管了。

至于现在这个“重复数据”和“onMetaData”，是B站直播服务器或者主播的问题。直接打开直播间就能看到。
![image](https://user-images.githubusercontent.com/11240579/183298784-def6916f-5b31-4223-acee-2dbb11bcd507.png)
