### ISSUE TITLE
标准模式处理非 H.264 直播流会内存泄漏

### ISSUE THREAD

**Issue by 6Bpencle** [Bililive/BililiveRecorder#373]
版本2.2.0安装版
转存文件：https://sc.bilirecord.icu/s/LJUb

**Comment by Genteure** [comment]
看起来是因为直播服务器给的直播数据没有关键帧，导致的直播数据全部攒在内存里。
考虑到这个是以不受支持的方式录的 HEVC 流，暂时忽略不管了。
如果要“修”的话估计也就只是在 Tag 分组那里设置一个上限，超过上限之后直接断开录制。

**Comment by 6Bpencle** [comment]
> 看起来是因为直播服务器给的直播数据没有关键帧，导致的直播数据全部攒在内存里。 考虑到这个是以不受支持的方式录的 HEVC 流，暂时忽略不管了。 如果要“修”的话估计也就只是在 Tag 分组那里设置一个上限，超过上限之后直接断开录制。

我今晚再试一下吧，发现内存泄露之前是发现webhook出了问题（hevc录制应该是结束的），重弄完没一会发现的内存漏

**Comment by Genteure** [comment]
和这个地方有关，回头可以改一下
https://github.com/BililiveRecorder/BililiveRecorder/blob/05897e9533e5805822b9683400e46d06058fd821/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs#L246

![image](https://user-images.githubusercontent.com/11240579/183292174-dee8bcb7-6123-4d40-ab17-d4c4c7cda152.png)
![image](https://user-images.githubusercontent.com/11240579/183292999-6c8468cb-b0d4-46a6-85ed-d2e50683d5dd.png)

**Comment by 6Bpencle** [comment]
哦对，发现内存泄露创建的转存文件是2523.3MB结尾的，创建完成后发现直接爆内存了，然后又创建了一个，也就是10577MB结尾的dmp文件
![image](https://user-images.githubusercontent.com/31346958/183305241-e92d8457-331a-49f5-a12a-cadcddad8d7b.png)
![HY6{~Q~TQIAKZR6P2}A``N1](https://user-images.githubusercontent.com/31346958/183305281-4bd9bde5-e8e8-4094-865f-ada59a6d2aff.png)

![image](https://user-images.githubusercontent.com/31346958/183305258-5f650ddc-48f5-4c97-98d5-48c66748a134.png)
![image](https://user-images.githubusercontent.com/31346958/183305267-bd9396dd-3a6a-4e4f-912a-144cfc3d6d88.png)

**Comment by 6Bpencle** [comment]
再补一个，录制HEVC流用的是原始模式，标准模式会提示发生错误，已取消一个任务，没法录制

**Comment by Genteure** [comment]
1e8bab2
