### ISSUE TITLE
希望可以添加一个磁盘测速功能

### ISSUE THREAD

**Issue by SSSSSSSan** [Bililive/BililiveRecorder#374]
有些虚拟化方案极差，添加磁盘测速功能可以最直观测试当前运行环境能承受的最大写入速度，方便配置
也许只有我这种把录播姬docker丢路由器里用的人需要？

**Comment by Genteure** [comment]
只是测试最大写入速度的话建议用其他现成的脚本工具。
实时监测写入是否跟得上和 #309 重复了。
