### ISSUE TITLE
.webui/build.sh不兼容macOS内置的cp和mv的选项

### ISSUE THREAD

**Issue by PiraticAshin** [Bililive/BililiveRecorder#375]
macOS默认内置的cp和mv并没有--recursive这个选项。
如果改成-r的话Linux和macOS都能用，会不会更好……
<img width="840" alt="截屏2022-08-13 18 17 55" src="https://user-images.githubusercontent.com/36768731/184479417-60ebd365-9663-4aec-a18a-617f3a391db5.png">

**Comment by Genteure** [comment]
两个命令的 `--recursive` 都是改成 `-r` 就行了吗？
我没有 mac 设备不方便测试

**Comment by shugen002** [comment]
似乎是因为在mac上面有两个不同的cp的实现导致的，一个应该是自带的，一个是bash的。
https://github.com/BililiveRecorder/BililiveRecorder/runs/7630851587?check_suite_focus=true
毕竟咱们github action上面这个脚本是没有问题的。

然后是你这里改成`-r`个人表示怀疑，因为看你上面的usage中并没有`-r`这个参数，只有`-R`，希望确认一下这个参数的兼容性。

**Comment by PiraticAshin** [comment]
感谢提醒大小写的问题，虽然事实上macOS上的cp一般情况下-r和-R都能用，但是苹果官网包括大多数的教程都是用-R，所以我也对大小写r持保留态度
但是我又看了某些主流linux发行版的cp的manpage，我发现-R选项在Linux上依旧适用……

> -R, -r, --recursive
              copy directories recursively

至少在debian和centos上都是这样。

macOS上则是一大段废话……

> -R    If source_file designates a directory, cp copies the directory and the entire subtree connected
           at that point.  If the source_file ends in a /, the contents of the directory are copied rather
           than the directory itself.  This option also causes symbolic links to be copied, rather than
           indirected through, and for cp to create special files rather than copying them as normal files.
           Created directories have the same mode as the corresponding source directory, unmodified by the
           process' umask.

所以说正确改法应该是改成-R……

**Comment by PiraticAshin** [comment]
感谢提醒大小写的问题，虽然-r和-R在macOS的cp和mv命令都能用，但是Apple官网的教程和其他的教程几乎没有用-r的，所以我对-r是否使用也持保留态度（万一以后噶了就不好了……

但是当我查询各系统的manpages后，我发现-R选项在Linux发行版中也适用（无论是cp还是rm）。

debian系的描述：

cp

> https://manpages.debian.org/bullseye/manpages-zh/cp.1.zh_CN.html#R
-R, -r, --recursive
        递归地复制文件

rm

> https://manpages.debian.org/bullseye/manpages-zh/rm.1.zh_CN.html#r
-r, -R, --recursive
        递归地移除目录及它们的内容

centos的描述：

cp

> https://man.linuxtool.net/centos7/u3/man/1_cp.html
−R, −r, −−recursive
        copy directories recursively

rm

> https://man.linuxtool.net/centos7/u3/man/1_rm.html
−r, −R, −−recursive
        remove directories and their contents recursively

最后搬一下macOS上的描述。

cp

> -R    If source_file designates a directory, cp copies the directory and the entire subtree connected
           at that point.  If the source_file ends in a /, the contents of the directory are copied rather
           than the directory itself.  This option also causes symbolic links to be copied, rather than
           indirected through, and for cp to create special files rather than copying them as normal files.
           Created directories have the same mode as the corresponding source directory, unmodified by the
           process' umask.
           Note that cp copies hard linked files as separate files.  If you need to preserve hard links,
           consider using tar(1), cpio(1), or pax(1) instead.

rm

> -R      Attempt to remove the file hierarchy rooted in each file argument.  The -R option implies the
             -d option.  If the -i option is specified, the user is prompted for confirmation before each
             directory's contents are processed (as well as before the attempt is made to remove the
             directory).  If the user does not respond affirmatively, the file hierarchy rooted in that
             directory is skipped.
…
-r      Equivalent to -R.

讲了一堆废话其实都是递归的意思……
所以最优的解决方案应该是把mv和cp的--recursive选项都改成-R，这样能兼容macOS。

**Comment by PiraticAshin** [comment]
Linux上-R和--recursive等价所以没测试意义
macOS上测试结果：

> $ cat ./webui/build.sh
#!/usr/bin/env bash
set -ex
SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]:-$0}"; )" &> /dev/null && pwd 2> /dev/null; )";
pushd "$SCRIPT_DIR/source"
export BASE_URL="/ui/"
export VITE_EMBEDDED_BUILD="true"
npm ci && npx vite build
rm -R ../../BililiveRecorder.Web/embeded/ui 2>/dev/null || true
cp -R dist ../../BililiveRecorder.Web/embeded/ui
popd
$ ./webui/build.sh
+++ dirname -- ./webui/build.sh
++ cd -- ./webui
++ pwd
+ SCRIPT_DIR=/Volumes/ProgramLibrary/program/BililiveRecorder/webui
+ pushd /Volumes/ProgramLibrary/program/BililiveRecorder/webui/source
/Volumes/ProgramLibrary/program/BililiveRecorder/webui/source /Volumes/ProgramLibrary/program/BililiveRecorder
+ export BASE_URL=/ui/
+ BASE_URL=/ui/
+ export VITE_EMBEDDED_BUILD=true
+ VITE_EMBEDDED_BUILD=true
+ npm ci
npm WARN deprecated vscode-pug-languageservice@0.29.8: WARNING: This project has been renamed to @volar/pug-language-service. Install using @volar/pug-language-service instead.
npm WARN deprecated vscode-typescript-languageservice@0.29.8: WARNING: This project has been renamed to @volar/typescript-language-service. Install using @volar/typescript-language-service instead.
npm WARN deprecated vscode-vue-languageservice@0.29.8: WARNING: This project has been renamed to @volar/vue-language-service. Install using @volar/vue-language-service instead.

added 347 packages, and audited 348 packages in 13s

50 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
+ npx vite build
vite v2.9.1 building for production...
✓ 122 modules transformed.
✓ 138 modules transformed.
✓ 141 modules transformed.
✓ 183 modules transformed.
✓ 6180 modules transformed.
dist/assets/funthing.bc6b66cc.png          19.16 KiB
dist/assets/editor.worker.5710991c.js      167.16 KiB
dist/assets/json.worker.ea6de446.js        292.87 KiB
dist/assets/html.worker.2bf169a2.js        602.98 KiB
dist/assets/ts.worker.708f4620.js          4777.77 KiB
dist/assets/codicon.c99115f8.ttf           69.12 KiB
dist/index.html                            0.42 KiB
dist/assets/About.fa37eb1b.js              3.97 KiB / gzip: 1.30 KiB
dist/assets/ComponentsDebug.cf0ece07.js    0.39 KiB / gzip: 0.30 KiB
dist/assets/apex.4a5ec4a4.js               4.10 KiB / gzip: 1.86 KiB
dist/assets/azcli.4c9b6b47.js              1.07 KiB / gzip: 0.45 KiB
dist/assets/bat.8a420ace.js                2.04 KiB / gzip: 0.98 KiB
dist/assets/bicep.5032e09b.js              2.72 KiB / gzip: 1.08 KiB
dist/assets/cameligo.00bc63f8.js           2.37 KiB / gzip: 1.07 KiB
dist/assets/coffee.54897858.js             3.75 KiB / gzip: 1.41 KiB
dist/assets/cpp.337468ce.js                5.56 KiB / gzip: 2.20 KiB
dist/assets/csharp.01a8eaa8.js             4.66 KiB / gzip: 1.82 KiB
dist/assets/csp.aec2811b.js                1.63 KiB / gzip: 0.65 KiB
dist/assets/css.4c22ed20.js                4.64 KiB / gzip: 1.48 KiB
dist/assets/abap.6ba285e6.js               14.07 KiB / gzip: 5.34 KiB
dist/assets/clojure.bc79377e.js            9.66 KiB / gzip: 3.65 KiB
dist/assets/dart.50deccbd.js               4.39 KiB / gzip: 1.73 KiB
dist/assets/flow9.c44e3f2e.js              2.01 KiB / gzip: 0.96 KiB
dist/assets/elixir.a6460ae7.js             9.77 KiB / gzip: 2.55 KiB
dist/assets/fsharp.d9204eef.js             3.15 KiB / gzip: 1.42 KiB
dist/assets/graphql.900d9927.js            2.45 KiB / gzip: 1.13 KiB
dist/assets/ecl.19ccc34b.js                5.46 KiB / gzip: 2.33 KiB
dist/assets/dockerfile.de6a0f2c.js         2.07 KiB / gzip: 0.79 KiB
dist/assets/hcl.c0959a07.js                3.75 KiB / gzip: 1.58 KiB
dist/assets/go.1e1292ae.js                 2.83 KiB / gzip: 1.25 KiB
dist/assets/ini.75848fa5.js                1.32 KiB / gzip: 0.66 KiB
dist/assets/javascript.a7b82560.js         1.19 KiB / gzip: 0.62 KiB
dist/assets/freemarker2.a70381f7.js        16.43 KiB / gzip: 4.32 KiB
dist/assets/html.96007ddc.js               4.99 KiB / gzip: 1.48 KiB
dist/assets/kotlin.3399aeb6.js             3.60 KiB / gzip: 1.57 KiB
dist/assets/typescript.47977918.js         5.53 KiB / gzip: 2.24 KiB
dist/assets/less.b6aad23a.js               4.04 KiB / gzip: 1.52 KiB
dist/assets/lexon.44f813b3.js              2.62 KiB / gzip: 1.04 KiB
dist/assets/julia.21f68d09.js              7.29 KiB / gzip: 2.69 KiB
dist/assets/handlebars.cbdf259c.js         6.88 KiB / gzip: 1.71 KiB
dist/assets/lua.bbdfa9c0.js                2.31 KiB / gzip: 1.04 KiB
dist/assets/markdown.236ff8ef.js           3.94 KiB / gzip: 1.48 KiB
dist/assets/java.13c44e5c.js               3.39 KiB / gzip: 1.50 KiB
dist/assets/liquid.20fea29a.js             4.14 KiB / gzip: 1.76 KiB
dist/assets/mips.148d2978.js               2.76 KiB / gzip: 1.19 KiB
dist/assets/objective-c.67633c2a.js        2.59 KiB / gzip: 1.17 KiB
dist/assets/pascal.c9d19959.js             3.17 KiB / gzip: 1.50 KiB
dist/assets/m3.92f755b1.js                 2.99 KiB / gzip: 1.41 KiB
dist/assets/msdax.f39564e2.js              5.04 KiB / gzip: 2.05 KiB
dist/assets/pascaligo.1c7de3c7.js          2.19 KiB / gzip: 1.03 KiB
dist/assets/perl.140c1c72.js               8.30 KiB / gzip: 3.16 KiB
dist/assets/pgsql.1a3b46c8.js              13.33 KiB / gzip: 4.50 KiB
dist/assets/pla.c3f817e8.js                1.88 KiB / gzip: 0.77 KiB
dist/assets/postiats.8064247a.js           7.91 KiB / gzip: 2.49 KiB
dist/assets/powershell.d93de61d.js         3.43 KiB / gzip: 1.47 KiB
dist/assets/python.a16f617e.js             3.77 KiB / gzip: 1.68 KiB
dist/assets/pug.03a3b993.js                4.96 KiB / gzip: 1.74 KiB
dist/assets/qsharp.c08b4fea.js             3.10 KiB / gzip: 1.46 KiB
dist/assets/mysql.fdc04fe1.js              11.23 KiB / gzip: 4.09 KiB
dist/assets/r.1e4576a7.js                  3.30 KiB / gzip: 1.39 KiB
dist/assets/redis.8da5f515.js              3.71 KiB / gzip: 1.58 KiB
dist/assets/php.a9540a84.js                8.08 KiB / gzip: 2.15 KiB
dist/assets/protobuf.0ea0cf3d.js           9.07 KiB / gzip: 2.15 KiB
dist/assets/razor.7e5cdbbb.js              8.84 KiB / gzip: 2.38 KiB
dist/assets/restructuredtext.992abef6.js   4.04 KiB / gzip: 1.46 KiB
dist/assets/powerquery.bc98d188.js         16.78 KiB / gzip: 4.88 KiB
dist/assets/rust.349e1143.js               4.30 KiB / gzip: 1.91 KiB
dist/assets/scheme.d835dccb.js             1.97 KiB / gzip: 0.93 KiB
dist/assets/sb.e7ab3b92.js                 2.03 KiB / gzip: 0.94 KiB
dist/assets/shell.4305d323.js              3.24 KiB / gzip: 1.31 KiB
dist/assets/ruby.71d129bb.js               8.54 KiB / gzip: 2.64 KiB
dist/assets/sophia.69f82176.js             2.94 KiB / gzip: 1.31 KiB
dist/assets/scss.19caa34f.js               6.50 KiB / gzip: 1.84 KiB
dist/assets/scala.ef542eb6.js              7.39 KiB / gzip: 2.17 KiB
dist/assets/redshift.4a60845d.js           11.76 KiB / gzip: 4.35 KiB
dist/assets/sparql.1dcfd6e8.js             2.73 KiB / gzip: 1.27 KiB
dist/assets/swift.575aa114.js              5.29 KiB / gzip: 2.15 KiB
dist/assets/tcl.50105b28.js                3.73 KiB / gzip: 1.47 KiB
dist/assets/st.3f9156a8.js                 7.46 KiB / gzip: 2.31 KiB
dist/assets/sql.5f2f7ebd.js                10.30 KiB / gzip: 3.89 KiB
dist/assets/systemverilog.a897e382.js      7.67 KiB / gzip: 2.82 KiB
dist/assets/twig.74745959.js               6.07 KiB / gzip: 1.62 KiB
dist/assets/xml.49d4faec.js                2.63 KiB / gzip: 1.09 KiB
dist/assets/vb.42b9f30d.js                 5.90 KiB / gzip: 2.14 KiB
dist/assets/yaml.7d8c6ae6.js               3.70 KiB / gzip: 1.33 KiB
dist/assets/ComponentsDebug.4b553a38.css   0.05 KiB / gzip: 0.07 KiB
dist/assets/About.612822b3.css             0.05 KiB / gzip: 0.07 KiB
dist/assets/solidity.212cde55.js           18.40 KiB / gzip: 4.47 KiB
dist/assets/tsMode.f7fa7134.js             22.11 KiB / gzip: 6.30 KiB
dist/assets/VideoPlayer.cb2a3d3b.css       0.40 KiB / gzip: 0.21 KiB
dist/assets/index.7264809e.css             3.68 KiB / gzip: 0.90 KiB
dist/assets/jsonMode.6c89035c.js           38.84 KiB / gzip: 10.80 KiB
dist/assets/htmlMode.e91e7c03.js           33.48 KiB / gzip: 8.81 KiB
dist/assets/AdvancedEditor.5dc2c226.css    76.97 KiB / gzip: 13.25 KiB
dist/assets/cssMode.549428ba.js            32.73 KiB / gzip: 8.67 KiB
dist/assets/VideoPlayer.24ba3942.js        354.62 KiB / gzip: 91.68 KiB
dist/assets/index.68ab1105.js              828.88 KiB / gzip: 233.29 KiB
dist/assets/AdvancedEditor.ec5273c7.js     2631.81 KiB / gzip: 660.90 KiB

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
+ rm -R ../../BililiveRecorder.Web/embeded/ui
+ cp -R dist ../../BililiveRecorder.Web/embeded/ui
+ popd
/Volumes/ProgramLibrary/program/BililiveRecorder

**Comment by PiraticAshin** [comment]
Linux上-R和--recursive等价，所以没有测试意义。
macOS测试：
`sed -i '' 's?--recursive?-R?g' ./webui/build.sh`
`./webui/build.sh`
<img width="962" alt="image" src="https://user-images.githubusercontent.com/36768731/184547903-8dcf3a04-e677-4b71-aba4-8b8791de6e0d.png">
（macOS的sed语法和Linux上的略有差异）

webUI运行正常
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/36768731/184547971-d45fbdc2-cf38-46ea-9c2d-82e9aee7543d.png">

**Comment by shugen002** [comment]
那就来个PR？
