### ISSUE TITLE
文件名模版 为每次直播 新建文件夹，产生错误（`19700101`文件夹）

### ISSUE THREAD

**Issue by Jue-Xu** [Bililive/BililiveRecorder#377]
我采用如下文件名命名模版 为每次直播新建一个文件夹
`{{ roomId }}-{{ name }}/{{ json.room_info.live_start_time | time_zone: 'Asia/Shanghai' | format_date: "yyyyMMdd-HHmmss" }}/{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd-HHmmss-fff" }}-{{ title }}.flv`
但是这个模版会产生一个`19700101`文件夹，每次开始录的一些片段会在这个错误的文件夹内。
比如：
<img width="500" alt="image" src="https://user-images.githubusercontent.com/16731479/184560975-818bda30-bf1a-42df-9ed6-729324814215.png">
希望能够改进一下，谢谢

**Comment by Genteure** [comment]
你用的是最新版本吗？这个问题应该已经在 2.2.0 解决了，每次开始录制之前都会请求一次 API 刷新房间信息。

**Comment by Jue-Xu** [comment]
我用的2.0.0，忘记更新了。我更新之后，再来汇报。感谢开发者！
