### ISSUE TITLE
更新 2.2.0 后时间戳经常错误

### ISSUE THREAD

**Issue by Handgrip** [Bililive/BililiveRecorder#379]
投稿到B站提示：该视频时长超过十小时。
使用 ffmpeg -c copy，警告：[flv @ 0x5563e76ae6c0] Found invalid index entries, clearing the index.
都是大文件（3GB+），一个 55min，两个 1h（设置了满 1h 切割）。
之前没有这个问题，近两天出现3次了。

**Comment by Genteure** [comment]
麻烦导出一下分析数据发一下，在 “工具箱”、“录播修复”里面，选中文件之后点 “修复失败？” 然后导出分析数据。
日志文件也发一下，在房间列表页面的 “文件” 菜单里有 “显示日志文件” 选项。
如果不方便直接公开发在这里的话也可以邮件发到 rec@danmuji.org

**Comment by Handgrip** [comment]
已反馈。

**Comment by Genteure** [comment]
导出分析数据对应的命令是 `./brec tool export`，最新版本导出的是一个 zip 文件，里面对应着 FLV 文件的主要信息。
日志文件在可执行文件旁边的 logs 文件夹里，里面是每行一个 json，记录的信息比 stdout 更多。

**Comment by Handgrip** [comment]
export&nbsp;那个发了，只是在最后，一个很小的链接，你可能没看见，抱歉。json&nbsp;日志我稍后看看。


---Original---
From: ***@***.***&gt;
Date: Wed, Aug 17, 2022 01:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [BililiveRecorder/BililiveRecorder] 更新 2.2.0 后时间戳经常错误 (Issue #379)




 
导出分析数据对应的命令是 ./brec tool export，最新版本导出的是一个 zip 文件，里面对应着 FLV 文件的主要信息。
 日志文件在可执行文件旁边的 logs 文件夹里，里面是每行一个 json，记录的信息比 stdout 更多。
 
&mdash;

**Comment by Genteure** [comment]
确实是没看见，现在下载了。

**Comment by Genteure** [comment]
在 574c689c3ca0a67215f6beb546444fc590118d4c 解决了这个问题

可以在 GitHub Actions 里下载编译好的二进制，再修复一次文件就 ok 了

**Comment by Handgrip** [comment]
好的，感谢！
