### ISSUE TITLE
当录制到的直播流不满60帧时，对应视频导入pr等剪辑软件后，音画不同步且音频总会少掉后面1/6

### ISSUE THREAD

**Issue by TANGhz17** [Bililive/BililiveRecorder#382]
当录制到的直播流不满60帧时，对应视频导入pr等剪辑软件后，音画不同步且音频总会少掉后面1/6

![Snipaste_2022-08-22_10-34-40](https://user-images.githubusercontent.com/42084546/185827411-c402b40b-f21a-4413-b929-f3eabb11bc01.png)

但是使用potplayer等播放软件播放时，音画同步且没有丢失。

我做了一个测试，将单次直播所有的直播片段合并后，导入pr发现依旧是少掉1/6的音频，音画也不同步，初步怀疑是pr的解码器和ffmpeg不兼容导致的

我又将录播导入达芬奇剪辑，虽然也会出现一样的少音不同步的情况，但是当我将文件属性的帧数设置成60帧时，音画同步了但同时视频少了10分钟左右

![Snipaste_2022-08-22_10-41-30](https://user-images.githubusercontent.com/42084546/185828450-88818ad8-a921-4d69-b77e-23efeed31f11.png)

![Snipaste_2022-08-22_10-41-42](https://user-images.githubusercontent.com/42084546/185828318-3467b7b7-9c7d-4f70-bf23-99e60a53eaed.png)

原文件1小时
![Snipaste_2022-08-22_10-46-25](https://user-images.githubusercontent.com/42084546/185828675-02f758b6-9c82-4c53-a102-014ff96c82ab.png)
达芬奇中修改帧率后50分钟
![Snipaste_2022-08-22_10-45-40](https://user-images.githubusercontent.com/42084546/185828657-0b2517fb-d90c-4d31-a8bd-c1698fba3edd.png)

我不理解了，有没有什么办法能让录制下来的视频修复成兼容视频剪辑工具的

**Comment by Genteure** [comment]
没太看懂具体的问题，如果原文件还留着的话，可以在录播姬工具箱里面导出一下分析数据，在 “分析失败” 按钮里。我看起来更直观一点，方便确认视频文件里到底有多长时间的数据。

因为主播推流一侧可能会丢帧，直播服务器也有可能会有一些问题，录出来的文件是不能保证稳定 60 FPS 的，需要作为动态帧率文件处理。
目前一般解决丢帧+剪辑软件把视频作为固定帧率文件处理导致的音画不同步方法是先重新编码一次，我不剪辑文件，这方面的处理没啥经验。

**Comment by TANGhz17** [comment]
尝试重编码 ffmpeg -i in.flv -r 60 -crf 18 -c:a copy out.mp4

**Comment by TANGhz17** [comment]
![image](https://user-images.githubusercontent.com/42084546/185830817-1ea41f87-cc19-437a-a871-cb88ecbbf77f.png)
在工具箱里分析的结果

**Comment by TANGhz17** [comment]
重编码后导入依旧有问题，失败

**Comment by 6Bpencle** [comment]
> ![image](https://user-images.githubusercontent.com/42084546/185830817-1ea41f87-cc19-437a-a871-cb88ecbbf77f.png) 在工具箱里分析的结果

重编码成固定帧率50帧的视频，音频也需要重新编码一下
主播推的应该是50帧的视频源，或者推的是60帧，因为b站cdn烂的原因，缺少了部分帧
主流非编剪辑软件对可变帧率的视频文件支持的不好

**Comment by dangjinghao** [comment]
我也遇到相同问题，经过ffmpeg提取音频发现音频长度正好少约1/6，我在这里提供一个我正在用的解决方案作为参考
1. 提取音频
2. 提取视频
3. 使用ffmpeg的 -r 参数指定输入流帧率，重新将视频压制为60帧以缩短视频时长
4. 将音频和新的视频重新压在一起

参考bash脚本（使用了nvenc编解码器以加速

```bash
rec_filename=${1%.*}
rec_fullname=$1
rec_patch_fps=${2:-60}
rec_aac_filename=${rec_filename}_tmp.aac
rec_video_filename=${rec_filename}_tmp.mp4
rec_video_patch_filename=${rec_filename}_${rec_patch_fps}fps_tmp.mp4
rec_handled_filename=${rec_filename}_patch.mp4 

IFS=$'\t'
if [ ! ${rec_filename} ]
then
echo '空文件名'
exit
fi

echo '提取音频'
 ffmpeg -i $rec_fullname -vn -sn -c:a copy -y -map 0:a:0 ${rec_aac_filename} -loglevel quiet
echo '提取视频'
 ffmpeg -i $rec_fullname -an -sn -c:v copy -y -map 0:v:0 ${rec_video_filename} -loglevel quiet
echo '使用nvenc压制 fps:' $rec_patch_fps
 ffmpeg -r ${rec_patch_fps} -i ${rec_video_filename} -vcodec h264_nvenc ${rec_video_patch_filename} 
echo '拼接'
 ffmpeg -i ${rec_video_patch_filename} -i ${rec_aac_filename} -c:v copy -c:a aac -strict experimental ${rec_handled_filename} -loglevel quiet
echo '清除临时文件'
rm *_tmp.mp4 *_tmp.aac
```

**Comment by TANGhz17** [comment]
当初问题解决了，是主播端的obs版本太低，升级后使用内置的blive服务器接口后问题解决了
