### ISSUE TITLE
将命令行工具部署在网站子路径时 UI 页面无法正常加载

### ISSUE THREAD

**Issue by chirsz-ever** [Bililive/BililiveRecorder#383]
我使用的命令行工具版本是 2.2.0 Linux x86_64。

假定命令行工具运行在 2356 端口，网站域名是 `abc.com`，用 nginx 反向代理将 `http://abc.com/brec` 转发到 `http://localhost:2356`，工具似乎假定自己会被部署到网站根目录：

- 访问 `http://abc.com/brec` 得到的页面中相关链接指向 `http://abc.com/file` 和 `http://abc.com/ui` 等，都是不正确的路径。
- `http://abc.com/brec/ui` 无法正常访问，原因是试图加载 `http://abc.com/ui` 下的脚本失败。
- `http://abc.com/brec/file` 能正常访问。

这个问题应该能够在前端范围内解决？

**Comment by Genteure** [comment]
这个得问 @shugen002 ，目前前端路径是在编译的时候指定的。

https://github.com/BililiveRecorder/BililiveRecorder/blob/574c689c3ca0a67215f6beb546444fc590118d4c/webui/build.sh#L5

我之前问过 shugen 能不能做成用相对路径，我记得当时是说不能。

**Comment by chirsz-ever** [comment]
读了一些文档
- https://cli.vuejs.org/zh/config/index.html#publicpath
- https://router.vuejs.org/zh/guide/essentials/history-mode.html#服务器配置示例
- https://router.vuejs.org/zh/api/#createwebhistory

或许可以在配置中使用 `publicpath = "./"`，并在[调用 `createWebHistory` 时](https://github.com/BililiveRecorder/BililiveRecorder-WebUI/blob/fd0683edd23d386abb4c93b161ba955505851e76/src/router.ts#L26) 使用 `window.location.pathname` 之类的参数来产生可以放在任意子路径下的单页面应用？

**Comment by shugen002** [comment]
> 读了一些文档
> 
> * https://cli.vuejs.org/zh/config/index.html#publicpath
> * [https://router.vuejs.org/zh/guide/essentials/history-mode.html#服务器配置示例](https://router.vuejs.org/zh/guide/essentials/history-mode.html#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE%E7%A4%BA%E4%BE%8B)
> * https://router.vuejs.org/zh/api/#createwebhistory
> 
> 或许可以在配置中使用 `publicpath = "./"`，并在[调用 `createWebHistory` 时](https://github.com/BililiveRecorder/BililiveRecorder-WebUI/blob/fd0683edd23d386abb4c93b161ba955505851e76/src/router.ts#L26) 使用 `window.location.pathname` 之类的参数来产生可以放在任意子路径下的单页面应用？

目前这个问题主要是怎么保证js/css的加载不会出错，我可以配置成`./`，但是js/css的加载也跟着`./`就裂开了。

**Comment by chirsz-ever** [comment]
转到 https://github.com/BililiveRecorder/BililiveRecorder-WebUI/issues/29 了。
