### ISSUE TITLE
请求增加录播结束自动关机以及开机启动功能

### ISSUE THREAD

**Issue by FinderBGG** [Bililive/BililiveRecorder#386]

**Comment by Genteure** [comment]
自动关机：因为不能稳定可靠判断直播是结束了、还是因为录播一侧或主播的网络波动暂时断开了，不打算实现。
可以用 shutdown 命令实现定时关机，估算一下主播平常结束直播的时间，定时到结束之后自动关机。

开机自启：可以复制快捷方式到启动文件夹来实现，文档：[常见问题¶怎么设置开机启动？](https://rec.danmuji.org/user/faq/#%E6%80%8E%E4%B9%88%E8%AE%BE%E7%BD%AE%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8)
