### ISSUE TITLE
【外部关于ffmpeg的问题】用bat跑转封装命令会报错

### ISSUE THREAD

**Issue by b1xcy** [Bililive/BililiveRecorder#389]
在官网查到录播机转封装的指令是：

```
ffmpeg -hide_banner -loglevel error -y -i ${INPUT} -c copy ${OUTPUT}
```

我用bat写的是：

```
@echo off
ffmpeg -hide_banner -loglevel error -y -i "%1" -c copy "%~n1.mp4"
pause
```

我本设想的是，把flv文件直接拖到bat中就可以省去打开录播机的步骤。
但有些flv文件都会报错（部分flv正常）：

```
[NULL @ 000001f872b27300] Invalid NAL unit size (2047 > 271).
[NULL @ 000001f872b27300] missing picture in access unit with size 275
```

![temp](https://user-images.githubusercontent.com/24545756/187019844-12d23bfe-8faf-4852-a836-d728d7c1f4f3.png)

请问这是录播机的录制出问题了吗？
但我在录播机里使用“录播修复”功能，却提示我报错的flv文件无需修复。

**Comment by Genteure** [comment]
这个是视频文件的问题，把 `-loglevel error` 去掉看看输出了什么信息

**Comment by b1xcy** [comment]
依然输出：
[NULL @ 000001763de66f40] Invalid NAL unit size (2047 > 271).
[NULL @ 000001763de66f40] missing picture in access unit with size 275
![B](https://user-images.githubusercontent.com/24545756/187020228-4dc45230-767d-43a1-8d4a-d98c523a30c6.png)

**Comment by Genteure** [comment]
原文件能用视频播放器打开吗？看起来像是原文件的视频数据本身就是坏的。
如果你是上传到网盘平台再下载下来的，也有可能是在传输过程中损坏的，以前有人遇到过。

录播姬的分析只是 FLV 封装这一层的，所以显示无需修复。

因为不是录播姬的问题，issue 先 close 了。

**Comment by b1xcy** [comment]
源文件和封装之后的文件都可以打开。而且源文件是从OneDrive上下载的。感谢解答。
