### ISSUE TITLE
录播机仅能录一个房间

### ISSUE THREAD

**Issue by b1xcy** [Bililive/BililiveRecorder#394]
具体反应为：webui中房间内在“录制中”于“监控中”来回横跳
![rec](https://user-images.githubusercontent.com/24545756/188484838-1474493d-1e41-43f3-857b-83a504db3c37.png)
在运营商处发现内存占用过高
![运营商](https://user-images.githubusercontent.com/24545756/188484845-131797f6-4ba6-4c91-ad5b-f6c3844c8bb9.png)
后释放buff/cache
![top](https://user-images.githubusercontent.com/24545756/188484840-41a5b105-fe60-4bc4-bd9a-e7e10dd0ea81.png)
宝塔中资源与流量占用：
![宝塔](https://user-images.githubusercontent.com/24545756/188484841-8ad9fdcf-63ed-43ad-946b-285f15b1f12e.png)
![流量](https://user-images.githubusercontent.com/24545756/188484843-5da44fc2-bd0b-4af0-aca1-f7c83a17cabd.png)
录播机版本：
![录播机](https://user-images.githubusercontent.com/24545756/188485317-c7c32189-8d34-4e74-9343-d270e456ad78.png)
在下载目录中没发现开播主播的录播文件

**Comment by shugen002** [comment]
能给下日志吗？
没有日志的话我们没法给出有用的信息。
（顺带，现在最新版本是2.4.0

**Comment by b1xcy** [comment]
[bilirec20220905.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/9491118/bilirec20220905.txt)
准备今晚下播之后更新（

**Comment by b1xcy** [comment]
发现是网盘挂了。
因为我是使用rclone将网盘挂载在服务器上，工作目录设置在网盘内。
而网盘突然挂了导致无法写入（包括config文件）
![error](https://user-images.githubusercontent.com/24545756/188499678-2720b20d-b9b9-48aa-aebf-e906177a0574.png)
但现在仍然不知道为什么一个能录另一个不能录

**Comment by Genteure** [comment]
是有两个问题的意思？

一个问题是，因为 rclone 挂载掉了所以无法写入文件。

另一个问题是，录不到一个特定的直播间？是 25788785 这个吗？从日志里看全都是请求直播服务器超时。
我记得是有的时候部分直播间的流不会发到海外服务器，可能是这个原因。

**Comment by b1xcy** [comment]
我最开始其实只有一个问题：一个房间能录，另一个不行。
rclone挂掉是我后面发现的，怀疑是不是rclone导致的无法录25788785房间。
但确实是能收到直播开始的数据，却没办法录下来，不知道是不是b站那边的问题。
对于“录不到一个特定的直播间”应该不是这样的，因为我9.4日还能录这个直播间。

**Comment by Genteure** [comment]
海外服务器（域名里带有 `ov` 字样的）没有直播流是偶然现象，偶尔就会遇到，不是特定某一个直播间一直没有。
这个问题其他人以前也遇到过，国内服务器（域名带 `cn` 的）就是正常的。

**Comment by Genteure** [comment]
有再出现类似的问题吗？

**Comment by b1xcy** [comment]
暂时未发现

**Comment by mengguyi** [comment]
> 是有两个问题的意思？
> 
> 一个问题是，因为 rclone 挂载掉了所以无法写入文件。
> 
> 另一个问题是，录不到一个特定的直播间？是 25788785 这个吗？从日志里看全都是请求直播服务器超时。 我记得是有的时候部分直播间的流不会发到海外服务器，可能是这个原因。

我想问一下，你一共录了多少个直播间，在发生崩溃时有多少个直播间在录制

**Comment by b1xcy** [comment]
> > 是有两个问题的意思？
> > 一个问题是，因为 rclone 挂载掉了所以无法写入文件。
> > 另一个问题是，录不到一个特定的直播间？是 25788785 这个吗？从日志里看全都是请求直播服务器超时。 我记得是有的时候部分直播间的流不会发到海外服务器，可能是这个原因。
> 
> 我想问一下，你一共录了多少个直播间，在发生崩溃时有多少个直播间在录制

一共有三个直播间，崩溃时有一个直播间是正常录制，另一个是录不上。现在猜测是b站那边直播间推流有问题
