### ISSUE TITLE
主播下播后立即开播导致再结束直播后不会自动结束

### ISSUE THREAD

**Issue by SSSSSSSan** [Bililive/BililiveRecorder#396]
主播下播后不到1秒重新开播，然后下播后不会自动断开，反复请求最后的鬼畜片段，网速之快令人咋舌
![3U(5)@NLE3$3SR7EX)VEZ K](https://user-images.githubusercontent.com/40064285/190472233-5001e00d-8d20-4db8-85f1-48399b15e496.png)
也许是因为最后有人连麦，但是连麦的人说是先下的麦，具体怎样不是很清楚了
日志文件里只有开始接受直播流 新建文件 然后就是我的手动结束录制
最后出来的文件11个G....

**Comment by Genteure** [comment]
这个是B站直播服务器的问题，是服务器在主动发送这些数据。
桌面版公告页里面有写
![image](https://user-images.githubusercontent.com/11240579/190523996-ddfee266-245c-40ba-974a-881859af86b5.png)
[2.2.0 的更新日志](https://github.com/BililiveRecorder/BililiveRecorder/releases/tag/v2.2.0)里也有提到

**Comment by SSSSSSSan** [comment]
好吧 其他的都自动退出录制了 就这个没自动结束我以为是最后的骚操作引发的问题
