### ISSUE TITLE
设置不同的直播画质 qn 值，所产生的录播文件分辨率不一致

### ISSUE THREAD

**Issue by b1xcy** [Bililive/BililiveRecorder#397]
注意到文档中说“这个设置项 不是录制码率 。这个设置项也不是录制分辨率、录制帧率。”
所以我在服务器上设置的录制画质填的是400，日志显示也是用400录制的。录制模式是原始数据模式。
但取回录制文件发现是720P。
而本地设置的录制画质填的是10000，其他设置均为默认设置。录制文件是1080P。
所以想问一下是文档中的有误还是B站出问题，或者是录播机出BUG？

**Comment by Genteure** [comment]
直播画质设置的是图里这个选项
![image](https://user-images.githubusercontent.com/11240579/190848514-72ae3b01-5f45-49c6-bc63-68cc19c89194.png)
![image](https://user-images.githubusercontent.com/11240579/190848722-ea6c08b5-0782-48cf-bf17-9f188f017338.png)

它确实不是码率 —— 不是设置 10000 就输出 10000kbps 的文件。
它也不是分辨率 —— 写 1920x1080 进去不会输出 1080P 的文件。
它也不是帧率 —— 写 60 进去不会输出 60 FPS。
它是B站设置的各个画质的 ID。

每个画质对应数字以后有可能会变动，以网站上最新的为准。

**Comment by b1xcy** [comment]
这点我知道，我的疑问就是，为什么把qn值从10000修改到400后，输出给我的分辨率不一样？

**Comment by Genteure** [comment]
因为不同画质它的参数就是不一样的啊，要是都一样那不就没有区分不同画质的意义了
![image](https://user-images.githubusercontent.com/11240579/190848919-d586a69d-02f7-48dc-b0fd-7c08c70b8838.png)

**Comment by b1xcy** [comment]
但我刚刚试了很多主播，蓝光和原画都是1080P，超清高清才是720P。而我在服务器中设置的是400，蓝光选项，按理来说应该也是1080P

**Comment by Genteure** [comment]
各个画质的压制参数是B站控制的
