### ISSUE TITLE
[特性请求]请求把弹幕录制功能(包括SC和礼物记录)单独拆分出来使用

### ISSUE THREAD

**Issue by ghost** [Bililive/BililiveRecorder#398]
请求把弹幕录制功能(包括SC和礼物记录)单独拆分出来使用
确实非常好用hhh

**Comment by shugen002** [comment]
弹幕姬： ？？？？？

**Comment by Genteure** [comment]
单独记录弹幕的话用其他现成的工具比较好。
直接在 GitHub 上搜 `B站 直播 弹幕` 就有几十个做类似事情的仓库，当然不一定所有的都能用。
