### ISSUE TITLE
出现录制启动错误

### ISSUE THREAD

**Issue by jeagerkira** [Bililive/BililiveRecorder#399]
[](url)
![image](https://user-images.githubusercontent.com/114297831/192143950-cbc44839-81eb-4b7c-8281-9eee85496d7f.png)

**Comment by jeagerkira** [comment]
均为默认设置，未进行过更改。

**Comment by Genteure** [comment]
请求超时了，有可能是B站教育网CDN节点的问题，也有可能是你的网络问题。
