### ISSUE TITLE
建议每个房间的录播画质选项能根据当前直播间提供的画质种类进行选择

### ISSUE THREAD

**Issue by axojhf** [Bililive/BililiveRecorder#400]
有些情况下，可能需要选择一个不是原画的画质，这个时候只能先打开直播间网页看有哪些画质选项再去修改录播姬的画质选项，这一来一回就挺麻烦的，希望录播姬能在（单独房间的）画质设置那里根据API识别画质再提供选项，这样方便一些，也不容易出现画质选择的问题。

**Comment by Genteure** [comment]
画质设置支持填写多个画质ID，逗号分隔，优先用靠前的，例：`80,400,10000`。
文档：https://rec.danmuji.org/user/settings/#s-RecordingQuality
