### ISSUE TITLE
请求支持正在录播的文件增加后缀

### ISSUE THREAD

**Issue by xun404** [Bililive/BililiveRecorder#401]
因为需要自动化同步已录制的文件，建议对正在录制的文件增加类似".tmp"等临时后缀，待本次录播完成或文件分割完成后修改为正式后缀。

**Comment by Genteure** [comment]
推荐用 webhook 来判断文件是否写入完成，可以写入完成之后重命名/移动文件
https://rec.danmuji.org/user/webhook/
