### ISSUE TITLE
请求增加录制暂停功能

### ISSUE THREAD

**Issue by zhangch259** [Bililive/BililiveRecorder#403]
不知是否可以添加录制暂停后再开始，前后录制片段保持为一个文件的功能，减少视频文件数量和剪辑合并的时间，十分感谢。

**Comment by Genteure** [comment]
不打算做，原因：

- 实现起来会比较复杂麻烦
- 如果实现了暂停录制、继续写入同一个文件的功能，最终效果就只是减少了一次合并文件
- 现在直接用 `ffmpeg -c copy` 合并文件操作也挺简单、速度也不慢
- 综合考虑感觉不太值得在录播姬里实现，开发的时间成本远大于这个功能带来的便利
