### ISSUE TITLE
命令行版的录播机自动分段不生效

### ISSUE THREAD

**Issue by b1xcy** [Bililive/BililiveRecorder#404]
在webui中设置为10mb一分割，但是在文件大小到达10mb时不分割文件，设置按时间分割也不生效
![工作目录](https://user-images.githubusercontent.com/24545756/193511014-b9d71881-255c-4a1a-b0d8-d67b965d5025.png)
![设置](https://user-images.githubusercontent.com/24545756/193511023-cd421278-76c8-458b-978c-a6f95bd66f36.png)
工作目录设置为rclone中挂载的网盘目录，尚不清楚是否是因为：录播保存前不会上传到网盘中，所以录播机无法检测工作目录下的录播文件大小是否达标，但是保存时长应该能够检测到
设置与log（web中保存的）如下
[config.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/9695038/config.txt)
[log.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/9695061/log.txt)

**Comment by Genteure** [comment]
原始数据模式是直接把从直播服务器收到的数据原封不动写入硬盘，没有任何处理，不支持分段。
两个录制模式的区别：https://rec.danmuji.org/user/record-mode/

**Comment by b1xcy** [comment]
但是在设置为标准模式后，写入硬盘发生错误：**录制时发生IO错误System.IO.IOException: Illegal seek : '/home/onedrive/多多poi丶/10.03/我知道你很急，但你先别急！-145144.flv'**
log如下：
[log.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/9695241/log.txt)

**Comment by shugen002** [comment]
（webui作者表示看到这里有点麻，，，这日志一看就是从网页复制的，，，，

**Comment by b1xcy** [comment]
是的，因为不知道为什么今天的logs文件夹还没生成，只能在web上复制下来orz

**Comment by Genteure** [comment]
标准模式录的时候会 seek 到文件开头重新写 metadata。

我 Google 了一下 `rclone illegal seek` 找到了这个可以试一下：https://rclone.org/commands/rclone_mount/#vfs-file-caching
其中 `off` 和 `minimal` 两个模式都有 _Files opened for write can't be seeked_ 这个限制。

**Comment by b1xcy** [comment]
感谢帮助！
