### ISSUE TITLE
申请增加一个选项，不录制视频，因为有时候只想录制弹幕、礼物等信息，做数据用

### ISSUE THREAD

**Issue by Nm1s** [Bililive/BililiveRecorder#406]
### Feature Description

```Markdown
申请增加一个选项，不录制视频，因为有时候只想录制弹幕、礼物等信息，做数据用
```

**Comment by Genteure** [comment]
已经有 3、4 个 issue 想要只录制弹幕了。
目前实现起来会很别扭，推荐在 GitHub 上找一下其他的专门录制直播弹幕的项目，直接搜 `B站 直播 弹幕` 就有不少结果。
以后在遥远的将来如果大改录播姬的代码结构的话，_有可能_ 会考虑实现这个功能，短期是不考虑了。
