### ISSUE TITLE
有没有这个可能性可以添加投稿功能

### ISSUE THREAD

**Issue by ghost** [Bililive/BililiveRecorder#407]
### Feature Description

```Markdown
感觉自动录制自动上传很性感
```

**Comment by mengguyi** [comment]
有没有可能用户文档里在其他工具和项目写了全自动录播上传脚本的GitHub链接
https://github.com/valkjsaaa/auto-bilibili-recorder

**Comment by Genteure** [comment]
太复杂了工作量太大，不会在录播姬里实现。

可以看一下上面那个项目，或者用 [webhook](https://rec.danmuji.org/user/webhook/) + 自己写脚本 + [biliup](https://github.com/biliup/biliup) 实现自动投稿。
