### ISSUE TITLE
命令行版本：增加检查新版本并且能自动升级的功能

### ISSUE THREAD

**Issue by ghost** [Bililive/BililiveRecorder#408]
### Feature Description

想要一个检查是否有新版本，有的话自动升级的功能！
比如 `./BililiveRecorder.Cli --update`或者`程序目录里附一个 update.ps1 和 update.sh`

功能建议两种，我觉得都行：
1. 个人想法：可以检查github上的发布版本的值，和当前版本做比较，并自动根据当前平台，下载对应的包，解压替换，可能要🪜
2. 仅提示是否有新版本和新的版本号

**Comment by InterestingFred** [comment]
2 这个想法已经在webui里做了明显的提示 如果显示为黄色则不是最新版本

**Comment by InterestingFred** [comment]
![图片](https://user-images.githubusercontent.com/106480847/194459789-39feaf54-8f2a-4f95-8913-c5ab22042fdf.png)

**Comment by InterestingFred** [comment]
录播姬cli和webui基本是同时更新的 因而可以据此判断是否需要更新

**Comment by scalpl** [comment]
以及，wpf是有自动更新的

**Comment by InterestingFred** [comment]
> 以及，wpf是有自动更新的

额额 ta好像说的是命令行版本

**Comment by InterestingFred** [comment]
![图片](https://user-images.githubusercontent.com/106480847/194460704-103dd67f-7f9c-4f85-a44d-c166ef1b46a9.png)

**Comment by Genteure** [comment]
> ……可能要🪜

可能要什么？

关于检查新版本：我记得现在 WebUI 里已经有提醒了，是在前端请求 GitHub API 获取版本号对比的。

关于自动更新：
要考虑的东西太多了。各个操作系统和架构的版本，还有不自带、使用系统的 .NET Runtime 的版本。文件读写权限、自己替换自己。想想就头疼。
手动更新也没有太麻烦，两三行命令就完成了。

**Comment by ghost** [comment]
> > ……可能要🪜
> 
> 可能要什么？
> 
> 关于检查新版本：我记得现在 WebUI 里已经有提醒了，是在前端请求 GitHub API 获取版本号对比的。
> 
> 关于自动更新： 要考虑的东西太多了。各个操作系统和架构的版本，还有不自带、使用系统的 .NET Runtime 的版本。文件读写权限、自己替换自己。想想就头疼。 手动更新也没有太麻烦，两三行命令就完成了。

明白了，没发现webUI的info里有提醒且和cli同步。是我星际玩家了。

and 关于自动更新还是由用户自行shell脚本替换或者手动下载吧。
（自己写了个简单的bash 和 powershell脚本，暂时解决）

有这个想法是因为之前看的mpv播放器的windows构建，也是版本迭代的很快，且有多个版本，作者附了一个更新脚本，感觉很方便。如下：
https://github.com/shinchiro/mpv-packaging/blob/master/mpv-root/installer/updater.ps1

因为已经有解决办法，故关闭此issue。如后续有开发计划，再open。

感谢诸位的回复。
