### ISSUE TITLE
请求增加是否录制声音的功能

### ISSUE THREAD

**Issue by Davinci-D7** [Bililive/BililiveRecorder#409]
### Problem

有的直播间在直播的时候是无mic或者只有纯音乐，因此不太需要录制声音。希望能自己选择时候录制声音，谢谢。

### Proposal

增加是否录制声音的功能。

**Comment by Genteure** [comment]
没啥必要吧，音频也不占多大硬盘空间。B站也不提供只有视频没有音频的流，也不能减少下载的数据量。

如果真的需要去除视频文件里的音频的话可以用 ffmpeg 处理一下，比如：

```sh
ffmpeg -i in.flv -c:v copy -vn out.flv
```
