### ISSUE TITLE
检测到分辨率变更时自动重新开始录制

### ISSUE THREAD

**Issue by najloa** [Bililive/BililiveRecorder#411]
### Problem

先说明一下疑问：我将一位使用手机直播的主播配置为**开播后自动录制**，开播后以**720p**录制，然后经过一段时间，可能因为平台策略（达到一定观看人数开放更高画质）或主播个人修改直播参数的原因导致分辨率更改为**1080p**，这时候录播姬会**检测到分辨率更改而开始新录制**吗？

### Proposal

如上

**Comment by Genteure** [comment]
这个问题要分成两部分：

## 1. 主播推流分辨率变动的时候会不会“重新开始录制”

不会断开与直播服务器的连接然后重连，但可能会切分录制写入的文件。

标准录制模式检测到分辨率变动后会新建一个文件写入，原始数据模式会原封不动把从服务器收到的数据写到硬盘，这个在 https://rec.danmuji.org/user/record-mode/ 里面有说明。

一般出现这种情况是主播在 PK 连麦、或者手机直播切换横竖屏。如果直接存成一个文件的话会导致后半部分花屏不能正常播放。

## 2. B站开放了新的“画质选项”之后会不会重新开始录制

不会。录播姬不会为了切换画质主动断开录制。对应的文档：https://rec.danmuji.org/user/settings/#s-RecordingQuality

所有主播刚开播的时候都是只有 “原画” 画质的，也就是主播推流的没有二压的原始数据，这个是最高画质了。
观众数量变多了之后会开始压制低画质流，也就是开始有 “高清” “蓝光” 之类的画质。
部分主播的 “原画” 流也会二压，特征是视频码率显示为 10M、实际不到 10M、直播流链接以 `_blueray` 结尾。

B站编码低画质流的时候偶尔会把主播推的 720p 的直播流压成 1080p 的，但通常来说实际码率会更低，画质也肯定不如原始直播流（毕竟是有损压缩）
