### ISSUE TITLE
录播分段问题

### ISSUE THREAD

**Issue by ghost** [Bililive/BililiveRecorder#413]
### Platforms

Docker

### Version

v2.5.0

### Description

我设置了录播每隔60分钟自动分段一次，没有开启遇到错误自动分段，但是在服务器断联之后还是自动分段了

**Comment by Genteure** [comment]
> 服务器断联之后

与直播服务器的连接断开了？那肯定会断的啊

**Comment by ghost** [comment]
> > 服务器断联之后
> 
> 与直播服务器的连接断开了？那肯定会断的啊

但是诡异的是，有的时候就算没有错误的txt（提示可能上流服务器和直播服务器断开连接）也会自动分段，很明显这是不正常的，或者能不能在普通模式下面加一个就算有没有断链都会不会自动分段

![D0$CM7KN01P1YGKKKA6J7CW](https://user-images.githubusercontent.com/17939484/195664103-778e6192-54e4-4492-a231-1de8fe7b4da3.png)

**Comment by Genteure** [comment]
发一下日志吧。

如果录播姬与直播服务器之间的连接断开了，那肯定是分段的。

**Comment by ShCby** [comment]
`{"@t":"2022-10-13T10:02:26.3111983Z","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000],"SelectedQn":10000,"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.3113695Z","@mt":"连接直播服务器 {Host} 录制画质 {Qn} ({QnDescription})","Host":"cn-sccd-cm-03-06.bilivideo.com","Qn":10000,"QnDescription":"原画","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.3114963Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"https://cn-sccd-cm-03-06.bilivideo.com/live-bvc/765110/live_4773861_8140128.flv?expires=1665659006&pt=web&deadline=1665659006&len=0&oi=0x24098a557217f090f34&platform=web&qn=10000&trid=10004fc37d4fe07b4d0dafec4c5ee75625dd&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=76fda6bdececed5ae17671499e4b9f78&sk=49c1bf6d346a788252e36c1f5aec39af&p2p_type=1&src=57345&sl=1&free_type=0&sid=cn-sccd-cm-03-06&chash=1&sche=ban&score=1&usgroup=eg&pp=rtmp&machinezone=jd&source=onetier&site=beab27ce223cc13beec0bf81495c5d4f&order=1","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.3436007Z","@mt":"指定直播服务器地址 {DnsHost}: {SelectedIp}, Allowed: {AllowedAddressFamily}, {IPAddresses}","@l":"Debug","DnsHost":"cn-sccd-cm-03-06.bilivideo.com","SelectedIp":"2409:8c62:e10:2::7","AllowedAddressFamily":"Any","IPAddresses":["2409:8c62:e10:2::7","223.85.58.67"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.5345583Z","@mt":"开始接收直播流","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":23,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.5352256Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到了 onMetaData"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":33,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:28.6151194Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-180228-586-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":153,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T11:02:32.4465317Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 3603792, diff: 3603792"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":140,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T11:02:32.5985054Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-190232-596-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":140,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T12:02:36.7504053Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 7207959, diff: 7207959"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T12:02:36.8270482Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-200236-825-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:02:41.1520449Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 10812126, diff: 10812126"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":77,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:02:41.1544639Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-210241-152-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":77,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:37:58.5402406Z","@mt":"检测到录制卡住，可能是网络或硬盘原因，将会主动断开连接","@l":"Warning","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":169,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:37:58.5416626Z","@mt":"录制被取消","@l":"Debug","@x":"System.OperationCanceledException: The operation was canceled.\n   at System.Threading.CancellationToken.ThrowOperationCanceledException()\n   at System.IO.Pipelines.Pipe.GetReadAsyncResult()\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadNextTagAsync(CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 64\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadTagAsync(CancellationToken token) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 349\n   at BililiveRecorder.Flv.Grouping.TagGroupReader.ReadGroupAsync(CancellationToken token) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Grouping/TagGroupReader.cs:line 89\n   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 167","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":174,"ThreadName":".NET ThreadPool Worker","ExceptionDetail":{"Type":"System.OperationCanceledException","HResult":-2146233029,"Message":"The operation was canceled.","Source":"System.Private.CoreLib","TargetSite":"Void ThrowOperationCanceledException()","CancellationToken":"CancellationRequested: true"}}
{"@t":"2022-10-13T13:37:59.4606118Z","@mt":"录制结束","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":174,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:37:59.4606508Z","@mt":"Create record task with mode {RecordMode} for room {RoomId}","@l":"Debug","RecordMode":"Standard","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.RecordTaskFactory","ProcessId":678,"ThreadId":130,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.4136445Z","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000,150],"SelectedQn":10000,"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.4137811Z","@mt":"连接直播服务器 {Host} 录制画质 {Qn} ({QnDescription})","Host":"cn-jssz-cm-02-08.bilivideo.com","Qn":10000,"QnDescription":"原画","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.4143585Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"https://cn-jssz-cm-02-08.bilivideo.com/live-bvc/649486/live_4773861_8140128.flv?expires=1665671944&pt=web&deadline=1665671944&len=0&oi=0x24098a557217f090f34&platform=web&qn=10000&trid=10004cb711bc7eab4ec187d5e07fee6397d7&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=3836f914d8b2fdfd89770335add70d15&sk=49c1bf6d346a788252e36c1f5aec39af&p2p_type=1&src=57345&sl=1&free_type=0&sid=cn-jssz-cm-02-08&chash=1&sche=ban&score=1&usgroup=eg&pp=rtmp&machinezone=jd&source=onetier&site=a5ca8a83e771aeeaefd4064b274cd7c0&order=1","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.5587709Z","@mt":"指定直播服务器地址 {DnsHost}: {SelectedIp}, Allowed: {AllowedAddressFamily}, {IPAddresses}","@l":"Debug","DnsHost":"cn-jssz-cm-02-08.bilivideo.com","SelectedIp":"223.111.250.45","AllowedAddressFamily":"Any","IPAddresses":["2409:8c20:5624::45","223.111.250.45"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:06.1261189Z","@mt":"开始接收直播流","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":174,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:06.1268136Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到了 onMetaData"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:07.0205755Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(DecodingHeader,A): 检测到延后收到的音频头","(DecodingHeader,A): 因为 Header 问题新建文件"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":16,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:07.0227551Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-213807-020-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":16,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T14:38:06.4216024Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 3600007, diff: 3600007"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":178,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T14:38:06.5793488Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-223806-577-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":178,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T14:46:31.7326068Z","@mt":"录制结束","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":29,"ThreadName":".NET ThreadPool Worker"}`

**Comment by ShCby** [comment]
> 发一下日志吧。
> 
> 如果录播姬与直播服务器之间的连接断开了，那肯定是分段的。

`{"@t":"2022-10-13T10:02:26.3111983Z","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000],"SelectedQn":10000,"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.3113695Z","@mt":"连接直播服务器 {Host} 录制画质 {Qn} ({QnDescription})","Host":"cn-sccd-cm-03-06.bilivideo.com","Qn":10000,"QnDescription":"原画","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.3114963Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"https://cn-sccd-cm-03-06.bilivideo.com/live-bvc/765110/live_4773861_8140128.flv?expires=1665659006&pt=web&deadline=1665659006&len=0&oi=0x24098a557217f090f34&platform=web&qn=10000&trid=10004fc37d4fe07b4d0dafec4c5ee75625dd&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=76fda6bdececed5ae17671499e4b9f78&sk=49c1bf6d346a788252e36c1f5aec39af&p2p_type=1&src=57345&sl=1&free_type=0&sid=cn-sccd-cm-03-06&chash=1&sche=ban&score=1&usgroup=eg&pp=rtmp&machinezone=jd&source=onetier&site=beab27ce223cc13beec0bf81495c5d4f&order=1","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.3436007Z","@mt":"指定直播服务器地址 {DnsHost}: {SelectedIp}, Allowed: {AllowedAddressFamily}, {IPAddresses}","@l":"Debug","DnsHost":"cn-sccd-cm-03-06.bilivideo.com","SelectedIp":"2409:8c62:e10:2::7","AllowedAddressFamily":"Any","IPAddresses":["2409:8c62:e10:2::7","223.85.58.67"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.5345583Z","@mt":"开始接收直播流","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":23,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:26.5352256Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到了 onMetaData"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":33,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T10:02:28.6151194Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-180228-586-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":153,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T11:02:32.4465317Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 3603792, diff: 3603792"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":140,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T11:02:32.5985054Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-190232-596-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":140,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T12:02:36.7504053Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 7207959, diff: 7207959"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T12:02:36.8270482Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-200236-825-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":83,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:02:41.1520449Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 10812126, diff: 10812126"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":77,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:02:41.1544639Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-210241-152-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":77,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:37:58.5402406Z","@mt":"检测到录制卡住，可能是网络或硬盘原因，将会主动断开连接","@l":"Warning","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":169,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:37:58.5416626Z","@mt":"录制被取消","@l":"Debug","@x":"System.OperationCanceledException: The operation was canceled.\n   at System.Threading.CancellationToken.ThrowOperationCanceledException()\n   at System.IO.Pipelines.Pipe.GetReadAsyncResult()\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadNextTagAsync(CancellationToken cancellationToken) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 64\n   at BililiveRecorder.Flv.Parser.FlvTagPipeReader.ReadTagAsync(CancellationToken token) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Parser/FlvTagPipeReader.cs:line 349\n   at BililiveRecorder.Flv.Grouping.TagGroupReader.ReadGroupAsync(CancellationToken token) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Grouping/TagGroupReader.cs:line 89\n   at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 167","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":174,"ThreadName":".NET ThreadPool Worker","ExceptionDetail":{"Type":"System.OperationCanceledException","HResult":-2146233029,"Message":"The operation was canceled.","Source":"System.Private.CoreLib","TargetSite":"Void ThrowOperationCanceledException()","CancellationToken":"CancellationRequested: true"}}
{"@t":"2022-10-13T13:37:59.4606118Z","@mt":"录制结束","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":174,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:37:59.4606508Z","@mt":"Create record task with mode {RecordMode} for room {RoomId}","@l":"Debug","RecordMode":"Standard","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.RecordTaskFactory","ProcessId":678,"ThreadId":130,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.4136445Z","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000,150],"SelectedQn":10000,"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.4137811Z","@mt":"连接直播服务器 {Host} 录制画质 {Qn} ({QnDescription})","Host":"cn-jssz-cm-02-08.bilivideo.com","Qn":10000,"QnDescription":"原画","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.4143585Z","@mt":"直播流地址 {Url}","@l":"Debug","Url":"https://cn-jssz-cm-02-08.bilivideo.com/live-bvc/649486/live_4773861_8140128.flv?expires=1665671944&pt=web&deadline=1665671944&len=0&oi=0x24098a557217f090f34&platform=web&qn=10000&trid=10004cb711bc7eab4ec187d5e07fee6397d7&uipk=100&uipv=100&nbs=1&uparams=cdn,deadline,len,oi,platform,qn,trid,uipk,uipv,nbs&cdn=cn-gotcha01&upsig=3836f914d8b2fdfd89770335add70d15&sk=49c1bf6d346a788252e36c1f5aec39af&p2p_type=1&src=57345&sl=1&free_type=0&sid=cn-jssz-cm-02-08&chash=1&sche=ban&score=1&usgroup=eg&pp=rtmp&machinezone=jd&source=onetier&site=a5ca8a83e771aeeaefd4064b274cd7c0&order=1","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:04.5587709Z","@mt":"指定直播服务器地址 {DnsHost}: {SelectedIp}, Allowed: {AllowedAddressFamily}, {IPAddresses}","@l":"Debug","DnsHost":"cn-jssz-cm-02-08.bilivideo.com","SelectedIp":"223.111.250.45","AllowedAddressFamily":"Any","IPAddresses":["2409:8c20:5624::45","223.111.250.45"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:06.1261189Z","@mt":"开始接收直播流","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":174,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:06.1268136Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(OnMetaData,C): 收到了 onMetaData"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":53,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:07.0205755Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(DecodingHeader,A): 检测到延后收到的音频头","(DecodingHeader,A): 因为 Header 问题新建文件"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":16,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T13:38:07.0227551Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-213807-020-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":16,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T14:38:06.4216024Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(Logging,C): New file before data by split rule","(TimestampJump,A): 时间戳间隔过大, curr: 3600007, diff: 3600007"],"RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":178,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T14:38:06.5793488Z","@mt":"新建录制文件 {Path}","Path":"/video/录播/435453-喵大卫-/录制-435453-20221013-223806-577-狠！给我啵啵的狠！.flv","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":178,"ThreadName":".NET ThreadPool Worker"}
{"@t":"2022-10-13T14:46:31.7326068Z","@mt":"录制结束","RoomId":435453,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":678,"ThreadId":29,"ThreadName":".NET ThreadPool Worker"}`

**Comment by ghost** [comment]
> 发一下日志吧。
> 
> 如果录播姬与直播服务器之间的连接断开了，那肯定是分段的。

[bilirec20221013.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/9779238/bilirec20221013.txt)

**Comment by ghost** [comment]
> 发一下日志吧。
> 
> 如果录播姬与直播服务器之间的连接断开了，那肯定是分段的。

"检测到录制卡住，可能是网络或硬盘原因，将会主动断开连接"我的保存盘使用的是SMB挂载的网络硬盘（ubuntu环境）会不会是这个的问题呢？

**Comment by Genteure** [comment]
有可能。
这个检测的是连续 10 秒没有新的直播数据。

**Comment by ghost** [comment]
> 有可能。 这个检测的是连续 10 秒没有新的直播数据。

那应该就是网络问题了，SMB怎么样都不可能10秒没有响应，或者是主播的问题

**Comment by ghost** [comment]
> 有可能。 这个检测的是连续 10 秒没有新的直播数据。

这边想问一下，这边录播姬是实时写入数据还是缓存一部分再一次性写入？（我排查发现SMB是十分钟没有文件读取和写入就断开连接，即deadtime = 10）

**Comment by Genteure** [comment]
见 #416
