### ISSUE TITLE
[Feature Request] 希望可以加一个长时间低速自动重新录制/切换线路的开关

### ISSUE THREAD

**Issue by Miuzarte** [Bililive/BililiveRecorder#414]
### Problem

自动开始录制的速度总是跟不上直播速度，然后每次都可以通过重新开始录制这个方法解决，挺迷的 不太懂什么原因
![IC6T$U_NL0AMKY~5T%WI1OJ](https://user-images.githubusercontent.com/66856838/195840942-7c6274c4-7fcf-4c52-9b45-0e14a469a3f3.png)
![DYNKPFTNW}GC4)HQ6)0VQ_3](https://user-images.githubusercontent.com/66856838/195840957-bc8d886e-a20c-418a-9f10-a6640b4738bc.png)

### Proposal

长时间低速自动重新录制/切换线路
且可以指定重试次数

**Comment by Genteure** [comment]
duplicate of #346

这个应该是直播服务器问题，时不时就会遇到，录出来的直播内容也会少。
