### ISSUE TITLE
导航栏有些项目有文字，有些没文字，建议补齐文字

### ISSUE THREAD

**Issue by userzzzq** [Bililive/BililiveRecorder#417]
### Problem

导航栏有些项目有文字，有些没文字

### Proposal

建议补齐文字。
**另外，能否默认就显示文字，不要折叠？文字比图标更容易理解，更容易上手。**

![Snipaste_2022-10-26_14-52-53](https://user-images.githubusercontent.com/69742519/197955563-9d2ab07e-0d7e-4472-b341-4c66be653a2b.jpg)

**Comment by Genteure** [comment]
最上面的语言切换和配色切换其实不是导航栏的一部分，是用菜单实现的。
我记得写这部分的时候试着加了文字，但是布局会有问题，忘记具体是什么问题了。
最后因为默认整个导航栏都是折叠起来的只有一个图标也没啥影响，就做成现在这样了。

关于导航栏，默认展开的话有文字说明确实比较了解软件界面和功能，主要的缺点是比较占面积、用熟之后更希望能多显示一列房间卡片。
现在录播姬打开之后默认窗口大小是 `1000*650`，我希望能把它控制在 `1024*768` 以下，主要是方便在一些低端设备上运行。在这个窗口大小的情况下，左侧导航栏展开效果是浮在正文上面的，就像你截图里的一样，点一下其他地方就会自动消失，就算默认展开了意义也不大。只有把窗口大小拉的更大，导航栏展开之后才会固定在左侧显示。

**Comment by userzzzq** [comment]
如果能记忆窗口大小设置就好了
