### ISSUE TITLE
希望可以添加定时录制,定时关闭

### ISSUE THREAD

**Issue by Sissidark** [Bililive/BililiveRecorder#419]
### Problem

一般比赛类的直播间都是24小时直播的,自动录制无法判断是回放还是直播,无法进行预想的录制

### Proposal

希望可以添加根据**网络时间/系统时间**来设置什么时候**开始录制/停止录制**
即可以对对应的直播间设置一个录制开始的时间,一个录制结束的时间(以及可能用到的录制持续时间,开始录制后经过这个时间后结束录制)

**Comment by Genteure** [comment]
duplicate of #285
