### ISSUE TITLE
工作目录支持Webdav

### ISSUE THREAD

**Issue by earthjasonlin** [Bililive/BililiveRecorder#420]
### Problem

本机硬盘吃紧，开了个云盘支持webdav

### Proposal

工作目录支持webdav

**Comment by Genteure** [comment]
考虑以后支持类似的需求。

有试过把 webdav 挂载到本地使用吗？

比如使用 rclone: https://rclone.org/commands/rclone_mount/ https://rclone.org/webdav/
或者 https://www.raidrive.com/
或者 Windows 系统本身的挂载功能

**Comment by earthjasonlin** [comment]
没（linux用不是很明）

**Comment by shugen002** [comment]
> 没（linux用不是很明）

https://rclone.org/docker/
了解一下，不过我不是很确定实际是什么时候上传，或录播姬能否上传

**Comment by PeanutMelonSeedBigAlmond** [comment]
> > 没（linux用不是很明）
> 
> https://rclone.org/docker/ 了解一下，不过我不是很确定实际是什么时候上传，或录播姬能否上传

这个我一直在用，我试过，不论是把rclone挂载为本地磁盘，还是用rclone插件挂载为docker数据卷，据我的观察，都是在文件句柄被释放之后开始有上传流量，没释放之前会写在本地缓冲区。

挂载的网盘是OneDrive。

**Comment by ayumi-otosaka-314** [comment]
https://github.com/BililiveRecorder/BililiveRecorder/issues/438#issuecomment-1345676141
> 或者基于 [录播姬 WebHook](https://rec.danmuji.org/user/webhook/) 自己写一个脚本接收事件，文件关闭之后调用 rclone 上传文件。

https://github.com/ayumi-otosaka-314/brec-pp 
我试着做了一个webhook，可以自动上传到google drive并删除本地最老的录播来确保空间。
有需要的话也可以追加rclone或者webdav的功能

**Comment by Genteure** [comment]
最近又想了想直接支持 WebDAV 和 S3 之类的存储目标，但感觉实现起来都会比较麻烦，而且不是大部分用户都能用得上的。
目前即使录播姬不直接支持这些也有 workaround （即使用 rclone 之类的工具挂载到一个路径上）能实现相应的效果。

其中一个“难点”是 FLV 的标准模式录制目前需要有随机读写能力，要重新覆盖文件开头的 metadata。如果录播姬直接支持 S3 之类的存储目标的话需要改成不重写 metadata。

综合考虑还是不支持了吧。
