### ISSUE TITLE
支持类似blrec中“flv 添加元数据”的功能

### ISSUE THREAD

**Issue by snfcx** [Bililive/BililiveRecorder#421]
### Problem

![image](https://user-images.githubusercontent.com/55078254/201478434-324aab8a-4b15-4c6b-bad1-9db5b63b7d8d.png)
添加关键帧等元数据使定位播放和拖进度条不会卡顿，这个很有用在10小时20码率的直播里，大概超过3小时左右在PotPlayer中播放拖进度条就会明显卡顿了，在blrec测试中这个情况有很好的改善。

### Proposal

rt

**Comment by Genteure** [comment]
录播姬一直都有这个功能。

因为录播姬是一次写完，不是录制结束之后再重写一次文件，文件开头预留的大小是固定的。预留太多了浪费、预留太少了不够用。最后决定预留 6300 个索引的位置，大约是差一点不到 100KB 的大小。按关键帧间隔 2 秒算，是 3.5 小时。

超过这个大小的话，播放拖进度条就需要读取整个文件（或没有索引的部分），可以用 ffmpeg remux 成 MP4 解决。

https://github.com/BililiveRecorder/BililiveRecorder/blob/a9a2a18f25fc9e7100bf60979c905351cd923a12/BililiveRecorder.Flv/Writer/KeyframesScriptDataValue.cs#L14-L22

**Comment by lhyzf** [comment]
> 最后决定预留 6300 个索引的位置

请问该项能否作为配置项提供，并且自动分段支持按此值进行分段？
