### ISSUE TITLE
定时录制功能

### ISSUE THREAD

**Issue by Nevidebla** [Bililive/BililiveRecorder#422]
### Problem

在UI界面中没看到有给各个房间设定定时开启和关闭录制的功能（可能高级配置里面有？个人水平有限，没研究高级配置）
有些主播每场直播都是有确定时间预告的，而如果自动监控的话就有多录制上前面很长一段无意义内容，投稿视频之前还要费很多时间剪裁掉。现在只能通过盯着表手动操作实现，但是不够自动化，占用人力。

### Proposal

增加一个能给每个频道设定定时录制的功能。

**Comment by Genteure** [comment]
与 #285 重复，之后会做

切割视频可以用 `ffmpeg` 加上 `-c copy` 参数，不需要重新编码视频数据，速度会比较快。

**Comment by Nevidebla** [comment]
> 与 #285 重复，之后会做
> 
> 切割视频可以用 `ffmpeg` 加上 `-c copy` 参数，不需要重新编码视频数据，速度会比较快。

可能是我水平不行，之前用的各种软件进行无编码切割合并，经常投稿的时候出现时间戳问题。
