### ISSUE TITLE
有办法区分原画RRO和普通原画吗？

### ISSUE THREAD

**Issue by snfcx** [Bililive/BililiveRecorder#423]
### Problem

在直播开始前打开录制会录制原画，在直播一段时间后会录制就自动是原画RRO了。

### Proposal

有什么办法可以设置让软件只录制原画或者原画RRO吗

**Comment by snfcx** [comment]
我在 用户文档 看到不支持录制 HEVC 流（原画RRO） ，但是确实在直播一段时间后打开录制码率会明显下降。主播原画本来是2w码率的在直播一段时间后打开录制只有3-4k了

**Comment by Genteure** [comment]
“原画” 曾经是主播推的、原始的、没有经过压制的音视频数据，后来B站直播会对一部分观众多的直播间的原画进行二压，对观众显示的还是 “原画”。所以有两种 “原画”：真“原画” 和 二压过的“原画”。
所有带 “PRO” 字样的画质都是用主播推流数据重新编码成 H.265 的，“原画PRO” 是其中码率给的比较多的一档。

录播姬目前只支持录制 H.264 的直播流，不支持 H.265，也就不会录到带有 “PRO” 字样的直播流。
“原画” 码率降低是因为录到二压过的原画了，不是因为录到 “原画PRO” 了。

之前录真原画的方法是：主播一开播马上就开始录，并且保持录制一直不断开，就能录到完整的真原画直播流。如果断开了，再重连的时候就只能获取到二压过的直播流了。现在不确定这个方法还可行不可行。在[常见问题](https://rec.danmuji.org/user/faq/#b%E7%AB%99%E4%BA%8C%E5%8E%8B%E5%8E%9F%E7%94%BB%E5%90%8E%E5%A6%82%E4%BD%95%E5%BD%95%E5%88%B6%E7%9C%9F%E5%8E%9F%E7%94%BB)页面有写。

可以安装我写的这个脚本 https://greasyfork.org/scripts/443043
可以显示直播流码率信息以及当前使用的直播流画质

![image](https://user-images.githubusercontent.com/11240579/202892683-4b920df9-2e18-48bf-b91a-fe6b81456c33.png)
![image](https://user-images.githubusercontent.com/11240579/202892687-e8492a3c-e67b-4b8e-bbeb-f07ca79659bb.png)
![image](https://user-images.githubusercontent.com/11240579/202892715-ba6a5258-a793-4254-b399-13c112373f9a.png)
