### ISSUE TITLE
支持使用环境变量传入 HTTP Basic 用户名密码等参数

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#424]
### Problem

在某些场景下不方便使用命令行参数传入用户名密码

### Proposal

支持使用环境变量配置用户名密码

**Comment by Jue-Xu** [comment]
可以用 docker compose 传入 HTTP Basic 用户名密码吗

**Comment by akwangl** [comment]
linux可以创建启动服务在服务中写账号密码还是很方便的官网已经把服务脚本贴出来了

**Comment by Genteure** [comment]
用户名环境变量: `BREC_HTTP_BASIC_USER`
密码: `BREC_HTTP_BASIC_PASS`

命令行参数优先
