### ISSUE TITLE
ipv4 only / 连接失败时尝试仅使用ipv4

### ISSUE THREAD

**Issue by U5ER-N4ME** [Bililive/BililiveRecorder#426]
### Problem

直播姬Windows桌面版，版本2.5.0.

今天突然发现录制无法启动，一天的log达到了5MB（太长懒得细看），直接重启录播姬后直接刷新不出直播间并出现红色感叹号，偶然发现系统使用代理后能够正常使用并开始录制。

检查发现：
ipv6连接无网络（可能是偶发情况或网络调整，以前均正常），代理能够正常连接ipv6，如图。![v6a](https://user-images.githubusercontent.com/12830249/204564995-232801ad-6326-4eb7-ae8e-70270f942b17.png)
使用代理后能够正常刷新直播间，关闭代理后问题恢复。
因此我猜测可能是ipv6带来的问题，不过也不一定。

### Proposal

添加仅ipv4/ipv6/混合的选项（可以，但感觉不是很必要）；
当弹幕服务器无法连接时尝试切换为ipv4/ipv6（这个在 #279 提到过）；
弹幕服务器连接失败一定时间/一定次数后以一定频率（如每5/10分钟）弹出系统通知（一般开机自启之后直接最小化了，之前太稳定了没太在意状态）

**Comment by U5ER-N4ME** [comment]
测试了，关掉ipv6之后就正常了，应该就是ipv6没网络的问题

**Comment by Genteure** [comment]
我感觉如果你的 IPv6 网有问题并且不需要使用 IPv6 的话，还是直接在系统层面禁用最合理了。

现在有一个 IPv4/IPv6/混合/系统默认 的设置项，但只对直播流请求生效。这个在 Linux 上还有个 bug 还没修 #370

**Comment by U5ER-N4ME** [comment]
正常情况（昨天以前，以及今天）都是有的，只是昨天不能连接，所以不能正常使用。
不过还是建议添加一个连接弹幕服务器出错一段时间后弹出通知的功能。
既然已经解决，那我就先关掉了。
