### ISSUE TITLE
关闭弹幕录制的情况下，一直反复连接弹幕服务器

### ISSUE THREAD

**Issue by chesha1** [Bililive/BililiveRecorder#427]
### Platforms

CLI - Linux

### Version

v2.5.0

### Description

因为连不上国内的弹幕服务器，我就把录制弹幕的功能关了，但是还是一直报“连接弹幕服务器时出错”

**Comment by Genteure** [comment]
录播姬需要通过弹幕连接接收开播通知、房间状态更新，不止是用来录制弹幕，所以不管录制弹幕是开还是关都会连接。
如果没有连不上弹幕服务器的话也会影响到自动录制功能，会导致不能及时检测到直播间开始直播了，现在默认主动检查的间隔是 10 分钟一次。

**Comment by chesha1** [comment]
> 录播姬需要通过弹幕连接接收开播通知、房间状态更新，不止是用来录制弹幕，所以不管录制弹幕是开还是关都会连接。 如果没有连不上弹幕服务器的话也会影响到自动录制功能，会导致不能及时检测到直播间开始直播了，现在默认主动检查的间隔是 10 分钟一次。

那怎么处理一直生成的报错信息比较好呢，因为不像Windows有图形界面，我把弹幕姬的输出重定向到文本文件里方便查看录制的状态，但是输出文件里都被弹幕服务器的报错填满了。似乎是可以写个shell脚本过滤一下输出再重定向，但是有点超出我能力范围了，这种情况还可以怎么处理呢？

**Comment by Genteure** [comment]
从日志文件里读的话可以用 [jq](https://stedolan.github.io/jq/) `sudo apt install jq`

```sh
jq -c 'select( .["@mt"] | contains("弹幕服务器") | not )' 日志文件.txt
```
