### ISSUE TITLE
路线出现问题时，不会切换到其他路线，而是在有问题的路线上反复尝试

### ISSUE THREAD

**Issue by HunDunDM** [Bililive/BililiveRecorder#430]
### Platforms

WPF (桌面版)

### Version

v2.5.0

### Description

在能正常观看直播的情况下，发现无法进行录制。该房间反复在录制中和非录制中状态横跳，且不能产生录播文件。（该表现类似主播开播但没有推流）。其他路线没问题的房间录制不受影响

观察日志发现在反复尝试连接有问题的路线（经过验证发生问题时，在直播间使用同样的路线也是不能正常观看直播）。

发生问题时有问题的路线如下：cn-hnld-ct-01-44.bilivideo.com

![image](https://user-images.githubusercontent.com/19789302/205316313-8bf153b0-0f46-4074-a924-62e2daf43807.png)
![image](https://user-images.githubusercontent.com/19789302/205316223-9e9368e9-7a22-4af7-b10a-d541b18cecad.png)

日志如下
![image](https://user-images.githubusercontent.com/19789302/205316603-e0f504d8-80d3-4f4b-8582-b3acf7a14b56.png)

**Comment by HunDunDM** [comment]
有可能提供手动切换路线的功能吗？

**Comment by Genteure** [comment]
录播姬会在 B站 API 返回的直播服务器里随机选一个使用，如果B站只给了一个，那就只会用这一个。

**Comment by HunDunDM** [comment]
也就是说目前有可能 API 返回的路线数量少于实际直播间显示的路线数量（4个）

**Comment by Genteure** [comment]
B站从来都没有给过 4 个直播线路，3 个都极其少见，只有官方组织的大型直播活动才能遇到。
网页上那 4 个线路实际的选择逻辑是 `选择的线路序号 % 实际线路.length`。
也就是说实际返回 2 个不同直播服务器的情况下 `主线` `备线2` 是一样的、`备线1` `备线3` 是一样的。
大多数小主播实际只会返回 1 个直播服务器。

**Comment by Genteure** [comment]
现在还有一个判断逻辑，如果返回的直播服务器里有 `*.mcdn.bilivideo.cn` 的，就会过滤掉优先用其他的直播服务器。
实际使用中经常就会导致 API 返回了两个服务器但是只会用 `bilivideo.com` 的那个。
添加这个判断逻辑是因为当初这些服务器比其他的服务器质量差很多，不过现在应该都半斤八两吧，在考虑去掉这个规则了。

`*.mcdn.bilivideo.cn` 都是域名里带 IP 地址的，看起来像是那种家宽跑的“赚钱宝”之类的那种，不过具体是不是、是哪家的不清楚。
例子：`https://xy123x246x199x22xy.mcdn.bilivideo.cn:486` `https://xy123x246x199x18xy.mcdn.bilivideo.cn:486`

**Comment by HunDunDM** [comment]
我在另一个直播间试了下，我在直播间选择不同的路线实际在以下两个路线间切换，且都可以正常观看
* cn-hnld-ct-01-44.bilivideo.com
* c1--cn-gotcha208.bilivideo.com

而使用录播姬录制该直播间时，有以下几种路线的可能。碰到部分路线时依然会出现无法录制的情况，但重试后可以选到正常的路线
* cn-hnld-ct-01-44.bilivideo.com ×
* cn-hnld-ct-01-40.bilivideo.com ×
* cn-hnld-ct-01-42.bilivideo.com √
* cn-jsyz-ct-03-35.bilivideo.com √

（以下日志也来自同一个直播间）
![image](https://user-images.githubusercontent.com/19789302/205324085-d31300ae-664d-475a-a8e8-03b65d36e94e.png)

有点怀疑是不是灰度了什么新功能导致了不兼容。

**Comment by jkfujr** [comment]
你也可以参考群友的操作，找台能连稳定线路的机器做反代。
`https://docs.qq.com/doc/DV2dvbXBrckNscU9x`

**Comment by HunDunDM** [comment]
> 你也可以参考群友的操作，找台能连稳定线路的机器做反代。 `https://docs.qq.com/doc/DV2dvbXBrckNscU9x`

感谢！

**Comment by Genteure** [comment]
B站现在有 3 种直播流格式，HLS-FMP4、HLS-TS、HTTP-FLV。
从 7 月份开始 FLV 流的问题就变得特别特别多，各种缺数据、断开、重复数据、没有直播流(HTTP404、日志里显示 `NotFound` 等等)。
你截图里显示 `InternalServerError` 是 HTTP 500。

网页上看的是 HLS-FMP4 的流不是 FLV 的，`c1--cn-gotcha208.bilivideo.com` 只提供 HLS 流。https://rec.danmuji.org/dev/bilibili-cdn/

录播姬现在还不支持录 HLS #283

**Comment by HunDunDM** [comment]
学到了新知识，非常感谢！那这个 issue 我就先关闭了。
