### ISSUE TITLE
现在的直播录制是多个录制同时写入？

### ISSUE THREAD

**Issue by zzh151223** [Bililive/BililiveRecorder#432]
### Platforms

CLI - Linux

### Version

v2.5.0

### Description

我看了一下硬盘监控，写入要么是0，要么就是很大，直接就把硬盘给干的延迟了，导致录播一直因为硬盘卡住断开连接然后又重新录制，全是些小文件，录制的数量少没事，数量一多硬盘写入就炸了

**Comment by Genteure** [comment]
是同时写入。
不同时写入的话，怎么写？

**Comment by zzh151223** [comment]
不能分开写吗？每个直播按它自己线程的执行进度写入。我不会c#，不知道这个的写入方式。

**Comment by Genteure** [comment]
我没看懂，换个说法描述一下？因为什么原因导致什么问题？不会 C# 用其他语言或者伪代码表达一下意思也行。

现在的标准模式写入逻辑是，从网络连接收数据、修复系统进行处理、写入文件末尾、更新文件头的 metadata，每次写入一个 GOP，根据主播的码率和关键帧间隔设置，每次写入可能是 几百KB 到 十几MB 不等的直播数据。
原始数据的写入逻辑是，从网络连接接收数据、写入硬盘，每次最多 8KB。

**Comment by zzh151223** [comment]
现在是写入时数据量太大，硬盘卡住导致重复断开、录制，数据的写入集中到了一次写入。举个例子，现在有十个直播间，我想的是这一秒有4个直播间写入，下一秒6个直播间写入。现在的情况就是10个直播间同时进行写入，其它时间硬盘是空闲的。就像春运，都在一个时间点回家，车站容量就不够了。
![$ ($7%LQ19DECG ))YXBKK5](https://user-images.githubusercontent.com/47099284/205500185-429b4d89-0c50-43f6-ad72-c490f214820c.png)
![7LX}I(U0CO ~}@H`0CY2 `E](https://user-images.githubusercontent.com/47099284/205500187-d1dc4a9d-5ea3-464b-ba5d-61fa69b75dd7.png)

**Comment by KenshinLemon** [comment]
用固态硬盘做缓存，固定时间移动到机械里
