### ISSUE TITLE
为CLI修复工具添加flv自动分段选项/添加说明

### ISSUE THREAD

**Issue by gin3715** [Bililive/BililiveRecorder#436]
### Problem

目前命令行的修复工具`BililiveRecorder.Cli tool fix`没有GUI的“自动分段”的单独选项，想要分段需要手动添加`pipeline-settings '{"SplitOnScriptTag": true}'`参数，而`pipeline-settings`要如何配置在帮助和文档中均无说明

### Proposal

希望能为`pipeline-settings`支持的选项添加帮助说明，并在文档中给出json示例
或单独添加例如`--split-flv-at-jumps`这样的配置项实现`"SplitOnScriptTag": true`的功能，用于维持旧版本自动分段的行为

**Comment by Genteure** [comment]
你是怎么找到这个参数项的？是翻代码吗？
我记得有写文档的，找了一下确实没有。。我加一下

**Comment by Genteure** [comment]
https://github.com/BililiveRecorder/website/commit/7b1fe2b81606085ce486c44b4ae267c125b5e0c6

**Comment by gin3715** [comment]
对的，搜代码找的
