### ISSUE TITLE
希望加入根据直播间标题自动分段功能

### ISSUE THREAD

**Issue by mengguyi** [Bililive/BililiveRecorder#441]
### Problem

一些主播有二台的希望做到主播换标题就自动分段
例:
![PSVAZ}6C MIKB67TFQ6RIA](https://user-images.githubusercontent.com/73788063/207317150-21d54e76-7299-4120-9e9b-35bf75c0cc76.png)

### Proposal

希望在主播更改直播标题时自动分段

**Comment by lzy0702** [comment]
这样也便于录制连续播出的多个节目

**Comment by mengguyi** [comment]
是的
