### ISSUE TITLE
macOS 12.6.1 经常出现分段情况

### ISSUE THREAD

**Issue by Zrzzzz** [Bililive/BililiveRecorder#442]
设置是不分的，电脑也没有息屏，会自己分段。
一晚上录了这么多
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/55821646/206862599-02accf16-6917-4acf-b244-8816b676ec80.png">

**Comment by Genteure** [comment]
看看日志文件和录播文件旁边那个txt，里面有你想要知道的一切答案。

**Comment by Zrzzzz** [comment]
显示是网络或者硬盘原因，可是我一直在工作，没有息屏什么事件啊

**Comment by kira1928** [comment]
可能是直播卡了，被判定为网络波动，所以主动断连刷新连接重新录制了吧。
分段比卡住不刷新结果上要好接受一些。

**Comment by Genteure** [comment]
这个判定逻辑是连续 10 秒没有数据，所以不管到底是主播、B站直播服务器、你的网络还是你的硬盘的问题，肯定是有哪一个环节是卡住了。
