### ISSUE TITLE
考虑去除视频数据中的多余header

### ISSUE THREAD

**Issue by gin3715** [Bililive/BililiveRecorder#444]
### Problem

部分来源的录播的视频数据中会多一个时间戳header，或许可以考虑去除
![image](https://user-images.githubusercontent.com/17375889/209132901-459d511a-99f6-4726-801d-87b56c83942c.png)
带header的该录播CDN: cn-zjjh-ct-04-05.bilivideo.com
无header的CDN: d1--ov-gotcha07.bilivideo.com
[tags.zip](https://github.com/BililiveRecorder/BililiveRecorder/files/10286816/tags.zip)

### Proposal

可以先观望一下
如可行，后续可以考虑修复处理过程中去除不必要的header

**Comment by Genteure** [comment]
去掉的作用是啥，留着也没啥问题吧？
如果是为了去除不必要的数据的话，那理论上整个 `onMetaData` 里面的东西都是不必须的

**Comment by gin3715** [comment]
是我之前比对视频数据的时候发现不一样，不过想了一下这个确实是算我个人归档的需求，对录播姬来说不是必要的功能

**Comment by Genteure** [comment]
哦这个看起来是视频帧数据里面的 SEI NALU，留着吧，影响不大。
如果你归档想删除 _所有_ SEI NALU 的话可以

```
ffmpeg -i in.flv -c copy -bsf:v 'filter_units=remove_types=6' out.mp4
```

注意这个是针对 H264 编码的视频的。
