### ISSUE TITLE
提议新增选项：禁用元数据写入，保护隐私

### ISSUE THREAD

**Issue by gouku** [Bililive/BililiveRecorder#450]
### Problem

目前录制出来的flv都包含metadata信息，里面会有场次、连接服务器等信息，通过ffprobe可以观察到：

```
  Metadata:
    Rawdata         : 
    displayWidth    : 1920
    displayHeight   : 1080
    fps             : 60
    profile         : 
    level           : 
    encoder         : obs-output module (libobs version 27.2.1)
    server          : BSRS/1.4.12(Sco)
    server_version  : 1.4.12
    Title           : xxxxx
    Artist          : xxxxxx
    Comment         : B站直播间 123123 的直播录像
                    : 主播名: xxxx
                    : 直播标题: xxxxx
                    : 直播分区: 虚拟主播·虚拟主播
                    : 录制时间: 2022-12-25T17:29:40.0423869+08:00
                    : 直播服务器:
                    : cn-gddg-ct-01-24.bilivideo.com [14.17.92.25]
                    : 
                    : 使用 B站录播姬 录制 https://rec.danmuji.org
                    : 录播姬版本: 2.5.0
    RecordedBy      : BililiveRecorder B站录播姬
    RecordedFrom    : cn-gddg-ct-01-24.bilivideo.com
    StreamServers   : cn-gddg-ct-01-24.bilivideo.com [14.17.92.25]

```

### Proposal

增加选项，禁止metadata写入

**Comment by Genteure** [comment]
为什么？这些都不是隐私信息吧？

**Comment by gouku** [comment]
@Genteure 首先这里可以暴露直播服务器地址，比如上面的cn-gddg-ct，大概率能猜到是广东电信，我不太确定这里拿到的地址是否是根据访问ip临近的cdn去拿的，但总感觉写入这些信息并没有太多用途，不如写到 .log里

另外一个就是有时候做切片的人需要做歌切，就是只保留音频不要视频，然后把唱歌的部分切出来，但目前的流程是切出来的音频每个都会附带这个metadata，还需要批量去除掉然后再打上正确的曲目标签，就会很麻烦。

**Comment by Genteure** [comment]
CDN 信息就是为了方便溯源才加上的，虽然日志里也有但是实际用的时候去翻日志麻烦很多。有的时候发现问题了需要这个信息的时候视频文件已经不在原来录制的设备上了，找不到对应的日志了。
这个地址是B站分配的，总体是接近当前请求的客户端的位置的，但不会很精准，这个分配更多的是根据各个B站直播流机房的带宽容量之类的来分的，经常会分到物理距离更远的服务器上。我也有收集[这些服务器的域名和 IP 地址](https://rec.danmuji.org/dev/bilibili-cdn/)，这些信息自身也都是公开信息（指DNS）。
论精准度，B站投稿、评论的省级位置比这个精准多了。

现在歌切的流程是什么？都使用了什么工具？
从你的描述来看，如果需要打实际的曲目信息的话，原来是有或没有信息都不影响吧，反正最后是要改掉的。
使用 ffmpeg 的话可以参考一下 [这个](https://superuser.com/questions/441361/strip-metadata-from-all-formats-with-ffmpeg) 或者 [这个](https://stackoverflow.com/questions/38964861/how-to-remove-all-metadata-using-ffmpeg) 移除所有的 metadata

**Comment by gouku** [comment]
我们是人工用https://github.com/mifi/lossless-cut 这个软件对着坐标提取音频。

我知道ffmpeg可以很轻松处理，但是这边并不是所有人都会用命令行。

我们要做的话只能通过webhook调用外部脚本，脚本里调用ffmpeg来处理？用起来感觉其实挺麻烦的

所以如果能增加个开关禁止写入metadata就好了～

**Comment by Genteure** [comment]
已在 6376c9ac4fe2eb61354cfec78c1e93ac5f883b61 里实现
