### ISSUE TITLE
配置关闭弹幕录制时，程序仍然在链接弹幕服务器并输出错误

### ISSUE THREAD

**Issue by tumuyan** [Bililive/BililiveRecorder#451]
### Platforms

CLI - Linux

### Version

v2.5.0

### Description

使用Windows GUI生成配置文件，全局设置如下，是关闭弹幕录制的
`"global":{"RecordDanmaku":{"HasValue":true},"SaveStreamCover":{"HasValue":true,"Value":true},"FileNameRecordTemplate":{"HasValue":true,"Value":"{{ roomId }}-{{ name }}/{{ qn | format_qn }}-{{ roomId }}-{{ \"now\" | time_zone: \"Asia/Shanghai\" | format_date: \"yyyyMMdd-HHmmss-fff\" }}-{{ title }}.flv"}},`

在Linux端使用cli程序运行，（可能由于主机和弹幕服务器连接不上，但是视频是可以正常录制的），持续输出如下打印信息：
```
[10:36:06 WRN (BililiveRecorder.Core.Room)] [21672023] 连接弹幕服务器时出错
    [System.Threading.Tasks.TaskCanceledException]: A task was canceled.
[10:36:25 WRN (BililiveRecorder.Core.Room)] [21672023] 连接弹幕服务器时出错
    [System.Threading.Tasks.TaskCanceledException]: A task was canceled.
[10:38:05 WRN (BililiveRecorder.Core.Room)] [6248308] 连接弹幕服务器时出错
    [System.Net.Sockets.SocketException]: Connection timed out
[10:38:16 WRN (BililiveRecorder.Core.Room)] [21470454] 连接弹幕服务器时出错
    [System.Net.Sockets.SocketException]: Connection timed out
[10:38:24 WRN (BililiveRecorder.Core.Room)] [6248308] 连接弹幕服务器时出错
    [System.Threading.Tasks.TaskCanceledException]: A task was canceled.
[10:38:25 WRN (BililiveRecorder.Core.Room)] [21470454] 连接弹幕服务器时出错
    [System.Net.WebSockets.WebSocketException]: Unable to connect to the remote server
[10:38:34 WRN (BililiveRecorder.Core.Room)] [6248308] 连接弹幕服务器时出错
    [System.Net.WebSockets.WebSocketException]: Unable to connect to the remote server
[10:38:43 WRN (BililiveRecorder.Core.Room)] [6248308] 连接弹幕服务器时出错
    [System.Net.WebSockets.WebSocketException]: Unable to connect to the remote server
[10:38:44 WRN (BililiveRecorder.Core.Room)] [21470454] 连接弹幕服务器时出错
```

希望可以当配置文件不录制弹幕时，程序不链接弹幕服务器，从而不报这些毫无意义的错误

**Comment by Genteure** [comment]
录播姬是通过弹幕服务器接收开播通知实现开播实时启动录制的。
如果纯靠定时请求 API 来检测开播，不仅延迟高，还容易因为请求过于频繁被B站屏蔽IP，导致完全不能录制。所以目前主动定时请求默认是 10 分钟一次，只是作为备份的检测开播手段。
如果没有连接弹幕服务器，开始录制会有最多 10 分钟的延迟。

**Comment by tumuyan** [comment]
目前连接弹幕服务器，是间隔几秒刷新一次嘛？还是只有连接失败时才会重复刷新？
能否通过参数设置，减少打印这样的信息呢？

**Comment by Genteure** [comment]
“连接弹幕服务器时出错” 是没有连上弹幕服务器，所以会重试。高级设置里有弹幕服务器重连间隔的设置项，但是如果弹幕服务器没有连上的话还是会有上面说的开始录制延迟的问题。

你是在什么设备上运行的？网络环境是什么？如果是在境外并且IP被墙了，连接国内的B站弹幕服务器是连不上的。
以前我记得有香港、日本、北美之类地方的弹幕服务器，不过最近好像是没有？这个不太确定。

高级设置里也有轮询API间隔的设置，根据你的情况可以考虑把间隔调低一点。

**Comment by tumuyan** [comment]
我是尝试在colab和百度aistudio上运行的，都有这个问题

我在Windows端2.5.0的设置中没有找到高级设置

**Comment by Genteure** [comment]
桌面版的高级设置是右键点击两次左下角的设置按钮打开
