### ISSUE TITLE
希望加入直播间优先级的功能

### ISSUE THREAD

**Issue by eweca-d** [Bililive/BililiveRecorder#453]
### Problem

使用时发现，同时监控很多个直播间时，若是有好多个直播间同时直播，那么由于带宽的限制，会有一些直播间录播几乎完全没法录上，产生很多的碎片录播文件。所以有没有可能做一个优先级呢？

或许是我漏掉了，但是目前没找到类似的功能。

### Proposal

请问能否加入优先级，在UI房间列表中越靠前的优先级越高，通过拖拽调整优先度，或者对于直播间可以手动设置优先级系数0.0~10.0（前者可能会破坏现有的排序功能，后者虽然不直观但可能效果更好），然后可以全局设置一次录播的数量（比如录播数量为N=3）。那么可以有：

1. 一次只能维持N个直播间录播，其他的扔进waiting list。
2. 当没达到录播数量上限时，有新直播间开播则可以直接开始录播。
3. 当达到录播数量上限时，若新直播间的优先级高于当前录播的N个直播间里最小的那个，则将最小那个优先级的直播间的录播停止，让位给新直播间的录播要求；若不高于则挂到waiting list里去。
4. 当有正在录播的直播间结束直播时，从waiting list选出优先级最高的直播间开始直播。

**Comment by Genteure** [comment]
这个需求感觉不是大部分人都能用得到的，而且逻辑也比较复杂，适合单独做成一个工具通过调用录播姬的 API 来实现。
可以通过录播姬的 webhook 接收实时的录制状态推送、或者主动定时请求录播姬 API 检查录制状态，根据你需要的判断逻辑来控制开始录制、停止录制、和开关自动录制。

在做这个工具之前我觉得你需要确认一下，录制断开是否真的是因为录制设备的带宽不够？

- 录制了多少直播间？总码率加在一起接近你的下行带宽吗？
- 使用的是否是有线网？如果是 WiFi，偶尔的波动会导致录制断开。
- 硬盘写入速度是否能跟上？
- 最近（1月中旬左右开始到现在、春节前后）有很多人反馈B站直播服务器主动断开直播流，是否是B站的问题？

**Comment by eweca-d** [comment]
- 同时录4个就有点炸了，大概40Mbps，我家应该是100Mbps。也不知道啥情况。可能家里其他人也在用所以分了一些走吧。
- 是有线网络。
- 硬盘是致态 tiplus5000，应该压力不大。
- 额，不好说。

感谢大大的回复，有道理。我之后尝试用python写个脚本吧。

**Comment by eweca-d** [comment]
等到开学之后，用校园网，估计这个需求很挺重要了，在家其实还好。

**Comment by jkfujr** [comment]
建议722935608问群佬
