### ISSUE TITLE
希望能加入自动删除旧录像的功能

### ISSUE THREAD

**Issue by ray24777** [Bililive/BililiveRecorder#454]
### Problem

在NAS上部署后存储空间有限，若长期自动录制，则硬盘可能会被写满。

### Proposal

希望能根据直播间加入自动删除旧视频文件的功能，例如

- 自动删除7天前的录像，或
- 当直播间录像达到20G时，删除旧录像释放空间

**Comment by Genteure** [comment]
不打算做删除文件相关的功能，有需要的话可以考虑写个脚本定时运行来删除。

**Comment by ray24777** [comment]
自己写了删除的脚本，供各位参考

    #Automatically delete .flv videos captured 3 days before
    find /path/to/video -type f -name "*.flv"  -ctime 3 -exec rm {} \;
