### ISSUE TITLE
录播姬脚本的 sharedStorage.key(index: number) 方法只能输出null

### ISSUE THREAD

**Issue by komori-flag** [Bililive/BililiveRecorder#457]
### Platforms

WPF (桌面版)

### Version

v2.6.0

### Description

![QQ截图20230203130713](https://user-images.githubusercontent.com/105255344/216517566-1c798962-5d31-477a-a502-03a9ce610cc4.png)
![QQ截图20230203130824](https://user-images.githubusercontent.com/105255344/216517573-174d8aa3-ec0f-40b7-a903-14ce0871a3e8.png)
![QQ截图20230203130919](https://user-images.githubusercontent.com/105255344/216517585-743e7cb9-1e46-4fb1-abaf-c7e4e8365b12.png)

测试所使用的脚本
```javascript
recorderEvents = {
    onTest(alert) {
        let message = '此条为测试消息​(〜￣△￣)〜';
        if (typeof sharedStorage !== 'undefined') {
            message += `\n
                ==========录播姬暂存数据部分==========\n
                录播姬暂存了${sharedStorage.length}个房间的真原画直播流地址\n
                ${sharedStorage.key(0)}`;
        }

        alert(message);
    }
}
```
和
[komori-flag/reuse-old-url-test.js](https://github.com/komori-flag/recorder-scripting-DebugTest/blob/main/examples/reuse-old-url.js)

**Comment by bbaa-bbaa** [comment]
https://github.com/BililiveRecorder/BililiveRecorder/blob/3b83a16bc76591e3fa24a877b8388d4a8735f664/BililiveRecorder.Core/Scripting/Runtime/JintStorage.cs#L14
感觉是这行的大于号打反了（

**Comment by komori-flag** [comment]
> https://github.com/BililiveRecorder/BililiveRecorder/blob/3b83a16bc76591e3fa24a877b8388d4a8735f664/BililiveRecorder.Core/Scripting/Runtime/JintStorage.cs#L14
> 
> 
> 感觉是这行的大于号打反了（

把“感觉”去掉，就是[doge]
![QQ截图20230203171226](https://user-images.githubusercontent.com/105255344/216559799-f9683822-0157-4b35-8c78-c6b0dac6472b.png)
![QQ截图20230203171236](https://user-images.githubusercontent.com/105255344/216559798-30bfab43-1210-48c1-abc4-6d8deb21f75c.png)
