### ISSUE TITLE
Cli版本内置的网页管理界面的文件管理器增加支持的下载文件的格式

### ISSUE THREAD

**Issue by tumuyan** [Bililive/BililiveRecorder#459]
### Problem

Cli版本内置的网页版本文件管理器，
确认可以正常列出全部文件，下载json、xml和视频文件，但是无法下载srt字幕（字幕是我调用webhook识别出来的），点击下载时返回404.

### Proposal

希望可以支持srt字幕的下载，或者自定义文件管理器支持的格式

**Comment by Genteure** [comment]
过几天会发新版本，急用的话可以从 Actions 里下载 dev build，或者从 GitHub Registry 拉取最新的开发版 docker 镜像。
