### ISSUE TITLE
Linux 服务器命令行版本

### ISSUE THREAD

**Issue by kaidiren** [Bililive/BililiveRecorder#46]
可否把录播的功能部分剥离下，以便跨平台在 linux 上运行

https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x

 这样就可以挂在服务器上自动录制了。然后接住其他程序自动上传，完全无需人工干预了。
我先用的是python 实现的版本，功能没你提供的这个完善。 所以想咨询一下。

如果觉得太麻烦也不用勉强的~

**Comment by Genteure** [comment]
最初设计的时候就是分离的。
所有实现录制所必需的逻辑都在 `BililiveRecorder.Core` 这个项目里，有设计打算做服务器版，提供 API 和一套前端。
但是，最近几个月不会有时间做。如果自己有能力想自己做自己用的话，可以自己写一个 .NET Core 的外壳调用 `BililiveRecorder.Core`。

**Comment by kaidiren** [comment]
我回头试试看
