### ISSUE TITLE
录播文件名时区错误

### ISSUE THREAD

**Issue by tumuyan** [Bililive/BililiveRecorder#460]
### Platforms

CLI - Linux

### Version

2.5.0

### Description

文件名信息
原画-5224688-20230208-051338-376

弹幕xml文件内时间信息这样的
录制开始时间 | 2023-02-08T05:13:38.3766137+00:00
-- | --

log是这样的
下午1:13:35Info[StandardRecordTask]5224688连接直播服务器 [d1--ov-gotcha05.bilivideo.com](https://tumuyan-recorder.hf.space/ui/d1--ov-gotcha05.bilivideo.com) 录制画质 10000 (原画)

时间设置为默认
{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd-HHmmss-fff" }}

设置的预览（可以看到手机时间）
![IMG_20230208_163500](https://user-images.githubusercontent.com/3126801/217477238-b2cf0648-89e9-402d-9b70-956132f4187f.jpg)

**Comment by Genteure** [comment]
你是在什么环境运行的？哪个发行版？什么版本？有安装 `tzdata` 这个包吗？

**Comment by tumuyan** [comment]
是自己构建的docker，用的nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
安装 tzdata 这个包后文件名正常了，希望可以更新一下安装说明
