### ISSUE TITLE
内嵌网页文件管理器增加删除文件的功能

### ISSUE THREAD

**Issue by tumuyan** [Bililive/BililiveRecorder#462]
### Problem

因为是24h录播, 如果不删除部分不要的文件,硬盘空间可能不够用.

### Proposal

在内嵌的网页文件管理器增加删除文件的功能

虽然内嵌的文件管理器只是一个简易文件管理器, 确实应该用其他文件管理器删除文件,但是如果有删除功能就不需要再安装一个文件管理器了.

**Comment by shugen002** [comment]
https://github.com/BililiveRecorder/BililiveRecorder/issues/387

**Comment by ayumi-otosaka-314** [comment]
https://github.com/ayumi-otosaka-314/brec-pp/pull/11
我试着做了一个自动上传的webhook，其中可以通过删除最老的录播确保本地的空间，也许可以使用这个功能试试

**Comment by Genteure** [comment]
不太想做文件管理相关的功能，感觉有点 out of scope。如果做了删除功能之后会不会有人说想要复制、移动、重命名、打包下载之类的功能。。？
单独运行一个 alist 之类的也没多复杂，感觉更合适一些。

定时删除除了上面两个以外还有参考 #454

-----

@ayumi-otosaka-314 这个项目可以加到 https://rec.danmuji.org/user/other-projects/ 这个页面上吗？

**Comment by ayumi-otosaka-314** [comment]
@Genteure 完全没问题！
请问一下需要我这边raise pull request吗？虽然之前没有调查https://rec.danmuji.org/ 的文档放在哪里……
