### ISSUE TITLE
能不能只录声音？

### ISSUE THREAD

**Issue by zhaopingsun** [Bililive/BililiveRecorder#463]
### Problem

只想在路上听听声音，视频网络不好，现在每次录播完了得手工转换，挺麻烦的

### Proposal

房间录播设置加上只录声音

**Comment by Genteure** [comment]
不能，实现不了。
如果有能力写脚本的话，可以接收录播姬发的webhook，然后在录制完成之后调用 ffmpeg 提取音频。

**Comment by zhaopingsun** [comment]
好的，有空我研究研究webhook，谢谢

**Comment by zhaopingsun** [comment]
> 不能，实现不了。 如果有能力写脚本的话，可以接收录播姬发的webhook，然后在录制完成之后调用 ffmpeg 提取音频。

能大概解释一下为什么实现不了么？ 视频音频流不好分离？ 目前没有精力? 或者需要资金支持?

**Comment by Genteure** [comment]
接收到的直播流就是音视频在一起的，录播姬也没有处理音视频任意文件格式的能力。如果把这个功能加到录播姬里，也会是等录制结束之后用 ffmpeg 读取录好的文件输出音频。

录播姬主要功能就是录制直播，后期处理单独实现更合理。提供 webhook 功能就是为了对接自动化脚本实现各自需要的定制功能的。

就目前来说录播姬不依赖于 ffmpeg，只为这一个功能带一个 ffmpeg 不太合理。

**Comment by zhaopingsun** [comment]
明白了，非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月14日(周二) 晚上10:06
收件人: ***@***.***&gt;;
抄送: "zhaoping ***@***.******@***.***&gt;;
主题: Re: [BililiveRecorder/BililiveRecorder] 能不能只录声音？ (Issue #463)




 
接收到的直播流就是音视频在一起的，录播姬也没有处理音视频任意文件格式的能力。如果把这个功能加到录播姬里，也会是等录制结束之后用 ffmpeg 读取录好的文件输出音频。
 
录播姬主要功能就是录制直播，后期处理单独实现更合理。提供 webhook 功能就是为了对接自动化脚本实现各自需要的定制功能的。
 
就目前来说录播姬不依赖于 ffmpeg，只为这一个功能带一个 ffmpeg 不太合理。
