### ISSUE TITLE
能否添加一个保存弹幕为ass文件的选项

### ISSUE THREAD

**Issue by Jue-Xu** [Bililive/BililiveRecorder#465]
### Problem

首先非常感谢录播姬这个项目！

我的痛点是 我要使用工具(DanmakuFactory)把xml文件转换成ass字幕，才能在我常用的播放器上观看弹幕

### Proposal

我希望录播姬能够内置这个小功能（增加一个保存为ass的选项）。因为这样就不用其他工具和脚本，就能基本满足我方便地看弹幕的需求了。

再次感谢！

**Comment by Genteure** [comment]
这远不是“小功能”啊，不就相当于在录播姬里面重新实现了一遍 DanmakuFactory 吗？

**Comment by Jue-Xu** [comment]
谢谢你非常快速的回复！

我不清楚 能不能或者方不方便 把直接把 DanmakuFactory 合并进录播姬？

不好意思，原谅我不了解这方面，可能是我把这个想太简单了。

**Comment by Genteure** [comment]
代码层面的合并肯定不行

- 编程语言都不一样
- 我不想维护 DanmakuFactory
- DanmakuFactory 作为一个独立的弹幕格式转换工具，用途和适用范围和录播姬完全不一样

也不太想打包进来。

- 不是所有（或大部分）用户都需要用 DanmakuFactory，需要的人可以单独安装。
- 和 #463 类似，这个更像是录制之后的处理这一步的需求，适合做成一个相对独立的配套工具，而不是内置到录播姬里。
- 功能越多、问题越多、越难维护。录播姬只做录制，用不同的工具做不同的事是最合理的。

现在作为两个互相的独立的工具，手动操作 DanmakuFactory 转换弹幕文件是比较合理的。

不过确实有不少 “录制结束之后自动XXXX” 类的需求，其中有一些需求还挺常见的，比如转换弹幕文件、转封装视频文件之类。
目前最合理的实现方法是用录播姬的 webhook 功能，写一个脚本/程序接收 webhook，在录制完成之后执行命令等。

也许可以单独做一个专门接收录播姬 webhook 实现各种常见功能的项目？或者插件系统？

**Comment by Jue-Xu** [comment]
好的，非常感谢回复 以及 期待插件！
我也会自己思考一下如何使用脚本配合webhook实现这个功能。

**Comment by renmu123** [comment]
DanmakuFactory 有cli版本，可以出一个在录播结束后自动执行某个命令
