### ISSUE TITLE
无法正常修改config.json

### ISSUE THREAD

**Issue by chesha1** [Bililive/BililiveRecorder#466]
### Platforms

WPF (桌面版)

### Version

2.6.2

### Description

关于弹幕是否录制：
1. 当录播姬运行过程中，更改弹幕是否录制的图形按钮，RecordDanmaku["Value"]不变化
2. 关闭录播姬后，json文件仍然不变化
3. 再次打开录播姬，RecordDanmaku["Value"]才变化

config.json中其他内容，如添加房间，config.json都能得到及时修改  
另外，能否增加一个在CLI里方便的修改config的方法？

**Comment by Genteure** [comment]
> 在CLI里方便的修改config的方法

现在有 `BililiveRecorder.Cli configure` 但是之后可能考虑删除这个命令。
或者运行的时候加一个 `--bind http://localhost:2356` 启用 WebUI 在浏览器里改。
参考网站文档：https://rec.danmuji.org/user/install/cli/

-----

关于桌面版配置文件的保存，房间增删之后会马上触发一次配置文件保存，其他设置改动不会触发马上保存。录播姬退出的时候会触发一次保存。
你说的下一次打开录播姬之后文件内容才变化显然不可能发生，如果这个改动不在配置文件里，录播姬是怎么把这个信息传递到下一次运行的？我觉得是变化了你没注意到、或者文件修改了文本编辑器没有检测到没重新加载之类的原因。

如果配置文件写入失败，日志里会有记录。
配置文件写入流程是：

1. 写入 `config.{随机字符}.json`
2. 如果存在，删除 `config.backup.json`
3. 同步移动 `config.json` 到 `config.backup.json` 和移动上一步写入完成的文件到 `config.json`

大部分错误都发生在第 3 步，如果是这一步发生错误，工作目录里会多出一个 `config.{随机字符}.json` 文件。
