### ISSUE TITLE
缩放界面/最小化后再激活界面，程序完全卡死

### ISSUE THREAD

**Issue by HunDunDM** [Bililive/BililiveRecorder#471]
### Platforms

WPF (桌面版)

### Version

v2.6.2

### Description

目前当我进行下列操作时，程序会卡死无响应，只能强制关闭。
* 对界面进行缩放调整 / 最大化
* 将程序最小化后，从状态栏再次激活

出问题时，左上角的系统信息这部分界面会消失，推测与这部分信息的显示无法缩放有关。不知道有没有办法关闭它的显示？最近有升级显卡驱动，不确定是否有关。
![image](https://user-images.githubusercontent.com/19789302/227733035-39e7e688-f292-4319-b6c2-a044f675334c.png)

### Logs

```JSON
因程序完全卡死，所以没有相关的日志
```

**Comment by HunDunDM** [comment]
我在设置界面和高级设置界面都没找到怎么关闭这个，看起来它并不是默认显示的东西，不知道是怎么被打开的。

**Comment by Genteure** [comment]
这个是其他工具注入到显卡渲染流程里画上去的，一般是画到游戏窗口上面。WPF也是用显卡渲染的所以估计被判定成游戏了。

找一下是哪个工具注入渲染流程画的这个信息，关掉之后再看看还有没有这个问题，会不会卡死。可能是 ASUS 的 GPU Tweak？
![image](https://user-images.githubusercontent.com/11240579/227747792-cc293e9a-b61a-4dfe-9fbe-546cf5d22150.png)
https://www.asus.com/campaign/GPU-Tweak-III/us/img/video/GT3-Web-Refresh-OSD-GT3.mp4 [来源](https://www.asus.com/campaign/GPU-Tweak-III/us/index.php)

搜相关信息的时候发现 GPU Tweak 以前好像还在游戏里注入过广告 https://www.guru3d.com/news-story/asus-gpu-tweak-ii-injects-ads-into-your-games.html

**Comment by HunDunDM** [comment]
是 GPU Tweak 的 OSD 功能引起的，关了就不会崩了。
GPU Tweak 确实是刚刚装的软件之一，应该早点想到去排查一下的。万万没想到拿来调显卡频率的软件会引起这样的问题。

感谢快速精准的排查！
