### ISSUE TITLE
询问录播姬所需的环境

### ISSUE THREAD

**Issue by b1xcy** [Bililive/BililiveRecorder#472]
### Platforms

CLI - Linux

### Version

v2.6.2

### Description

当我自己构建一个brec的全新docker时（基于rclone镜像，而rclone使用Alpine Linux），我在进入docker内部后，尝试运行/app/BililiveRecorder.Cli，但提示/bin/ash: /app/BililiveRecorder.Cli: not found。

**Comment by Genteure** [comment]
Docker Hub 和 ghcr.io 上提供的镜像文件是用 [这个 Dockerfile](https://github.com/BililiveRecorder/BililiveRecorder/blob/dev/Dockerfile.GitHubActions) 打包出来的。另外 [这个 Dockerfile](https://github.com/BililiveRecorder/BililiveRecorder/blob/dev/Dockerfile) 也是可以用的。

你是怎么构建的镜像？
在容器里面运行 `ls /app` 的输出是什么？

**Comment by b1xcy** [comment]
我的构建方法如下：
```
FROM rclone/rclone
WORKDIR '/app/brec'
COPY brec.zip /app/brec
RUN unzip brec.zip \
    && chmod 777 * 
WORKDIR '/app'
COPY start.sh /app
RUN chmod +x start.sh
EXPOSE 2356/tcp
ENTRYPOINT ["/bin/ash","./start.sh"]
```
start.sh的内容是`./brec/BililiveRecorder.Cli --version`
其中brec.zip为[BililiveRecorder-CLI-linux-x64.zip]
容器里运行`ls /app`确实会输出brec文件夹
我现在暂时的解决办法是换用ubuntu的底包，在ubuntu中直接运行./BililiveRecorder.Cli可以启动录播机

**Comment by Genteure** [comment]
> 容器里运行 `ls /` app确实会输出brec文件夹

所以完整的路径是 `/app/brec/BililiveRecorder.Cli`?
那进入容器运行 `/app/BililiveRecorder.Cli` 的话提示找不到文件是正常的啊？

**Comment by b1xcy** [comment]
但是我在brec路径下直接运行BililiveRecorder.Cli也是找不到文件，而运行BililiveRecorder.Cli.dll则会出现报错

**Comment by Genteure** [comment]
> 但是我在brec路径下直接运行BililiveRecorder.Cli也是找不到文件

`ls /app/brec` 输出里有这个文件吗？

> 其中brec.zip为[BililiveRecorder-CLI-linux-x64.zip]

你在哪个架构运行的？

**Comment by b1xcy** [comment]
docker version输出的结果是`OS/Arch:           linux/amd64`

**Comment by Genteure** [comment]
试一下安装 `krb5-libs libgcc libintl libssl3 libstdc++ zlib`
https://github.com/dotnet/dotnet-docker/blob/f4786b8c0b4469f7eb18f891fd6c090561e50006/src/runtime-deps/6.0/alpine3.17/amd64/Dockerfile#L7-L12C13

或者从 `FROM mcr.microsoft.com/dotnet/runtime-deps` 构建
https://hub.docker.com/_/microsoft-dotnet-runtime-deps/

**Comment by b1xcy** [comment]
我在构建的时候加入了
```
RUN apk add --no-cache \
        krb5-libs \
        libgcc \
        libintl \
        libssl3 \
        libstdc++ \
        zlib \
        dotnet6-runtime \
        bash
```
重新进入容器执行出现以下错误
![image](https://user-images.githubusercontent.com/24545756/229144690-7d02445b-0e75-472b-8612-785ffbb34dae.png)

**Comment by QmZh** [comment]
安卓手机上模拟Linux终端的termux里直接运行也是提示找不到文件。但是termux里安装ubuntu之后（使用AnLinux应用可以安装），在ubuntu里可以使用，不过时区似乎需要安装一次桌面端（也是使用AnLinux应用）才能自动使用本地时区否则使用的是UTC时间

**Comment by Genteure** [comment]
@QmZh 试一下安装 `tzdata`

**Comment by b1xcy** [comment]
安装`tzdata`后执行./BililiveRecorder.Cli --version仍然报错
```
6b3820965da1:/app/brec# ./BililiveRecorder.Cli --version
bash: ./BililiveRecorder.Cli: cannot execute: required file not found
```

**Comment by Genteure** [comment]
@b1xcy 安装 `tzdata` 是回复上面关于时区的问题

你可以试一下 `ldd BililiveRecorder.Cli`

实在不行就 FROM  录播姬的镜像构建吧，反过来，把 rclone 加到录播姬的镜像里。

**Comment by b1xcy** [comment]
查看了依赖都在
```
6b3820965da1:/app/brec# ldd BililiveRecorder.Cli
	/lib64/ld-linux-x86-64.so.2 (0x7f0fe777f000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f0fe777f000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f0fe777f000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f0fe750d000)
	libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f0fe777f000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f0fe74ef000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f0fe777f000)
```
还是不理解到底缺了什么，只能基于ubuntu构建了

**Comment by shugen002** [comment]
@Genteure 你看下dotnet的构建目标里面是不是有个什么`linux-musl-x64`之类的可以加。
@b1xcy 我这边试了下，在alpine:latest下，`apk add gcompat libstdc++` 后可以运行
![image](https://user-images.githubusercontent.com/10257291/235360563-2a846a4a-00fc-411e-8002-5c4fffe428f9.png)

**Comment by shugen002** [comment]
> 我在构建的时候加入了
> 
> ```
> RUN apk add --no-cache \
>         krb5-libs \
>         libgcc \
>         libintl \
>         libssl3 \
>         libstdc++ \
>         zlib \
>         dotnet6-runtime \
>         bash
> ```

我注意到你这里尝试了dotnet-runtime，走这条路的话应该使用不带环境的any包，我试了下，会被提示
```
You must install or update .NET to run this application.

App: /root/BililiveRecorder.Cli.dll
Architecture: x64
Framework: 'Microsoft.AspNetCore.App', version '6.0.0' (x64)
.NET location: /usr/lib/dotnet/

No frameworks were found.

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=6.0.0&arch=x64&rid=alpine.3.17-x64
```
这里我给出的建议是使用微软的预安装镜像`mcr.microsoft.com/dotnet/aspnet:6.0-alpine`
一行`dotnet ./BililiveRecorder.Cli.dll`直接运行

![image](https://user-images.githubusercontent.com/10257291/235361415-5117d543-e66e-40bd-963a-2084454549c3.png)

**Comment by shugen002** [comment]
又去测试了一下，用any包，又不想用官方镜像可以`apk add aspnetcore6-runtime`，启动命令不变`dotnet ./BililiveRecorder.Cli.dll`

**Comment by Genteure** [comment]
确实，是 musl 的原因。不好意思，看这个 issue 的时候潜意识就想着 arm == musl 了，其实不是的。

可以用包管理器安装一下 runtime，然后调用 anycpu 的录播姬文件。

**Comment by holwell** [comment]
> 安卓手机上模拟Linux终端的termux里直接运行也是提示找不到文件。但是termux里安装ubuntu之后（使用AnLinux应用可以安装），在ubuntu里可以使用，不过时区似乎需要安装一次桌面端（也是使用AnLinux应用）才能自动使用本地时区否则使用的是UTC时间

您是用的chroot还是proot方式呢

**Comment by QmZh** [comment]
> > 安卓手机上模拟Linux终端的termux里直接运行也是提示找不到文件。但是termux里安装ubuntu之后（使用AnLinux应用可以安装），在ubuntu里可以使用，不过时区似乎需要安装一次桌面端（也是使用AnLinux应用）才能自动使用本地时区否则使用的是UTC时间
> 
> 您是用的chroot还是proot方式呢

您好，我使用的是proot方式。

另外有两件事情可能要注意。一个是解压release文件需要到Ubuntu系统里进行，另一个是我之前在未root手机上曾经出现过录制文件无法移动到/sdcard/Movie或/storage/emulated/0/Movie的情况，后来用root了的手机，没有问题。

手机浏览器如Chrome也可以使用网页UI。唯一不太方便的可能是没有一键录制、取消录制所有房间的选项

**Comment by holwell** [comment]
很感谢您的回复，腾讯云小水管我真的顶不住啦，换备用手机试试了👊😭👊



---原始邮件---
发件人: "Qimeng ***@***.***&gt;
发送时间: 2023年8月10日(周四) 下午2:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BililiveRecorder/BililiveRecorder] 询问录播姬所需的环境 (Issue #472)




   
安卓手机上模拟Linux终端的termux里直接运行也是提示找不到文件。但是termux里安装ubuntu之后（使用AnLinux应用可以安装），在ubuntu里可以使用，不过时区似乎需要安装一次桌面端（也是使用AnLinux应用）才能自动使用本地时区否则使用的是UTC时间
  
您是用的chroot还是proot方式呢
  
您好，我使用的是proot方式。
 
另外有两件事情可能要注意。一个是解压release文件需要到Ubuntu系统里进行，另一个是我之前在未root手机上曾经出现过录制文件无法移动到/sdcard/Movie或/storage/emulated/0/Movie的情况，后来用root了的手机，没有问题
