### ISSUE TITLE
录播文件浏览器中文件按照文件名或者修改时间排序

### ISSUE THREAD

**Issue by chang196700** [Bililive/BililiveRecorder#473]
### Problem

现在录播文件浏览器中文件排序未知，有些混乱

### Proposal

录播文件浏览器中文件按照文件名或者修改时间排序

**Comment by Genteure** [comment]
是 WebUI (vue) 里的浏览器还是 `/file/` 里面的那个？
现在应该就已经是有排序的了吧，可以发个截图吗？

**Comment by chang196700** [comment]
/file/里面的，截图：

<https://imgloc.com/i/iGJC7A>

**Comment by Genteure** [comment]
我当时看了你发的图片，只记得确实有问题，忘了具体长啥样了。现在这个链接 404 了。GitHub 自己就有图床，直接把图片拖进来就行了，下次传图可以直接传 GitHub 上。
最近几天检查一下这个问题改一改。

**Comment by shugen002** [comment]
打完这把l4d2就来看看

**Comment by shugen002** [comment]
多看了一眼，好像不是我webui的。。。

**Comment by chang196700** [comment]
![屏幕截图 2023-04-20 205559](https://github.com/BililiveRecorder/BililiveRecorder/assets/13818037/dbd25267-487f-4707-a4ae-bca04eb9a332)

**Comment by Genteure** [comment]
我这里复现不了，不过还是加了个排序上去。
