### ISSUE TITLE
有时候会一小段花屏

### ISSUE THREAD

**Issue by CHDKBL** [Bililive/BililiveRecorder#474]
录制完之后视频中间有时会有一部分花屏跳到下一幕，用修复工具没显示问题。是不是写入速度没有匹配下载速度导致的。

**Comment by Genteure** [comment]
主播如果用SRT推流并且网络有波动，可能会导致花屏绿屏。
B站直播服务器有时候会给有问题的直播数据，缺少直播片段。
录播姬不会对直播流重新编码，音视频数据本身没有修改。
