### ISSUE TITLE
直播弹幕阿瓦隆问题，怀疑是发出后被删除

### ISSUE THREAD

**Issue by QmZh** [Bililive/BililiveRecorder#475]
今天我在看直播时发了三条弹幕，当时自己看是发送出去了，等几分钟再看弹幕时第二条消失了。查看录播姬录下来的xml弹幕文件里也没有记录，想问一下是根本没发出去，还是发出去后被撤回了然后录播姬也没有录下，如果是后者，能否录下，谢谢

**Comment by Genteure** [comment]
如果直播间的弹幕特别特别多，弹幕服务器会丢弃一部分弹幕，因为 1.就算全发了屏幕上也显示不下 2.可以节省带宽。
如果是观众少弹幕少的直播间，刷新页面后刚才发送的弹幕消失，那就是没发出去。

具体是否是被关键词匹配屏蔽可以看发送弹幕请求的返回数据，如果 `msg` 或 `message` 不是空字符串就是没发送成功。
