### ISSUE TITLE
b站生病了？

### ISSUE THREAD

**Issue by CoreneMerchant** [Bililive/BililiveRecorder#476]
### Platforms

Docker

### Version

v2.6.2

### Description

最近录制原画只有 2000码率

容器：Flash Video
总码率：2 866 Kbps
大小：383 MiB
时长：18mn 42s 20ms
视频()：AVC
码率：10 000 Kbps
大小：1.31 GiB
分辨率：1920x1080
宽高比：16:9(1.778)
帧率：60.000 fps
位深度：8 bits
像素宽高比：1.000
编码库：
Profile：High@L4.2
编码时间：
总帧数：67320
音频()：AAC
大小：16.7 MiB (4%)
码率：125 Kbps
采样率：48.0 KHz
声道数：2

测速其他软件也是

总码率：2 911 Kbps
大小：464 MiB
时长：22mn 15s 0ms
视频(256)：HEVC
码率：
大小：
分辨率：1920x1080
宽高比：16:9(1.778)
帧率：60.000 fps
位深度：8 bits
像素宽高比：1.000
编码库：
Profile：Main@L4.1@Main
编码时间：
总帧数：80246
音频(257)：AAC
大小：
码率：
采样率：48.0 KHz
声道数：2

**Comment by Genteure** [comment]
从2022年3月开始就有二压过的“假原画”了，除此以外从2022年年末（忘了几月了，大概是10月左右）开始直播流的稳定性也变得很差，会出现没有直播流、直播流频繁断开、大量重复给同一段直播数据等等问题。

可以装一个我写的这个脚本，看浏览器里直播间当前播放的直播流是哪个 https://greasyfork.org/scripts/443043
