### ISSUE TITLE
Http-basic 密码输入框不显示

### ISSUE THREAD

**Issue by uminosaki** [Bililive/BililiveRecorder#477]
### Platforms

Docker

### Version

2.6.2

### Description

如果创建容器时加入http-basic 的密码设定命令，访问WebUI时不会弹出密码输入框，浏览器提示拒绝访问。
移除此命令后即可进入WebUI但是无密码保护。

浏览器：Safari / MAC；Chrome/Win11

**Comment by Genteure** [comment]
用 `curl -I` 或者浏览器的开发者控制台看一下 response header 的内容是啥？有没有 `WWW-Authenticate`

**Comment by uminosaki** [comment]
似乎并没有连接上？请请求内容可看截图
我不确定这是否可能是输入的命令有问题造成的？
我的命令输入的是 `run --bind "http:/*:2356" --http-basic-user "username" --http-basic-pass "passcode" /rec`
![image](https://github.com/BililiveRecorder/BililiveRecorder/assets/28702990/7cb2b77f-ab8f-4390-9119-ae6e62ffdb84)

**Comment by Genteure** [comment]
看看容器的日志

**Comment by uminosaki** [comment]
```
stdout: [17:48:38 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [17:48:40 INF] Web host started.
stdout: [18:16:19 INF] Shutdown in progress.
stdout: [18:16:27 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [18:16:29 INF] Web host started.
stdout: [18:17:28 INF] Shutdown in progress.
stdout: [18:29:43 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [18:29:45 INF] Web host started.
stdout: [18:30:13 INF] Shutdown in progress.
stdout: [18:30:20 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [18:30:22 INF] Web host started.
stdout: [18:35:46 INF] Shutdown in progress.
stdout: [18:53:05 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [18:53:08 INF] Web host started.
stdout: [18:53:09 INF (BililiveRecorder.Core.Room)] [2644549] 弹幕服务器已连接
stdout: [19:12:28 INF] Shutdown in progress.
stdout: [19:18:25 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [19:18:27 INF] Web host started.
stdout: [19:18:29 INF (BililiveRecorder.Core.Room)] [2644549] 弹幕服务器已连接
stdout: [19:18:38 INF] Shutdown in progress.
stdout: [19:19:15 WRN] 侦听参数解析失败，使用默认值 http://localhost:2356
stdout: [19:19:17 INF] Web host started.
```

**Comment by Genteure** [comment]
`http:/*:2356` 少了一个 `/` 吧，换成 `http://*:2356` 试试

**Comment by uminosaki** [comment]
谢谢，这确实是一个问题，但是我修改后日志还是“侦听参数解析失败”，我仔细对比过文档上的示例但是没有看到问题出在哪里。这是我现在docker的命令。
dotnet /app/BililiveRecorder.Cli.dll run --bind "http://*:2356" --http-basic-user "user" --http-basic-pass "psw" /rec

**Comment by Genteure** [comment]
你是用了什么管理面板吗？
ssh 到设备上，用 `ps` `htop` 或 `docker inspect` 之类的工具/命令检查一下容器里实际执行的命令是啥，有没有转义、多括号、少括号之类的问题。

**Comment by uminosaki** [comment]
我用了Docker Man的面板在OpenWrt上使用的。
我看了一下是`“`的问题，去掉之后就好了。
谢谢。
