### ISSUE TITLE
弹幕录制受系统时间影响

### ISSUE THREAD

**Issue by 1099255210** [Bililive/BililiveRecorder#478]
### Platforms

WPF (桌面版)

### Version

v2.6.2

### Description

弹幕录制的时候会跟系统的时间走。
比如系统时间不准，比直播时间慢了，那么弹幕也会跟着慢。

**Comment by Genteure** [comment]
是录制的过程中系统时间变慢了？这个没法解决吧，总要有一个参照的时间。

**Comment by 1099255210** [comment]
> 是录制的过程中系统时间变慢了？这个没法解决吧，总要有一个参照的时间。

之前的描述不准确，是录制过程中系统时间发生变动（比如突然调整快半小时）时会出现问题。

这个只能参考系统的时间吗？

**Comment by Genteure** [comment]
不参考系统时间还有什么其他选择吗？

**Comment by 1099255210** [comment]
> 不参考系统时间还有什么其他选择吗？

参考开始录制后经过的时间？

**Comment by Genteure** [comment]
录制后经过的时长就是用当前系统时间减去录制开始时间啊。
一条弹幕的时间就是用当前系统时间减去录制开始时的系统时间。

**Comment by 1099255210** [comment]
> 录制后经过的时长就是用当前系统时间减去录制开始时间啊。 一条弹幕的时间就是用当前系统时间减去录制开始时的系统时间。

那不可以用运行的时间作参考吗

**Comment by Genteure** [comment]
我又研究了一下，看起来 [`StopWatch`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.stopwatch) 在 Windows XP 以上的系统不会受到系统时间调整的影响，可以考虑换成这个。

**Comment by Genteure** [comment]
已在上面那个 commit 里修改，过几天发一个新的小版本。
如果现在就想试用的话可以在本仓库的 Actions 页面下载编译好的测试版。
