### ISSUE TITLE
自动分段

### ISSUE THREAD

**Issue by Areeway** [Bililive/BililiveRecorder#479]
### Platforms

WPF (桌面版)

### Version

2.6.2

## 全局设置：
* 弹幕录制全开
* 原始数据模式
* 修复关闭
* 不自动分段
* 保存封面
* 文件名格式：{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd" }}-{{ roomId }}-{{ title }}.flv
* 画质：30000,20000,10000,401,400,250,150,80
## 房间设置同上

结果如下：
* 4h的视频被分为391份，大小由4MB-509MB不等
* 仅工作目录下的一份文件文件名和命名一致，其余（390份）位于工作目录\roomid-name文件夹下，且名字为默认名字

### Logs
未保存
_No response_

**Comment by Genteure** [comment]
从去年年末开始B站直播服务器的稳定程度下降，就经常会这样了，没啥办法。

录制文件的文件名冲突之后会使用默认文件名模板。

**Comment by Areeway** [comment]
所以我需要将391个片段合到一起去合并成一个4小时直播QAQ
还是谢谢了

**Comment by leng-yue** [comment]
还有更新自动合并的意向么 (

**Comment by Genteure** [comment]
> 还有更新自动合并的意向么 (

@leng-yue 更新什么内容？

**Comment by leng-yue** [comment]
把一大堆碎片视频合并成完整的 (

**Comment by Genteure** [comment]
哦自动**合并**，我看成自动**分段**了。有一说一，不是很想做（

**Comment by leng-yue** [comment]
> 哦自动**合并**，我看成自动**分段**了。有一说一，不是很想做（

我有空看看吧 C# 不那么熟

**Comment by Genteure** [comment]
目前 “自动化后处理” 类的功能一般都推荐基于 [录播姬的webhook](https://rec.danmuji.org/user/webhook) 功能实现，包括像自动转封装、上传网盘等等之类的需求。
网站上 [_其他工具和项目_ 页面的基于 _录播姬的项目_ 部分](https://rec.danmuji.org/user/other-projects/#%E5%9F%BA%E4%BA%8E%E5%BD%95%E6%92%AD%E5%A7%AC%E7%9A%84%E9%A1%B9%E7%9B%AE) 有一些别人写的项目例子。

这个 issue 最初的问题（自动分段太多）因为不在录播姬软件本身能控制的范围内（B站直播服务器断开的）所以这个 issue 先 close 了，相关讨论可以继续。
