### ISSUE TITLE
录制统计数据始终为0

### ISSUE THREAD

**Issue by xiayuxingchen** [Bililive/BililiveRecorder#481]
### Platforms

Docker

### Version

v2.6.2

### Description

使用群晖docker运行录播姬时，房间左下角的录制时间始终为00:00:00，录制统计数据也不会变化
![Screenshot_2023-06-03-09-08-21-646_com microsoft emmx](https://github.com/BililiveRecorder/BililiveRecorder/assets/89284974/97355dd9-7771-4786-bd1c-bfcdedb5e378)

### Logs

无

**Comment by Genteure** [comment]
用的是什么录制模式？原始数据模式不解析直播流，也就没有统计信息。
https://rec.danmuji.org/user/record-mode
