### ISSUE TITLE
记录直播间被封禁到日志

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#484]
### Problem

-

### Proposal

直播间被封禁时在日志里记录一条消息

**Comment by Janet-Baker** [comment]
现有的API请求中，`/xlive/web-room/v2/index/getRoomPlayInfo`可以获取到`is_locked`和`lock_till`。在封禁持续时间内，不用开启录制监控和弹幕服务器连接（直播间都进不去）（参考[被封禁房间](https://live.bilibili.com/6758157) 至 2023-06-17 16:04:27）。

或者，用`https://api.live.bilibili.com/room/v1/Room/getBannedInfo?roomid={roomid}`也可以获取到封禁持续时间

**Comment by Genteure** [comment]
目前弹幕服务器连接没有主动不连接的逻辑，不管是什么状态都会尝试连接。多连一个弹幕服务器也没有什么负面影响。单独添加逻辑故意不监控反而更麻烦。
