### ISSUE TITLE
网络出错时填充预生成的画面而不是结束录制

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#49]
在发生主播直播断开、录制系统网络不稳定、录制连接断开等情况时，不结束录制，而是填充预生成的黑屏画面或写有一些文字的画面（如：黑色背景白色文字的“录制网络连接断开”），使得整个直播流能完整的串起来。
注：应当给出选项，能切换本功能的开关。

**Comment by Genteure** [comment]
因为每个直播间编码参数、分辨率、FPS的不同，所以不能用预先生成数据的方式填充。考虑带一个 x264 做编码器，动态生成纯色视频画面用来填充。编码器设置使用最快、码率最低的设置。录播姬设置里提供修改颜色的选项，默认纯黑色 `#000000`。

音频方面还需要再研究，需要检测前一段直播数据的音频编码和当前直播数据音频编码完全一致才能进行拼接，否则关闭上一个文件重开新文件。

在考虑使用 mkv 作为此录制模式的输出容器，有可能方便写入更多 metadata 如视频里从什么地方开始、到什么地方是填充画面。因为直播录制的文件写入是流式的，在文件开头添加新数据的话需要把整个文件的数据都向后移动。具体细节还需要再研究。

**Comment by Genteure** [comment]
把 FlvProcessor 项目重构，只留下与 Flv 解析生成密切相关的逻辑，考虑改名为 Flv （去掉 Processor），把现在的各种“业务逻辑”移到 Core 项目。
为了支持多个录制模式，把直播数据处理改成插件式。

实现三种录制模式：

- 原始 - 不做任何处理，直接把收到的数据转存到硬盘，每条连接录制成一个文件。
- 标准 - 修改所有 Tag 的时间戳，在 Script Tag 中添加视频总长度信息，每条连接录制成一个文件。
- 拼接 - 断开重连后如果 Sequence Header 不变，则存到同一个文件里，中间填充生成的纯色画面。

```csharp
interface IStreamSession
{
  // TODO
}
interface IConnectionSession
{
  // TODO
}
interface IStreamProcessor
{
  // 录制会话开始结束，直播间状态切换时调用
  void StartSession(IStreamSession session);
  void StopSession(IStreamSession session);

  // HTTP-FLV 连接成功/连接断开
  void Connected(IConnectionSession connection);
  void Disconnected(IConnectionSession connection);

  // 处理收到的 FLV 数据并写入文件
  void HandleFlvHeader(byte[] header); // FLV 通常 9 bytes 长的 Header
  void BeforeHandle(IFlvTag tag); // 所有 Tag
  void HandleScript(IFlvTag tag); // 理论只有一个的 Script Tag
  void HandleSequenceHeader(IFlvTag tag); // 理论只有两个的 Sequence Header
  void HandleVideo(IFlvTag tag); // 不含 Sequence Header 的所有视频数据
  void HandleAudio(IFlvTag tag); // 不含 Sequence Header 的所有音频数据
  void AfterHandle(IFlvTag tag); // 所有 Tag
}
```

**Comment by Genteure** [comment]
Clip 功能感觉几乎用不到，考虑去除掉

**Comment by cqjjjzr** [comment]
是否可以将重新连接后拼接的数据通过对整个GOP进行Hash来自动寻找合适的拼接点进行拼接，例如两条连接分别为：  
ABCDEFGHIJ(其中J不完整)  
GHIJKLMOP

此时是否可以尝试拼接为ABCDEFGHIJKLMOP呢？

已知可能的失败因素

- B站分发直播流的时候可能因为二压而并不按照一个一个GOP规整地传输
- 如何设计算法，使得中途如果产生 ABCDEF IJKLMN 而丢失GH的情况得到正确处理

**Comment by Genteure** [comment]
目前来看不太现实，应该不会实现了。
