### ISSUE TITLE
关于请求添加仅音频录制的新想法

### ISSUE THREAD

**Issue by dfgggg233** [Bililive/BililiveRecorder#494]
### Problem

b站直播间内也有许多单纯唱歌聊天的直播间，对画面的要求不高，尤其是弹幕可以有ass加载的情况下。并且长期录制视频占用的存储空间相比单纯音频实在是过大了。
当然这也要考虑您的意愿和能力，非常感谢您做出的贡献！

### Proposal

据我所知b站的手机客户端是有仅播放声音的选项的。
并且我所用的第三方uwp客户端也有仅播放声音的功能，因此我认为是有相应的api可以直接抓取音频。

**Comment by Genteure** [comment]
我印象中也是有纯音频流的，但是后来好像又有人说是没有的、客户端只是没播放视频画面而已。
最近没有去确认过所以我也不是很确定。

作为 workaround: 可以把所有画质id从小到大都加上，就会优先录制画质最低的那个流。

或者可以写个脚本在录制结束后用 ffmpeg 提取音频，删除视频画面。

**Comment by dfgggg233** [comment]
感谢回复
目前还是只能用这样的方法变通一下
所以还是希望您考虑下能不能加上这个功能
