### ISSUE TITLE
是否可以考虑实现登录B站账号或使用/导入浏览器cookie的功能，以正确录制弹幕发送者用户名

### ISSUE THREAD

**Issue by WZQ02** [Bililive/BililiveRecorder#496]
### Problem

从6月30日下午开始，未登录状态下监听直播间，时间超过5分钟后就会出现获取到的弹幕发送者用户名被屏蔽的情况（见 https://github.com/SocialSisterYi/bilibili-API-collect/issues/732 ）。使用最新版本录播姬录制下来的弹幕用户名全部被屏蔽，UID显示为0。

### Proposal

因此是否可以考虑实现登录B站账号或使用/导入浏览器cookie的功能，以使软件能够正确录制弹幕发送者的用户名？

**Comment by oldking139** [comment]
参考：
https://rec.danmuji.org/user/settings/#s-Cookie

cookies可从`live.bilibili.com`的请求中取得。

**Comment by WZQ02** [comment]
> 参考： https://rec.danmuji.org/user/settings/#s-Cookie
> 
> cookies可从`live.bilibili.com`的请求中取得。

了解了

**Comment by c-basalt** [comment]
目前只添加cookies还不行。在向弹幕服务器发送auth的时候提供用户的UID现在是固定为0，需要等一个发送auth的修正
https://github.com/BililiveRecorder/BililiveRecorder/blob/25b5a81db77ad208897b2d43b99fd226a86e8442/BililiveRecorder.Core/Api/Danmaku/DanmakuClient.cs#L214-L223

```C#
private Task SendHelloAsync(int roomid, string token, long uid) =>
...
        uid = uid,
...
```

@WZQ02 可以先不用急着关issue

**Comment by Genteure** [comment]
#498 已合并到主分支

**Comment by c-basalt** [comment]
@Genteure 
虽然不是100%确定，但对比其他的弹幕项目，无cookies状态下“连接弹幕服务器时使用主播UID认证”的不稳定的情况可能与 `protover = 0` 有关
需要将握手改成 `protover = 3`（**并相应实现brotli协议**）才能实现无cookies+任意非零uid稳定连接弹幕服务器

**Comment by Genteure** [comment]
@c-basalt 今天有其他人也给我说了类似的说法。
打算先这样观察一下（还有一个考虑是感觉连续发版本不太好），可能过几天会改成类似你说的这样然后再发个新版本。
