### ISSUE TITLE
重构设置系统，从全局设置改为每个直播间独立设置

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#50]
从现在的整个工作目录一个共享的设置，改为每个直播间一个独立设置。

可以独立设置录制模式（普通录制、剪辑、将来的“填充录制”）、各种超时时间、（将来的）是否保存弹幕、（将来的）填充录制无数据填充颜色。

**Comment by sy1412** [comment]
可否加个直接录制文件为MP4或MKV格式的文件的选项...而不是像其它软件那样录完再转换

**Comment by Genteure** [comment]
@sy1412 应该不会做。实现起来麻烦，用起来也没方便多少。

**Comment by Genteure** [comment]
在 1.2.0 实现了
