### ISSUE TITLE
希望增加录制文件路径控制

### ISSUE THREAD

**Issue by QLozin** [Bililive/BililiveRecorder#506]
### Problem

- [X] 已查阅文档
- [X] 已查阅Issue
---
使用docker部署录播姬后想把录制文件存放在存储空间较大的位置(`/media`)，但是录制文件只会存储在`/rec`中
我使用视频格式命名为`工作区/media/...`，尝试单独将`/rec/media`挂载到宿主机的`/media`中
有点担心出现*重复挂载*的问题
具体指令如下：
- `/media`：分配好的大容量硬盘
- `/home/user/recoder`：希望的配置文件存放处

```bash
docker run --name recoder -v /home/user/recoder/conf:/rec \
 -v /home/user/recoder/logs:/app/logs \
 -v /media:/rec/media -u 1000:1000 -e PUID=1000 -e GUID=1000 -e UMASK=022 bilibili/recoder
```
我本想通过软连接的方式解决问题，但是意外发现视频文件无法自动创建
![日志](https://github.com/BililiveRecorder/BililiveRecorder/assets/53658214/54de850a-25f7-4282-91bd-17a47bddf1a9)
如果删掉`/media`就能正确创建视频文件了，似乎说明视频文件只接受直接存放在`/rec`下，不知道是不是需要遵循*某种语法*

显然，配置文件跟视频文件不能分开存放的话，服务器为数不多的空间很快会被占据，视频也无法自动存放到外挂的硬盘中。

---
[这里放置错误信息]
```json
{"Type":"System.IO.DirectoryNotFoundException","HResult":-2147024893,"Message":"Could not find a part of the path '/rec/media/虚拟主播/阿梓从小就很可爱-80397/20230714/Rec[原画]-ID[80397]-Time[20230714 19:02:21 099]-我来了！-P1.flv'.","Source":"System.Private.CoreLib","TargetSite":"Void CheckIo(Error, System.String, Boolean, System.Func`2[Interop+ErrorInfo,Interop+ErrorInfo])"}
```
[我不知道这个是什么，但是看起来能定位错误]
```text
System.IO.DirectoryNotFoundException: Could not find a part of the path '/rec/media/虚拟主播/阿梓从小就很可爱-80397/20230714/Rec[原画]-ID[80397]-Time[20230714 19:02:21 099]-我来了！-P1.flv'. at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) at BililiveRecorder.Core.Recording.StandardRecordTask.WriterTargetProvider.CreateOutputStream() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 310 at BililiveRecorder.Flv.Writer.FlvTagFileWriter.CreateNewFile() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvTagFileWriter.cs:line 74 at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.OpenNewFileThenWriteHeadersImpl() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 233 at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteDataTags(PipelineDataAction dataAction) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 240 at BililiveRecorder.Flv.Writer.FlvProcessingContextWriter.WriteAsync(FlvProcessingContext context) in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Flv/Writer/FlvProcessingContextWriter.cs:line 64 at BililiveRecorder.Core.Recording.StandardRecordTask.RecordingLoopAsync() in /home/runner/work/BililiveRecorder/BililiveRecorder/BililiveRecorder.Core/Recording/StandardRecordTask.cs:line 181
```

### Proposal

在视频文件格式输入框允许自定义存放路径（不强制存放在工作区）
这样我就可以映射到外挂存储器上了

**Comment by Genteure** [comment]
首先要了解 docker 内部映射的路径和宿主机路径的关系，这部分如果不了解的话可以看一下 docker 官方文档或者其他的教程。通过你问的问题我感觉你是知道的，就不细说了。

容器内部使用什么路径是由命令行参数决定的，docker 镜像默认设置的是 `/rec`。软件设置里的文件名模板是基于命令行参数传入的这个路径的，而且只能在这个路径下面，如果在这个路径外面就会用默认文件名格式。这个设计有两个原因，一是防止有人设置了一个奇怪的模板把视频录到了不知道什么地方找不到文件，二是一定程度上避免了任意文件写入。

配置文件和视频文件在一起这个设计主要是给桌面版考虑的，方便运行多个录播姬进程，也方便软件本体安装、卸载、更新不影响配置。配置文件不和软件可执行文件放在一起的话另外的选择就是和视频文件放在一起了。

命令行版（包括docker镜像）支持指定配置文件的完整路径，命令参数是 `--config-override`，传入配置文件的完整文件名，参考 #388。
注意录播姬保存文件的时候会先写入一个新文件里 `config.{random}.json` 、删除 `config.backup.json`、再同时移动新文件到 `config.json` 和移动 `config.json` 到 `config.backup.json`，所以推荐配置文件挂载一个文件夹而不是只挂载单独一个文件。
这个写入流程是为了防止保存配置文件时系统断电、硬盘停转等情况导致配置文件丢失，之前没加这个逻辑的时候经常出现电脑直接关机导致配置文件损坏的情况。

不确定出现找不到路径的错误是什么原因，容器里面应该是真的没有这个路径，可能是 docker 不支持这种嵌套着挂载的用法？我没有测试。用上面指定新的配置文件路径的方法就不需要把一个路径挂载另一个路径下面了。如果你想研究一下具体原因可以用同样的 `-v` 参数运行一个 shell （指 `alpine` `ubuntu` `debian` 之类的镜像）然后用 `ls` `mount` 等命令检查一下容器内的文件系统状态。

考虑到这是个使用问题而不是录播姬本身的 bug/feature request，这个 issue 就先 close 了。有问题可以继续讨论。

**Comment by QLozin** [comment]
感谢回复 🙏 
参数`--config-override`似乎只能在命令行版使用，我尝试使用`docker run -e --config-override`来传入变量没有成功，而`docker run`也没有这个参数。

# P1
我改变了一下思路。现在我直接将`/rec`整个映射到`/home/reocder/rec`内，将`/outside_media`映射到容器内的`/inner_media`，视频录制只会在开始录制的时候才创建文件，因此我决定在容器启动后手动进入`/rec`然后使用`ln -s /inner_media /rec/media`的方式创建一个软连接，期望视频能保存到这个容器内的`/inner_media`中，这样我就能在外部得到视频。

```docker
docker run --name recoder -d -v /outside_media:/inner_media \
-v /home/recoder/rec:/rec \
-v /home/recoder/logs:/app/logs \
-u 1000:1000 -e PUID=1000 -e GUID=1000 bilibili...
```
然后设置视频格式为
```text
media/{{areaParent}}/{{name}}-{{ roomId }}/{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd" }}/Rec[{{ qn | format_qn }}]-ID[{{ roomId }}]-Time[{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd HH:mm:ss fff" }}]-{{ title }}-P{{partIndex}}.flv
```
![路径格式预览](https://github.com/BililiveRecorder/BililiveRecorder/assets/53658214/8ca9cc4e-b184-4f0c-b72e-486178c3ff4d)

~~不幸的是，我尝试进行录制，但是依然提示了路径找不到的错误。~~ 
**问题已经解决了，排障写在P2** 👍 
>![日志](https://github.com/BililiveRecorder/BililiveRecorder/assets/53658214/666ce86e-f1e9-43e9-a4ed-380800370176)
>
>我检查了文件夹，是存在`mddia`文件夹的。
>![文件夹](https://github.com/BililiveRecorder/BililiveRecorder/assets/53658214/5388f1a0-8c9e-459b-a760-df884478ecc4)

# P2
接着上文，我尝试直接在docker容器内创建了一个`media_2`然后改变路径到这个文件夹内，是能正常工作的，那么肯定是路径映射出了问题。

经过检查，发现宿主机的`/media`所属用户的`root`，只不过因为用户组是`manager`（775）所以管理员账号有权操作。但是映射的时候docker只会按照所属用户来映射，到了容器内部权限就是默认`root` (750) 😢 

而为了方便日志文件查阅和配置修改，我使用了`-u 1000:1000`的参数，导致录播姬没有权限操作软连接的`/media`，不知道为什么只报了`文件找不到`而不是`权限不足`（catch Exception { 反正就是找不到嘛 } ）

在宿主机修改好所属用户后重新挂载，再创建软连接，就能成功运作了。

![日志](https://github.com/BililiveRecorder/BililiveRecorder/assets/53658214/ae45cc07-3396-44b5-ba46-d082287a559d)

![容器内文件实况](https://github.com/BililiveRecorder/BililiveRecorder/assets/53658214/2ec4be4f-d441-472d-b592-28e02aa252a6)

希望不会再出什么奇怪的问题 🥲 🙏 
**感谢你的帮助！**  ❤️ 

# P3
虽然问题已经解决了，但是这里记录一下另一个想法。如果没解决我可能会尝试一下它。

因为直接在`/rec`内创建一个文件夹来方视频文件是可行的。
那么，吧这个文件夹`软连接`到映射的文件夹，不就行了？

因此变成了
- `/outside_media --挂载到--> /inner_media`
- `/rec/data --软连接到--> /inner_media/data`
说不定就能在宿主的`/outside_media/data`访问到资源了 🤔

**Comment by Genteure** [comment]
可以

```sh
docker run -v ./config:/config -v ./media:/rec -v ./logs:/app/logs bililive/recorder run --config-override /config/config.json --bind http://*:2356 /rec
```

容器内部的路径，视频在 `/rec`，配置文件在 `/config`，然后自行映射到需要的宿主机路径。
