### ISSUE TITLE
h.265编码的直播无法录制

### ISSUE THREAD

**Issue by YukiChoco** [Bililive/BililiveRecorder#509]
### Platforms

WPF (桌面版)

### Version

v2.8.0

### Description

编码端是禾鸟的V导播app使用h.265编码，此时录播姬标准模式开始录制后一秒自动中断且不产生录制文件。原始数据模式可以录到文件，但是只有potplayer能播放，无法导入剪辑软件（Pr原本对flv兼容就差，剪映显示源文件损坏）

**Comment by Genteure** [comment]
Duplicate of #470 

最近 _有可能_ 改一下录播姬加上对 HEVC FLV 的 _兼容_，但录出来的文件后续处理还是需要用户自己解决。
后续处理就是用魔改版 ffmpeg 把这个非标 FLV 转封装成本来就支持 HEVC 的格式比如 MP4。

只有 potplayer 能播放的原因就是 FLV 标准是不支持 HEVC 的，这个用法是以国内厂商为主的一些平台/工具自己改的。按照标准来实现的话肯定就不认识这个文件里的数据。

除此以外录播姬后续支持录 HLS 流了之后直接出 MP4 文件，也能正儿八经的支持 HEVC 编码。

**Comment by shugen002** [comment]
Duplicate of #470
