### ISSUE TITLE
想有一个只录制弹幕的功能（无视频），不开播也录

### ISSUE THREAD

**Issue by 2-3-5-7** [Bililive/BililiveRecorder#510]
### Problem

我追的 vtuber 有个特点，就是会在不开播的时候（此时直播间轮播以前的内容），时不时进入直播间用弹幕与当时在场的粉丝聊天。

而目前所有的记录软件都是记录开播时候的弹幕，这样我就根本看不到，不播的时候他们都聊了什么内容（ddstats.ericlamm.xyz 也只能看到主播的发言）。

### Proposal

所以我希望有一个手动强制录制（可录不开播时）且只录制弹幕（可选择不录视频）的功能。我知道这个需求很奇怪，如果不好弄的话，作者能否推荐一下能实现类似功能的仓库也行。十分感谢！

**Comment by shugen002** [comment]
未阅读提问指引。
![image](https://github.com/BililiveRecorder/BililiveRecorder/assets/10257291/026e1635-b98b-4ee1-8af9-87b20ad41b09)

**Comment by Arukassss** [comment]
blivedm，请

**Comment by 2-3-5-7** [comment]
> blivedm，请

谢谢，我也是找到的这个
