### ISSUE TITLE
建议添加录制的开始和结束时点限制，添加web-ui删除录播文件功能

### ISSUE THREAD

**Issue by holwell** [Bililive/BililiveRecorder#511]
### Problem

1. 因为录制资源总是那么有限的，对于有些录播场景，例如主播有二台，固定时段是早上 8 点-下午 1 点，像这种时段就没必要录制，这似乎是一个很简单实现又常用的功能，建议作者添加！再次感谢伟大的开源作者！
2. 删除录播文件也是一个非常常用的功能，因为硬盘资源有限且录播具有时效性，建议在 web-ui 添加删除文件功能，每次上服务器删除挺麻烦的。 

### Proposal

1. 增加录制时点限制功能。
2. web-ui 增加删除录播视频文件功能。

**Comment by shugen002** [comment]
重复。

1. https://github.com/BililiveRecorder/BililiveRecorder/issues/285

2. https://github.com/BililiveRecorder/BililiveRecorder/issues/462#issuecomment-1445976982
