### ISSUE TITLE
房间号正则表达式在部分情况下存在结尾不匹配

### ISSUE THREAD

**Issue by c-basalt** [Bililive/BililiveRecorder#516]
### Platforms

CLI - Linux

### Version

2.8.0

### Description

https://github.com/BililiveRecorder/BililiveRecorder/blob/e9342d43c4c7cf59685e105028af16dbb0bdee01/BililiveRecorder.WPF/Pages/RoomListPage.xaml.cs#L27

如 https://live.bilibili.com/30653161 在浏览器中会自动变为 https://live.bilibili.com/30653161#/ ，导致正则表达式不匹配

是否可以将正则结尾改成这样的，以匹配`/#`、`/?`、`#/`等结尾的URL：
 `^(?:https?:\/\/)?live\.bilibili\.com\/(?:blanc\/|h5\/)?(\d*)\/?(?:[\?#]|$)`

**Comment by Genteure** [comment]
之后改一下。WebUI 在另一个仓库，也改一下。

**Comment by shugen002** [comment]
> 之后改一下。WebUI 在另一个仓库，也改一下。

~我试了一下我这边，好像没有这个问题~

~https://github.com/BililiveRecorder/BililiveRecorder-WebUI/blob/master/src/views/recorder/RoomList.vue#L380C33-L380C118~

```regexp
/^(?:(?:https?:\/\/)?live\.bilibili\.com\/(?:blanc\/|h5\/)?)?(\d+)(?:\?.*)?(?:#.*)?$/
```

我这个在`/?`下寄掉了。。。

**Comment by shugen002** [comment]
根据我的测试，我这边大概最终会使用这个

```js
/^(?:(?:https?:\/\/)?live\.bilibili\.com\/(?:blanc\/|h5\/)?)?(\d+)(?:[#\?\/].*)?$/
```
附regex101测试结果
![image](https://github.com/BililiveRecorder/BililiveRecorder/assets/10257291/962775c1-1181-4fdf-b9de-aade7589500a)

https://regex101.com/r/EukteU/1 
点这个进去，左边选一下Unit Test 就可以体验同款

**Comment by shugen002** [comment]
不过我在思考，对于 `https://live.bilibili.com/388/abc` 这种实际打不开的链接要不要去做兼容，让他去匹配上中间的388，还是说当错误丢掉

**Comment by Genteure** [comment]
这种匹配不上比较好
```^(?:(?:https?:\/\/)?live\.bilibili\.com\/(?:blanc\/|h5\/)?)?(\d+)\/?(?:[#\?].*)?$```
