### ISSUE TITLE
2.8.2版本在WinServer2008出现The WebSocket protocol is not supported on this platform

### ISSUE THREAD

**Issue by mcbaiyun** [Bililive/BililiveRecorder#517]
### Platforms

WPF (桌面版)

### Version

v2.8.2

### Description

在昨日2023-08-22使用录播机过程中，发现录播机原本绿色的云图标呈现红色警告状态，打开日志发现每个设置的房间ID每秒都有The WebSocket protocol is not supported on this platform.的问题刷屏
初步估计为IP被B站列为风险IP，进行了风控处理
在进行更换IP后，问题仍然存在，所以并不是IP被B站封禁导致的
于是我尝试将版本降级到2.8.1，录播机恢复了正常（我录播机监控了两个直播间，其中有一个直播间在录播机首次打开提示了一次上述WebSocket protocol,但是后续恢复正常）
再次尝试使用2.8.2版本后，问题复现，“The WebSocket protocol is not supported on this platform.”的提示在日志反复刷屏

综上所述：本人在老旧的WinServer2008SP1环境下使用录播机，在2.8.2版本中会触发“The WebSocket protocol is not supported on this platform.”，但能够通过降级到2.8.1版本解决

**Comment by Genteure** [comment]
目前录播姬桌面版只有在最新版本（现在是 2.8.2）使用 WS 或 WSS 能正常接收开播推送，最新版本的弹幕连接协议从以前的 **随机** 改成了 **WSS**。
Windows 7 以及对应的 Windows Server 系统不支持 websocket。

桌面版修改连接协议的方式是：鼠标右键点两次界面左下角的齿轮按钮打开高级设置。
需要注意：目前录播姬桌面版只有在最新版本（现在是 2.8.2）使用 WS 或 WSS 能正常接收开播推送。

命令行版因为用的是不同的 runtime （.NET 6 而不是 .NET Framework）目前还支持在 Windows 7 上使用 websocket。
但我打算等大概 11 月或 12 月 .NET 8 正式发布后升级，到时候也就不支持这些系统版本了。

**Comment by mcbaiyun** [comment]
非常感谢您的解答。根据您的解答，我成功进入了高级设置面板，并在 SERVER2008系统 下使用 2.8.2WPF版录播机 设置“TCP”协议成功连接弹幕服务器，图标也恢复了正常。非常感谢您的提示，我也了解到我使用的系统过于老旧，以至于越来越多的组件不支持，我会尽快考虑更新我的系统。再次感谢您的解答！
