### ISSUE TITLE
  希望增加“当直播间标题改变时分段”的选项

### ISSUE THREAD

**Issue by lzy0702** [Bililive/BililiveRecorder#518]
### Problem

希望增加“当直播间标题改变时分段”的选项
部分直播间，特别是机构的直播会连续播出多个不同栏目，目前的录制方式会将所有节目连续录制为一个整体，需要后期人工切分

### Proposal

希望增加当直播间标题改变时分段的功能

**Comment by Genteure** [comment]
Duplicate of #441
