### ISSUE TITLE
支持其它平台直播录制

### ISSUE THREAD

**Issue by shensizhebobo** [Bililive/BililiveRecorder#522]
### Problem

是否考虑支持抖音等平台的直播间录制？

### Proposal

用了很多录制软件，还是录播姬最稳定上手，所以能支持多平台就好了，感恩

**Comment by Genteure** [comment]
不会考虑，主要原因有：

- 项目从最初设计就只支持一个平台。要加其他平台支持的话，除了一部分界面和数据处理代码以外，其他地方都需要大改或重写，和重新写一个新项目没啥区别了。
- 我不用抖音也不用快手，没有这个需求。（甚至B站都不怎么看了（不会有人看B站吧（不会有人用录播姬吧）））
- 维护起来很费劲。维护一个比较熟悉的平台就挺费劲了，何况抖音之类那些一天改三次（夸张）故意不让你抓的。

**Comment by KnIfER** [comment]
这个录制的原理是什么呢，好像和和ffmpeg录制下来的不太一样。

我用ffmpeg录制，总会出现一些小问题。

若能代替ffmpeg，能够录制直链那就好了！（或配合外部的脚本解析？）

readme找到了，是 flv-streamer-2-file 这个项目吧，不知有无改进。
---

除了录制，似乎还可以做成订阅器 ——界面模仿qq，功能从录制变成通知。（监听到关注内容有更新时，发送通知给手机。）

**Comment by Genteure** [comment]
@KnIfER 

> 这个录制的原理是什么呢，好像和和ffmpeg录制下来的不太一样。

用录播姬“录制直播”和用ffmpeg“录制直播”都是下载数据、然后简单解析处理数据、保存到硬盘，没有解码编码。区别就是下载数据之后的解析处理这一步不太一样。

> readme找到了，是 flv-streamer-2-file 这个项目吧，不知有无改进。

不是。这个项目最初写的时候有参照它，但代码是完全自己写的。

> 若能代替ffmpeg，能够录制直链那就好了！（或配合外部的脚本解析？）

FLV 处理部分是一个相对比较独立的项目，虽然不能直接单独运行。有能力的话可以在遵守项目的开源协议的前提下，自己拿去改改。检测、界面之类的部分可复用性比较差。

最简单的做法是直接在用最简单的下载文件的方法下载了原始数据之后，用录播姬工具箱里的录播修复功能处理一遍，能达到差不多的效果。
有不少人是用其他工具录制抖音直播之后，遇到了问题用录播姬再处理的，据用户反馈效果还不错。

**Comment by KnIfER** [comment]
已完成转换。

Windows 可以直接用FLV模块，封装个exe，从 std in 而非 file 读取输入数据。
（但是，为什么有时会产生好几个flv文件，是网络不稳定，还是格式不连续？）

分享地址：https://github.com/appxmod/flv-stream-saver-csharp


Android 我依照 flv-streamer-2-file 写了个Java库，纯 Java，同样支持写入keyframes元数据。

分享地址：https://github.com/appxmod/flv-stream-saver-java
