### ISSUE TITLE
存在有的直播间无法录制的问题

### ISSUE THREAD

**Issue by saladxuanzhi** [Bililive/BililiveRecorder#523]
![ZD7@R9S E{}P@$6AD@EOGCA](https://github.com/BililiveRecorder/BililiveRecorder-WebUI/assets/28952405/26b94de2-cdd3-45c5-b308-53d27f7c7885)
版本：linux-x64
运行方式：systemctl
已重启服务，但仍无法解决。

**Comment by Genteure** [comment]
Duplicate of #283

“我的世界”分区最近被划到“特殊处理”的分区里面了，像 Overwatch Apex 雀魂 之类，B站为了防炸弹人狙击主播炸直播间，据说是开了全区统一的直播延迟。直播流也只提供 HLS 没有 FLV，现在录播姬只支持 FLV 所以录不了。

录播姬的 HLS 录制功能已经写了一部分了，不过完成还得有段时间。现在可以尝试一下 [blrec](https://github.com/acgnhiki/blrec)。

**Comment by newvoid7** [comment]
> Duplicate of #283
> 
> “我的世界”分区最近被划到“特殊处理”的分区里面了，像 Overwatch Apex 雀魂 之类，B站为了防炸弹人狙击主播炸直播间，据说是开了全区统一的直播延迟。直播流也只提供 HLS 没有 FLV，现在录播姬只支持 FLV 所以录不了。
> 
> 录播姬的 HLS 录制功能已经写了一部分了，不过完成还得有段时间。现在可以尝试一下 [blrec](https://github.com/acgnhiki/blrec)。

请问“怪物猎人”分区是否也是同样的情况？或者如何确认直播间未提供FLV流？我在录制时也存在同样的问题，但是间歇性，想确认是否因为无FLV流导致的。

**Comment by Genteure** [comment]
@newvoid7 https://hls.bilibili.stream/
源码在这里 https://github.com/BililiveRecorder/are-we-hls-yet

手动确认的话最简单的方法，查看网页源代码，搜 `.m3u8?` 确认存在，再搜 `.flv?` 看有没有。
