### ISSUE TITLE
M1 mac studio下无法运行

### ISSUE THREAD

**Issue by qchenac** [Bililive/BililiveRecorder#524]
### Platforms

CLI - macOS

### Version

2.9.0

### Description

2.8.2和2.9.0都会直接杀进程，都已经给了权限，加sudo也一样，以下是输入和输出：
`❯ /Users/***/Downloads/BililiveRecorder-CLI-osx-arm64-2.9.0/BililiveRecorder.Cli  --help

[1]    76785 killed     /Users/***/Downloads/BililiveRecorder-CLI-osx-arm64-2.9.0/BililiveRecorder.Cli`
现在只能用2.6.2版本，这个版本一切正常

**Comment by Genteure** [comment]
是不是这个问题？ https://rec.danmuji.org/user/faq/#macos-%E6%97%A0%E6%B3%95%E6%89%93%E5%BC%80bililiverecordercli%E5%9B%A0%E4%B8%BA%E6%97%A0%E6%B3%95%E9%AA%8C%E8%AF%81%E5%BC%80%E5%8F%91%E8%80%85

**Comment by qchenac** [comment]
确实，操作后就可以了，谢谢大佬。请问“移除 quarantine 属性”这一步是干嘛的，执行过程中全是permission denied和no such file，但是不影响之后的第二步

**Comment by Genteure** [comment]
我不知道，我没 Mac 设备，那条 FAQ 是其他人提交的。
