### ISSUE TITLE
希望可以添加舰长直播间录制的支持

### ISSUE THREAD

**Issue by BingoZha** [Bililive/BililiveRecorder#526]
### Problem

目前貌似无法录制只有舰长才能观看的直播间。

### Proposal

可以添加一个登录设定。

**Comment by Genteure** [comment]
现在支持在高级设置里填写 Cookie。录播姬发送的请求的特征和浏览器里网页发送的请求的特征区别肯定是很大的，如果真要认真区分的话是能分辨出来的。因此账号如果出现任何问题录播姬都不负责，也是为什么 Cookie 设置是放在高级设置里的原因。
录播姬桌面版打开高级设置的方法是：鼠标右键点击两次界面左下角的设置按钮。
https://rec.danmuji.org/user/settings/#%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE

**Comment by BingoZha** [comment]
> 现在支持在高级设置里填写 Cookie。录播姬发送的请求的特征和浏览器里网页发送的请求的特征区别肯定是很大的，如果真要认真区分的话是能分辨出来的。因此账号如果出现任何问题录播姬都不负责，也是为什么 Cookie 设置是放在高级设置里的原因。 录播姬桌面版打开高级设置的方法是：鼠标右键点击两次界面左下角的设置按钮。 https://rec.danmuji.org/user/settings/#%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE

请教一下，如果要录制上面说的直播间，要填入哪些cookie？cookie的格式是“key1=value;key2=value2”吗

**Comment by Genteure** [comment]
> 要填入哪些cookie？

不知道

> cookie的格式是“key1=value;key2=value2”吗

是。填进去的内容会原封不动放到 request header 的 cookie 一项里。

**Comment by BingoZha** [comment]
> > 要填入哪些cookie？
> 
> 不知道
> 
> > cookie的格式是“key1=value;key2=value2”吗
> 
> 是。填进去的内容会原封不动放到 request header 的 cookie 一项里。
好的，谢谢

**Comment by BingoZha** [comment]
> > 要填入哪些cookie？
> 
> 不知道
> 
> > cookie的格式是“key1=value;key2=value2”吗
> 
> 是。填进去的内容会原封不动放到 request header 的 cookie 一项里。

好的，谢谢

**Comment by BingoZha** [comment]
> 现在支持在高级设置里填写 Cookie。录播姬发送的请求的特征和浏览器里网页发送的请求的特征区别肯定是很大的，如果真要认真区分的话是能分辨出来的。因此账号如果出现任何问题录播姬都不负责，也是为什么 Cookie 设置是放在高级设置里的原因。 录播姬桌面版打开高级设置的方法是：鼠标右键点击两次界面左下角的设置按钮。 https://rec.danmuji.org/user/settings/#%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE

这个cookie可以设置部分房间使用吗，设置cookie后新添加的房间貌似录不了了了

**Comment by Genteure** [comment]
不能。多开录播姬。

**Comment by douhenhuidyf** [comment]
我也有同样的问题 现在你试过添加cookie录制舰长直播了吗 需要添加哪些cookie？

**Comment by BingoZha** [comment]
> 我也有同样的问题 现在你试过添加cookie录制舰长直播了吗 需要添加哪些cookie？

当时是可以录制的，F12 Networkl捕获里面随便试几个cookie就行，不过舰长直播只能录制开舰长的那个房间。
实在不好获取Cookie也可以试试这个工具：https://github.com/renmu123/biliLive-tools
