### ISSUE TITLE
时间戳修复异常 添加大量重复帧

### ISSUE THREAD

**Issue by Jared-02** [Bililive/BililiveRecorder#527]
### Platforms

WPF (桌面版)

### Version

2.9.1-alpha.1+2

### Description

版本 Hash：https://github.com/BililiveRecorder/BililiveRecorder/commit/2d6d68216503a249a03fea3b0fae11c9d249a561
时间戳修复异常，添加大量重复帧。具体表现为与弹幕不同步，最后一条弹幕发送时间比录像结束时间早出好几分钟。
尝试使用的替代方案：
- 录播姬【工具箱】-【录播修复】：检测无问题，重新输出时长不变；
- ffmpeg '-map 0 -c copy'：重新混流转封装容器，输出时长不变；
- VideoReDo TVSuite V6：重新混流同步音视频帧，输出文件时长减少，**与弹幕大致同步**；
- 使用其他录播工具备录 https://github.com/HMBSbige/BilibiliLiveRecordDownLoader ：因为连接到的 CDN 服务器不同，延迟原因导致开始录制的时间稍有初入（5秒以内）：备录视频文件时长正常，**与弹幕大致同步**。

此 issue 局限性：
- 测试的版本较少，只检查了在**录播姬 v2.6.2 版本**的录播文件没有此问题；
- 测试的直播间较少，可能需要更广泛的检查以定位问题

### Logs

```JSON
{"@t":"2023-10-01T16:00:01.1661403Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(TimestampJump,A): 时间戳变小, curr: 14574029, diff: -68"],"RoomId":27271452,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":29252,"ThreadId":10}
{"@t":"2023-10-01T16:00:04.0384049Z","@mt":"修复逻辑输出 {@Comments}","@l":"Debug","Comments":["(TimestampJump,A): 时间戳变小, curr: 14577029, diff: -76"],"RoomId":27271452,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","ProcessId":29252,"ThreadId":139}
```

**Comment by Jared-02** [comment]
[bilirec20231002_clip.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/12780648/bilirec20231002_clip.txt)
日志文件

**Comment by Genteure** [comment]
确实修复逻辑部分有问题，只在接收B站自建的CDN发送的数据时会出现。最近几天会看一下，预计会用简单粗暴的增加阈值的方法解决。

**Comment by Jared-02** [comment]
> 确实修复逻辑部分有问题，只在接收B站自建的CDN发送的数据时会出现。最近几天会看一下，预计会用简单粗暴的增加阈值的方法解决。

嗯，确实。这个日志里录制的直播流域名是 `cn-jlcc-cu-03-16.bilivideo.com`

**Comment by Jared-02** [comment]
但是貌似先前版本的录播姬没有这个问题呢，好像是哪次更新之后引入的 issue。

**Comment by Genteure** [comment]
没有哦，数据处理部分已经很长时间没有改过了。是B站服务器提供的数据里面的内容变了。
https://github.com/BililiveRecorder/BililiveRecorder/commits/dev/BililiveRecorder.Flv
或者
https://github.com/BililiveRecorder/BililiveRecorder/commits/dev/BililiveRecorder.Flv/Pipeline

**Comment by Jared-02** [comment]
> 没有哦，数据处理部分已经很长时间没有改过了。是B站服务器提供的数据里面的内容变了。 https://github.com/BililiveRecorder/BililiveRecorder/commits/dev/BililiveRecorder.Flv 或者 https://github.com/BililiveRecorder/BililiveRecorder/commits/dev/BililiveRecorder.Flv/Pipeline

那就是叔叔的锅！(*｀Ω´*)v

**Comment by Genteure** [comment]
fixed in d2440d1199ce132896bb006f2e1bd3c24cd2f3e4
