### ISSUE TITLE
舰长限定直播不能录

### ISSUE THREAD

**Issue by zyw787878** [Bililive/BililiveRecorder#531]
### Problem

有舰长的时候舰限直播也不能录

### Proposal

能不能添加账号系统 有舰长的时候可以录舰限直播

**Comment by Genteure** [comment]
账号系统不会做。
现在在高级设置里有填写 Cookie 的功能 https://rec.danmuji.org/user/settings/

**Comment by douhenhuidyf** [comment]
我也有同样的问题 现在你试过添加cookie录制舰长直播了吗 需要添加哪些cookie？
