### ISSUE TITLE
左上角悬挂“mikufans录播姬”小窗，无法关闭

### ISSUE THREAD

**Issue by ouuqqo** [Bililive/BililiveRecorder#532]
### Platforms

WPF (桌面版)

### Version

v2.10.0

### Description

左上角悬挂“mikufans录播姬”小窗，点击会穿透点击后面的内容，设置中无法关闭。
![image](https://github.com/BililiveRecorder/BililiveRecorder/assets/83007155/35a71651-c915-4a5a-9e26-2cead3cff0b0)

**Comment by Genteure** [comment]
这个是任务栏托盘图标的悬浮窗，正常情况是鼠标放在图标上的时候显示在托盘图标附近的，鼠标挪动到托盘图标上再挪走就会消失了。
