### ISSUE TITLE
弹幕列表无法显示用户ID和完整用户名

### ISSUE THREAD

**Issue by huoyan1231** [Bililive/BililiveRecorder#533]
### Platforms

WPF (桌面版)

### Version

2.9.1

### Description

标题
用户名仅显示第一个字符，后面的均为*
用户ID固定为0
理论上应该还有随机的弹幕丢失问题

**Comment by Genteure** [comment]
是已知问题，已经摆了。前阵子B站给直播弹幕加了风控，所有第三方直播弹幕相关的项目都不能用了。
主播工具现在唯一获取直播弹幕的渠道是用B站“直播开放平台”另外一个单独的接口，给的信息量比以前的也少。接入直播开放平台后要用主播开播页面的身份码连接，不是房间号，所以录播姬也用不了。
现在录播姬提供了[一个用户脚本接口](https://github.com/BililiveRecorder/recorder-scripting-template/blob/32d36b2860a36c960c2841646a5cb00c829cc7fe/recorder.d.ts#L31-L38)可以自定义与弹幕服务器握手时发的数据，我知道有其他人折腾到能获取到用户名不打码的弹幕了，但我也不确定具体是怎么搞的，我也不打算去研究这个，在线等一个 PR（

**Comment by huoyan1231** [comment]
好好好，意料之中的解决不了（
