### ISSUE TITLE
返回的直播流地址的画质是 150 而不是请求的 10000

### ISSUE THREAD

**Issue by chesha1** [Bililive/BililiveRecorder#534]
### Platforms

CLI - Linux

### Version

v2.6.1

### Description

输出的前后几条日志如下：
```
[17:31:55 INF (BililiveRecorder.Core.Recording.StandardRecordTask)] [23945626] 录制结束
[13:11:42 WRN (BililiveRecorder.Core.Recording.StandardRecordTask)] [34162] 返回的直播流地址的画质是 150 而不是请求的 10000
[13:11:42 INF (BililiveRecorder.Core.Recording.StandardRecordTask)] [34162] 连接直播服务器 d1--ov-gotcha05.bilivideo.com 录制画质 150 (高清)
[13:11:43 INF (BililiveRecorder.Core.Recording.StandardRecordTask)] [34162] 开始接收直播流
```
理论上来说，每个直播间都有原画画质啊，为什么这里会只接收到150的画质？

**Comment by Genteure** [comment]
今天B站新的改动，给直播流地址API加了登录验证，没有登录账号的请求不提供高画质的直播流。
如果你想登录账号的话可以在高级设置里添加 Cookie。

**Comment by chesha1** [comment]
> 今天B站新的改动，给直播流地址API加了登录验证，没有登录账号的请求不提供高画质的直播流。 如果你想登录账号的话可以在高级设置里添加 Cookie。

cookie是https://live.bilibili.com/房间号?session_id=xxxx的请求头里的cookie吗？
如果用cli版本，怎么添加cookie，看了下文档没写，能否把这部分使用方法更新上

**Comment by Genteure** [comment]
是。
在 webui 里设置页面加。
需要注意，如果要查的话，录播姬发的请求是很容易和普通请求区分出来的，因此账号可能会被B站标记成机器人号，出现任何问题别来找我就OK。

**Comment by Sefank** [comment]
@Genteure 未登录状态下，B站最高可以获取到超清画质，但是好像录播姬只能拿到高清画质流？

<img width="401" alt="_20231029002547" src="https://github.com/BililiveRecorder/BililiveRecorder/assets/12670778/a8237b6b-20f6-46da-a3df-117e5738dbaf">

**Comment by BugKun** [comment]
现在即使添加了cookie，画质依旧是150
```json
{"@t":"2023-11-12T07:52","@mt":"拉取房间信息成功: {@room}","@l":"Debug","room":{"Room":{"Uid":374377,"RoomId":45104,"ShortId":116,"LiveStatus":1,"AreaId":236,"ParentAreaId":6,"AreaName":"主机游戏","ParentAreaName":"单机游戏","Title":"岚色
纯爱直播间","$type":"InnerRoomInfo"},"User":{"BaseInfo":{"Name":"泪腺战士","$type":"UserBaseInfo"},"$type":"UserInfo"},"$type":"RoomInfo"},"RoomId":45104,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":2940424,"ThreadId":38,"ThreadName":".NE
T ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId":"","RequestPath":"/api/room/","ConnectionId":"0HMURMTHDK
9V8"}
{"@t":"2023-11-12T07:52","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000,400,250,150],"SelectedQn":10000,"RoomId":45104,"SourceContext":"BililiveRecorder.Core.R
ecording.StandardRecordTask","ProcessId":2940424,"ThreadId":38,"ThreadName":".NET ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId
":"","RequestPath":"/api/room/","ConnectionId":"0HMURMTHDK9V8"}
{"@t":"2023-11-12T07:52","@mt":"返回的直播流地址的画质是 {CurrentQn} 而不是请求的 {SelectedQn}","@l":"Warning","CurrentQn":150,"SelectedQn":10000,"RoomId":45104,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","Process
Id":2940424,"ThreadId":38,"ThreadName":".NET ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId":"","RequestPa
th":"/api/room/","ConnectionId":"0HMURMTHDK9V8"}
```

**Comment by chesha1** [comment]
> 现在即使添加了cookie，画质依旧是150
> 
> ```json
> {"@t":"2023-11-12T07:52","@mt":"拉取房间信息成功: {@room}","@l":"Debug","room":{"Room":{"Uid":374377,"RoomId":45104,"ShortId":116,"LiveStatus":1,"AreaId":236,"ParentAreaId":6,"AreaName":"主机游戏","ParentAreaName":"单机游戏","Title":"岚色
> 纯爱直播间","$type":"InnerRoomInfo"},"User":{"BaseInfo":{"Name":"泪腺战士","$type":"UserBaseInfo"},"$type":"UserInfo"},"$type":"RoomInfo"},"RoomId":45104,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":2940424,"ThreadId":38,"ThreadName":".NE
> T ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId":"","RequestPath":"/api/room/","ConnectionId":"0HMURMTHDK
> 9V8"}
> {"@t":"2023-11-12T07:52","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000,400,250,150],"SelectedQn":10000,"RoomId":45104,"SourceContext":"BililiveRecorder.Core.R
> ecording.StandardRecordTask","ProcessId":2940424,"ThreadId":38,"ThreadName":".NET ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId
> ":"","RequestPath":"/api/room/","ConnectionId":"0HMURMTHDK9V8"}
> {"@t":"2023-11-12T07:52","@mt":"返回的直播流地址的画质是 {CurrentQn} 而不是请求的 {SelectedQn}","@l":"Warning","CurrentQn":150,"SelectedQn":10000,"RoomId":45104,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","Process
> Id":2940424,"ThreadId":38,"ThreadName":".NET ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId":"","RequestPa
> th":"/api/room/","ConnectionId":"0HMURMTHDK9V8"}
> ```

你确定你添加了正确的cookie，而且cookie没有expire吗？我这里使用是正常的

**Comment by BugKun** [comment]
> > 现在即使添加了cookie，画质依旧是150
> > ```json
> > {"@t":"2023-11-12T07:52","@mt":"拉取房间信息成功: {@room}","@l":"Debug","room":{"Room":{"Uid":374377,"RoomId":45104,"ShortId":116,"LiveStatus":1,"AreaId":236,"ParentAreaId":6,"AreaName":"主机游戏","ParentAreaName":"单机游戏","Title":"岚色
> > 纯爱直播间","$type":"InnerRoomInfo"},"User":{"BaseInfo":{"Name":"泪腺战士","$type":"UserBaseInfo"},"$type":"UserInfo"},"$type":"RoomInfo"},"RoomId":45104,"SourceContext":"BililiveRecorder.Core.Room","ProcessId":2940424,"ThreadId":38,"ThreadName":".NE
> > T ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId":"","RequestPath":"/api/room/","ConnectionId":"0HMURMTHDK
> > 9V8"}
> > {"@t":"2023-11-12T07:52","@mt":"设置画质 {QnSettings}, 可用画质 {AcceptQn}, 最终选择 {SelectedQn}","@l":"Debug","QnSettings":[10000],"AcceptQn":[10000,400,250,150],"SelectedQn":10000,"RoomId":45104,"SourceContext":"BililiveRecorder.Core.R
> > ecording.StandardRecordTask","ProcessId":2940424,"ThreadId":38,"ThreadName":".NET ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId
> > ":"","RequestPath":"/api/room/","ConnectionId":"0HMURMTHDK9V8"}
> > {"@t":"2023-11-12T07:52","@mt":"返回的直播流地址的画质是 {CurrentQn} 而不是请求的 {SelectedQn}","@l":"Warning","CurrentQn":150,"SelectedQn":10000,"RoomId":45104,"SourceContext":"BililiveRecorder.Core.Recording.StandardRecordTask","Process
> > Id":2940424,"ThreadId":38,"ThreadName":".NET ThreadPool Worker","ActionId":"","ActionName":"BililiveRecorder.Web.Api.RoomController.CreateRoom (BililiveRecorder.Web)","RequestId":"","RequestPa
> > th":"/api/room/","ConnectionId":"0HMURMTHDK9V8"}
> > ```
> 
> 你确定你添加了正确的cookie，而且cookie没有expire吗？我这里使用是正常的

找到问题了，cookie有效期只有2天
