### ISSUE TITLE
WebUI的密码无法设置为特殊字符

### ISSUE THREAD

**Issue by chesha1** [Bililive/BililiveRecorder#535]
### Platforms

CLI - Linux

### Version

v2.10.0

### Description

用如下命令设置密码时，密码无法包含特殊字符，要么是设置成功，但是登录不了，要么是 brec 启动失败
```shell
./brec run --bind "http://*:2356" --http-basic-user "用户名" --http-basic-pass "密码" "工作目录"
```

比如：密码是 `SvT4^g$Gbocir8P0` 时无法登录
密码是 `gN1SFwi0i#%w!Hfj` 时，提示 `-bash: !Hfj: event not found`

**Comment by Genteure** [comment]
命令行参数需要转义，你看报错是 bash 在告诉你没有找到 `!Hfj` 这个 event

**Comment by Genteure** [comment]
https://stackoverflow.com/questions/26443880/bash-event-not-found

**Comment by chesha1** [comment]
> https://stackoverflow.com/questions/26443880/bash-event-not-found

了解了，谢谢大佬

顺便请教一下，目前需要cookie才能看原画的这个cookie，有效期是几天

**Comment by Genteure** [comment]
不知道

**Comment by chesha1** [comment]
> 不知道

我对前端不是很了解，所以想问下

cookie中有一个内容`bili_ticket_expires=1698506533;`，一般来说，这个是cookie失效时间的unix时间戳吗

**Comment by Genteure** [comment]
不知道，完全不知道，一丁点都不知道（
