### ISSUE TITLE
画质是480P

### ISSUE THREAD

**Issue by ZX828** [Bililive/BililiveRecorder#537]
### Platforms

WPF (桌面版)

### Version

2.10.0和2.9.0

### Description

无论是默认10000还是30000,20000,10000,401,400,250,150,80，都是480P
可能是B子改规则了，26号录的还是1080P

**Comment by Genteure** [comment]
是，25号开始的，不登录账号就只会返回最高 qn 150 也就是“高清”画质的直播流。

**Comment by ZX828** [comment]
我看录制的标题，26号有1个是1080P的。下个版本会加个扫码登录吗？
或者，直接copy个cookie保存成txt，用到的时候读取也可以达到登录的效果吧？

**Comment by Genteure** [comment]
看标题？为啥分辨率和标题有关。

任何登录相关的功能都不会做，可以参考一下录播姬的高级设置 https://rec.danmuji.org/user/settings

**Comment by ZX828** [comment]
哈，可能是我没说明白，打开是1080P，标题上有开始录制的日期。
现在想来，我可能看错了。可能是我把26号预告，看成26号录制了。

**Comment by smallwhitedesu1** [comment]
> 看标题？为啥分辨率和标题有关。
> 
> 任何登录相关的功能都不会做，可以参考一下录播姬的高级设置 https://rec.danmuji.org/user/settings

问一下 cookie是要怎么填的....？
![0231027184401](https://github.com/BililiveRecorder/BililiveRecorder/assets/103363926/ce98e124-885b-4461-8f60-191b0b4e2e0a)

**Comment by Genteure** [comment]
设置框里的文本内容会原封不动加到 request header 的 cookie 一项里

**Comment by AppreciateL** [comment]
> 是，25号开始的，不登录账号就只会返回最高 qn 150 也就是“高清”画质的直播流。

今天遇到一个问题，当主播网络波动导致直播结束以后短时间内重新推流，录播姬再次录制的就是 qn 150 的高清画质了，重试了几次都还是高清画质。
那目前就必须填写 cookie 才能够保证，当出现上面这种情况以后也可以保证录制的还是 qn 10000 的原画画质吗？
