### ISSUE TITLE
开启了 “直播间更改标题自动分段” 但没有分段

### ISSUE THREAD

**Issue by ZX828** [Bililive/BililiveRecorder#539]
### Platforms

WPF (桌面版)

### Version

2.10.0和2.9.0

### Description

![image](https://github.com/BililiveRecorder/BililiveRecorder/assets/144084680/59c49b07-fd3d-49f9-ac7b-a724b63dcda7)
![QQ截图20231029132700](https://github.com/BililiveRecorder/BililiveRecorder/assets/144084680/f3c63fd7-8b0d-47fa-9c8e-a60703f56cf4)

**Comment by Genteure** [comment]
录播姬有检测到房间信息变动吗？看看日志文件。

**Comment by ZX828** [comment]
[bilirec20231029.txt](https://github.com/BililiveRecorder/BililiveRecorder/files/13225950/bilirec20231029.txt)

**Comment by ZX828** [comment]
是这个吗？

**Comment by Genteure** [comment]
你的账号 Cookie 泄露了，comment 帮你删掉了，建议修改密码让旧的登录 session 失效。

从日志来看好像确实是没有触发分段，回头我测试一下。

**Comment by ZX828** [comment]
哦，好的。是我发的log文件里吗。
还有我刚才发现，按时间分段也没有触发。版本是2.10.0

**Comment by Genteure** [comment]
哦。。。你用的录制模式是原始数据吗？原始数据模式分段功能无效，因为是直接把服务器发的数据原封不动写硬盘，没有任何分析处理，也就无法分段。

Edit: 翻了一下你发的日志文件，确实是原始数据模式。

**Comment by ZX828** [comment]
哦，确实是原始数据。标准模式是把原始数据重新编码了吗？
我觉得原始数据直接保留，需要转码什么的我需要的时候再转就行，所以就选的这个。而且我有时候会边录边看。

**Comment by Genteure** [comment]
标准模式和原始数据模式的区别网站上有写 https://rec.danmuji.org/user/record-mode/
两个模式都不会对音视频内容二次编码。
