### ISSUE TITLE
针对bililive近期更新的“加密直播间"功能进行适配

### ISSUE THREAD

**Issue by yowanep** [Bililive/BililiveRecorder#54]
问题复现直播间地址
https://live.bilibili.com/21449068
追加直播间
提示
WARN 21449068 不能获取 21449068 的信息: "该房间已经被锁定" 

原因为正式直播之前直播主进行了调试，调用了最近添加的加密直播间的功能，使游客访问为该直播间已锁定，登录之后则反馈为需要输入密码进入，但问题在于就算该直播间取消加密之后进行追加也反馈着同样的内容（此时游客进行访问并不会出现该直播间已锁定的反馈）

**Comment by Genteure** [comment]
加密直播间这个功能有了很长时间了，估计至少有一年以上了吧，不是近期新出的功能。
录播姬用的是 哔哩哔哩 Android 客户端 的直播API，那个API和网页返回的直播间状态不同的原因我也不清楚。
使用 Android API 的原因是当初网页API需要请求两次才能获取到需要的信息，并且返回的信息不足。现在可以考虑换到 `https://api.live.bilibili.com/room/v1/Room/get_info?id=1`

**Comment by Genteure** [comment]
嗷。。我想起来为什么没有用这个 API 了，没有主播昵称。
要再用 UID 请求一次其他的 API 获取昵称

**Comment by Genteure** [comment]
Android API 要下一次开播才会更新加密状态

**Comment by VurtneYang** [comment]
获取房间信息接口,建议从 /AppRoom/index 更换成https://api.live.bilibili.com/room/v1/Room/get_info?id=1

**Comment by Genteure** [comment]
已在 1.1.12 修改
#61
