### ISSUE TITLE
获取直播间信息和获取直播流分开处理是否携带cookie

### ISSUE THREAD

**Issue by koro33e** [Bililive/BililiveRecorder#542]
### Problem

当前需要添加cookie才可以获取到高画质的直播流，然而在设置里添加了cookie无论是轮询开播还是获取直播流都会带这个cookie。

### Proposal

轮询是否开播可以不需要cookie的，当检测到开播再携带cookie去请求直播流。把这两者分开应该可以减少被ban/标记为机器人的概率。同理连接弹幕服务器也可以加上是否携带cookie的设置。

**Comment by Genteure** [comment]
感觉有点过于复杂了，而且不一定真有多少实际效果。
最简单的一个检测指标就是 `user-agent`，用户登录时使用的、平常请求里的和这个另外的请求的 UA 是否一致。录播姬的 UA 是直接写死的。
如果真的要实现这个功能，除了改录播姬源码以外也可以通过在录播姬前面放一个反代、设置录播姬的 API Host、在反代上加/删 cookie 来实现。

**Comment by koro33e** [comment]
确实，但反代的方案貌似也不简单。
目前来说我是开小号的cookie来用，还没有被gank，但未来的情况也不好说。
现在匿名api权限逐渐收紧，合理的猜测就是为了anti-robot。实现一些类似自定义UA，cookie之类的伪装功能还是很有必要的。

**Comment by Genteure** [comment]
所有“高级设置”的定位都是“替代自行修改源码编译的非正式功能”，我不是很想“正式支持”。
如果B站要想办法屏蔽这些请求、不允许录播，那技术上总是有方法的，我也不是很有玩猫捉老鼠游戏的意愿。

我是觉得给录播姬提供一个 API 反代是实现起来最简单也是最灵活的，如果有人给录播姬发一个 PR 并且代码逻辑不是*特别*混乱、没有对后续维护修改造成太大负面影响的话也可以合并。我个人不想写这类的功能。
