### ISSUE TITLE
不登录只能录制最低画质，请问如何登录？

### ISSUE THREAD

**Issue by f59375543** [Bililive/BililiveRecorder#543]
### Problem

不登录只能录制最低画质

### Proposal

请问如何登录？

**Comment by Genteure** [comment]
高级设置里可以填 Cookie https://rec.danmuji.org/user/settings/

**Comment by f59375543** [comment]
> 高级设置里可以填 Cookie https://rec.danmuji.org/user/settings/

好的，谢谢
