### ISSUE TITLE
请问现在只能录到480p的画质了吗，有什么解决方法吗

### ISSUE THREAD

**Issue by Ward-zzZ** [Bililive/BililiveRecorder#551]
### Platforms

WPF (桌面版)

### Version

2.10.1

### Description

画质选原画，但是录制文件是480p

**Comment by Genteure** [comment]
在录播姬高级设置里填登录过的 cookie，高级设置是鼠标右键点两次界面左下角的齿轮按钮打开。建议用小号，账号发生任何事情均不负责。

**Comment by sysdefault** [comment]
> 在录播姬高级设置里填登录过的 cookie，高级设置是鼠标右键点两次界面左下角的齿轮按钮打开。建议用小号，账号发生任何事情均不负责。

设置过后，当时能10000，过段时间下回再打开录就还是480了

**Comment by Genteure** [comment]
> 过段时间

正常。在浏览器里访问网站，服务器会时不时设置新的 cookie 值，旧的就失效了。

**Comment by MerlinCN** [comment]
能不能加个自动刷新Cookie

**Comment by Genteure** [comment]
不能，不做登录相关功能。
有需求的话你可以在录播姬外部实现账号登录和 cookie 刷新，然后需要更新的时候通过命令行版的 API 设置到录播姬里用。
