### ISSUE TITLE
希望能开机自启后自动隐藏到托盘，不显示主界面

### ISSUE THREAD

**Issue by YunZhiYaoYao** [Bililive/BililiveRecorder#555]
### Problem

Windows 上复制快捷方式到启动文件夹这种方式会直接显示主界面，不能直接隐藏到托盘

### Proposal

希望能开机自启后自动隐藏到托盘，不显示主界面

**Comment by Genteure** [comment]
用 `/path/to/BililiveRecorder.WPF.exe run --hide` 可以自动隐藏界面

**Comment by YunZhiYaoYao** [comment]
cmd中直接输入吗？

**Comment by Genteure** [comment]
在快捷方式的目标的最后面加参数

**Comment by YunZhiYaoYao** [comment]
好的，成功了，谢谢
