### ISSUE TITLE
主播切换分区后检测不到正在直播，无法录制

### ISSUE THREAD

**Issue by XiaoeEe** [Bililive/BililiveRecorder#557]
### Platforms

Docker

### Version

v2.10.1

### Description

主播切换分区后一直处于监控中状态 无法开启自动/手动录制

**Comment by Genteure** [comment]
B站对部分分区有特殊处理，有强制打码强制直播延迟之类的，只给 HLS 流没有 FLV 流。录播姬现在只支持 FLV 所以录不了。HLS 在写。
