### ISSUE TITLE
选择/屏蔽某条流服务器

### ISSUE THREAD

**Issue by koro33e** [Bililive/BililiveRecorder#558]
### Problem

之前的 issue 有人提过类似的

我这里总有某条线路录出来几秒一卡(比如 d1--ov-gotcha07.bilivideo.com)，最近这种情况分外严重，每次我都要手动点结束开始结束开始，直到随机到那条能录正常的流

### Proposal

能够**选择/屏蔽**某条流，现在代码里流的选择是随机的

可以简单的在 advanced 设置里设一个流**白名单/黑名单**，然后在这里

https://github.com/BililiveRecorder/BililiveRecorder/blob/fe9bd29c7d50b44525099931ac2453c53c1e300b/BililiveRecorder.Core/Recording/RecordTaskBase.cs#L251-L259

**优先使用/屏蔽掉**匹配的流就可以了

**Comment by shugen002** [comment]
你可以走自定义脚本那里自行实现。。。

**Comment by koro33e** [comment]
之前没看到，我去试试
