### ISSUE TITLE
有一个直播间无法录制

### ISSUE THREAD

**Issue by Karmylr** [Bililive/BililiveRecorder#559]
### Platforms

WPF (桌面版)

### Version

v2.10.1

### Description

![image](https://github.com/BililiveRecorder/BililiveRecorder/assets/69903376/93b6e84a-1a52-4ab5-849a-a82747b3d307)

**Comment by Karmylr** [comment]
直播间的HAR文件：https://drive.google.com/file/d/1xh8-PTe72H0hmMKjV7EgfDahc1fjJAA1/view?usp=sharing

**Comment by Genteure** [comment]
部分分区有特殊处理，为了防炸弹人有强制直播延迟、打码之类，只提供 HLS 流没有 FLV。录播姬现在只支持 FLV 不支持 HLS 所以就录不了。

现在录播姬的 HLS 已经写到能输出文件了，不过距离能发测试版还有段时间。

参考 #501 #283
