### ISSUE TITLE
录制虚拟游戏区的时候部分主播无法录制。

### ISSUE THREAD

**Issue by Rinkomochi** [Bililive/BililiveRecorder#560]
### Platforms

Docker

### Version

2.10.1

### Description

提示:System.Exception: no supported stream url, qn: 10000
部分主播又可以可以正常录。是否是B站对主播进行了分类，导致部分主播显示原画其实不是原画？
目前测试鲸鱼娘西丝特official 房间ID:26545331的直播间在虚拟Gamer分区是正常可以录的。但是我测试了一些别的虚拟Gamer分区的主播一直提示没有这个画质选项？

**Comment by Genteure** [comment]
部分分区有特殊处理，为了防炸弹人有强制直播延迟、打码之类，只提供 HLS 流没有 FLV。录播姬现在只支持 FLV 不支持 HLS 所以就录不了。

现在录播姬的 HLS 已经写到能输出文件了，不过距离能发测试版还有段时间。可以试试 https://github.com/acgnhiki/blrec

参考 https://github.com/BililiveRecorder/BililiveRecorder/issues/501 https://github.com/BililiveRecorder/BililiveRecorder/issues/283
