### ISSUE TITLE
cookie过期很快，1-2或2-3天就会过期，且无规律，希望有自动定时测试与提醒功能

### ISSUE THREAD

**Issue by Utopia1916** [Bililive/BililiveRecorder#561]
### Problem

如题，我不清楚这是B站的问题，还是我的网络波动导致的？例如断网？更换节点？(我有使用VPN，绝大多数时候都是开启的)，如果短期内不会添加自动检测cookie功能，请问有什么方法诀窍来规避或是尽可能延长B站cookie的寿命？这应该不能通过用命令来实现？如果能请务必告知我，谢谢

### Proposal

希望添加定时test cookie是否过期的设置

**Comment by Genteure** [comment]
## 为什么 Cookie 会“过期”

Cookie 是一个可**读写**的数据存储，网站可以往里面写入任意数据，各个网站自主决定 Cookie 里存什么数据、怎么读取和解析收到的 Cookie 内容。这里的重点是，**各个网站自主决定它们怎么使用 Cookie**，它就是一个简单的 KV 存储。

网站为了实现登录等功能，可能会在 Cookie 里写一个 session id 之类的值。一个很常见的做法是定时更换 session cookie 的值。一个 session cookie 是否有效**完全是服务器说了算**。

## 录播姬的 Cookie 设置

浏览器里的 Cookie 功能是按域名、路径、名字存储的多条记录，发送请求时会根据域名和路径等条件把 cookie 组成一个字符串加到请求头里，会根据 response header 里的 `Set-Cookie` 修改。

而录播姬里的 Cookie 设置只是一个简单的文本字符串。录播姬会把 Cookie 设置项中的文本原封不动加到部分请求的请求头里 `Cookie` 一项里，仅此而已。

录播姬不是浏览器，没有完整复刻浏览器里 Cookie 和相关 HTTP Header 的行为，录播姬也不会像浏览器访问网站一样请求页面 HTML 和所有相关的接口。服务器认为它设置了新 Cookie 但录播姬没有更新，是符合预期的。

## 为什么不自动刷新 Cookie

有技术原因也有非技术原因。长话短说就是模拟浏览器里访问网站，接收、更新、维护 Cookie 内容过于麻烦，不想在录播姬里实现也不想维护相关代码。

如果有需求，可以自己写代码在录播姬外部维护一个可用的 Cookie 然后使用录播姬命令行版的 HTTP API 设置到录播姬里。

## 为什么不加一个登录功能

同上。

## 能不能自动测试

建议在录播姬外写脚本实现。可以用 HTTP API 读当前录播姬里设置的 Cookie，或者在外部维护 Cookie 内容再通过 HTTP API 传给录播姬，两个方向都可以。

## 总结

- Cookie 怎么用、内容是否有效完全由对应的网站决定。
- 录播姬只提供了一个设置 HTTP 请求头 `Cookie` 一项的值的方法。
- 其他状态维护功能建议在外部实现，用 HTTP API 与录播姬交互。

**Comment by komori-flag** [comment]
Cookie 的过期与否不是录播姬能决定的，决定权在啊b手上；
如果想能够实现 Cookie 更新 / 过期提醒，可通过撰写脚本程序等方式；
涉及啊b账号相关的功能并不想加入到此项目当中，原因的话想想 BiliPlus 便可知。

既然选择了将自己的账号登录态 Cookie 添加进录播姬当中，那么之后所发生的任何情况请自行承担。

`
如您知晓您的账号会因以上所列出的部分原因导致账号无法正常使用或权益受损等情况，并愿意承担由此所带来的一系列后果，请继续以下的操作，录播姬的开发者不会对您的账号所发生的任何后果承担责任。
`

**Comment by wintertee** [comment]
似乎使用浏览器中复制得到的cookie似乎有效期很短(nilaoda/BBDown#507)。[BBDown](https://github.com/nilaoda/BBDown)的方式是手机客户端扫描二维码获得一个新的cookie。我现在填写的cookie是BBdown二维码扫描登录，从BBDown.data文件中拷贝过来的，用了一周左右还没有失效。

**Comment by komori-flag** [comment]
> 似乎使用浏览器中复制得到的cookie似乎有效期很短（[nilaoda/BBDown#507](https://github.com/nilaoda/BBDown/issues/507)）。[BBDown](https://github.com/nilaoda/BBDown)的方式是手机客户端扫描二维码获得一个新的cookie。我现在填写的cookie是BBdown二维码扫描登录，从BBDown.data文件中拷贝过来的，用了一周左右还没有失效。

[Web端Cookie刷新](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/cookie_refresh.md)
其实，在一般情况下（非登录过期、账号风控等强制下线等），cookie 是不会自动更新的，网页版有效期短是因为访问啊b网页的时候就会触发检测是否需要更新 cookie，一更新就会导致老 cookie 失效。

**Comment by Utopia1916** [comment]
> > 似乎使用浏览器中复制得到的cookie似乎最近很短（[nilaoda/BBDown#507](https://github.com/nilaoda/BBDown/issues/507)）。BBDown[的](https://github.com/nilaoda/BBDown)方式是手机客户端扫描二维码获得一个新的cookie。我现在填写的cookie是BBdown二维码扫描登录，从BBDown.data文件中复制过来的，用了一周左右还没有失效。
> 
> [Web端Cookie刷新](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/login/cookie_refresh.md) 其实，一般情况下（非登录过渡、账号风控等强制下线等），cookie是不会自动更新的，网页版本大大短是因为访问啊b网页的时候就会触发检测是否需要更新 cookie，一更新就会导致旧 cookie 失效。

没，我都是开的小号，拿到cookie后就不会再登录了，这两天换了BBDown的cookie好像就没那么快过期了
