### ISSUE TITLE
docker环境变量指定UID与GID无效

### ISSUE THREAD

**Issue by BeyondandSharp** [Bililive/BililiveRecorder#563]
### Platforms

Docker

### Version

2.10.1

### Description

威联通docker，生成的文件都是admin权限的，环境变量中尝试了PUID,PGID,UID,GID均无效。在其他容器中，例如qbittorrent中使用相同的环境变量，生成的文件是指定用户的，日志中也明确表示应用了指定的UID与GID，这样的话我姑且认为威联通的docker是正常的。
不确定是哪个旧版本时，我一直使用PUID与PGID来指定用户，都挺好的，近期突然就如此。

**Comment by Genteure** [comment]
通过环境变量制定 UID GID 是在容器镜像里实现的功能，不是 docker 提供的通用功能，录播姬的镜像从来都没有读取环境变量切换用户的功能。

你可以使用 docker 提供的 [`--user`](https://docs.docker.com/engine/reference/run/#user) 参数设置容器启动时使用的 UID 和 GID。

你说的通过环境变量设置，是 docker 首先用默认的 `uid=0,gid=0` 也就是 `root:root` 启动容器，容器内的脚本再自行读取环境变量切换用户。如果你用的是 linuxserver.io 提供的 qbittorrent 镜像的话，它设置 UID/GID 的脚本源码在这里: https://github.com/linuxserver/docker-baseimage-alpine/blob/1bfc5cb7a7f5414b0f0672ae2c3d0e601314091d/root/etc/s6-overlay/s6-rc.d/init-adduser/run

**Comment by BeyondandSharp** [comment]
谢谢解答，非常全面！网上查的都是在环境变量里面指定，你这么一说我突然想起来之前是使用 docker compose 创建的录播姬。感谢！
