### ISSUE TITLE
webui版本和录播姬本体版本不同步

### ISSUE THREAD

**Issue by chesha1** [Bililive/BililiveRecorder#565]
### Platforms

CLI - Linux

### Version

v2.10.1

### Description

已经将录播姬版本更新到最新，从远程访问webui时，右上角仍然弹出提示”检测到新版本WebUI：v2.10.1，请及时更新！“

**Comment by Genteure** [comment]
现在是这样，webui的版本号是独立的所以有点乱。之后可以考虑内置的 webui 不单独检查版本。

**Comment by shugen002** [comment]
其实是我改漏一个文件`package.json`了，顺带，确实不同步的。。。 @Genteure 你下次发版的时候帮我那边+0.0.1（也就是`2.10.2`），`package.json`我已经提前改了
