### ISSUE TITLE
录制结束后产生的临时文件未能转成视频文件存储

### ISSUE THREAD

**Issue by ShineSunsun** [Bililive/BililiveRecorder#567]
### Platforms

CLI - Windows

### Version

2.10.1

### Description

手动结束录制后产生的临时文件未转换为视频文件，原录播存储目录中生成错误日志
![IMG_20240119_213351](https://github.com/BililiveRecorder/BililiveRecorder/assets/135199852/aaf0606c-7e65-49b2-be1b-f20b53a4fa23)
![IMG_20240119_213333](https://github.com/BililiveRecorder/BililiveRecorder/assets/135199852/30b317a6-11f8-4c5e-979c-c977f210c046)
![IMG_20240119_213311](https://github.com/BililiveRecorder/BililiveRecorder/assets/135199852/24f67fd6-baee-4e7d-8bf9-a4482c5812c9)

**Comment by Genteure** [comment]
这个 `C:\linshi` 看起来和录播姬没有关系，日志截图里写的录播姬输出的文件路径不在这里，录播姬也不会输出以 UUID/GUID 作为文件名的文件。

**Comment by ShineSunsun** [comment]
> 这个 `C:\linshi` 看起来和录播姬没有关系，日志截图里写的录播姬输出的文件路径不在这里，录播姬也不会输出以 UUID/GUID 作为文件名的文件。

这个linshi文件夹是录播姬用来存放正在录制直播内容时生成的临时文件（反转了这玩意是我上传云盘预留的临时文件夹，确实跟录播姬没关系，打扰您了对不起🙏）
这个应该不算bug,因为在我回复这条消息的时候这个临时文件似乎已经自动转换成了视频文件放在了它应该在的位置，推测应该是硬盘存储速度导致在我看到的时候文件还未上传完成（）这个issue可以关了
