### ISSUE TITLE
只能录制一个网站太浪费了，建议增加更多直播网站兼容

### ISSUE THREAD

**Issue by shofotolavski** [Bililive/BililiveRecorder#570]
### Problem

这么好用的软件只能录制一个网站太浪费了

### Proposal

建议增加对chaturbate的支持

**Comment by citiao233** [comment]
建议增加对mikufans生放送的支持

**Comment by komori-flag** [comment]
#522 #286 #482 #205
请在提 Issue 前自行查询是否已有相关的 Issue，尽量不提重复的 Issue。

此处引用 [Genteure](https://github.com/Genteure) 在 [#522](https://github.com/BililiveRecorder/BililiveRecorder/issues/522#issuecomment-1713329030) 中的回答
> 不会考虑，主要原因有：
> 
> * 项目从最初设计就只支持一个平台。 要加其他平台支持的话，除了一部分界面和数据处理代码以外，其他地方都需要大改或重写，和重新写一个新项目没啥区别了。
> * 我不用抖音也不用快手，没有这个需求。 （甚至B站都不怎么看了（不会有人看B站吧（不会有人用录播姬吧）））
> * 维护起来很费劲。 维护一个比较熟悉的平台就挺费劲了，何况抖音之类那些一天改三次（夸张）故意不让你抓的。
