### ISSUE TITLE
无法显示用户名，每个用户ID都为0

### ISSUE THREAD

**Issue by abcdefghHIM** [Bililive/BililiveRecorder#575]
### Platforms

WPF (桌面版)

### Version

v2.10.1

### Description

尝试对两个2个直播间进行录制，发现无法显示用户名
![QQ截图20240214222106](https://github.com/BililiveRecorder/BililiveRecorder/assets/55306203/4147f9be-7cf1-429d-aeae-80b86df581f5)

**Comment by suica-me** [comment]
在高级设置中填入cookie可解决这个问题
[https://rec.danmuji.org/reference/settings/#s-Cookie](https://rec.danmuji.org/reference/settings/#s-Cookie)

以下是webui中的警告内容：
> Cookie 会用于包括获取直播间信息、获取直播流地址、连接弹幕服务器在内的所有 API 请求中。录播姬的请求与浏览器内正常使用所发送的请求不完全一致，能通过分析请求日志识别出来。
> 软件开发者不对账号发生的任何事情负责，包括并不限于被标记为机器人账号、大会员被冻结、无法参与各种抽奖和活动等。建议使用小号。
> 如您知晓您的账号会因以上所列出来的部分原因所导致无法使用或权益受损等情况，并愿意承担由此所会带来的一系列后果，请继续以下的操作，软件开发者不会对您账号所发生的任何后果承担责任。

**Comment by Genteure** [comment]
确实，这个没啥好办法。服务器给的数据就这样，不是录播姬主动丢弃的用户信息。
