### ISSUE TITLE
请求新增批量录播修复功能

### ISSUE THREAD

**Issue by zhongjitianqianguai** [Bililive/BililiveRecorder#582]
### Problem

每次一个个进行修复  在录播文件较多时比较麻烦耗时

### Proposal

新增批量录播修复功能 在原有基础上支持修复选择文件夹下所有子文件夹下的录播文件

**Comment by shugen002** [comment]
考虑下命令行？https://rec.danmuji.org/user/toolbox/analyze-repair/

**Comment by zhongjitianqianguai** [comment]
> 考虑下命令行？https://rec.danmuji.org/user/toolbox/analyze-repair/

哦对  把命令行忘记了
