### ISSUE TITLE
api 实现对于设置的修改

### ISSUE THREAD

**Issue by chesha1** [Bililive/BililiveRecorder#584]
### Platforms

CLI - Linux

### Version

v2.10.1

### Description

能否通过 api 修改 cookie？每过几天就手动调一下太烦了，看了下文档，关于 api 的部分很不详细，完全没说怎么修改设置

而且能否加上鉴权部分？比如简单点直接在请求头里加个 token 校验，不然在公网 post 一下，谁都能改录播姬的行为也太不安全了

**Comment by shugen002** [comment]
emmm，鉴权这块依靠的是basic auth，现在最新版本中，要求在启动参数中设置了用户名及密码才允许疑似来自公网的请求，除非非要作死加了那个参数。
然后通过api修改cookie的话也是可以的
具体可以看对应版本的swagger里的 `/api/config/global` 设置全局设置
可以只带`optionalCookie`这个属性。

**Comment by Airo0** [comment]
希望添加关于手动修改config.json的描述, 明明手动改一下配置文件就能很轻松的添加cookie, 但是就是不说明config.json的具体字段格式, 只能用那个抽象的api修改配置, 真的很难绷

**Comment by Airo0** [comment]
如何在非WFP版本中设置cookie(说人话版):

1. 关闭录播机
2. 在配置目录中的`config.json`文件的`global`结构中添加`Cookie`对象.
  `Cookie`对象包含两个值:  
  第一个是名为`HasValue`的布尔值, 内容为`true`
  第二个是名为`Value`的字符串值, 内容为从浏览器中提取的B站Cookie  
3. 保存配置文件, 重新启动录播机
