### ISSUE TITLE
添加定时测试“录制画质”是否能达到默认设置的功能

### ISSUE THREAD

**Issue by TANGhz17** [Bililive/BililiveRecorder#585]
### Problem

B站对直播流加了认证限制，我虽然已经加上了Cookie，现在录制是10000原画。

### Proposal

想着能不能加个定时测试可录画质的功能，不是默认设置就输出Error或者触发Webhook。

**Comment by TANGhz17** [comment]
因为cookie可能会失效，所以希望失效的时候可以有触发，毕竟录播姬一直挂在服务器里

**Comment by Genteure** [comment]
不是很想在录播姬里加 cookie 状态维持相关的逻辑。既然已经是挂在服务器上配合webhook用了，可以写个脚本用录播姬的 cookie 请求一下接口测试。
因为涉及到登录状态就很头疼、各种乱七八糟情况，写起来维护起来都麻烦。写完过几天哪里有变动功能失效了又得持续跟着改。
录播姬就只提供一个文本字符串设置项、原封不动加到 header 里最简单的。

**Comment by TANGhz17** [comment]
好吧，我有空搓一个脚本挂上去
