### ISSUE TITLE
不能自动登录

### ISSUE THREAD

**Issue by ZX828** [Bililive/BililiveRecorder#586]
### Problem

每过一段时间就发现，录制的清晰度变低了。
需要手动设置一次cookie。

### Proposal

浏览器就不需要过一段时间登录一次，这个能自动更新cookie吗？

**Comment by shugen002** [comment]
https://github.com/BililiveRecorder/BililiveRecorder/issues/585#issuecomment-2067539185

**Comment by ZX828** [comment]
哦这样啊……这段话我看了好几遍，虽然还没弄明白webhook是啥，大概知道这段话什么意思了。
我实在windows上用的，也能写个脚本实现“cookie 状态维持相关的逻辑”吗？
怎么做？能不能给点提示？给个方向啥的？

**Comment by ZX828** [comment]
找到文件目录，认识后缀名的文件打开看了一眼，“文本字符串设置项”在哪？不知道从哪下手……

**Comment by ZX828** [comment]
在工作目录里找到了cookie的value，但我还是不知道，怎么自动更新cookie……
我的是windows的，也能写个脚本自动更新cookie吗？
给点提示呗？

**Comment by Genteure** [comment]
桌面版不行，没有提供 API。
录播姬不打算加自动维持状态之类的功能，写起来很麻烦、功能容易失效、维护起来太费心思。
那个 issue 里面说的自动更新是可以自己写脚本想办法在外部检查和保持更新登录状态，然后通过录播姬命令行版提供的 HTTP API 设置到录播姬里用。录播姬命令行版有 Swagger (OpenAPI) 里面列出了相关的接口和文档。
