### ISSUE TITLE
Windows不兼容?字符导致文件名乱码的问题

### ISSUE THREAD

**Issue by pop-929** [Bililive/BililiveRecorder#589]
### Platforms

CLI - Linux

### Version

v2.10.2

### Description

设置文件写入的文件名中包含title时，如果主播的title中带有"?"字符，在Windows文件名将出现乱码。但是在Linux中是正常的。
![Snipaste_2024-05-05_00-32-51](https://github.com/BililiveRecorder/BililiveRecorder/assets/46913968/75cce63a-7118-4aa7-bb4b-32af9bc7167c)
![Snipaste_2024-05-05_00-33-40](https://github.com/BililiveRecorder/BililiveRecorder/assets/46913968/2225c3b5-b29d-4126-8f74-05556bf45b99)
能否在创建文件时，检测一下是否路径中是否包含"?"字符，然后将其替换为中文的“？”或其他字符
还有Windows上文件名不能包含":*<>|"，这些字符实测在Linux上能正常显示但是Windows中会乱码。

**Comment by Genteure** [comment]
这是 Windows 或者 NAS SMB share 的功能（我不知道是哪个的），符合预期。现在的文件名替换是用当前运行的操作系统提供的不能使用的字符做替换的，在 Windows 上运行的时候会过滤掉 Windows 文件系统不能用的字符。如果需要在 Linux 上也过滤 Windows 不能使用的字符，可以在文件名模板里加几个 `replace`。

语法文档：https://shopify.github.io/liquid/filters/replace/

例：

```liquid
{{ roomId }}-{{ name }}/录制-{{ roomId }}-{{ "now" | time_zone: "Asia/Shanghai" | format_date: "yyyyMMdd-HHmmss-fff" }}-{{ title | replace: "?", "" | replace: ":", "" }}.flv
```

**Comment by whc2001** [comment]
是 SMB 的问题，在 Linux 机器上使用 CLI 录制到 NFS 挂载的 NAS 目录，在 Windows 机器上使用 SMB 挂载查看文件有复现，但在 NAS 本身查看文件名正常

![image](https://github.com/user-attachments/assets/9ae356b9-0486-4af6-a414-11b337784cb9)
