### ISSUE TITLE
获取直播间信息出错

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [Bililive/BililiveRecorder#59]
更新版本之后一直出现获取直播间信息出错的提示
![BUG](https://user-images.githubusercontent.com/44915585/63134704-35b20100-bffd-11e9-8b13-2fd85479a86a.PNG)

**Comment by Genteure** [comment]
和更新无关。
是B站服务器的问题，有可能是新设置了请求频率限制之类的限制，再观察一下吧

**Comment by SaltyFishOnTheSea** [comment]
两天多次重启还是老样子，这个配置文件在1.1.10版本的时候还是正常运作的
![BUG-2](https://user-images.githubusercontent.com/44915585/63366469-6488f800-c3ac-11e9-929a-4cbb7802cc2c.PNG)

**Comment by Genteure** [comment]
是，最近在改。明天（今天）晚上应该可以再发个新版本。（如果顺利的话）

**Comment by Genteure** [comment]
已在 1.1.12 修改
#61
