### ISSUE TITLE
cli如何开机后台运行？创建快捷方式添加到shell:common startup会占用一个任务栏🥺

### ISSUE THREAD

**Issue by specked2527** [Bililive/BililiveRecorder#592]
创建快捷方式添加到shell:common startup会占用一个任务栏
快捷方式-属性-目标 bc.exe run  --bind "http://*:2356" --http-basic-user "1" --http-basic-pass "1" "i:\bc"

**Comment by Genteure** [comment]
也可以用 [winsw](https://github.com/winsw/winsw) 注册成 Windows 服务，就不会有命令行窗口了
