### ISSUE TITLE
舰长专属的直播间是不是只要添加上舰长的cookie就可以了?这个cookie能维持多久，需要每天都去添加新的cookie吗？

### ISSUE THREAD

**Issue by JYWXJ327** [Bililive/BililiveRecorder#593]

**Comment by Genteure** [comment]
1. 理论上是，具体是否有效不保证
2. 不知道，也不知道

**Comment by douhenhuidyf** [comment]
我也有同样的问题 现在你试过添加cookie录制舰长直播了吗 需要添加哪些cookie？

**Comment by gyhyfj** [comment]
请问cookie可以添加在哪里呢

**Comment by gyhyfj** [comment]
github有人提供自动刷新cookie的代码，但是不知道哪里可以添加cookie

**Comment by JYWXJ327** [comment]
> 我也有同样的问题 现在你试过添加cookie录制舰长直播了吗 需要添加哪些cookie？

最好是无痕模式下的cookie，这个能维持很久，但是至少一个月是可以的

**Comment by douhenhuidyf** [comment]
这周b站更新了 对舰长直播充电直播做了加密 你还能录制吗

**Comment by gyhyfj** [comment]
> 这周b站更新了 对舰长直播充电直播做了加密 你还能录制吗

不能

**Comment by gyhyfj** [comment]
> 这周b站更新了 对舰长直播充电直播做了加密 你还能录制吗

0|bilibili |     [System.Exception]: playurl is null
0|bilibili | [01:49:22 WRN (BililiveRecorder.Core.Room)] [11163068] 启动录制出错
