### ISSUE TITLE
房间配置项被删除

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [Bililive/BililiveRecorder#60]
之前添加过的录制房间，在重启录播姬后房间配置消失
第一张为重新启动后的录播姬，第二张为百度云盘上存储的备份文件，相当多的直播间都消失了
![lbj](https://user-images.githubusercontent.com/44915585/63269470-d8ea6b00-c2c8-11e9-9770-dce6c941a554.PNG)

![配置](https://user-images.githubusercontent.com/44915585/63269482-ddaf1f00-c2c8-11e9-8c80-dde9262fde9e.PNG)

**Comment by Genteure** [comment]
已在 1.1.12 修改
#61
