### ISSUE TITLE
如何去除 Traceparent header

### ISSUE THREAD

**Issue by shynome** [Bililive/BililiveRecorder#602]
### Platforms

Docker

### Version

2.11.1

### Description

我现在通过浏览器获取推流地址但是请求到达浏览器的时候会有个 Traceparent 请求头导致浏览器请求失败, 我想知道该如何去除该请求头

**Comment by shugen002** [comment]
https://stackoverflow.com/questions/72277304/remove-traceparent-header-from-httpclient-requests
