### ISSUE TITLE
docker版修改了配置文件中的cookie之后重启无法读取到cookie

### ISSUE THREAD

**Issue by Aithosa** [Bililive/BililiveRecorder#604]
### Platforms

Docker

### Version

v2.12.0

### Description

cookie过期之后我获取了新的cookie，并且在windows版中试过可以使用，之后把docker版使用的两个配置文件(包括备份的那个)cookie也换成新的，之后重启docker，看日志还是录制不了原画，我怀疑配置文件有问题，就下载下来替换到windows版本中，发现文件是正常的，请问下docker版更新cookie是我的操作有问题还是有别的影响？

**Comment by Genteure** [comment]
录播姬退出的时候会写入配置文件。所以如果你是先改配置文件再重启容器，重启的时候就会把原来的配置写回去。

**Comment by Aithosa** [comment]
> 录播姬退出的时候会写入配置文件。所以如果你是先改配置文件再重启容器，重启的时候就会把原来的配置写回去。

不过我是先改文件之后重启发现没用，然后又把文件下载下来给windows版使用，发现是正常的，如果按照你的说法我下载下来的应该是旧文件。

我再确认下。

**Comment by Aithosa** [comment]
试验了下，先停止服务，再修改配置，可以让cookie生效，并且启动不会报错。
