### ISSUE TITLE
直播间添加数量有上限吗？

### ISSUE THREAD

**Issue by Aithosa** [Bililive/BililiveRecorder#607]
### Platforms

WPF (桌面版), Docker

### Version

v2.12.0

### Description

添加监控的直播间，同一个直播间添加多次都显示成功，才发现一直没有添加上

**Comment by Aithosa** [comment]
docker版的可以重复添加而不报错

**Comment by Aithosa** [comment]
希望可以显示“直播间已添加，配置无变更”之类的话，或者在日志显示直播间已添加，无需操作之类的

**Comment by Genteure** [comment]
没有看懂，最后是加上了还是没加上？有什么问题？

**Comment by Aithosa** [comment]
> 没有看懂，最后是加上了还是没加上？有什么问题？

我看提示就是这个感觉，根本不知道加没加上，建议优化一下：
- 如果直播间已经存在就提示添加成功，并且直接说直播间已经存在，然后不做操作(避免列表顺序改变)
- 如果不在就添加，并且显示添加成功
- 如果有问题就报错
然后日志也记录一下

**Comment by Genteure** [comment]
API 里面[现在这个逻辑](https://github.com/BililiveRecorder/BililiveRecorder/blob/f48fbf4d38fa52fedf40bbe928b0ce3e875c03c5/BililiveRecorder.Web/Api/RoomController.cs#L49)还是当初写的时候 QQ 群里群友提出来的，说的大概意思“已经存在的房间重复添加不应该返回报错，调用方只需要关心调用了添加接口、返回了成功，这个房间就加上了。不应该去考虑它之前是不是已经加过了”。所以做成这样的。

@shugen002 有没有什么意见

**Comment by shugen002** [comment]
TL;DR: 代码没问题的话懒得改

我现在还是没看懂，他到底添加成功没有

> 添加监控的直播间，同一个直播间添加多次都显示成功，才发现一直没有添加上

我是直接看懵了，如果是已经在列表里面直接报添加成功，并且没有额外的重复提示我觉得是无所谓的，反正都已经在里面了。

但是如果说没有添加上的话，我在我webui这头也很明确告诉你我识别到了几个直播间号，然后才开始逐个替你添加，这时候你也应该能够知道到底有没有直播间被漏掉了。。。，剩下就是gen佬那头应该也不会犯低级错误，那我就不知道啥情况了。。。
