### ISSUE TITLE
定时录制  定时关闭的功能  

### ISSUE THREAD

**Issue by yibingchaoyue** [Bililive/BililiveRecorder#610]
### Problem

有一些主播半夜会挂机  来不及去关闭  导致每次都录的很多

### Proposal

定时录制  定时关闭的功能  有一些主播半夜会挂机  来不及去关闭  导致每次都录的很多

**Comment by yibingchaoyue** [comment]
那种放录播的主播 还有24小时直播的 真人直播时间其实挺固定的

**Comment by yibingchaoyue** [comment]
就是定时录制主播 定时关闭一个主播的录制  不是关机

**Comment by luboyyxx** [comment]
加1

**Comment by shugen002** [comment]
Duplicate of #285
