### ISSUE TITLE
对同一主播的同一画质ID可能因服务器不同返回分辨率相同但码率不同的视频流

### ISSUE THREAD

**Issue by rgw87** [Bililive/BililiveRecorder#611]
### Problem

在2台PC（异地）上使用相同的配置文件部署录制器，版本均为v2.12.0，发现对同一主播的同一画质ID有概率录到码率不同的视频流（分辨率相同），看日志，有时码率相差挺大，比如一台录到的码率1000M出头，另一台能有9000M，日志都显示录制的是“原画”，但服务器不同。

### Proposal

如果是现在B站本身的机制，好像也没什么办法……

**Comment by Genteure** [comment]
如果画质 ID 都是 10000 那就都是 “原画”，但是原画也有压过的和没被压过的。
看日志文件里的直播流链接，有 `_bluray` 字样的是被直播服务器二压过的。

**Comment by rgw87** [comment]
搜到issue 446有提到这个问题，还看到你写的脚本
https://github.com/BililiveRecorder/recorder-scripting-template/blob/main/examples/reuse-old-url.js
今天尝试用了下，开始时能获得未二压的流，但录了大概2小时，有一次统一的录制结束事件，然后重新获得的就都是低画质流（不止一个直播间，直接流链接里都有_1500）
看来目前能录到二压原画流也是最不坏的结果了吧，毕竟不是低分辨率……
