### ISSUE TITLE
cookie的设置是存在哪个文件里？

### ISSUE THREAD

**Issue by ZX828** [Bililive/BililiveRecorder#616]
### Problem

BililiveRecorder-WPF-Portable
cookie的设置是存在哪个文件里？
高级设置里的cookie的设置经常失效，突然想录的某一段，如果没设置cookie的话，会很模糊。
设置cookie，是不是要先登录，在f12里找到cookie然后复制，粘贴到高级设置里？还是说我的这个方法，不是正常的方式，所以才这么麻烦？

### Proposal

如果不想做自动更新cookie的话，配置文件弄成字符串的怎么样？.json.xml这种，别的格式我看不懂，不知道怎么直接修改文件。能直接修改的话，设置起来会轻松不少。
或者说只是桌面版不支持，其他的版本可以？

**Comment by Genteure** [comment]
配置文件在录制目录里的 `config.json`。
录播姬不会从配置文件热加载/刷新配置内容。如果有动态更新的需求建议用命令行版的 HTTP API。

-----

> 粘贴到高级设置里

一般来说是这样的。

> 经常失效

不想做登录系统也是这个原因，我不想折腾账户系统风控。就只能留给用得到这个东西的人去折腾了（

**Comment by ZX828** [comment]
哦！！！
cookie原来在工作目录里啊，怪不得我找了好多次我都没找到！！

呃，这个自动更新cookie的功能，我只能想到，写个crx，每次登录的时候获取一下cookie，然后再搞个本地tomcat这种的服务接收字符串，然后写到.json里这种方式。
还没试，不知道浏览器有没有什么安全措施，让crx获取不到cookie的。

多谢解答。
