### ISSUE TITLE
关于HTTP代理

### ISSUE THREAD

**Issue by sy1412** [Bililive/BililiveRecorder#62]
为何这种格式的127.0.0.1:1080不能用 
设置代理时发生错误 提示无效的URI: URI方案无效
用的SSR代理
难道只能那种专门的HTTP代理才行么 难找啊

**Comment by Genteure** [comment]
前面带 `http://`
[SS](https://github.com/shadowsocks/shadowsocks-windows) 侦听的本地代理端口是同时支持 HTTP 和 Socks5 的，不了解 SSR。

**Comment by sy1412** [comment]
好使了 但直播流以为好像也得走代理才能录.. 把IE代理打开就可以录 关了就不行..
还是全得走代理才能录 我腾讯云 看来屏蔽的很彻底 唉
[17:05:11] INFO 1362072 连接直播服务器 ws.live-play.acgvideo.com
[17:05:11] INFO 1362072 尝试下载直播流时服务器返回了 (571)

**Comment by Genteure** [comment]
那就没啥办法了（
