### ISSUE TITLE
【新功能请求】希望命令行版本可以注册成windows服务运行

### ISSUE THREAD

**Issue by yandujun363** [Bililive/BililiveRecorder#623]
### Problem

我管理录播姬主要是通过网页来管理  
但命令行版本不能后台无窗口运行  
也试过使用sc命令注册成服务  
但无法正常运行

### Proposal

如题  
或者添加一个后台运行参数

**Comment by Genteure** [comment]
强烈推荐使用 https://github.com/winsw/winsw/tree/master
立刻解决一切 Windows 服务注册运行相关的问题
