### ISSUE TITLE
Centos 升级2.13.0后启动命令报错 `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by qqzhal** [Bililive/BililiveRecorder#625]
### Platforms

CLI - Linux

### Version

v2.13.0

### Description

/usr/local/src/rec/BililiveRecorder.Cli: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/local/src/rec/BililiveRecorder.Cli)
/usr/local/src/rec/BililiveRecorder.Cli: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/local/src/rec/BililiveRecorder.Cli)

上面是报错内容
Linux VM-4-3-centos 3.10.0-1160.108.1.el7.x86_64 #1 SMP Thu Jan 25 16:17:31 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Genteure** [comment]
2.13.0 从 [.NET 6](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux) 升级到了 [.NET 8](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#linux)。我不知道这个问题怎么解决。。个人意见，按推荐顺序：

- 最好是换一个还在被支持的系统，CentOS 7 已经 EOL 了。CentOS 都没了，想系统类似的话可以考虑换 Stream 或者 [Rocky Linux](https://rockylinux.org/)。
  - 比如 https://docs.rockylinux.org/guides/migrate2rocky/
- 试试用 docker/其他容器方案比如 podman，这样就不用主机上的 lib
- 继续用 2.12.0

**Comment by qqzhal** [comment]
> 2.13.0 从 [.NET 6](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md#linux) 升级到了 [.NET 8](https://github.com/dotnet/core/blob/main/release-notes/8.0/supported-os.md#linux)。我不知道这个问题怎么解决。。个人意见，按推荐顺序：
> 
> * 最好是换一个还在被支持的系统，CentOS 7 已经 EOL 了。CentOS 都没了，想系统类似的话可以考虑换 Stream 或者 [Rocky Linux](https://rockylinux.org/)。
>   
>   * 比如 https://docs.rockylinux.org/guides/migrate2rocky/
> * 试试用 docker/其他容器方案比如 podman，这样就不用主机上的 lib
> * 继续用 2.12.0

好，换Stream可以用新版本了~
