### ISSUE TITLE
检测到b站hvc流漏掉当次录制的问题

### ISSUE THREAD

**Issue by RageMeoww** [Bililive/BililiveRecorder#626]
### Problem

hevc即h265编码流
不能用以下方法录制:录播姬_标准模式(爆内存)、blrec_flv、blrec_fmp4标准模式(仅限1.15版本)
可以用以下方法录制:录播姬_原始模式、blrec_fmp4(beta2.0)、blrec_fmp4原始(仅限1.15版本)

目前已经遇到过多次因为检测到h265而漏掉接下来所有录播的情况，即使很快就产生了二压流，或者切换回h264编码也是如此

### Proposal

【封装】
blrec_fmp4录制的流可以直接用ffmpeg封装
录播姬_原始模式录制的流无法直接使用ffmpeg封装，需要用mkvmerge封装之后才能用ffmpeg封装
另外，最新版的ffmpeg似乎已经支持flv_hevc封装了，刚刚亲测7.1版本封装无压力

【解法】
检测到非h264编码
切换原始录制模式
或者切换fmp4录制，但fmp4也得使用原始模式，如果引入的处理机制只支持h264则不能录制
(不推荐)其他清晰度，其他清晰度高概率存在二压的avc，比如超清(250)
(不推荐)原画如果有二压流，二压高概率存在avc流，在一段时间内继续尝试录制原画也是一种策略

自动化:为blrec和录播姬制作自动切换录制模式或清晰度的功能
制作弹性检测功能，默认可以设置为10秒，检测到非h264编码后在10秒内继续检测是否有二压流，超过时间则切换录制模式
设置为0秒则直接切换，还可以添加检测频率，持续尝试录制二压流

265推流有两种情况：
①是仅开播时使用h265推流，随后转为h264推流
②是从开播到下播都一直使用h265推流
不管是第一种情况还是第二种情况，检测到h265停止录制都会导致完全错过当次录制
自动切换录制模式才能保证不会漏掉录制

例子:
以塔菲录播为例，这天开播时使用h264推流，之后切换h265推流，然后又换回h264推流
![11 12 塔菲2](https://github.com/user-attachments/assets/c4b237d8-391b-4fc3-bb92-84d7dbd4440c)

因为blrec目前还不支持切换录制模式，所以flv录制h265时会持续请求且只能录到二压流，以此可以计算出二压流的产生时间
通过对比，可以得知在h265推流55分钟之后才开始产生二压原画流
![22603245-20241112-191612-头部对齐1](https://github.com/user-attachments/assets/1ba68c51-f3ba-4cac-bff4-61a3a19b597d)

而另外的h265例子中(多数情况)，开播后几乎跟真原画流同时产生了二压原画流
但是，两个录播姬标准模式都因为检测到非h264编码停止了当次录制，直到我手动开始录制，
或者，一个停止了录制，漏掉了该次录播，但另外一个却在开播时录到了二压流
还有一次只有真原画流的h265推流，在开播大概3分钟之后产生了超清画质二压流，或者更早就产生了

二压流可能刚开播就产生，也可能很久才产生，也可能一直没有二压流
二压流产生的时间不确定，可以作为备用选项
还是切换录制模式比较靠谱

**Comment by Genteure** [comment]
不好意思没看见这个 issue，GitHub 没给这个 issue 发邮件通知也没发 webhook 然后我就给看漏了。。

<details>
<summary>Details</summary>

![image](https://github.com/user-attachments/assets/c064a0f4-e76a-40a9-ae51-c841c2071d04)

</details>

上周发的最新版本 2.13.1 已经改成检测到 HEVC 之后切换原始数据模式录了，所以这个 issue 我先 close 了，相关问题可以继续在这里发。

-----

关于封装，最新的 ffmpeg 把 hevc 封装到 flv 里用的是这个标准吧 https://github.com/veovera/enhanced-rtmp ，不是国内 CDN 厂商的 codec 12 的事实标准，两个格式不一样也不兼容的。

录播姬 FLV 标准模式不支持 HEVC 主要是因为处理逻辑里有一点针对 AVC 的东西。理论上说检测到 HEVC 之后把处理逻辑里针对 AVC 的东西禁用掉保留其他的应该也是可行的，不过没有测试过，现在也有点懒得测试（测这个不如写录播姬v3）。

FMP4 (fragmented mp4) 本身就支持装 HEVC，是标准的格式，能录能读能播非常正常也符合预期。

**Comment by RageMeoww** [comment]
好吧，是这样的，我之前号被github封了，开了工单才解决的
另外，我也猜到了，你的风格就是能用更简单的方式解决绝对不用更复杂的，哪怕更复杂的方式效果可能更好
也行，解决了就好

**Comment by RageMeoww** [comment]
确实格式不一样，就算看起来都是flv其实根本不是一个东西
跟ffmpeg封装出来的格式有微妙的区别
ffmpeg封装的hevc_flv拿mkvmerge就不能识别音频了，但是封装之前就可以

我发现就算是同样直播姬推的265的流编码名字也可能不一样
一个编码叫hvc，一个叫hev，但这只是编码，实际效果是一样的

**Comment by RageMeoww** [comment]
这个简单粗暴的改动果然有很大缺陷，检测到H.265后是先结束录制，然后才改成原始模式的，结果以原始模式录制了二压流，感觉好尴尬，二压流应该用标准模式录才对啊，这样分段功能也失效了
![12 10 检测到H 265后改成原始模式，结果以原始模式录制了二压流，感觉好尴尬](https://github.com/user-attachments/assets/4541443f-0680-4a53-8fd4-5414b6a3c57d)
![12 10 检测到H 265后改成原始模式，结果以原始模式录制了二压流，感觉好尴尬2](https://github.com/user-attachments/assets/b40d7ffa-14bf-44fb-9a7c-59aa79c0bb6a)

**Comment by Genteure** [comment]
试试 #634 
在 Actions 的 Artifacts 里下载编译好的二进制

**Comment by RageMeoww** [comment]
正在测试中，目前这种情况(原始模式录制二压流)只遇到一次，大部分情况下获取不到真原画流，而是直接就录制二压流了，要配合真原画脚本测试吗？

**Comment by Genteure** [comment]
那我就不知道了。脚本里的自定义逻辑不算录播姬的功能，我也不知道你的脚本里写了啥。

**Comment by RageMeoww** [comment]
目前的改动似乎失败了，在录到H.265真原画流时，本地并没有产生录播文件，而且检测信息全部爆红
内存有没有炸还没注意到
为了确认是否是偶然情况，我专门等了两天，确认并非偶然
并且也确认了，本地没有产生录播文件和弹幕，是因为都录制到内存里了
【爆红】
![12 13 测试录播姬成功又失败？1](https://github.com/user-attachments/assets/cfac1117-0ac8-4f1d-bb01-e0603f09c12f)
![12 15 测试结果2](https://github.com/user-attachments/assets/358a8c0d-b5c2-4221-91df-a665f8e90211)
【内存占用非常高，而且还在不断提升】
![12 15 内存确实爆炸了](https://github.com/user-attachments/assets/5d8d5354-8043-4f68-ba17-8ea04e31235f)
![12 15 内存占用非常高，而且还在不断提升](https://github.com/user-attachments/assets/9f5aa7c9-7c7f-4c1d-ad2d-022b71406bae)
![12 15 内存占用非常高，而且还在不断提升1](https://github.com/user-attachments/assets/df54cf8a-576d-406b-b3a5-57a9fc735ed0)
![12 15 内存占用非常高，而且还在不断提升2](https://github.com/user-attachments/assets/fe16a5db-1a2f-4faf-93a9-0d5d01939208)
【日志】
![12 15 日志](https://github.com/user-attachments/assets/1cda38c3-3c71-4d1e-958e-b0186f074ea3)

**Comment by RageMeoww** [comment]
我想的是当前版本(v2.13.1)再改动两个点就完美了
①无缝切换②二压流优化
如果不能做到无缝切换的话，完成二压流的优化选项，就是我认为目前能做到的最好的优化了

具体改动：
增加一个默认是关闭的选项，打开后把检测到H.265后改为原始模式再改成检测到H.265就停止，然后重新请求，直到请求到264
或者超过设置时间为止

[无缝切换]
无缝切换指检测到H.265不结束录制再切换模式后请求而是无缝切换模式，无缝切换从技术上肯定是很困难的，
但如果能做到的话就不会出现尴尬状况，开始录制也能更早
[二压流优化]
二压流优化很简单，就是把检测到H.265后改为原始模式再改成检测到H.265就停止，然后重新请求，直到请求到264
或者超过设置时间为止

**Comment by Genteure** [comment]
“无缝切换”现在的代码结构做不到，录制模式在开始录制之前就选好了的，标准模式解析直播流内容读完的数据也不能回退。
“二压流优化” emmmmmm 要不你发个 PR 看看

#634 新推了个 commit 试试

**Comment by RageMeoww** [comment]
仿佛能看到你的表情哈哈哈
新commit已经在测试了，有结果我会立刻反馈
我还没有能力提PR，因为我没有学过[C#](https://github.com/BililiveRecorder/BililiveRecorder/search?l=c%23)

**Comment by RageMeoww** [comment]
gen快看快看好像成功了唉，牛逼啊
![gen快看快看好像成功了唉，牛逼啊](https://github.com/user-attachments/assets/8d44358f-5b94-42d8-be75-9235c2e15de5)
[录制-923833-20241216-120945-476-小游戏版植物大战僵尸！.1.zip](https://github.com/user-attachments/files/18146089/-923833-20241216-120945-476-.1.zip)

**Comment by RageMeoww** [comment]
之前修改之后，265录制、分段都正常、工具箱也可以正常使用，但是之前检测的结果无一例外都是没有问题
令我非常困惑，怀疑是不是工具箱不能正常运作
之后我终于录到了一个工具箱检测有问题的265录播

确认没有工具箱检测没有问题，但是录制的时候有一些奇怪的表现
比如，开播时总是会显示没有10000画质，显示几次之后就会返回一个二压流的链接
让人怀疑开播时265跟264的链接是分开的，所以会请求不到
之前不是公告里说265会混进264，但可能不是所有时候都会混进264，所以才会造成这种情况？
但是264也会这样，不过，改版之后，标准模式录制265，没有用真原画脚本的话，一次好像都录到过？
就算用了，也很难录到265，除非是原画不二压的那种小主播才能录到
可能再等一段时间就有了吧

**Comment by holwell** [comment]
mark 现在录播姬实现网络波动时的片段修复吗
