### ISSUE TITLE
直播原画是1080p，录制出来是720p

### ISSUE THREAD

**Issue by katamabo** [Bililive/BililiveRecorder#628]
直播原画是1080p，录制的是720p。

录制模式：原始数据模式
录制画质：10000

问题出在哪？

**Comment by Genteure** [comment]
得看日志，不排除主播推的就是 720p 的情况。

**Comment by katamabo** [comment]
> 得看日志，不排除主播推的就是 720p 的情况。

日志显示确实是录制的超清，但主播应该是推的1080p，试了几个直播间了，原画下直播间内看视频统计信息是1080p的。

日志：
返回的直播流地址的画质是 250 而不是请求的 10000
连接直播服务器 d1--ov-gotcha05.bilivideo.com 录制画质 250 (超清）

**Comment by Genteure** [comment]
API 不登录不给高画质。
https://rec.danmuji.org/reference/settings/#s-Cookie
https://rec.danmuji.org/reference/userscript/
