### ISSUE TITLE
要怎么设置录制高1080P的高画质

### ISSUE THREAD

**Issue by fgo1212** [Bililive/BililiveRecorder#629]
### Platforms

WPF (桌面版)

### Version

mikufans录播姬2.13.0

### Description

别的软件录制是1080P的高画质，mikufans录播姬录制的却是720p的低画质，要怎么设置录制高1080P的高画质
![QQ截图20241126174833](https://github.com/user-attachments/assets/48bb922e-1296-482b-93eb-bca1e3f18486)
![1](https://github.com/user-attachments/assets/dd3a969a-ca47-4151-9a19-4ebe3e65c3e9)
[bilirec20241125.zip](https://github.com/user-attachments/files/17917419/bilirec20241125.zip)

**Comment by Genteure** [comment]
API 返回什么就录什么，录播姬相当于浏览器隐身标签页看直播
![image](https://github.com/user-attachments/assets/6b51476e-cc06-4b46-b3a1-00f14e9ece17)
可以试试加一个[Cookie](https://rec.danmuji.org/reference/settings/#s-Cookie)
