### ISSUE TITLE
提示已取消一个任务

### ISSUE THREAD

**Issue by kevinluo6188** [Bililive/BililiveRecorder#63]
RT
![QQ图片20190829192520](https://user-images.githubusercontent.com/36571233/63936620-d8a15b00-ca92-11e9-976e-295617350f5b.png)
[log截取.txt](https://github.com/Bililive/BililiveRecorder/files/3555314/log.txt)

**Comment by Genteure** [comment]
这个应该是请求超时，应该已经不是问题了。
