### ISSUE TITLE
FileOpening/FileClosed webhook events for XML 弹幕文件

### ISSUE THREAD

**Issue by SpriteOvO** [Bililive/BililiveRecorder#630]
### Problem

下游软件期望使用 WebHook 将录播文件上传到第三方平台，目前似乎只能收到录播视频文件的 webhook events，但没有针对 XML 弹幕文件的，导致无法得知上传弹幕文件的时机。

### Proposal

添加 FileOpening/FileClosed webhook events for XML 弹幕文件

**Comment by Genteure** [comment]
直接用 `FileClosed` 就可以吧，弹幕文件是和视频文件强关联一一对应的

**Comment by SpriteOvO** [comment]
> 直接用 `FileClosed` 就可以吧，弹幕文件是和视频文件强关联一一对应的

@Genteure 感谢答复。

那在*视频文件*的 FileClosed event 收到时，*弹幕文件*的 fd 是保证被 closed / flushed 的吗。文档里好像没有明确这一点。

**Comment by Genteure** [comment]
对的，在尝试发送 FileClosed 之前视频文件和弹幕文件都是已经关闭了。

**Comment by SpriteOvO** [comment]
感谢解答~w
