### ISSUE TITLE
增加二级路径配置，方便反向代理

### ISSUE THREAD

**Issue by gaaichan998** [Bililive/BililiveRecorder#632]
### Problem

如题，现web页面只能在根路径下，需要多开放一个端口

### Proposal

增加base_url 设置，方便反向代理在二级路径下

**Comment by Genteure** [comment]
现在就应该支持反代到其他路径的，你是怎么配置的，具体报错是什么？

另，用一个子域名也是可以的。应该没有多少项目是支持运行在任意子路径上的吧。

**Comment by gaaichan998** [comment]
问题解决了，我复制链接的时候复制错了，写成了`proxy_pass http://10.0.0.1:19159/ui/;`，这样api拉取请求会出错
正确的应该是 `proxy_pass http://10.0.0.1:19159/;`
