### ISSUE TITLE
添加了Cookie只能录制1080p30fps，请问怎么设置录制1080p60fps，有录制画质选项吗？

### ISSUE THREAD

**Issue by fgo1212** [Bililive/BililiveRecorder#635]
### Problem

添加了Cookie只能录制1080p30fps，请问怎么设置录制1080p60fps，有录制画质选项吗？

### Proposal

添加了Cookie只能录制1080p30fps，请问怎么设置录制1080p60fps，有录制画质选项吗？

**Comment by Genteure** [comment]
有没有可能主播播的就30FPS

**Comment by fgo1212** [comment]
> 有没有可能主播播的就30FPS

不是，另一个软件录制的就是60fps的
![QQ截图20241212174309](https://github.com/user-attachments/assets/f9bd42ab-ea0a-423c-9b49-1d0981a9369d)
![QQ截图20241212182422](https://github.com/user-attachments/assets/768d3d6a-3d0a-4136-86fb-711e02f9ede5)
