### ISSUE TITLE
希望添加一个登录功能

### ISSUE THREAD

**Issue by pingshazikdjnd** [Bililive/BililiveRecorder#638]
### Problem

录播无法获取原话画质，要添加cookie，很麻烦

### Proposal

希望添加一个登录功能

**Comment by Genteure** [comment]
不做。。登录这种东西，要不就是你麻烦要不就是我麻烦，我不想麻烦，所以只能谁用到这个东西谁麻烦了。。
录播姬命令行版有 HTTP API，很久以前就有人提过可以做一个外置的系统然后用 API 传进去更新，不过到现在也没有人写（

**Comment by pingshazikdjnd** [comment]
找到解决方法了，用biliup就行了

**Comment by RageMeoww** [comment]
你好，楼主，能分享一下使用biliup来实现录播姬登录效果的方法吗？

**Comment by lixueshu** [comment]
> 你好，楼主，能分享一下使用biliup来实现录播姬登录效果的方法吗？

https://biliup.github.io/biliup/

**Comment by pingshazikdjnd** [comment]
> 你好，楼主，能分享一下使用biliup来实现录播姬登录效果的方法吗？

https://github.com/biliup/biliup

**Comment by RageMeoww** [comment]
你好，楼主，我不太明白你的用法是什么样的，biliup可以直接添加录播姬的链接来登录吗？
因为我不会用biliup，希望能获得你的教程或者截图讲解之类的

**Comment by pingshazikdjnd** [comment]
> 你好，楼主，我不太明白你的用法是什么样的，biliup可以直接添加录播姬的链接来登录吗？ 因为我不会用biliup，希望能获得你的教程或者截图讲解之类的

biliup是别的录播软件，直接下最新的不需要配置那么复杂的东西。录播后的文件会存在程序所在文件夹

**Comment by pingshazikdjnd** [comment]
> > 你好，楼主，我不太明白你的用法是什么样的，biliup可以直接添加录播姬的链接来登录吗？ 因为我不会用biliup，希望能获得你的教程或者截图讲解之类的
> 
> biliup是别的录播软件，直接下最新的不需要配置那么复杂的东西。录播后的文件会存在程序所在文件夹

https://github.com/biliup/biliup/releases/download/v0.4.81/biliup_v0.4.81.exe
下下来打开，然后用浏览器访问它给的网址

**Comment by pingshazikdjnd** [comment]
> 你好，楼主，我不太明白你的用法是什么样的，biliup可以直接添加录播姬的链接来登录吗？ 因为我不会用biliup，希望能获得你的教程或者截图讲解之类的

具体看这个项目的图文教程，在项目里有
