### ISSUE TITLE
无法录制付费直播

### ISSUE THREAD

**Issue by LzNOHentai** [Bililive/BililiveRecorder#67]
已登陆账号，已付费。
提示“尝试下载直播流时服务器返回了Not Found”

**Comment by Genteure** [comment]
软件没有登录B站账号的功能，也没有录制付费直播的功能。

**Comment by LzNOHentai** [comment]
> 软件没有登录B站账号的功能，也没有录制付费直播的功能。

啊，那“使用用户名和密码验证”是干什么用的，我以为可以用于验证下载付费直播……
希望能够适配一下吧，现在包括以后付费直播可能会越来越多……
![QQ截图20191013203022](https://user-images.githubusercontent.com/22359967/66715655-58dc0f80-edf8-11e9-8e8a-af45ec933d0a.jpg)

**Comment by Genteure** [comment]
那个是 HTTP 代理的用户名密码设置

**Comment by LzNOHentai** [comment]
> 那个是 HTTP 代理的用户名密码设置

原来如此，是我误解了……
那这个issue就当功能建议吧，先谢谢大佬的持续维护了，工具很好用。

**Comment by Genteure** [comment]
1.1.13 加入了设置 cookie 的功能，去掉了使用代理的功能。某种意义上算是支持了录付费直播？不过没测试。
