### ISSUE TITLE
建议新增格式转换

### ISSUE THREAD

**Issue by Rehtt** [Bililive/BililiveRecorder#69]
原始flv有点大，建议新增录制时进行格式转换，比如转成mp4等格式

**Comment by Genteure** [comment]
可是转换成其他格式不会减小一丁点文件大小，从flv转换成mp4反而会变大那么一丁点。为什么你会认为转换成mp4，文件大小就会变小。。。里面的音视频数据都是一样的啊
其他用途需要不能用flv需要其他格式的话请用 ffmpeg 之类的工具
`ffmpeg -i input.flv -c copy output.mp4`
