### ISSUE TITLE
关于 Cookie

### ISSUE THREAD

**Issue by HMBSbige** [Bililive/BililiveRecorder#71]
* 问一下 Cookie 怎么填？

* 这行应该是 `user["message"]`

https://github.com/Bililive/BililiveRecorder/blob/311c0593c94505b263419071359db003c806b072/BililiveRecorder.Core/BililiveAPI.cs#L156

**Comment by Genteure** [comment]
直接从浏览器开发者工具里复制出来 `x=y;a=b` 这种格式的贴进去就好了啊。注意 session 是 httponly 的。

下次更新时会修改

**Comment by Genteure** [comment]
fixed bfcd2cdca55a25a570043514c20605cfce0b364c
