### ISSUE TITLE
关于付费直播

### ISSUE THREAD

**Issue by HMBSbige** [Bililive/BililiveRecorder#75]
* 刚刚测试了付费直播，填入 Cookie 依旧无法获取正确的直播地址

	调试了一下，我直接加在 `DefaultRequestHeaders` 里就录制成功了，只需要 `SESSDATA` ，且值不需要 Decode。

	[参考代码](https://github.com/HMBSbige/AutoSplitVideo/blob/e266dd2498bee09ab2721e8fceb2d41e746b752a/BilibiliApi/BililiveAPI.cs#L32)（半成品）

* 又测试了一下，把值替换成 `access_token` 居然也行...

	如果之后还需要接入登录的话也许可以参考[这个](https://github.com/HMBSbige/BilibiliMangaAutoClockIn/blob/master/BilibiliApi/Passport.cs)

**Comment by Genteure** [comment]
不是很想主动加入登录和录制付费直播的功能，尤其是用户名密码登录。
回头再说吧。

**Comment by Genteure** [comment]
提醒一下你的 [AutoSplitVideo](https://github.com/HMBSbige/AutoSplitVideo)，有从本项目复制部分代码使用<sup>[[1]](https://github.com/HMBSbige/AutoSplitVideo/commit/73269a5d7e1d9e033f9db5d86706b4f549f6cf3d) [[2]](https://github.com/HMBSbige/AutoSplitVideo/commit/840a6f8fb86ba71743844aeb5c1516c92c9c1bad) [[3]](https://github.com/HMBSbige/AutoSplitVideo/commit/7f7546b56231ac2b1fb62afc2703d5598717e5a3)</sup>。
AutoSplitVideo 使用的开源协议是 [MIT](https://github.com/HMBSbige/AutoSplitVideo/blob/eb292ed4e538a557c7da51bac794acf37f8ac3bc/LICENSE#L1-L21)，而本项目使用的开源协议是 [GPL-3.0](https://github.com/Bililive/BililiveRecorder/blob/dev/LICENSE)
GPL-3.0 是不与 MIT 兼容的（但是 MIT 是与 GPL-3.0 兼容的），如果要使用这个项目的代码，你的项目也需要是 GPL-3.0。 https://en.wikipedia.org/wiki/License_compatibility

[1] : https://github.com/HMBSbige/AutoSplitVideo/commit/73269a5d7e1d9e033f9db5d86706b4f549f6cf3d
[2] : https://github.com/HMBSbige/AutoSplitVideo/commit/840a6f8fb86ba71743844aeb5c1516c92c9c1bad
[3] : https://github.com/HMBSbige/AutoSplitVideo/commit/7f7546b56231ac2b1fb62afc2703d5598717e5a3

**Comment by HMBSbige** [comment]
@Genteure done

**Comment by Genteure** [comment]
前几天修改了添加 Cookie 的方式，基本上算是完成了功能了。
就不在本项目里添加用户名密码登录之类的逻辑了。
