### ISSUE TITLE
程序启动时获取多个直播间信息的并行化

### ISSUE THREAD

**Issue by ZhMJiang** [Bililive/BililiveRecorder#77]
目前（所使用版本1.1.15）程序在启动时，若保存配置中包含多个直播间，则会**逐个**访问直播间信息，导致非常严重的延时。另一方面，多次出现（可能在网络不好的条件下）直播间信息获取过程卡在某个直播间上，进而导致整个启动过程无法继续进行，既无法完成所有直播间信息的获取，也不能开始监测已经获取信息的直播间，也不响应手动操作。
是否可以并行获取所有直播间的信息？

**Comment by Genteure** [comment]
1.1.21 修改了这部分的代码，现在会并行访问了
