### ISSUE TITLE
在windows server2016 数据中心版无法录制的问题

### ISSUE THREAD

**Issue by ricksantor** [Bililive/BililiveRecorder#84]
本人小白一个。主要是想把录播姬挂在windows平台的云服务器上，对喜欢的直播间进行7x24小时的监控录播。故打算使用腾讯云的windows server 2016数据中心镜像的vps进行解决。但是在服务器端运行后，问题来了，一直提示错误，错误内容为：
  “[23:33:23] WARN 14921180 启动直播流下载出错。将重试启动。 没有直播播放地址”
——————————————————————————————————————————————
现状：1、输入直播房间号后录播姬可以正确识别 主播名字 证明房间号没输错；
            2、在本地电脑可以畅通无阻观看b站直播；
            3、在服务器端上，浏览器可以正常观看其他非直播视频，但是看直播的话，直播页面，除了视频画面，页面其他内容都能加载出来；
            4、该up主正在直播，没有直播的up主房间反而没有上述的错误提示。
            5、在正常的直播间里，在本地电脑使用chrome的f12（或右键➡️检查）功能，选择“Network”选项卡，表格按“Name”排序，正常的话，邻近“log-reporter.js"一行，应该有一行“live_xxxxxx_xxxxxxx_xxxx.flv?cdn=.........“并且可以看见数据流在加载。但是在服务器端的chrome连这一行都没有。
 ——————————————————————————————————————————————
    虽然我也知道很可能不是录播姬的锅，很可能是服务器版本的系统缺了些什么，但是我也不知道上哪里求助，只能来这里向各路神仙求助了 :'( 谢谢！
    又或者能有更好的7x24小时录播方案也可以（x

**Comment by Genteure** [comment]
B站屏蔽了主流服务器大厂的IP段，包括 腾讯云 阿里云 AWS Azure GCP
最靠谱的7*27录播方案是在自己家里电脑上运行，或者家里的工控机/NAS

**Comment by ricksantor** [comment]
原来原因这么简单懂了，谢谢！

**Comment by GloomyGhost-MosquitoSeal** [comment]
在Windows Server 2019 数据中心版无法录制，显示
```
[12:19:55] WARN 4316215 启动直播流下载出错。将重试启动。 没有直播播放地址
```
服务器在家里，IP正常，考虑是否因为系统而错误？
测试网页打开正常。

**Comment by Genteure** [comment]
@GloomyGhost-MosquitoSeal 
和操作系统肯定是没有关系的。
你网页不登录账号可以正常播放直播吗？

**Comment by GloomyGhost-MosquitoSeal** [comment]
可以播放的

**Comment by Genteure** [comment]
把 `*.bilibili.com` 的 Cookie 清空，或者用隐身标签页呢？也可以正常播放吗？你用的是什么浏览器？网页上能正常播放的同时，录播姬也不能正常使用吗？

**Comment by GloomyGhost-MosquitoSeal** [comment]
> 
> 
> 把 `*.bilibili.com` 的 Cookie 清空，或者用隐身标签页呢？也可以正常播放吗？你用的是什么浏览器？网页上能正常播放的同时，录播姬也不能正常使用吗？

不能播放了，Cookie登录怎么用？

**Comment by Genteure** [comment]
> 不能播放了，Cookie登录怎么用？

可以试一下把 Request Header 里面的 Cookie 复制到录播姬的设置框里，有可能能用，有可能不行。

等有空了之后有可能加一个登录B站账号的功能
