### ISSUE TITLE
启动直播流下载出错

### ISSUE THREAD

**Issue by XiaoXiaoYanHe** [Bililive/BililiveRecorder#86]
怎么解决www

**Comment by Genteure** [comment]
具体什么问题？出错具体是怎么出错？

**Comment by XiaoXiaoYanHe** [comment]
[23:52:20] WARN 47867 启动直播流下载出错。将重试启动。 没有直播播放地址

**Comment by Genteure** [comment]
大厂的服务器IP段被B站屏蔽了，不能用。
如果你是在家里用，试一下重启路由器或者光猫。
有能力的话可以自己改一下，加一个登录B站账号后的Cookie请求API，应该可以缓解。

**Comment by XiaoXiaoYanHe** [comment]
解决了，感谢
