### ISSUE TITLE
B站启动直播流下载出错。

### ISSUE THREAD

**Issue by iac-cai** [Bililive/BililiveRecorder#88]
B站启动直播流下载出错。将重试启动。没有直播播放地址。

**Comment by Genteure** [comment]
#86 
大厂的服务器IP段被B站屏蔽了，不能用。
如果你是在家里用，试一下重启路由器或者光猫。
有能力的话可以自己改一下，加一个登录B站账号后的Cookie请求API，应该可以缓解。

**Comment by iac-cai** [comment]
谢谢~

**Comment by Smoke-N-Mirrors** [comment]
> #86
> 大厂的服务器IP段被B站屏蔽了，不能用。
> 如果你是在家里用，试一下重启路由器或者光猫。
> 有能力的话可以自己改一下，加一个登录B站账号后的Cookie请求API，应该可以缓解。

emmm加了cookie也不行, b站做得真绝啊
