### ISSUE TITLE
网络卡顿有时候会导致生成的视频音画不同步

### ISSUE THREAD

**Issue by jiangyifan123** [Bililive/BililiveRecorder#89]
网络卡顿有时候会导致生成的视频音画不同步

**Comment by Genteure** [comment]
不觉得是网络卡顿导致的问题，再卡顿也不会导致收到的数据时间戳变了。
常见音画不同步原因：
- 主播推出来就这样
- 主播直播丢帧，录出来的视频在用工具二次处理（编码转封装等）时，工具对动态帧率支持不好，导致音画不同步
- B站服务器抽风

无论是哪个问题，录播姬其实都处理不了。
如果你有其他更明确的修改建议可以 reopen
