### ISSUE TITLE
服务器版的网页前端

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#9]
目前打算自己用 TypeScript + Vue 写，最终打包成一个单页应用，布局类似目前的 WPF 界面。
要是有前端大佬来帮忙就好了😔

**Comment by climba03003** [comment]
![image](https://user-images.githubusercontent.com/23028015/62826508-7372ec00-bbef-11e9-9916-6f7929cde6e2.png)
雖然不是你希望的 Typescript + Vue
但我用 Polymer 3 和 Vaadin 弄了個基本的介面
不知道這樣子可以嗎？

**Comment by Genteure** [comment]
谢谢，但是服务器版这个坑大概会拖很长时间。。最近不是很有时间填坑。
等有时间了之后打算先继续完善现在的 Windows WPF 版，还有不少问题需要完善的。
可能会做一个最基本的命令行版本，带 HTTP 控制台 和 HTTP API 的版本近期应该不会有时间做。

**Comment by climba03003** [comment]
那你先開一個新 Repo
我把原碼先弄上去
你看何時能做個 HTTP 伺服器時
我再更新那邊
這樣可以？

還是你想直接 Pull Request 放這裏？
我個人感覺是新 Repo 再用 Sub-Modules 會比較方便維護

**Comment by Genteure** [comment]
你可以先放到你自己名下的一个 repo 里。
最后不一定会能用上。服务器版具体要做什么功能也都没想好没定下来，最终功能可能和 WPF 版会比较不一样。需要等到开始做的时候才能定下来。

**Comment by climba03003** [comment]
> 你可以先放到你自己名下的一个 repo 里。
> 最后不一定会能用上。服务器版具体要做什么功能也都没想好没定下来，最终功能可能和 WPF 版会比较不一样。需要等到开始做的时候才能定下来。

https://github.com/climba03003/BiliLive-Recorder-Web-Client
