### ISSUE TITLE
无法连接至弹幕服务器，但是录播可以正常触发

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [Bililive/BililiveRecorder#94]
![image](https://user-images.githubusercontent.com/44915585/80180760-08126280-8636-11ea-99c2-431a9a8dd14c.png)

**Comment by Genteure** [comment]
_应该_ 是单纯的服务器抽风或者网络问题，不是软件问题。
连不上弹幕服务器也不影响录制，设置里可以调整重连重试时间间隔。
如果长时间一致连不上的话再说（
