### ISSUE TITLE
弹幕连接持续断开重连，导致产生了大量的无用log

### ISSUE THREAD

**Issue by SaltyFishOnTheSea** [Bililive/BililiveRecorder#97]
自从弹幕服务器一直连接不上之后，每天都会产生巨量的无用log占用C盘空间
该服务器地址：120.92.158.137:2243 指向一个位于上海的金山云服务器，用ip工具无法ping通
有没有办法绕开这个服务器
![image](https://user-images.githubusercontent.com/44915585/80351450-eb2f9680-88a4-11ea-9ae7-cb3d4a92407d.png)

**Comment by Executor-Cheng** [comment]
建议禁止`StreamMonitor`连接到`broadcastlv.chat.bilibili.com`, 这个域名解析到的弹幕服务器具有IP连接数限制，超出就RST/FIN。
可以考虑通过访问`api.live.bilibili.com/room/v1/Danmu/getConf`获取host&token再连接上去
```CSharp
{
    uid = 0,
    roomid = roomId,
    protover = 2,
    platform = "web",
    clientver = "1.10.6",
    type = 2,
    key = token
}
```

**Comment by SaltyFishOnTheSea** [comment]
具体应该如何操作

> 建议禁止`StreamMonitor`连接到`broadcastlv.chat.bilibili.com`, 这个域名解析到的弹幕服务器具有IP连接数限制，超出就RST/FIN。
> 可以考虑通过访问`api.live.bilibili.com/room/v1/Danmu/getConf`获取host&token再连接上去
> 
> ```cs
> {
>     uid = 0,
>     roomid = roomId,
>     protover = 2,
>     platform = "web",
>     clientver = "1.10.6",
>     type = 2,
>     key = token
> }
> ```

**Comment by Genteure** [comment]
@SaltyFishOnTheSea 你录了多少个直播间？

**Comment by SaltyFishOnTheSea** [comment]
> @SaltyFishOnTheSea 你录了多少个直播间？

监控状态80+，最大同时录制25

**Comment by Genteure** [comment]
下载试一下这个版本

https://ci.appveyor.com/project/Genteure/bililiverecorder/builds/32570942/artifacts

**Comment by SaltyFishOnTheSea** [comment]
> 下载试一下这个版本
> 
> https://ci.appveyor.com/project/Genteure/bililiverecorder/builds/32570942/artifacts

好的，我试两天

**Comment by SaltyFishOnTheSea** [comment]
两天使用情况：旧情况不再出现，log数量回到正常水平

**Comment by Genteure** [comment]
那先close了，等会发个新版本
