### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by Genteure** [Bililive/BililiveRecorder#99]
- 测试研究 GitHub Actions
- 修改调整整个版本发布流程
- 添加命令行版录播姬

打算做命令行版， CICD 全集中放到一起比较方便

**Comment by climba03003** [comment]
如果有 CLI 版本
我感覺能把 Server 版也造出來
我直接用 NuxtJS 模版做 Web UI
之後 Server 運行命令

**Comment by Genteure** [comment]
已在 1.3 实现
